### ISSUE TITLE
share Image on Facebook from master branch

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#1007]
**Actual Behaviour**

The image is not sharing from the master after successfully authenticating it. 

**Expected Behaviour**

The image should be shared on Facebook from the master branch. 

**Steps to reproduce it**

SharingActivity->Facebook

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
@Subhankar please use api with facebook sdk.
