### ISSUE TITLE
Problems while uploading images to upload list

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#101]
**Actual Behaviour**

1- If you upload any image from upload activity it only add one picture and doesn't add more than one pictures to list view.
2- If you add pictures from floating upload button it corrupts first entry in list view of your uploaded list.
3- If you add pictures from floating upload button from gallery it doesn't prompt you on entering same picture again and again.  

**Expected Behaviour**
1- It should add selected image into an list instead of only single image. 
2- It should add image to uploaded list continuing from the last image in the list. 
3- I should ask user if user wants to enter same picture again as it is already in upload list.

**Steps to reproduce it**

It can be done by checking errors in making list of images and showing them in list view. 

**Would you like to work on the issue?**

Yes I would Like to work on these.

**Comment by AliAyub007** [comment]
@Abhi2424shek  I fork this repository even synced it but still it's not updating in my fork and in git it shows up to date. Can you please help me with this?
(It say this many commits behind and this many ahead on my fork. )

**Comment by Abhi2424shek** [comment]
@AliAyub007 pls delete your fork, as you have added many commits to it if you don't want them.

**Comment by Abhi2424shek** [comment]
@AliAyub007 is the issue still there?

**Comment by AliAyub007** [comment]
@Abhi2424shek I had my exams and in that time Someone has solved redundancy and sent pull request I think. but it's not merged yet.

**Comment by Abhi2424shek** [comment]
Pls check if it exists @AliAyub007 by testing it if you could, can you? ;)

**Comment by AliAyub007** [comment]
@Abhi2424shek Yes, Redundancy still exists like you can upload similar images multiple times.

**Comment by Abhi2424shek** [comment]
That's a feature
