### ISSUE TITLE
Add Filters To Camera

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#103]
**Actual Behaviour**

Currently there are very less filters in camera(Preview).

**Expected Behaviour**

There should be some basic filters so that user have options to pick from.

**Steps to reproduce it**

At present, i don't know how to implement it but i will learn and ask for help from the mentors if i get stuck but i will send a PR as soon as possible.

**Would you like to work on the issue?**

Yes

**Comment by madhavrathi** [comment]
@Abhi2424shek  sir please comment on this.

**Comment by Abhi2424shek** [comment]
Yep you may work on it @madhavrathi and edit your comment to remove the sir title.

**Comment by madhavrathi** [comment]
@Abhi2424shek  Hey, i am done with adding filters.
can you provide me with the Original tree photo(Normal Filter) so that i can filtered thumbnail in drawables folder and add photobuttons for respective filters.

**Comment by madhavrathi** [comment]
@Abhi2424shek  @pa1pal  
https://github.com/fossasia/phimpme-android/pull/123
Please Review!
