### ISSUE TITLE
App crashing on launch

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1032]
**Actual Behaviour**

App crashes on launch

**Expected Behaviour**

App shouldn't crash

**Steps to reproduce it**
Open the app

**LogCat for the issue**

08-16 16:21:19.039 27825-27825/? E/Zygote: v2
08-16 16:21:19.039 27825-27825/? I/libpersona: KNOX_SDCARD checking this for 10270
08-16 16:21:19.039 27825-27825/? I/libpersona: KNOX_SDCARD not a persona
08-16 16:21:19.043 27825-27825/? E/Zygote: accessInfo : 0
08-16 16:21:19.044 27825-27825/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0007, [-1 -1 -1 -1 0 1]
08-16 16:21:19.046 27825-27825/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=org.fossasia.phimpme 
08-16 16:21:19.058 27825-27825/? I/art: Late-enabling -Xcheck:jni
08-16 16:21:19.096 27825-27825/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
08-16 16:21:19.115 27825-27832/? E/art: Failed sending reply to debugger: Broken pipe
08-16 16:21:19.115 27825-27832/? I/art: Debugger is no longer active
08-16 16:21:19.115 27825-27832/? I/art: Starting a blocking GC Instrumentation
08-16 16:21:19.571 27825-27825/? D/AndroidRuntime: Shutting down VM
08-16 16:21:19.576 27825-27825/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.fossasia.phimpme, PID: 27825
                                                   java.lang.RuntimeException: Unable to get provider com.google.firebase.perf.provider.FirebasePerfProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.provider.FirebasePerfProvider" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6423)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
                                                       at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
08-16 16:21:19.576 27825-27825/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.provider.FirebasePerfProvider" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6408)
                                                       	... 10 more

**Would you like to work on the issue?**

No, as I am not sure about the reason of the crash.

**Comment by anantprsd5** [comment]
@mayank8318 It's not crashing on my device so can you please take a pull from this branch and check whether its crashing or not. Thanks.
https://github.com/anantprsd5/phimpme-android/tree/testfixCrash

**Comment by mayank8318** [comment]
@anantprsd5 It is still crashing.
**Logcat**
08-17 07:24:16.992 18191-18191/? E/Zygote: v2
08-17 07:24:16.992 18191-18191/? I/libpersona: KNOX_SDCARD checking this for 10271
08-17 07:24:16.992 18191-18191/? I/libpersona: KNOX_SDCARD not a persona
08-17 07:24:16.994 18191-18191/? E/Zygote: accessInfo : 0
08-17 07:24:16.994 18191-18191/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0007, [-1 -1 -1 -1 0 1]
08-17 07:24:16.997 18191-18191/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=org.fossasia.phimpme 
08-17 07:24:17.001 18191-18191/? I/art: Late-enabling -Xcheck:jni
08-17 07:24:17.102 18191-18191/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art: Rejecting re-init on previously-failed class java.lang.Class<org.fossasia.phimpme.MyApplication>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/multidex/MultiDexApplication;
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.VMClassLoader.findLoadedClass!(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:742)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:362)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader, java.lang.String, android.content.Context) (Instrumentation.java:1000)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at android.app.Application android.app.LoadedApk.makeApplication(boolean, android.app.Instrumentation) (LoadedApk.java:835)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5944)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1710)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.os.Looper.loop() (Looper.java:154)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6776)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1496)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1386)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a,
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.VMClassLoader.findLoadedClass!(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:742)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:362)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at android.app.Application android.app.Instrumentation.newApplication(java.lang.ClassLoader, java.lang.String, android.content.Context) (Instrumentation.java:1000)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at android.app.Application android.app.LoadedApk.makeApplication(boolean, android.app.Instrumentation) (LoadedApk.java:835)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5944)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1710)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.os.Looper.loop() (Looper.java:154)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6776)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1496)
08-17 07:24:17.718 18191-18191/org.fossasia.phimpme I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1386)
08-17 07:24:17.720 18191-18191/org.fossasia.phimpme D/AndroidRuntime: Shutting down VM
08-17 07:24:17.723 18191-18191/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 18191
                                                                      java.lang.RuntimeException: Unable to instantiate application org.fossasia.phimpme.MyApplication: java.lang.ClassNotFoundException: Didn't find class "org.fossasia.phimpme.MyApplication" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                          at android.app.LoadedApk.makeApplication(LoadedApk.java:846)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5944)
                                                                          at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
08-17 07:24:17.724 18191-18191/org.fossasia.phimpme E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.fossasia.phimpme.MyApplication" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          at android.app.Instrumentation.newApplication(Instrumentation.java:1000)
                                                                          at android.app.LoadedApk.makeApplication(LoadedApk.java:835)
                                                                          	... 9 more
                                                                      	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/multidex/MultiDexApplication;
                                                                          at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                          at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                          		... 12 more
08-17 07:24:17.724 18191-18191/org.fossasia.phimpme E/AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          		... 15 more

**Comment by mayank8318** [comment]
@anantprsd5 The app is now working with the latest commit. :)
Thanks
