### ISSUE TITLE
Some image is not visible in share activity

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#1039]
**Actual Behaviour**

Some image is not visible properly in share activity and image is not perfectly zoomed.

**Expected Behaviour**

It should visible.

**Steps to reproduce it**

Try with different images in share activity.

**Screenshots of the issue**

<img width=300 src="https://user-images.githubusercontent.com/9361754/29427955-15ed9f6a-83a9-11e7-914b-a8a32215b5df.png"/>

**Would you like to work on the issue?**

Yes.

**Comment by mayank8318** [comment]
@mohitmanuja One thing I observed is images taken from Phimpme Camera are never visible in Share Activity

**Comment by pa1pal** [comment]
@mayank8318 Yes.
I replaced the Universal Image Loader with Glide. It is working now, will open PR for this soon.
