### ISSUE TITLE
Image is zoomed-In in share Activity 

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#1044]
**Actual Behaviour**

Currently, the image is always zoomed-In in share Activity. This causes pixelating of the Image.

**Expected Behaviour**

The image should be displayed as the actual size and not zoomed in. 

**Steps to reproduce it**

Sharing Activity->ImageTouchView

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
Subhankar please check this issue : https://github.com/fossasia/phimpme-android/issues/1039

**Comment by vinaysajjanapu** [comment]
and also this is happening with smaller images @Subhankar29 
![screenshot_20170819-225609](https://user-images.githubusercontent.com/15368561/29488888-bca4f39c-8531-11e7-8a6c-6d473a440620.png)
