### ISSUE TITLE
No Loader to show while photo loads in SingleMediaActivity

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1045]
**Actual Behaviour**

No loader is shown while photo loads

**Expected Behaviour**

A progress bar should be shown while the image loads

**Steps to reproduce it**

Open any picture

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/22395998/29487233-af5ab082-8513-11e7-99b3-a31d1de54ed0.png)

**Would you like to work on the issue?**

Yes

**Comment by anantprsd5** [comment]
@mayank8318  To speed the image loading process, @mohitmanuja is working on implementing the image loading using the universal image loading library, so I don't feel the need for a loader here. https://github.com/nostra13/Android-Universal-Image-Loader
@vinaysajjanapu @pa1pal @Subhankar29 @mohitmanuja Suggestions?

**Comment by mohitmanuja** [comment]
@anantprsd5 Yes, I am working so please hold it now.

**Comment by mayank8318** [comment]
Oh that's cool then if the loading process can be made faster :+1:

**Comment by mohitmanuja** [comment]
@mayank8318 Yes, it is done. You can review https://github.com/fossasia/phimpme-android/pull/1047

**Comment by mayank8318** [comment]
@mohitmanuja Yes it loads faster!!
:+1:
