### ISSUE TITLE
Facebook access to the app to upload photos.

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#105]
**Actual Behaviour**

After the clicking the accounts "+" button and choosing facebook option the message prompts:
"App not Setup: This app is still in development mode, and you don't have access to it..."
**Expected Behaviour**

The facebook access should be granted so that users can upload the photos to facebook. 

**Steps to reproduce it**

Get a Facebook App ID, properly configured and linked to the app.
Add the Facebook SDK for Android to your project.
Add your Facebook app ID, display name, and URL scheme to your app's manifest.html file

**Screenshots of the issue**

![screenshot_2017-03-10-00-07-31-322](https://cloud.githubusercontent.com/assets/17337006/23765068/e69d1472-0525-11e7-861a-62974d352b22.jpeg)

**Would you like to work on the issue?**

Yes, Allow me to work on the issue.

**Comment by Abhi2424shek** [comment]
@mariobehling would be the person to look at it.

**Comment by pa1pal** [comment]
@Abhi2424shek This is known. As I implemented facebook integration. Rightnow my tested app is in the development. I will look in to this. Also the facebook integration and upload is working fine, no issues in this.
So @Subhankar29 I suggest you to work on some other account integration. 
Wordpress and Drupal are in higher priority, some contributors are working on it.

**Comment by Abhi2424shek** [comment]
@pa1pal good work as you got it right, I though it was Mario Behling who implemented the fb integration!
