### ISSUE TITLE
crashes on android O and slow to load

### ISSUE THREAD

**Issue by basavaraj1995** [fossasia/phimpme-android#1052]
uses more battery on android O DP4

**Comment by anantprsd5** [comment]
@basavaraj1995 I guess android o is still not official and the developer preview is only out as of now so it might be unstable. Let it officially release, then we can look for the Android O support for our application. Thanks!

**Comment by basavaraj1995** [comment]
May be tomorrow Android O is going to be official 😊

**Comment by anantprsd5** [comment]
@basavaraj1995 Please check this application if you get the official version tomorrow and reopen this issue if the problem persists. Thanks.

**Comment by basavaraj1995** [comment]
Okay
