### ISSUE TITLE
Add Label with issues and PRs

### ISSUE THREAD

**Issue by jsroyal** [fossasia/phimpme-android#108]
**Actual Behaviour**

There is very no labeling.

**Expected Behaviour**

Add labels with Issues and PRs like progress, need help, need to review, reviewing etc.

**Would you like to work on the issue?**
Yes, but it needs permission.
Please let me know if I can work on it.

**Comment by pa1pal** [comment]
Thanks @jsroyal for pointing. I agree there are very less labels in recent issue.
We will add them soon.

**Comment by jsroyal** [comment]
@pa1pal also progress if somebody working on that so it will easy to others.
