### ISSUE TITLE
Disappear image after resize in the editing mode

### ISSUE THREAD

**Issue by jsroyal** [fossasia/phimpme-android#109]
**Actual Behaviour**

when the editing mode and resize the image then disappear

**Expected Behaviour**
Do not disappear or a limited resize.
**LogCat for the issue**

03-10 12:10:39.692 6526-6526/vn.mbm.phimp.me E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
03-10 12:10:39.692 6526-6526/vn.mbm.phimp.me E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
03-10 12:10:41.702 6526-6526/vn.mbm.phimp.me D/HorizontalFling: OverScroller.fling() velocityX=0, ro.fling.distance.coef=1.0
03-10 12:10:41.882 6526-6526/vn.mbm.phimp.me D/HorizontalFling: SplineOverScroller.fling() getSplineFlingDistance(velocity)=0.0, getSplineFlingDuration(velocity)=0, mFinal=0
03-10 12:10:42.212 6526-6526/vn.mbm.phimp.me D/HorizontalFling: SplineOverScroller.fling() getSplineFlingDistance(velocity)=1106.3640979106378, getSplineFlingDuration(velocity)=977, mFinal=1401
03-10 12:10:42.852 6526-6526/vn.mbm.phimp.me I/HorizontalFling: SplineOverScroller.onEdgeReached() mFinal=404, mStart=295, mOver=109, mCurrentPosition=295
03-10 12:10:45.192 6526-6526/vn.mbm.phimp.me D/GestureDetector: Actiond[0] : 0Actiond[1] : 1
03-10 12:10:45.292 6526-6526/vn.mbm.phimp.me D/GestureDetector: Actiond[0] : 0Actiond[1] : 1
03-10 12:10:45.302 6526-6526/vn.mbm.phimp.me E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
03-10 12:10:45.302 6526-6526/vn.mbm.phimp.me E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

**Screenshots of the issue**
![screenshot_2017-03-10-12-00-52](https://cloud.githubusercontent.com/assets/10773353/23785204/7c2ab010-058c-11e7-830c-c63641fdff3a.png)

**Comment by Abhi2424shek** [comment]
If you could make a fix, we would be happy to read your PR.

**Comment by jsroyal** [comment]
Sure! @Abhi2424shek I'm still reading codebase of this project. Also, my term exam ongoing so it will take time.

**Comment by Abhi2424shek** [comment]
Is'nt this solved?

**Comment by Abhi2424shek** [comment]
It's solved.
