### ISSUE TITLE
Toolbar does not disappear on scrolling down

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1098]
**Actual Behaviour**

Toolbar is always present when I scroll down the image folders or pictures.

**Expected Behaviour**

Toolbar should disappear on scrolling down so that there is more space in the screen to see photos or other media folders and appear again when we scroll up.

**Steps to reproduce it**

Just open the app and start scrolling or open any folder and start scrolling

**LogCat for the issue**

.

**Screenshots of the issue**
This is how I expect the app to behave.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/20878145/30245991-8f32dddc-9609-11e7-9588-763491ea8f38.gif)

**Would you like to work on the issue?**
Yes

**Comment by mohitmanuja** [comment]
@nikit19 Go ahead  👍

**Comment by nikit19** [comment]
@mohitmanuja I have sent the PR. Please review
