### ISSUE TITLE
Camera Activity should be full screen - hide the bottom navigation 

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1104]
**Actual Behaviour**

The bottom navigation bar is still there when camera is opened

**Expected Behaviour**

The bottom navigation bar should disappear enabling the camera activity to take full screen size

**Steps to reproduce it**

Open camera 

**Would you like to work on the issue?**

Yes

**Comment by mayank8318** [comment]
@mohitmanuja What do you think?

**Comment by mohitmanuja** [comment]
@mayank8318 Then we need to press back button to go to previous activity which not look good. So imo let it be visible.

**Comment by mayank8318** [comment]
@mohitmanuja Ok. I thought we could have given full screen to the camera.
We can also do this -> Shift the camera navigation to a FAB on the home screen and the navigation can be only for Home and Accounts with a swipe to change pages like most app these days?

**Comment by vinaysajjanapu** [comment]
The way it is now is fine.
