### ISSUE TITLE
The name of the selected folders should be displayed on the toolbar

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1105]
**Actual Behaviour**

Currently when the user is either on local folders or hidden folders,there is no way to tell which one is selected.

**Expected Behaviour**

The name of the selected folders should be displayed on the toolbar.

**Steps to reproduce it**

Just open the app or select hidden folders from the navigation drawer  you will see "phimpme" written on the toolbar.

**Screenshots of the issue**

![screenshot_20170910-140226](https://user-images.githubusercontent.com/20878145/30270211-61e38b1e-9709-11e7-8bd2-67e459f9734b.png)

**Would you like to work on the issue?**

Yes

**Comment by mohitmanuja** [comment]
👍

**Comment by sanketkumar1996** [comment]
I would like to work on the same, if no one else has already taken it up !

**Comment by nikit19** [comment]
I am working on it!
