### ISSUE TITLE
Improving the UI of Basic Theme Dialog Box

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1108]
**Actual Behaviour**
In the Basic Theme Dialog Box in Settings Activity , when the user selects any particular theme , he doesn't get to know whether he has selected it or not i.e as the White,Dark and Dark Amoled belong to TextView there isn't any kind of reveal when the user selects any of the option.So the person isn't sure if the option has been selected or not.

**Steps to reproduce it**
2 solutions are possible here:
1) The TextViews can be converted to Button.
2) Radio Buttons can be added in front of each of the views so that views can be switched easily and also making the dialog box more appealing. 

**Screenshots of the issue**
![dialogbox](https://user-images.githubusercontent.com/20684618/30306073-d707049a-9793-11e7-92ae-7eae0acf7d08.jpg)

**Would you like to work on the issue?**
Yes!

**Comment by NamanRawat1** [comment]
Another solution for this to make a tick mark in front of theme which is selected.What do you think?@sridharjajoo

**Comment by mohitmanuja** [comment]
Yes, I agree with naman.

**Comment by sridharjajoo** [comment]
So should I add a checkbox in front of each view?

**Comment by sridharjajoo** [comment]
![darktheme](https://user-images.githubusercontent.com/20684618/30335348-b718ec22-97ff-11e7-8147-8849a4ec9d7d.png)

**Comment by mohitmanuja** [comment]
Yes, it's fine.
