### ISSUE TITLE
Fossasia contributors link not working in About activity

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1109]
**Actual Behaviour**

When we click on Fossasia contributors link in About activity nothing happens.

**Expected Behaviour**
On clicking on Fossasia contributors it should open this link https://github.com/fossasia/phimpme-android/graphs/contributors

**Steps to reproduce it**

Open the app. Select about and click on fossasia contributors link.

**Screenshots of the issue**
![screenshot_20170912-104920](https://user-images.githubusercontent.com/20878145/30309297-2e3ae40c-97a8-11e7-885e-0d36b2ecfdb0.png)

**Would you like to work on the issue?**

Yes

**Comment by Siddharth-Singhs** [comment]
Are you working on it?

**Comment by nikit19** [comment]
Yes. I am just waiting for the maintainers to approve it before I send a PR.

**Comment by mohitmanuja** [comment]
@nikit19 Go ahead.
