### ISSUE TITLE
Changing the flow of the App

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1110]
**Actual Behaviour**
The current behaviour can be explained by the following example.
Suppose a user navigates to the **Accounts**  from the **Gallery**  and again returns back to **Gallery** by clicking the Gallery tab.If the user now presses the back button to come out of the app , he is redirected to the Accounts page once again which is not what the user wants. 

**Expected Behaviour**
In my opinion the user should come out of the app immediately.

**Steps to reproduce it**
We need to add a clear top flag when the Gallery tab is pressed.

**Would you like to work on the issue?**
Yes!

**Comment by sridharjajoo** [comment]
@mohitmanuja Is this a valid issue?Should I work on it?

**Comment by mohitmanuja** [comment]
I don't think so. @anantprsd5 review.
