### ISSUE TITLE
App Crashes on API 17 Backward Compatibilty Issue

### ISSUE THREAD

**Issue by wookupmaker** [fossasia/phimpme-android#1117]
**Actual Behaviour**
App Crashes on API 17

**Expected Behaviour**
Work fine on API 17 as mentioned in the app level build.gradle file 
`minSdkVersion:17`

**Steps to reproduce it**
Install app on device running API 17 to API 19

**LogCat for the issue**
https://goo.gl/2WjmvN

**Screenshots of the issue**
![](https://goo.gl/RJBzqy)

**Would you like to work on the issue?**
YES!

**Comment by NamanRawat1** [comment]
#1122 pull request may solve this issue

**Comment by wookupmaker** [comment]
@NamanRawat1 Did you create the issue first before sending the PR?

**Comment by wookupmaker** [comment]
@anantprsd5 Can we just fix the issue without creating the issue over github and kick a PR, I mean I'm waiting for you to approve the issue, I already solve the problem with the project but didn't trigger the PR, because I thought first I have to create a issue and then you or any other project maintainer will assign this to me then I'll send the PR. Am I wrong here?

**Comment by NamanRawat1** [comment]
I make a pull request, not for this issue.I thought your issue can be solved by taking the idea of my pull request that's why I comment on your issue. You can check if my pull request can solve your issue too. @wookupmaker

**Comment by wookupmaker** [comment]
@NamanRawat1 Yup get it but its different

**Comment by wookupmaker** [comment]
@mohitmanuja  please take a look....
