### ISSUE TITLE
Bug in Gallery menu of the App

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1118]
**Actual Behaviour**
When we select multiple photo albums in the **Gallery** activity , the Toolbar title "Local Folders" changes to a counter of number of images which are being selected appears on the Toolbar which replaces the toolbar title.But now when we press the back button to exit  the title doesn't change i.e suppose 4 albums were selected from possible 9 albums , the title remains 4/9 even after back button is pressed.

**Expected Behaviour**
The title should change to Local Folders.

**Steps to reproduce it**
1) Select a few albums by long pressing on them.
2) Press the back button and observe the toolbar title.

**Would you like to work on the issue?**
Yes!

**Comment by sridharjajoo** [comment]
@mohitmanuja @anantprsd5 Can I work on it?Is it a valid issue?

**Comment by anantprsd5** [comment]
@sridharjajoo Sure. Go ahead!
