### ISSUE TITLE
Current launcher icon has white edges

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1119]
**Actual Behaviour**

Current launcher icon has white edges because of which it looks a bit smaller.

**Expected Behaviour**

We should use the real icon of the app.
I would be using this https://github.com/fossasia/phimpme-android/blob/development/docs/logo.png

**Steps to reproduce it**

Look at the launcher icon in the home screen.

**Screenshots of the issue**

![screenshot_20170912-223001](https://user-images.githubusercontent.com/20878145/30339646-566f3972-980d-11e7-8c2d-bd0fc47be1fb.png)

**Would you like to work on the issue?**

Yes.

**Comment by nikit19** [comment]
@mohitmanuja should I send a PR for this?

**Comment by mohitmanuja** [comment]
Yes
