### ISSUE TITLE
CursorIndexOutOfBoundsException at the time of App launch.

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#112]
**Actual Behaviour**

When we try to open the app on phones having photos less than 21, the app crashes with CursorIndexOutOfBoundsException.

**Expected Behaviour**

The app should not crash.

**Steps to reproduce it**

Try to run the app on an emulator with no photos.

**Would you like to work on the issue?**

Yes. Already worked on it. Sending the PR.

**Comment by pa1pal** [comment]
#113
