### ISSUE TITLE
Lag while closing of Navigation Drawer

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1124]
**Actual Behaviour**
Currently when we select either of **Settings**,**Upload History**,**About** from the Navigation Drawer the intent for the new Activity is fired and due to this the exit animation of the drawer isn't completed.Because of this the animation doesn't appear to be smooth.

**Expected Behaviour**
The exit animation should be completed fully and after that a new intent should be fired.

**Steps to reproduce it**
In the navigation drawer select either of the options mentioned above.

**Would you like to work on the issue?**
Yes!

@mohitmanuja Can I work on this issue?

**Comment by mohitmanuja** [comment]
Yes.
