### ISSUE TITLE
The name of the app is incorrect at various places

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1127]
**Actual Behaviour**

The name of the app is "Phimp.me" yet there are various places where "Phimpme" is written.

**Expected Behaviour**

"Phimp.me" should be written everywhere instead of "Phimpme"

**Steps to reproduce it**

There are various places in the app where the name is written wrong like below the launcher icon,in the navigation drawer("Share Phimpme"),3 times in the about activity etc

**Screenshots of the issue**
![screenshot_20170913-234733](https://user-images.githubusercontent.com/20878145/30394208-0adbeacc-98e0-11e7-8779-9c511efee9cc.png)
![screenshot_20170913-235823](https://user-images.githubusercontent.com/20878145/30394264-3d93bc24-98e0-11e7-896a-759417d6a685.png)
![screenshot_20170913-235840](https://user-images.githubusercontent.com/20878145/30394243-2f0d82a2-98e0-11e7-9c45-5a49ce37de46.png)

**Would you like to work on the issue?**
Yes

**Comment by nikit19** [comment]
@mohitmanuja should I send a PR for this?

**Comment by mohitmanuja** [comment]
Sure, Go ahead.
