### ISSUE TITLE
Kitkat 4.4 did not support drawable ripple 

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/phimpme-android#1132]
**Actual Behaviour**
App crashes or not showing app icon when running on KitKat 4.4 may be because Android drawable resource definitions (prior API 21) CANNOT use theme attributes at all.
**Expected Behaviour**
The app should work on KitKat 4.4  and able to use theme attributes in this version.

**Steps to reproduce it**
1.Run on an emulator in the android studio with KitKat using x86 images. 
2.Observe the application in emulator
OR
1.Run on the mobile device having android 4.4 KitKat version.

**Would you like to work on the issue?**
  YES

**Comment by vinaysajjanapu** [comment]
@NamanRawat1 could you add logcat for the crash in the description?

**Comment by NamanRawat1** [comment]
Not showing app icon in my emulator.I run it on a real device.

**Comment by vinaysajjanapu** [comment]
You can work on it if you wish.

**Comment by vinaysajjanapu** [comment]
@NamanRawat1 We used an vector icon for app icon. Use png image instead of vector and see if the problem still exists.

**Comment by NamanRawat1** [comment]
Even if the app icon becomes visible the issue(#1132) still will be there for lower versions.  We only created vector file for version>21  and in our build(module-app) we set minsdk to 17. So we must have set drawable vector files for version<21  so that app does not get crash. For this problem i send a pull request already.
