### ISSUE TITLE
Back button is not working when editMode and all_photos are true

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1133]
**Actual Behaviour**

Back button is not working in editMode when all_photos mode is selected and some photos are long pressed.

**Expected Behaviour**

Back button should clear all selected photos and come out of editMode.

**Steps to reproduce it**
Open the app. Select the all photos icon. Select 2-3 photos. click on the back button

**Screenshots of the issue**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20878145/30415393-7f0b09f4-9945-11e7-8c16-676d45f19a5a.gif)

**Would you like to work on the issue?**

Yes

**Comment by nikit19** [comment]
@mohitmanuja  should I send a PR for this?

**Comment by mohitmanuja** [comment]
Yes, Go ahead.
