### ISSUE TITLE
Changing toolbar transparency for Media Viewer is not working

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/phimpme-android#1137]
**Actual Behaviour**
toolbar transparency not changing in media viewer theme in Settings

**Expected Behaviour**
On changing transparency, toolbar must changes color according to it

**Steps to reproduce it**
1.Go to Settings
2.Customize Viewer->Media Viewer Theme
3.Change the transparency

**Would you like to work on the issue?**
YES

**Comment by sridharjajoo** [comment]
It is changing..
after selecting the any of the transparency **click on any of your pictures**..you would see the toolbar colour at that particular location getting changed.
