### ISSUE TITLE
Code contains mixed up spaces and tabs

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#114]
**Actual Behaviour**

The code contains mixed up tabs and spaces. This causes indentations to look messy!

**Expected Behaviour**

There should be a consistent indentation through out the code

**Steps to reproduce it**
1. File >  Settings > Editor > General > Appearance
2. Tick _Show Whitespaces_

**LogCat for the issue**
> Not available

**Screenshots of the issue**
![random](https://cloud.githubusercontent.com/assets/14261304/23823991/71f267c4-0694-11e7-8188-52c4977841e9.png)

**Would you like to work on the issue?**
One can take it! :gift:

**Comment by Abhi2424shek** [comment]
This should be done only when the PRs are 0 in number, we don't want to cause conflicts!
