### ISSUE TITLE
Add a Square Fit editing option in the App

### ISSUE THREAD

**Issue by neelanshsahai** [fossasia/phimpme-android#1140]
We can add a new Editing option with which a square image can be obtained without croping or scaling the image.
For example :-

**Original Image**

![20111207_android_fragmentation_001](https://user-images.githubusercontent.com/20770414/30443790-671670e6-999e-11e7-89ba-981f3322227a.jpg)

**Edited Image**

![whatsapp image 2017-09-14 at 10 23 28 pm](https://user-images.githubusercontent.com/20770414/30443809-79499856-999e-11e7-9fd9-ee695378d738.jpeg)

**I would like to work on this issue**

**Comment by mohitmanuja** [comment]
Go ahead.

**Comment by neelanshsahai** [comment]
@mohitmanuja thanks 😄 
I will create a PR by 25th of September

**Comment by neelanshsahai** [comment]
@mohitmanuja I am currently working on this Issue but I wont be able to create a PR by tomorrow.
So will it be okay if I take some time on it?
I will try to make it as soon as possible.

**Comment by mohitmanuja** [comment]
Ok

**Comment by batbrain7** [comment]
@mohitmanuja no progress for a long time may I take it?

**Comment by neelanshsahai** [comment]
@batbrain7 yeah...
although I am stuck at a point and that is why was unable to give any updates
please feel free to give it a try :wink: :+1: 
meanwhile I will also try to implement the same

**Comment by ashley8jain** [comment]
Now I am implmenting

**Comment by mariobehling** [comment]
Closing due to lower priority. Thanks.
