### ISSUE TITLE
Image Not Viewing Properly while toggling between Landscape and Portrait

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1144]
**Actual Behaviour**
2 images are shown instead of one while toggling between landscape and portrait and image is also not properly positioned.

**Expected Behaviour**

It should be properly positioned and viewed while switching between the landscape and portrait only that specific image should be viewed in that mode instead of two with distorted positions.

**Steps to reproduce it**
Go to a folder open image now change mode to landscape and then to portrait.

**LogCat for the issue**

09-15 02:15:35.993 7870-7870/org.fossasia.phimpme I/PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more.

**Screenshots of the issue**

![screenshot_2017-09-15-02-10-13](https://user-images.githubusercontent.com/20026440/30455040-02b5c67e-99bc-11e7-8277-e7e14123b49b.png)

**Would you like to work on the issue?**
Yes!

@mohitmanuja  @anantprsd5  kindly review the issue!

**Comment by codedsun** [comment]
@mohitmanuja @anantprsd5 @pa1pal @Subhankar29 Kindly review.

**Comment by mohitmanuja** [comment]
Go ahead.

**Comment by batbrain7** [comment]
@mohitmanuja its been a month and no progress yet, may I work on this?

**Comment by mohitmanuja** [comment]
@batbrain7 sure.

**Comment by batbrain7** [comment]
@mohitmanuja after intense research on this issue I would like to suggest to use the library : 
https://github.com/davemorrissey/subsampling-scale-image-view
and not include photoview package as that package contains existing issues that are not rectified yet, Or else I can just add that library and see how it works and then apply it to places where photoview package is being used?

**Comment by ashley8jain** [comment]
@mohitmanuja I agree with @batbrain7 , I need to use the subsampling-scale-image-view package instead of photoview package.

**Comment by ashley8jain** [comment]
this issue resolved as #1629 PR is merged. Kindly close this issue. @codedsun
