### ISSUE TITLE
Copying to same folder

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/phimpme-android#1145]
**Actual Behaviour**

When the user selects some image and tries to copy it to the same folder. It creates a copy of the same image in a folder.

**Expected Behaviour**
Not allow the user to copy the same image to a folder already containing it.

**Steps to reproduce it**
1.Select any folder image
2.Go to overflow menu and select Copy to
3.Select the same folder
4.See the duplicate image created in the same folder

**Would you like to work on the issue?**
YES
@mohitmanuja  Can I work on this issue?

**Comment by mohitmanuja** [comment]
Go ahead.

**Comment by vinaysajjanapu** [comment]
I don't see any issue here. In all applications copy function works this way.
Just display a confirmation dialog aksing user whether to duplicate the image or cancel copying.
That would be fine.
