### ISSUE TITLE
Action Bar is not coming on image selection

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1146]
**Actual Behaviour**

On image selection, action bar is not coming all of its own, the user has to scroll little upwards.

**Expected Behaviour**

Action Bar should come all of its own on image selection so that user can see how many images he has selected.

**Steps to reproduce it**

Open up the app, scroll a little, select images, but action bar will not come on its own!

**Screenshots of the issue**

![giphy](https://user-images.githubusercontent.com/21143936/30463119-917703f2-99e7-11e7-966a-da041883605c.gif)

**Would you like to work on the issue?**

Yes
@anantprsd5 @mohitmanuja Can I work on this issue?

**Comment by mohitmanuja** [comment]
👍
