### ISSUE TITLE
Add press back twice to exit

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1148]
**Actual Behaviour**

If the user presses back once the app exits.

**Expected Behaviour**

After first back press, display a toast telling the user to press back twice to exit.

**Steps to reproduce it**

Press back from the home screen

**Would you like to work on the issue?**

Yes

**Comment by Navd15** [comment]
hey..@mayank8318 i wuld like to work on this one..

**Comment by mayank8318** [comment]
@Navd15 I have almost finished the task and I will send a PR soon.
Maybe you can work on some other issue :)
