### ISSUE TITLE
Highlighting selected option while applying Filters

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1149]
**Actual Behaviour**
Currently while we are editing the photos , the option (Filter,Enhance,Transform,Stickers,Write)  which is selected isn't highlighted.

**Expected Behaviour**
When the user selects a particular option it should be highlighted.

**Steps to reproduce it**
1) Select an album .
2) Open any of the picture in full screen mode.
3) Go to edit option at the bottom.

**Would you like to work on the issue?**
Yes!
@mohitmanuja @anantprsd5 Can I work on this issue?

**Comment by sridharjajoo** [comment]
@vinaysajjanapu Actually the highlighting wasn't visible on my Redmi Phone so I created an issue.I apologize.

**Comment by vinaysajjanapu** [comment]
No need to apologize. It is fine.
You are making good contributions. Please continue to do so. Thanks.
