### ISSUE TITLE
Multiple warnings on building the project

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1153]
**Actual Behaviour**
On building the project , multiple warnings are issued which can be suppressed.

**Expected Behaviour**
The number of warnings should be minimum.

**Steps to reproduce it**
Go to Android Studio and build the project.

**LogCat for the issue**
Warning:(110, 39) [unchecked] unchecked cast
required: ArrayList<Album>
found:    Object
Warning:(145, 64) [unchecked] unchecked cast
required: ArrayList<Album>
found:    Object
/home/sridhar123/Desktop/PhimpMe/phimpme-android/app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java
Warning:(413, 19) [unchecked] unchecked call to add(E) as a member of the raw type List
where E is a type-variable:
E extends Object declared in interface List
Warning:(414, 19) [unchecked] unchecked call to add(E) as a member of the raw type List
where E is a type-variable:
E extends Object declared in interface List
Warning:(415, 19) [unchecked] unchecked call to add(E) as a member of the raw type List
where E is a type-variable:
E extends Object declared in interface List
Warning:(416, 19) [unchecked] unchecked call to add(E) as a member of the raw type List
where E is a type-variable:
E extends Object declared in interface List
Warning:(418, 24) [unchecked] unchecked method invocation: method login in class PDKClient is applied to given types
required: Context,List<String>,PDKCallback
found: AccountActivity,List,<anonymous PDKCallback>
Warning:(418, 31) [unchecked] unchecked conversion
required: List<String>
found:    List
Information:BUILD SUCCESSFUL
Information:Total time: 3 mins 21.357 secs
Information:0 errors
Information:8 warnings
Provide logs for the crash here

**Would you like to work on the issue?**
Yes

**Comment by sridharjajoo** [comment]
@mohitmanuja
Can I send a PR for this?

**Comment by vinaysajjanapu** [comment]
yes please work on it
