### ISSUE TITLE
Changing Navigation Icon on image/album selection

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1155]
**Actual Behaviour**

When image and album is/are selected, navigation icon is checked, but on clicking it every selection by the user is gone!

**Expected Behaviour**

According to the functionality, navigation icon should be X(Cross) instead of a check.

**Steps to reproduce it**
Just select any album or image.

**Screenshots of the issue**

![tempimg](https://user-images.githubusercontent.com/21143936/30509306-21f6b59c-9acb-11e7-871f-aeab7c52a4e8.jpeg)

**Would you like to work on the issue?**

Yes!
Should I work on this? @mohitmanuja @anantprsd5

**Comment by anantprsd5** [comment]
Go ahead.
