### ISSUE TITLE
Toolbar title changes on navigation icon after selecting an album

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1156]
**Actual Behaviour**

On Clicking navigation icon after selecting album(s), toolbar title changes to All

**Expected Behaviour**

Toolbar title should not change.

**Steps to reproduce it**

Select any album, toolbar title changes

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![giphy](https://user-images.githubusercontent.com/21143936/30510371-18b206de-9ae0-11e7-801f-733345185ecb.gif)

**Would you like to work on the issue?**

Yes

**Comment by Navd15** [comment]
@aditya98ak hey.... i would like to work on this one...

**Comment by aditya98ak** [comment]
@Navd15 I have done the changes!
