### ISSUE TITLE
Save button isn't visible after applying filters

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1162]
**Actual Behaviour**
While editing the photos the 5 possible options available are **Filter**,**Enhance**,**Transform**,**Stickers** and **Write**.When we select either of **Filter** or **Enhance** and select the apply button in the bottom slider fragment,the save button to the top right corner is invisible.

**Expected Behaviour**
After applying either of the above filters , the save option should be visible.

**Steps to reproduce it**
1) Go to editing mode of any of the picture.
2) Click on **Filter** or **Enhance**.
3) In the slider present below press on apply button.

**Screenshots of the issue**

![image 3](https://user-images.githubusercontent.com/20684618/30512921-6c6e2bfe-9b17-11e7-9a2d-9919e94847e6.jpg)

The **SAVE** button is invisible.

**Would you like to work on the issue?**
Yes!

@anantprsd5 @mohitmanuja Can I send a PR?

**Comment by anantprsd5** [comment]
Please do.
