### ISSUE TITLE
Toolbar should show automatically when album or photo is selected

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1166]
**Actual Behaviour**

This does not happen if the user is scrolling because of the scroll flags.

**Expected Behaviour**

The toolbar should be fixed if any item is selected.

**Steps to reproduce it**

Scroll till the toolbar disappears and then select any item.

**Screenshots of the issue**

![21742604_1806886932673446_3522559956580564992_n](https://user-images.githubusercontent.com/22395998/30518534-3899a808-9b9e-11e7-8f0c-a6b0b6f45ce9.gif)

**Would you like to work on the issue?**

Yes

**Comment by aditya98ak** [comment]
Please have a look at issue #1146

**Comment by mayank8318** [comment]
@aditya98ak Sorry my bad!!
