### ISSUE TITLE
Highlight edit sub-option just like the edit option

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1167]
**Actual Behaviour**

The edit sub-option like HUE in the screenshot is not highlighted when it is selected.

**Expected Behaviour**

It should be highlighted

**Steps to reproduce it**

Go to edit any photo and select any effect to add.

**Screenshots of the issue**

![21298069_1806911089337697_5885298401859338240_n](https://user-images.githubusercontent.com/22395998/30518814-8a086998-9ba5-11e7-8fc5-ae07545ab059.gif)

**Would you like to work on the issue?**

Yes
@mohitmanuja @vinaysajjanapu Should this be there?

**Comment by mohitmanuja** [comment]
Yes, Go ahead.

**Comment by vinaysajjanapu** [comment]
Sure work on it.
