### ISSUE TITLE
Revamping the UI of Upload History Option

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1168]
**Actual Behaviour**
Currently the UI of Upload History is quite simple and not very appealing.

**Expected Behaviour**
I would like to improve the UI of Upload History activity by adding card views to individual item and styling the text views.

**Steps to reproduce it**
Go to Upload History option from navigation drawer.

**Screenshots of the issue**

![](http://imageresize.org/Output/e8f25dee-695e-4632-b632-b8c085ed8c2f.jpg)

**Would you like to work on the issue?**
Yes!

@anantprsd5 @mohitmanuja Is it a valid enhancement?Can I work on  it?

**Comment by mohitmanuja** [comment]
Go ahead.

**Comment by sridharjajoo** [comment]
![uploadhistory](https://user-images.githubusercontent.com/20684618/30554216-666147a4-9cc1-11e7-8344-ea06de5144f0.png)
@mohitmanuja Kindly suggest any changes. The title bar color (Background Color of WHATSAPP,INSTAGRAM etc.) is the primary color which is applied to the app and changes if we change the primary color from the settings activity.

**Comment by mohitmanuja** [comment]
Keep the item size small and you can use the icon i.e whatsapp, flickr instead of name.

**Comment by sridharjajoo** [comment]
Does this look appealing?
@mohitmanuja @vinaysajjanapu 

![image 5](https://user-images.githubusercontent.com/20684618/30964453-069a7bd2-a46f-11e7-8d7d-aa7448ac5fa9.jpg)
