### ISSUE TITLE
Change language in the app

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#117]
**Actual Behaviour**

The app runs on the default language.

**Expected Behaviour**

Option to change the language of the app from the app settings itself.

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by Abhi2424shek** [comment]
We will first get the app working then work on localization.

**Comment by pa1pal** [comment]
I agree with @Abhi2424shek. I'm closing this now, we will reopen it once app is in stable condition.
