### ISSUE TITLE
Improve the UI of crop ratios list in editor 

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#1171]
**Actual Behaviour**

Currently, the list has only text items and is not visibly good.

![screenshot_20170917-211136](https://user-images.githubusercontent.com/15368561/30522400-e97aa2c8-9bec-11e7-9a59-020ee3f0c6ce.png)

**Expected Behaviour**

Add icons and make other changes to make it look some like this.

![screenshot_20170917-211035](https://user-images.githubusercontent.com/15368561/30522410-037b9092-9bed-11e7-8305-f19004787762.png)

**Steps to reproduce it**

Open image in editor -> transform -> crop

**Would you like to work on the issue?**

Anyone can take this issue.

**Comment by sridharjajoo** [comment]
I would like to do it

**Comment by vinaysajjanapu** [comment]
yeah, go on. 
Also the there are many ratios which are never used. Remove them and add some useful ratios.

**Comment by codedsun** [comment]
@sridharjajoo Are u working on it? else I want to take the issue.
Thanks.

**Comment by sridharjajoo** [comment]
@codedsun I am working on it!

**Comment by sridharjajoo** [comment]
![img_20171001_182703](https://user-images.githubusercontent.com/20684618/31054716-cdb9ee8c-a6d6-11e7-8a16-b469feb7477c.jpg)
Should I try to include the crop ratio slider as well?
@vinaysajjanapu @anantprsd5
