### ISSUE TITLE
Viewing any pic should be full screen

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1173]
**Actual Behaviour**

The image view is not full screen it shows the toolbar and the action menu.

**Expected Behaviour**

It should show the image in full screen(Immersive Mode) and on touching the image should show these toolbar and action bar and navigation menu.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
On Touching the image
![screenshot_2017-09-17-22-43-19](https://user-images.githubusercontent.com/20026440/30523153-e69cec66-9bf9-11e7-9132-ec29843a8736.png) |

Actual view
 ![screenshot_2017-09-17-22-43-53](https://user-images.githubusercontent.com/20026440/30523154-e6ec92e8-9bf9-11e7-8a60-752a832fbc05.png)

**Would you like to work on the issue?**
Yes! 

@Subhankar29 @mohitmanuja @anantprsd5 Kindly review.

**Comment by vinaysajjanapu** [comment]
@codedsun Hide the elements on touching the image.

When the user clicks on the image thumbnail in the gallery for preview let the toolbar and actionbar be visible and when the user touches the image again hide the toolbars and show the image in full screen.

**Comment by codedsun** [comment]
@vinaysajjanapu ok sure :+1:

**Comment by mohitmanuja** [comment]
@codedsun use toggleUi function.

**Comment by codedsun** [comment]
This means that I will have to create a toggleUi function and do the work in the following?

**Comment by mohitmanuja** [comment]
There is already a function in single media activity. Use that function.

On Sep 18, 2017 7:48 PM, "Suneet Srivastava" <notifications@github.com>
wrote:

This means that I will have to create a toggleUi function and do the work
in the following?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/phimpme-android/issues/1173#issuecomment-330237364>,
or mute the thread

**Comment by codedsun** [comment]
shall I add an onClick listener to the parent layout or to the recycler view?How to know the user touch events?.Need help!

**Comment by codedsun** [comment]
stucked in ImageAdapter.java ,in imageview.onClick listener ,it's not passing values through basicCallBack while performing touch on that image, i also logged some text in that function but no log is also shown.What shall be the issue?
