### ISSUE TITLE
Changing the background of Filter Icon and Switch Camera Icon

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1174]
**Actual Behaviour**

The filter icon and switch camera icon are not visible with a white background image.

**Expected Behaviour**

In Camera View, Filter Icon and Switch Camera icon should be provided with black/grey background and circular image button can be used instead of image button as while rendering an image which has a white background, these icons are not visible to the user.

**Steps to reproduce it**
Open Camera ,switch to front or render  white background /daylight.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes!

**Comment by yashLadha** [comment]
Can i send a PR for the same issue? @codedsun

**Comment by codedsun** [comment]
@yashLadha can u share the screenshot of the changes you made.because I was also trying to set the filter icon background but it's not setting up properly.

**Comment by codedsun** [comment]
Will be working on it today and sending the PR fot the same.

**Comment by yashLadha** [comment]
Sure. Cheers

On Tue, Sep 19, 2017 at 2:21 PM, Suneet Srivastava <notifications@github.com

**Comment by yashLadha** [comment]
I am interested to work on this issue but due to my mid sem exams, i can't work right now. I just glanced over it and it looked good for me. If you want to work on this issue them GFI. Else pling me :wink:
