### ISSUE TITLE
Selected medias are not cleared while pressing the back button

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1176]
**Actual Behaviour**
While viewing all the images under All Images section ,and selecting images to delete but while back pressing those selected medias are not cleared and still remain selected.

**Expected Behaviour**
On back press the selected medias should be cleared.

**Steps to reproduce it**

Go to App,on the toolbar click on Image Thumbnail /All photos view button.
Select images and then press back button.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-09-18-20-22-40](https://user-images.githubusercontent.com/20026440/30548232-3c21c5ac-9caf-11e7-9074-4d1cc623561b.png)

**Would you like to work on the issue?**
Yes !

@anantprsd5 @mohitmanuja Kindly review .

**Comment by mohitmanuja** [comment]
Go ahead.

**Comment by codedsun** [comment]
Closing issue! Someone has done it in their own PR and now its working.
