### ISSUE TITLE
Facebook account addition UI fix

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#118]
**Actual Behaviour**

An additional activity with "continue with facebook" button is opening which is out of given workflow.

**Expected Behaviour**

Facebook should be opened directly on clicking in the dialog box.

**Screenshots of the issue**

![screenshot_2017-03-12-01-59-43](https://cloud.githubusercontent.com/assets/13241256/23826726/ab29f38e-06c8-11e7-96a2-0c25eadd23f7.png)

**Would you like to work on the issue?**

Yes I would like to work on it.

**Comment by Abhi2424shek** [comment]
Yes pls go on.
