### ISSUE TITLE
Zoom functionality is not working 

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1184]
**Actual Behaviour**
Earlier on double clicking zoom was working but now it is not working

**Expected Behaviour**
The image should be able to zoom in/out on double-clicking it.

**Steps to reproduce it**
Just open up an image and double click it to zoom

**Screenshots of the issue**

![giphy](https://user-images.githubusercontent.com/21143936/30654681-457b645c-9e4c-11e7-9388-6593e1de8297.gif)

**Would you like to work on the issue?**

Yes

**Comment by aditya98ak** [comment]
@mohitmanuja @anantprsd5 @vinaysajjanapu Review this, 
Also, I was thinking to implement gestures, i.e pinch-in-out gesture.
What do you all say?
Should I work on it?

**Comment by aditya98ak** [comment]
@mohitmanuja @mayank8318 Should I resolve pinch-zoom in this issue only?
I have fixed the changes.
I am asking @mayank8318, as you have opened a similar issue :)

**Comment by mayank8318** [comment]
@aditya98ak If you have already fixed it, then cool go ahead with it.
