### ISSUE TITLE
Implementing Delete functionality in description of Image.

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1189]
**Actual Behaviour**

There is no Toast msg after the description is updated and no delete option to delete a description of an image.

**Expected Behaviour**

1.Added a delete option in AlertDialog Box
2.Shows a toast msg after every description saved or being deleted
3.The delete button will show error msg by toast if the user tries to delete a description of the image without giving a prior description.
4.EditText with empty string will not be saved as description

**Steps to reproduce it**

**Screenshots of the issue**

![20170922-013914 = 250x250 ](https://user-images.githubusercontent.com/20026440/30716462-beefcaa8-9f37-11e7-9032-6ecfe9a18b7e.gif)

**Would you like to work on the issue?**

Yes ! @anantprsd5 @mohitmanuja @Subhankar29

**Comment by Subhankar29** [comment]
@codedsun everything is alright. Just use snack bar beside toast.

**Comment by codedsun** [comment]
@Subhankar29 ok adding and sending a PR.

**Comment by codedsun** [comment]
@Subhankar29 while using Snackbar.handler(parentview,"String") the following snackbar is not visible .

**Comment by codedsun** [comment]
@Subhankar29 the Snackbar is visible in vertical layout while not in horizontal one.Please guide me for the same ,what could be the issue.
