### ISSUE TITLE
Background when input is prompted

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1201]
**Actual Behaviour**

The titlebar expands in the background when any kind of input is prompted from the user.

**Expected Behaviour**

This should not happen.

**Steps to reproduce it**

Try to rename an album, or apply a password.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/22395998/30781869-a0e17796-a144-11e7-80c4-3e53552912cd.png)

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@mayank8318 I think this issue is resolved, kindly close the issue.
