### ISSUE TITLE
Improve UI of SingleMediaActivity

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1203]
**Actual Behaviour**

The UI of SingleMediaActivity does not have a pinch-to-zoom feature and there is unnecessary margin at the top.

**Expected Behaviour**

It should have pinch-to-zoom. 

**Steps to reproduce it**

Open any image

**Would you like to work on the issue?**

Yes

**Comment by mohitmanuja** [comment]
@mayank8318 It is already there but due to toggleUI it is not working. Try to find how to handle toggleUI with zoom.

**Comment by mayank8318** [comment]
@mohitmanuja Ok I will do that.
