### ISSUE TITLE
Implementing Rename Functionality for Image

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1207]
**Actual Behaviour**

There is no rename functionality in an image name.

**Expected Behaviour*

Add rename button and sets the name of the image according to the user.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes! @anantprsd5 @mohitmanuja @vinaysajjanapu Kindly Review !

**Comment by anantprsd5** [comment]
@codedsun This was already there and we removed this feature actually as it is of very less use. So I wouldn't recommend this feature to be implemented.

**Comment by codedsun** [comment]
Ok ! Closing this issue.
