### ISSUE TITLE
Feature to add Frames to an Image

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1211]
**Actual Behaviour**

We should integrate a feature that can apply frames to an Image.

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes! @mohitmanuja @anantprsd5 Please review!

**Comment by abishekvashok** [comment]
Please go on :)
