### ISSUE TITLE
Add animation when toolbar veiws chanegs (eg when an item is selected)

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1212]
**Actual Behaviour**

There is no animation while changing views visibility in toolbar

**Expected Behaviour**

Some Animation should be there...

**Steps to reproduce it**

Open app, select any album., views of toolbar changes suddenly without any animation.

**Would you like to work on the issue?**

Yes.

**Comment by aditya98ak** [comment]
@anantprsd5 @mohitmanuja @vinaysajjanapu Should I start working on this?

**Comment by vinaysajjanapu** [comment]
Any demo or explanation on how it's gonna look after adding animation

**Comment by aditya98ak** [comment]
@vinaysajjanapu 
The same thing I want  to do
https://stackoverflow.com/questions/30787373/android-how-to-make-transition-animations-on-toolbars-menu-icons
What do you say?

**Comment by aditya98ak** [comment]
@vinaysajjanapu Should I start working on it?

**Comment by aditya98ak** [comment]
@vinaysajjanapu What if circular reveal is used?
