### ISSUE TITLE
Size of image reduces on rotation several times

### ISSUE THREAD

**Issue by nb2998** [fossasia/phimpme-android#1213]
**Actual Behaviour**

On rotating the image and saving it multiple times the size of image keeps on reducing.

**Expected Behaviour**

The size of image should not be affected on rotating image.

**Steps to reproduce it**

Open the app, start editing and move to Transform edit mode. Rotate the image and apply the changes. Repeat this several times and the size of image will keep on reducing.

**Screenshots of the issue**
1.
![screenshot_2017-09-25-20-50-38-126_org fossasia phimpme](https://user-images.githubusercontent.com/25134501/30820831-c8eff5e4-a240-11e7-99b5-78b656debcb3.png)

2.
![screenshot_2017-09-25-21-02-17-765_org fossasia phimpme](https://user-images.githubusercontent.com/25134501/30820848-d237d81a-a240-11e7-97d2-9075c7918428.png)

**Would you like to work on the issue?**

Yes

**Comment by nb2998** [comment]
@vinaysajjanapu @anantprsd5 @mohitmanuja Shall I work on this? Please guide me.

**Comment by vinaysajjanapu** [comment]
@nb2998 yeah start working on it

**Comment by codedsun** [comment]
This issue has been solved ! Close this issue please:)
