### ISSUE TITLE
App crashes on Samsung galaxy s8

### ISSUE THREAD

**Issue by shubham23596** [fossasia/phimpme-android#1227]
**Actual Behaviour**

Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by shubham23596** [comment]
app not working on Samsung galaxy s8

**Comment by codedsun** [comment]
@shubham23596 kindly fill in the description of the issue, like what is the actual behaviour,logcat etc.

**Comment by 0x48piraj** [comment]
Please provide `logs` :+1:

**Comment by codedsun** [comment]
No logs has been provided, kindly close this issue!
