### ISSUE TITLE
Hide the status bar in splash screen

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/phimpme-android#1234]
**Actual Behaviour**

Currently status bar is grey in colour in splash screen which is not recommended and hiding the status bar in splash screen is appropriate and we have done that in susi android also in intro activity.

**Expected Behaviour**

Status Bar should be hidden

**Screenshots of the issue**
this looks better and is recommended style of showing splash screen
<img src=https://user-images.githubusercontent.com/21264401/30982796-27fc7f14-a4a6-11e7-9248-1c93d90807ab.jpeg width="300" height="500">

<img src=https://user-images.githubusercontent.com/21264401/30982844-4a6d981c-a4a6-11e7-9500-ee67fe9e0d82.jpeg  width="300" height="500">

**Would you like to work on the issue?**
Yes

**Comment by mohitmanuja** [comment]
@Arshilgenius please check project.

**Comment by Arshilgenius** [comment]
@mohitmanuja  i am really sorry.
