### ISSUE TITLE
Old looking alert dialogs!

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#124]
**Actual Behaviour**

The system exit alert dialog is not material designed!

**Expected Behaviour**

The dialog boxes need to be designed according to material design guidelines

**Steps to reproduce it**

1. Open app
2. Press _Back Key_ and try to exit the app

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![old](https://cloud.githubusercontent.com/assets/14261304/23831849/12ec38de-074f-11e7-8863-82f7014257a3.png)

**Would you like to work on the issue?**

It's just change of imports to fix this. If this is really an issue and if a new potential contributor wants to start contributing, he can have it :) If not I can do it :)

**Comment by Abhi2424shek** [comment]
A beginner could claim this.

**Comment by Sanjayjeyavel** [comment]
Hey! I will try to work on this issue! It would be of great help if you could give me some references!

**Comment by Abhi2424shek** [comment]
All you need to do, is to update library by changing the import statement.

**Comment by CloudyPadmal** [comment]
Hello there!! Try to fix this and you will get to know the main classes! :) the fix needs to be done at the "PhimpMe.java" class :)

**Comment by Sanjayjeyavel** [comment]
I have a doubt! The style for the default dialog boxes are determined by appcompat right? So using the latest version of it should include material design right?

**Comment by CloudyPadmal** [comment]
@Sanjayjeyavel we can start an open conversation on slack about custom dialog boxes :D

**Comment by Sanjayjeyavel** [comment]
Sure.. Ill ping you!

**Comment by vaibhavsingh97** [comment]
@CloudyPadmal  I can fix this.

**Comment by Abhi2424shek** [comment]
@Sanjayjeyavel are you on it? :)
If not,
@vaibhavsingh97 can work on it but only after he replies. Till then you could find any other issues.

**Comment by Sanjayjeyavel** [comment]
@Abhi2424shek  I am working on it... just give me two days!

**Comment by Abhi2424shek** [comment]
It's fixed.
