### ISSUE TITLE
No details dialog for album

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1241]
**Actual Behaviour**

Currently there is no option to see details of an album

**Expected Behaviour**

There should be a details dialog for albums too similar to the one already present for photos.

**Steps to reproduce it**

Open the app. Long press any album.

**Would you like to work on the issue?**

Yes

**Comment by AkshayCHD** [comment]
I would like to work on this issue

**Comment by nikit19** [comment]
@AkshayCHD I have already solved this issue and sent the PR

**Comment by AkshayCHD** [comment]
Okk cool
