### ISSUE TITLE
Add an option to check details of an image

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#125]
**Actual Behaviour**

There is no option to display particular details like time, resolution etc. of the images.

**Expected Behaviour**

There should be an info button to check the basic details of the images, something like the below screen shot.

**Screenshots of the issue**

![photo_2017-03-12_21-42-20](https://cloud.githubusercontent.com/assets/20367966/23833503/d8d8d5c6-076c-11e7-81ca-3e6c32ff97f3.jpg)

**Would you like to work on the issue?**

Yes. Would love to.

**Comment by anantprsd5** [comment]
@Abhi2424shek @pa1pal Please review.

**Comment by Abhi2424shek** [comment]
Ok pls go on, but don't open it on a new activity, a pop-up is enough.

**Comment by anantprsd5** [comment]
@Abhi2424shek Yeah, I was thinking about a pop-up only.

**Comment by pa1pal** [comment]
#146
