### ISSUE TITLE
Improve the UI of AccountsActivity. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1256]
**Actual Behaviour**

The current UI for the Accounts Activity can be improved.

**Expected Behaviour**

Enhanced UI for AccountsActivity .

**Steps to reproduce it**

Open the AccountsActivity.

**Screenshots of the issue**

![screenshot_2017-10-02-11-04-20-566_org fossasia phimpme](https://user-images.githubusercontent.com/20841578/31065347-19bcedc6-a762-11e7-9e52-132f10eb1b18.png)

**Would you like to work on the issue?**

Yes.

**Comment by robillo** [comment]
I would like to work on this issue.

**Comment by AndyScherzinger** [comment]
I'd like to work on this.
Do you have anything in particular in mind?

What I would do for starters would be to add separators to the items, change the icon size and padding to standard material design and material design 1-line list item design recommendations.

**Comment by AndyScherzinger** [comment]
Can't get the app to run at all, probably needs linux or else. So anybody willing to take over feel free.

**Comment by sauravvishal8797** [comment]
@AndyScherzinger I'm already working on it. And yes for linux it is working fine.
