### ISSUE TITLE
Remake Snowy and Round Corner Icons as other Filters

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#126]
**Actual Behaviour**

The snow filter and rounded corner filter have different image buttons than rest of the filters
![screenshot_2017-03-12-17-47-01-775_vn mbm phimp me](https://cloud.githubusercontent.com/assets/22375731/23841985/66fef8c0-07d7-11e7-87cb-61744287cdbe.png)

**Expected Behaviour**

@Abhi2424shek  All the filters should have same photobutton.

**Steps to reproduce it**

As i have created all the other icons i can replace it too

**Would you like to work on the issue?**

Yes.

**Comment by Abhi2424shek** [comment]
It would be a simple fix, please go ahead.

**Comment by madhavrathi** [comment]
@Abhi2424shek https://github.com/fossasia/phimpme-android/pull/128
please review.
