### ISSUE TITLE
Canvas size too large while photo editing

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1265]
**Actual Behaviour**
Currently while we are painting on the photo the strokes can also be made outside the actual photo as shown in the figure below.
![image 5](https://user-images.githubusercontent.com/20684618/31126137-622d5404-a868-11e7-9086-353a84fc5f40.jpg)
The photo area is only the middle part while the rest of black part isn't a part of the photo.
But still we are able to draw on the black part as well which should't be the case as ultimately when the image is saved , it excludes that particular part as shown below.
![image 10](https://user-images.githubusercontent.com/20684618/31126229-a919fd86-a868-11e7-99a5-c94fc47db610.jpg)

**Expected Behaviour**
The painting strokes should only be made on the photo part and not on the outside.

**Would you like to work on the issue?**
Yes!
@mohitmanuja @anantprsd5 Can i work on it?

**Comment by mohitmanuja** [comment]
Go ahead.
