### ISSUE TITLE
Adding floating labels for all the Edittexts.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1268]
**Actual Behaviour**

The label acts as hint in the Edittext when the field is empty, when the users starts typing the labels disappear.

**Expected Behaviour**

When user start inputting the text, label starts animating by moving to floating label position.

**Steps to reproduce it**

Start inputting in the edittexts.

**Screenshots of the issue**

![screenshot_2017-10-03-21-29-11-290_org fossasia phimpme](https://user-images.githubusercontent.com/20841578/31135196-eb41969c-a881-11e7-88b0-84dd95d1380c.png)

**Would you like to work on the issue?**

Yes.

**Comment by codedsun** [comment]
@sauravvishal8797 I am not getting it what is the issue? please explain and if this is not needed, kindly close this issue.

**Comment by sauravvishal8797** [comment]
@codedsun It's not needed, I'm closing this issue.
