### ISSUE TITLE
Add a logo for the app.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/phimpme-android#127]
**Actual Behaviour**

There is nothing like a precisive logo for the app.

**Expected Behaviour**

The app should have a logo.

**Steps to reproduce it**

See the app icon on the home screen

**Would you like to work on the issue?**

Who is that designer who want this issue?

**Steps to solve the issue**

- [ ] Suggest a good icon for the app on the issue as a comment and get the icon approved by the people around here.

- [ ] Replace the icon on the app as it's logo as well as on the splash screen.

**Comment by madhavrathi** [comment]
can i work on this ? @Abhi2424shek

**Comment by dynamitechetan** [comment]
<table>
<tr>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/23848960/72fce646-07ff-11e7-8fde-bb392380cda7.png">
</td>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/23848977/85033da4-07ff-11e7-8b84-4b7c16f6ee01.png">
</td>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/23848900/328ee5e6-07ff-11e7-9e90-0d56eb00a993.png">
</td>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/23849053/eb1d111e-07ff-11e7-9856-8e8edef587f6.png">
</td>
</tr>
</table>

**Comment by dynamitechetan** [comment]
@mariobehling @Abhi2424shek @pa1pal Please Review the Icon.

**Comment by Abhi2424shek** [comment]
Basically it's a photo app so, don't take it up as a competition --- nothing in open source is a competition --- since, both of you @dynamitechetan and @madhavrathi are interested can you two cooperate and come up with one, use slack for communication, it would do you two good for sure. Others are also welcomed to join.

An icon relevant for the app!

**Comment by madhavrathi** [comment]
@dynamitechetan  hey your icon is great and @Abhi2424shek  i am currently developing mine so it will be a while. and if you wanna go ahead with icon above , i think it's great !

**Comment by Abhi2424shek** [comment]
IMO something related to a photo app?

**Comment by dynamitechetan** [comment]
@Abhi2424shek didn't I understood your last comment?

**Comment by madhavrathi** [comment]
@Abhi2424shek Just give me 2 hours,  i will finish up touching by then and then @dynamitechetan  we'll pick the best one.

**Comment by dynamitechetan** [comment]
My idea behind this icon was Location, Photos, Colors and the "P" of Phimpme.

**Comment by dynamitechetan** [comment]
@madhavrathi okay

**Comment by madhavrathi** [comment]
![1](https://cloud.githubusercontent.com/assets/22375731/23852852/df6988a6-080f-11e7-93f5-06b77b81c6e3.png)
@Abhi2424shek @dynamitechetan Hey check this out and you can suggest colors accordingly

**Comment by madhavrathi** [comment]
@Abhi2424shek @dynamitechetan   It seems like @dynamitechetan's  icon is better as it signifies what the app is about and regarding the colour, i guess second one of his icons seems good.

**Comment by dynamitechetan** [comment]
@madhavrathi  thanks.

**Comment by Abhi2424shek** [comment]
Ya, IMO 1st one.

**Comment by dynamitechetan** [comment]
I do think 1st one because it matches the blue theme of the app.

**Comment by madhavrathi** [comment]
@Abhi2424shek  hey what about the splash screen ?

**Comment by Abhi2424shek** [comment]
We will use an enlarged version.

**Comment by Abhi2424shek** [comment]
Let some more guys comment before we could accept things.

**Comment by anantprsd5** [comment]
I think the blue one by @dynamitechetan is great as it clearly depicts each and every thing about the app. This could be a great icon for this app IMO.

**Comment by AliAyub007** [comment]
![phimpme](https://cloud.githubusercontent.com/assets/25840461/23881718/1b1d5cc4-087e-11e7-8d7a-4d010d6fefed.png)
Here is my contribution. Give me some time I can design a professional one (till tomorrow). If you want to choose it now then logo by @dynamitechetan is really nice.

**Comment by Abhi2424shek** [comment]
@pa1pal whts your thoughts

**Comment by pa1pal** [comment]
I like @dynamitechetan Logo, which depicts all the expect. The reactions on the image also shows the people's votes. But right now we also don't have much options to select. We should wait for while till then we can get more options as well as Mario Behling permission for logo.

**Comment by heysadboy** [comment]
![phimplogo](https://cloud.githubusercontent.com/assets/22588035/23901807/dac568c6-08e4-11e7-9b6f-c4d12d0b02c8.png)

@pa1pal @Abhi2424shek Adding another one for muse

**Comment by anant-dev** [comment]
![untitled 1](https://cloud.githubusercontent.com/assets/13196029/24199021/284900c2-0f2e-11e7-93e3-7c701a66a456.png)

@pa1pal @Abhi2424shek how is this icon, i can improvise it with your suggestions

**Comment by mohitmanuja** [comment]
@Abhi2424shek  Please open this issue again because we need a logo for Phimpme.

**Comment by AliAyub007** [comment]
I am in different project but I made one for this earlier. Though this is splash screen but there is logo also. 
![title](https://cloud.githubusercontent.com/assets/25840461/26338181/8f7571a6-3f97-11e7-9c40-b24524a4a480.jpg)

**Comment by mohitmanuja** [comment]
@pa1pal @anantprsd5 @subhankar29 @vinaysajjanapu we require app icon for phimpme. Please give suggestions from the above icons.

**Comment by Subhankar29** [comment]
Well, I like the one made by @aliAyub007 it shows the necessary elements of the app.

**Comment by anantprsd5** [comment]
Icon made by @dynamitechetan is good I feel. Many other contributers also reacted to the icon.
![72fce646-07ff-11e7-8fde-bb392380cda7](https://user-images.githubusercontent.com/20367966/27002347-42cbff04-4dfd-11e7-8723-3eca0eece273.png)

**Comment by vinaysajjanapu** [comment]
@dynamitechetan 's icon looks good. But it will be apt for a camera application. It doesn't signify anything related to editing or sharing (which are our main features). Let's see if we can find any better icon. if not we will use this.

**Comment by vinaysajjanapu** [comment]
![phimpme_logg1](https://user-images.githubusercontent.com/15368561/27400246-285ebe98-56dd-11e7-9788-af439c1cc442.png)
![phimpme_logo copy](https://user-images.githubusercontent.com/15368561/27400264-30bf292e-56dd-11e7-8a89-4d9b18f860cb.png)
![phimpme_logo1](https://user-images.githubusercontent.com/15368561/27400268-330ef524-56dd-11e7-8263-c9bdf58bcaa2.png)
![phimpme_logo copy1](https://user-images.githubusercontent.com/15368561/27400272-35e2adf4-56dd-11e7-93a8-680ac17d177f.png)

Check these icons.
The camera in middle signifies camera feature of the app.
The arrow in letter P is supposed to signify sharing and brush stroke with which P is written should signify art or editing.

**Comment by pa1pal** [comment]
@vinaysajjanapu nice logo and with your explanation it looks much more good. :+1:

**Comment by Subhankar29** [comment]
@vinaysajjanapu Looks good. 👍

**Comment by pa1pal** [comment]
according to me, @vinaysajjanapu logo is nice, let's go with it for our first release of Phimpme.

**Comment by mariobehling** [comment]
Great!

**Comment by vinaysajjanapu** [comment]
@mariobehling Thanks
