### ISSUE TITLE
Improve UI of Upload History

### ISSUE THREAD

**Issue by nb2998** [fossasia/phimpme-android#1285]
**Actual Behaviour**

The current UI for the Upload History can be improved.

**Expected Behaviour**

Enhanced UI for UploadHistory .

**Steps to reproduce it**

Open the Upload History.

**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
@nb2998 I have already submitted the P.R for the same
Issue:[#1168](https://github.com/fossasia/phimpme-android/issues/1168)
PR:[#1264](https://github.com/fossasia/phimpme-android/pull/1264)
