### ISSUE TITLE
No feature to add photos to favourite collection. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1289]
**Actual Behaviour**

Currently there is no option to add photos to users favourite collection.

**Expected Behaviour**

Option to add photos to favourite collection should be there. It will help users to keep track of important photos and so they would not need to go through every photo to find important ones. A favourites folders will be there to display all the favourite marked photos.

**Steps to reproduce it**

Click on any photo, there is no option to add it to favourites.

**Would you like to work on the issue?**

Yes.

**Comment by sauravvishal8797** [comment]
@anantprsd5 Please reopen the issue, I will be doing one more commit for this issue.

**Comment by anantprsd5** [comment]
@sauravvishal8797 I guess the option to add photos to  favourites is added. I would suggest you to open another issue for other enhancements and proceed.

**Comment by sauravvishal8797** [comment]
@anantprsd5 Sure.
