### ISSUE TITLE
Color Picker for text isn't visible

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1297]
**Actual Behaviour**
When editing the image and adding text to it the color picker option isn't visible to the user.

**Expected Behaviour**
It should be visible.

**Steps to reproduce it**
1) Go to the editing mode of the image
2) Select Write->Text.
3) Beside the edittext , there actually exists a color picker option but isn't visible to the user.

**Screenshots of the issue**
![image 15](https://user-images.githubusercontent.com/20684618/31308379-bf281800-ab93-11e7-97f3-58e64d1a9b56.jpg)

**Would you like to work on the issue?**
Yes!

**Comment by ahsanbarkati** [comment]
@sridharjajoo I am new to FOSSASIA and I would like to contribute to this issue. I request you to please guide me on how to start with this issue. Where is the related code to be fixed?. Thank you.

**Comment by sridharjajoo** [comment]
@ahsanbarkati To start contributing you would have to first clone the Phimp.Me repo and then start testing the app on your device.If you find an issue kindly mention it in the issues section.Currently I am working on this particular issue.You can work on other isssues :)
