### ISSUE TITLE
UI of Camera Settings

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1303]
**Actual Behaviour**

The UI of camera settings is not theme based.

**Expected Behaviour**

The UI should be theme based.

**Steps to reproduce it**

Open settings and select camera settings.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/22395998/31316939-38ada340-ac55-11e7-9045-3dc8cd94c9f0.png)

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
What happened?

**Comment by mayank8318** [comment]
The whole Camera Settings section is written in traditional Preferences screen with heavy nesting. I think we cannot style it as of now. We will have to change the whole structure to resemble our Settings screen which is written in a custom manner with cards.
