### ISSUE TITLE
Add more effects in edit image from media options

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#131]
**Actual Behaviour**

Presently the edit option in media contains only few filters.

**Expected Behaviour**

We should add all the other filters which are present in camera preview

**Steps to reproduce it**

As i have added all the other camera filters, i will add them here too with suitable photo buttons

**Screenshots of the issue**
![screenshot_2017-03-14-06-43-48-207_vn mbm phimp me](https://cloud.githubusercontent.com/assets/22375731/23881676/fe3fbd5a-0881-11e7-87c8-7597862fa21e.png)

**Would you like to work on the issue?**

Yes

**Comment by madhavrathi** [comment]
@Abhi2424shek  @pa1pal @mariobehling  Please Review

**Comment by Abhi2424shek** [comment]
Yes @madhavrathi pls go on.

**Comment by madhavrathi** [comment]
@Abhi2424shek @pa1pal  https://github.com/fossasia/phimpme-android/pull/132
Please Review

**Comment by Abhi2424shek** [comment]
@madhavrathi pls see the comments
