### ISSUE TITLE
No option to flip an image

### ISSUE THREAD

**Issue by ahsanbarkati** [fossasia/phimpme-android#1310]
**Actual Behaviour**

The app does not have an option to flip the image in the edit mode.

**Expected Behaviour**

It should have the feature to flip the image both horizontally and vertically i.e. mirror imaging the image.

**Would you like to work on the issue?**
  Yes
should I add this feature? @mohitmanuja @anantprsd5

**Comment by abishekvashok** [comment]
Yep @ahsanbarkati
