### ISSUE TITLE
Memory management inside the app

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1311]
**Actual Behaviour**
Currently the app is leaking a lot of memory as shown in the canary leak.This leak is found out while opening the LFMainActivity as well as the EditImageActivity.

**Expected Behaviour**
The app shouldn't leak so much of memory . Memory leak is caused because of the static reference to the context .

**Screenshots of the issue**
![image 21](https://user-images.githubusercontent.com/20684618/31342231-b60ee37e-ad29-11e7-86e8-48a642382827.jpg)

**Would you like to work on the issue?**
Yes!

**Comment by codedsun** [comment]
Copy of #1655 Kindly close this issue and start working on that issue.

**Comment by isuruAb** [comment]
Copy of #1655

**Comment by codedsun** [comment]
![hy7az5ci](https://user-images.githubusercontent.com/20026440/36397395-9af603ba-15e8-11e8-9ad7-71c2a3c6619d.jpg)
