### ISSUE TITLE
UI Update for replacing the Bottom ActionBar in LFMainActivity

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1312]
**Actual Behaviour**

Their is action bar for navigating between the camera, gallery and accounts sections.

**Expected Behaviour**

Updating the UI so that on swipe left and swipe right we can navigate to these section.

**Would you like to work on the issue?**

Yes!

**Comment by sauravvishal8797** [comment]
@codedsun Will you be implementing fragments and viewpagers to achieve the same?

**Comment by mohitmanuja** [comment]
Copy of https://github.com/fossasia/phimpme-android/issues/711 and read comments.

**Comment by codedsun** [comment]
Closing this issue!
