### ISSUE TITLE
Updating Accounts activity

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1317]
**Actual Behaviour**

Currently, as theme is changed, item in accounts activity gets faded

**Expected Behaviour**

This should not be done

**Steps to reproduce it**

Change the basic theme, re-visit the account's activity

**Screenshots of the issue**
See the variation with the themes.
![2](https://user-images.githubusercontent.com/21143936/31391503-5a4c8ac0-adf4-11e7-88ed-c04dc0fc80d9.jpeg)

![1](https://user-images.githubusercontent.com/21143936/31391496-55ad81b8-adf4-11e7-80d8-f8d8281fd001.jpeg)

![3](https://user-images.githubusercontent.com/21143936/31391505-5cad6adc-adf4-11e7-8e6c-fd8e6f9e23d1.jpeg)

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
This issue has been resolved I think, Kindly close the issue!
