### ISSUE TITLE
Snackbar not displayed on performing copy or move operations in SingleMedia Activity. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1323]
**Actual Behaviour**

No toast message is displayed on copy and move operations. 

**Expected Behaviour**

An appropriate toast message should be displayed on the success or failure of the operation. 

**Steps to reproduce it**

Perform the copy or move operation for photos. 

**Would you like to work on the issue?**

Yes.

**Comment by sridharjajoo** [comment]
The above issue has already been resolved!
Issue:[#1165](https://github.com/fossasia/phimpme-android/issues/1165)
PR:[#1191](https://github.com/fossasia/phimpme-android/pull/1191)

**Comment by sauravvishal8797** [comment]
@sridharjajoo But options to copy or move are also provided in the overflow menu of the SingleMedia Activity and there no message is shown after the operation.
