### ISSUE TITLE
Adding link contribute.md file in Readme file

### ISSUE THREAD

**Issue by jsroyal** [fossasia/phimpme-android#133]
**Actual Behaviour**

Not link contribute.md file in readme.md

**Expected Behaviour**

Add link here so it will easy for see the coding style

**Steps to reproduce it**
![screenshot from 2017-03-14 11-28-56](https://cloud.githubusercontent.com/assets/10773353/23887714/9acb8240-08a9-11e7-8d03-5315da3d7fba.png)

**Comment by Abhi2424shek** [comment]
Easy fix pls make a PR

**Comment by jsroyal** [comment]
@Abhi2424shek Sure!
