### ISSUE TITLE
No selection reponse when selecting a basic theme.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1333]
**Actual Behaviour**

When we select a theme there is no response if a theme is selected, although the desired theme is selected.

**Expected Behaviour**

There should be a response showing that our desired theme is selected and now I can press OK.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by gautamjajoo** [comment]
When you select a particular theme , an arrow mark is visible in front of the theme.
