### ISSUE TITLE
No option to display details for folders. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1340]
**Actual Behaviour**

Currently there is no option to display all the details about a particular folder. 

**Expected Behaviour**

On performing long press on a folder an option should be there in the menu to display all the details about the particular folder. 

**Steps to reproduce it**

Long press on any folder. No option in the overflow menu to display details. 

**Would you like to work on the issue?**

Yes.

**Comment by nikit19** [comment]
Hi @sauravvishal8797 
this issue was already raised in #1241 
and solved with the PR #1243
