### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by m-murad** [fossasia/phimpme-android#1343]
There is a typo in the `readme.md` file in `apk` branch.
Fixing this.

**Comment by AdityaGupta030697** [comment]
Can I work on this? there are still some more typos.

**Comment by codedsun** [comment]
@AdityaGupta030697 Go on!

**Comment by abishekvashok** [comment]
I am going to close this. After we got a stable readme, we wi merge the same with the apk branch

**Comment by AdityaGupta030697** [comment]
Sure.
