### ISSUE TITLE
Improving UI for zooming of picture

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1345]
**Actual Behaviour**

Image is zoomed perfectly but the layout bounds for image view needs to be fixed, Currently, Image is not taking space of status bar and bottom bar when zoomed

**Expected Behaviour**

This should not happen

**Steps to reproduce it**

Zoom any image. It will not make use of the full screen, in fact, its layout will be limited.

**Screenshots of the issue**
This screenshot is of the full zoomed image, still, it is not using space of status bar and bottom bar.
![temp](https://user-images.githubusercontent.com/21143936/31572936-8f6d0bc6-b0ce-11e7-97ac-7c64fa17264e.jpeg)

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
Already fixed via #1360
