### ISSUE TITLE
Add Image Recoginition feature for Default image caption

### ISSUE THREAD

**Issue by xyphanajay** [fossasia/phimpme-android#1347]
**Actual Behaviour**

Images have no caption by default while sharing. Users have to add Caption every time.

**Expected Behaviour**

Add default caption by using Open Source Image Recognition API.

**Screenshots of the issue**

![screenshot_20171015-150655](https://user-images.githubusercontent.com/22711787/31583492-c27fbefe-b1ba-11e7-9d00-83bbe1542f94.jpg)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by abishekvashok** [comment]
Any updates
