### ISSUE TITLE
No option to delete items from Upload history.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1349]
**Actual Behaviour**

There is no option to delete items from upload history.

**Expected Behaviour**

There should be an option to delete upload history items.

**Steps to reproduce it**

Go to Upload history.

**Would you like to work on the issue?**

Yes.

**Comment by sd1998** [comment]
@sauravvishal8797 are you still working on the issue?

**Comment by sauravvishal8797** [comment]
@sd1998 Yeah. Will let you know if need any help.

**Comment by codedsun** [comment]
@sauravvishal8797 Can I work on this issue?

**Comment by abishekvashok** [comment]
@codedsun since it's been long, you can :)

**Comment by sauravvishal8797** [comment]
@abhishe I have done some work on it, was unable to work on it for some reasons, will try to finish work on this as soon as possible. Will mention it here if I face some problem.
