### ISSUE TITLE
"Press back again to exit" should be a SnackBar message

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1352]
**Actual Behaviour**

Currently a Toast message is displayed when the user tries to exit the app.

**Expected Behaviour**

We should use a SnackBar message instead of Toast message inLFMain activity

**Steps to reproduce it**

Open the app and press the back button

**Screenshots of the issue**

![screenshot_20171016-191651](https://user-images.githubusercontent.com/20878145/31615452-3b3b7e7c-b2a7-11e7-8b19-200b52a2a687.png)

**Would you like to work on the issue?**

Yes

**Comment by nityanandagohain** [comment]
I would like to work on this issue please guide me.

**Comment by nikit19** [comment]
Hi @nityanandagohain 
I have already solved this issue with the PR #1356
