### ISSUE TITLE
App crashing on selecting Description

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1366]
**Actual Behaviour**
The app is currently crashing after selecting Description of an image.

**Expected Behaviour**
The app shouldn't crash.

**Steps to reproduce it**
Select any of the image and then select the **Description** from the menu.

**Would you like to work on the issue?**
Yes!

**Comment by sauravvishal8797** [comment]
@sridharjajoo The description dialog seems to be working fine. Can you please check again and confirm the issue. Thanks.

**Comment by sridharjajoo** [comment]
@sauravvishal8797 It is crashing in my phone
