### ISSUE TITLE
On pinning album to top it is still shown as selected

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1371]
**Actual Behaviour**

When an album is pinned to the top, it is still shown as selected but the selection mode is off.

**Expected Behaviour**

The album should be unselected or selection mode should be on.

**Steps to reproduce it**

Select an album.
Select Pin to Top from overflow menu.

**Screenshots of the issue**

![22286920_1840910455937760_6074409819106705408_n](https://user-images.githubusercontent.com/22395998/31819289-a6eaa8ea-b5b9-11e7-9dba-b4f8b9a11082.gif)

**Would you like to work on the issue?**

Yes

**Comment by willyao94** [comment]
Hi, I'd like to work on this task. Would you like the expected behaviour to keep selection mode on or unselect the album?

**Comment by mayank8318** [comment]
@willyao94 I have already solved the issue and I am about to send the PR. Maybe you can work on some other issue.
Thanks.
