### ISSUE TITLE
Adding the Description of an image in Details dialog

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1373]
**Actual Behaviour**
Currently the Details dialog box doesn't consist of the description of any particular image which it should.

**Expected Behaviour**
When a user writes a description of an image it should appear inside the details dialog box as it is one of the details of the image.

**Steps to reproduce it**
Select any image and go to the details dialog box.

**Screenshots of the issue**
![image 24](https://user-images.githubusercontent.com/20684618/31821211-f813b59c-b5c1-11e7-9ac6-4980116b96ba.jpg)

**Would you like to work on the issue?**
Yes!

**Comment by codedsun** [comment]
I have made this in #1275
