### ISSUE TITLE
Fix Phimpme website and documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#1376]
The Phimpme website is currently not deploying automatically with Yaydoc. In order to fix this, please help with the following:
1. Set up Yaydoc on Google Cloud https://github.com/fossasia/yaydoc
2. Register Phimpme Android with your Yaydoc Setup
3. Auto-deploy the website documentation to the gh-pages branch (there is an existing Yaml helping with that here https://github.com/fossasia/phimpme-android/blob/development/.yaydoc.yml)
4. Open issues to use https://github.com/fossasia/sphinx_phimpme_theme and improve theme

**Comment by codedsun** [comment]
I want to work on this issue!

**Comment by codedsun** [comment]
@mariobehling Could u please guide me for the step1?

**Comment by yashLadha** [comment]
@mariobehling as i see there is no update on this issue from a long time. Can i work on this?

**Comment by abishekvashok** [comment]
@yashLadha it's working but screenshots are not showing. Please view that issue.
