### ISSUE TITLE
App crashing on performing the move operation for multiple photos. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1378]
**Actual Behaviour**

On performing move operation for multiple photos,  the app crashes. .

**Expected Behaviour**

The app should not crash on performing move operation for multiple photos. 

**Steps to reproduce it**

Perform move operation for multiple photos. 

**Would you like to work on the issue?**

Yes.

**Comment by yashLadha** [comment]
Can you share the error log? @sauravvishal8797

**Comment by sauravvishal8797** [comment]
@yashLadha The move operation is working fine now,  guess there was some problem with my device.  So I'm closing this issue.
