### ISSUE TITLE
Adding Album shortcut to HomeScreen

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1383]
**Actual Behaviour**
Currently there is no option to add album shortcuts to home screen of the phone.

**Expected Behaviour**
There can be an option to add shortcuts to home screen so that the user is directly able to access the albums without opening the app.

**Screenshots of the issue**
Shortcuts like the following can be added to the homescreen!

![image 25](https://user-images.githubusercontent.com/20684618/31858771-a5147040-b71d-11e7-9325-195ec024cf38.jpg)

**Would you like to work on the issue?**
Yes!

**Comment by abishekvashok** [comment]
@sridharjajo any updates?

**Comment by yashLadha** [comment]
If the user clicks on any album them
* Will it redirects the user to the app?
* Will it is redirecting the user to the photos (Google Photos/ Gallery)?
@sridharjajoo

**Comment by sridharjajoo** [comment]
@abishekvashok I have almost done the task but was facing an issue somewhere.I will try to complete the task within 2-3 days.
