### ISSUE TITLE
Fix Image Selection, by long click

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1388]
**Actual Behaviour**

After selecting an image, selecting another image by long pressing, results in the selection of all the images b/w range of the previously selected image, till the recently selected image.

**Expected Behaviour**

Only that image should be selected

**Steps to reproduce it**

Select an image, then select another image by long pressing, after some photos from the earlier selected photos.

**Screenshots of the issue**

![giphy 1](https://user-images.githubusercontent.com/21143936/31862945-5ff54dee-b764-11e7-9c8f-f6e7f7171f38.gif)

**Would you like to work on the issue?**

Yes

**Comment by nikit19** [comment]
@aditya98ak I guess it is a feature. You can select multiple photos by just long pressing one

**Comment by sridharjajoo** [comment]
I agree with @nikit19 . Check the selectAllPhotosUpTo() method which has been made for this very purpose.

**Comment by aditya98ak** [comment]
@nikit19 @sridharjajoo Okay then! I close this issue.
