### ISSUE TITLE
Selected media lost on pressing home button

### ISSUE THREAD

**Issue by nb2998** [fossasia/phimpme-android#1391]
**Actual Behaviour**

On selecting pictures/albums and pressing the home button or recents button, all selections are lost

**Expected Behaviour**

On resuming the app, all selected items should be retained

**Steps to reproduce it**

Select any pictures, press the home button or recents button and open the app again, all selections will be lost.

**Screenshots of the issue**

![20171022_232354](https://user-images.githubusercontent.com/25134501/31866113-d59a6f4c-b797-11e7-8994-9698e784cf05.gif)

**Would you like to work on the issue?**

Yes

**Comment by aditya98ak** [comment]
@nb2998 This PR([#1276](https://github.com/fossasia/phimpme-android/pull/1276)) of the same issue([#1258](https://github.com/fossasia/phimpme-android/issues/1258)) is already open.
