### ISSUE TITLE
Codeacy is not working

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1394]
**Actual Behaviour**

The pull request are not being analysed.

**Expected Behaviour**

Codeacy should be working fine.

**Would you like to work on the issue?**

Yes !

**Comment by codedsun** [comment]
Working in coordination with @mayank8318

**Comment by codedsun** [comment]
@mariobehling  We need ur help regarding setting up this issue, the commiters can only do that.
In order the resolve the issue, we need to update the codacy engine's
Hence follow this,
To update the control panel, simply run on your server terminal:
bash -c "$(curl -fsSL https://getenterprise.codacy.com/get)" -s update

Ref: https://support.codacy.com/hc/en-us/articles/207280529-Frequently-Asked-Questions-FAQ-

**Comment by codedsun** [comment]
@anantprsd5 @mohitmanuja

**Comment by codedsun** [comment]
@anantprsd5 Kindly mention if it's fixed and what changes u made that made this codacy setup again.It will help us in learning for future .

**Comment by 0x48piraj** [comment]
It's failing, now & then!

**Comment by codedsun** [comment]
0x48piraj It was fixed up few days back and again failing, I will get to check these issues by Sunday.

**Comment by 0x48piraj** [comment]
Thanks!
