### ISSUE TITLE
The details dialog for albums can be improved.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1398]
**Actual Behaviour**

Currently only path and name for the folder are the attributes shown in the details dialog. 

**Expected Behaviour**

More attributes can be displayed for the particular folder like size, lastmodified, no of items etc. The UI can be improved too.

**Steps to reproduce it**

Click on the details option in the menu to view the details for the folder.

**Would you like to work on the issue?**

Yes.

**Comment by sridharjajoo** [comment]
@sauravvishal8797 I think [#1387](https://github.com/fossasia/phimpme-android/issues/1387) is quite similar to your issue.

**Comment by sauravvishal8797** [comment]
@sridharjajoo I guess #1387 includes details for single photos only and not for the album folder.

**Comment by mayank8318** [comment]
I was talking about single media details in #1387. @sauravvishal8797 You can work on the album details.

**Comment by sauravvishal8797** [comment]
@mayank8318 Cool. 👍
