### ISSUE TITLE
Map Fragment Shows Black Screen 

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/phimpme-android#140]
**Actual Behaviour**
when i click on map option in bottom menu it turn black and after around 20 seconds it shows the map.
**Expected Behaviour**
It should show the map

**Steps to reproduce it**
Click on map option in bottom bar

**Would you like to work on the issue?**
Yes
I think when we are using bottom bar navigation and replacing fragments every time, we should not use map FragmentActivity. We can use a simple Fragment and then inflate map fragment in it.

**Comment by heysadboy** [comment]
It shows the map. The black screen appears for the time taken to scan the images from the device. In the readme.md the Map is implemented as an activity.
I think we should put a loader till the images are scanned instead of turning it into a fragment.

**Comment by dynamitechetan** [comment]
Okay. But still rest screens are fragments in the app so I changed it.

**Comment by heysadboy** [comment]
@pa1pal @dynamitechetan It's okay if this removes a black screen.
