### ISSUE TITLE
There are typos in README.md

### ISSUE THREAD

**Issue by jishnujayakumar** [fossasia/phimpme-android#1401]
**Actual Behaviour**
There are typos in README.md

**Expected Behaviour**
Typos should be removed.

**Would you like to work on the issue?**
Yes, I would like to work on it.

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by mayank8318** [comment]
@jishnujayakumar In case you want to commit again just amend your previous commit and force push once. Please don't open another PR for the same issue.
You can follow these commands :
`git commit --amend`
Then,
`git push -f origin BranchName`

Thanks!
