### ISSUE TITLE
After Deleting a Album the thumbnail of the album is still present

### ISSUE THREAD

**Issue by sd1998** [fossasia/phimpme-android#1410]
**Actual Behaviour**

When an album is deleted initially it gets removed from the album list. But on restarting the app the album which was previously deleted is present in the albums list though the content in the album is deleted and on deleting it again the app crashes.

**Expected Behaviour**

Once deleted the album should not be there in the list even if the app is restarted.

**Steps to reproduce it**

On clicking delete the album should be deleted.

**Would you like to work on the issue?**

Yes

**Comment by nikit19** [comment]
Hi @sd1998 can you elaborate a little? Currently deleting an album isn't possible because the app crashes.
I guess you don't have the latest changes in the app

**Comment by nikit19** [comment]
@sd1998 try pulling the latest changes from this repository. If the problem persists, go ahead and send a PR

**Comment by codedsun** [comment]
@sd1998 This issue is not persisting as of now, kindly close this issue.
