### ISSUE TITLE
EditImageActivity UI Enhancement

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1429]
**Actual Behaviour**

The UI of Edit Image should be updated.

**Expected Behaviour**

Enhancement of UI in Edit Image

**Would you like to work on the issue?**

Yes!

**Comment by sridharjajoo** [comment]
@codedsun What kind of UI changes will you be incorporating?

**Comment by codedsun** [comment]
@sridharjajoo WIll try to keep the action buttons aligned to parent top, and few other changes will send a PR shortly with screenshot.

**Comment by codedsun** [comment]
#1433  Closed , closing the issue.
