### ISSUE TITLE
Fix issue with overflow menu in camera activity

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1435]
**Actual Behaviour**

On selecting one of the option from camera activity's overflow menu(for eg, Torch), it is selected but we can't unselect in by clicking on it again, it can only be changed.

**Expected Behaviour**

Selected item should stop working after retouching it.

**Steps to reproduce it**

Open camera activity's overflow menu, select torch or any item from the top header and then try to shut that function by clicking it again. 
For eg, You clicked on the torch and then try to close the torch by re-clicking on that option.

**Screenshots of the issue**

![giphy 1](https://user-images.githubusercontent.com/21143936/32121954-5beb8418-bb7c-11e7-933d-6fbf1fbd528e.gif)

**Would you like to work on the issue?**

Yes

**Comment by srv-twry** [comment]
@aditya98ak Shall i take it if you aren't working on it ?
