### ISSUE TITLE
Hide status bar for camera activity

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1436]
**Actual Behaviour**

Currently, the status bar is present in camera activity.

**Expected Behaviour**

It should be hidden so that space can be used for different resolutions accordingly.

**Would you like to work on the issue?**

Yes

**Comment by divyabaid16** [comment]
I would like to work on this issue, please guide me.

**Comment by aditya98ak** [comment]
@divyabaid16 Follow [this](https://developer.android.com/training/system-ui/status.html#41)
and send the PR!

**Comment by mayank8318** [comment]
@divyabaid16 If possible maybe you can even extend the camera right till the bottom navigation bar so that the capture button and all are on top of the camera. Something like **Snapchat** or **Whatsapp**.
It is not a must but if it is possible for you to do it then it would be great.

**Comment by aditya98ak** [comment]
@mayank8318 Yeah, that sounds cooler!

**Comment by divyabaid16** [comment]
@mayank8318 I will try 👍

**Comment by aditya98ak** [comment]
@divyabaid16 Are you working on this? or else I send the PR?

**Comment by srv-twry** [comment]
@aditya98ak @mayank8318 is anyone working/worked on it ? I would like to take it.

**Comment by aditya98ak** [comment]
@srv-twry I am having my endsems, You can take this :+1:
