### ISSUE TITLE
No option to restore default settings in the settings activity

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1437]
**Actual Behaviour**

Currently there is no option to restore default settings of the app in the settings activity
They are present in the camera settings.

**Expected Behaviour**

The option to restore default settings of the app should be present in the settings activity.
The one present in the camera settings should be removed to avoid confusion
( it says "reset all open camera settings to default" but it resets all the settings)

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
We have this option 
Go to settings, then camera setting scroll to last .

**Comment by nikit19** [comment]
@codedsun yes I just saw that but it says "reset all open camera settings to default" 
(but it resets all the settings)
I think there should be  one option to reset all settings in the settings activity instead of them being in the camera setting activity
I'll update this issue accordingly
@codedsun @mayank8318 @aditya98ak @sridharjajoo 
what do you guys think?

**Comment by codedsun** [comment]
Yes , it could be done! Let other devs review.

**Comment by mayank8318** [comment]
@nikit19 Yeah this option should be there as it is standard for all settings in general.
