### ISSUE TITLE
Adding Intro Screens at the start of App

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1438]
**Actual Behaviour**

No Intro Screen in the app

**Expected Behaviour**
Intro screens in the app
which introduces the app to the user and takes the necessary permission from the user.

**Would you like to work on the issue?**

Yes! @mohitmanuja @anantprsd5 Can I?

**Comment by codedsun** [comment]
@nikit19 @sridharjajoo @aditya98ak @mayank8318 
Kindly review!

**Comment by nikit19** [comment]
@codedsun what's wrong with the current ShowcaseView? If I am right you want to replace it?

**Comment by codedsun** [comment]
@nikit19 No ! the material show case is not wrong but the permission are taken inside the app, when the user uses feature and it should be taken before hand, I think and it might add some more graphic UI to the app!

**Comment by nikit19** [comment]
@codedsun runtime permissions are supposed to be taken only when required
Eg- you don't need the permission to take a picture unless you open the camera activity
https://developer.android.com/training/permissions/requesting.html

**Comment by sridharjajoo** [comment]
I agree with @nikit19...The material showcase view looks alright right now.

**Comment by codedsun** [comment]
Closing issue ! :+1:
