### ISSUE TITLE
System UI is not hidden in slideshow

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1441]
**Actual Behaviour**

If we start slideshow after the system UI is hidden(after auto hide) ,the slideshow starts but the system UI is visible again
**Expected Behaviour**

System UI should remain hidden

**Steps to reproduce it**

Open any picture . select slideshow. Enter the time. Click on ok when the system UI is hidden

**Screenshots of the issue**
![ezgif com-video-to-gif 14](https://user-images.githubusercontent.com/20878145/32146730-2006dea2-bd02-11e7-9b76-b4da974523ef.gif)

**Would you like to work on the issue?**

Yes

**Comment by mayank8318** [comment]
@nikit19 Yes slide show should be full screen mode and not with the UI on. Cool!!
