### ISSUE TITLE
Feature to Add Trash Folder to the app

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1444]
**Actual Behaviour**

There is no thrash folder in the app, it must be present

**Expected Behaviour**
On Deleting the pics, it must be moved to the Thrash Folder, from where the pic can be deleted!

**Would you like to work on the issue?**

Yes!

**Comment by codedsun** [comment]
@anantprsd5  why this issue is closed?

**Comment by codedsun** [comment]
@mohitmanuja

**Comment by abishekvashok** [comment]
@codedsun status

**Comment by codedsun** [comment]
I am stuck somewhere between the deletion and restoing logic in the trash.

**Comment by yashLadha** [comment]
Can you share the point where you are stuck @codedsun . May be other dev's can help.

**Comment by codedsun** [comment]
Yeah sure, I will send a PR
