### ISSUE TITLE
Theme of Overflow menu is not updated when theme is changed

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1453]
**Actual Behaviour**

Theme of the overflow menu is not updated when theme is changed in the app.

**Expected Behaviour**

Theme of overflow menu should also get updated.

**Steps to reproduce it**

Change theme inside the app and check without restarting the app.

**Screenshots of the issue**

![22556572_1853349794693826_4354696680335998976_n](https://user-images.githubusercontent.com/22395998/32273452-8ff16bec-bf28-11e7-8518-3afe23062243.gif)

**Would you like to work on the issue?**

Yes

**Comment by mayank8318** [comment]
@nikit19 @codedsun @sridharjajoo @sauravvishal8797 Need help with this one.
`getPopupToolbarStyle( )` is returning the intended style. It works when the app is opened but any in-app changes are not reflected until the app is restarted even though the returned style is right. Any ideas on this one?

**Comment by abishekvashok** [comment]
Not seeing it currently.
