### ISSUE TITLE
Option to Share Image again from upload history

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1461]
**Actual Behaviour**

Their is no option to delete upload history

**Expected Behaviour**

- [ ] Has option to again share the same image.

 

**Would you like to work on the issue?**

Yes!

**Comment by sauravvishal8797** [comment]
@codedsun I have already opened an issue for this purpose. #1349 .Will be sending the PR shortly.

**Comment by codedsun** [comment]
Ok @sauravvishal8797 I will be updating the issue to has option to again share the same image?

**Comment by kittusailley** [comment]
@codedsun Cool. 👍

**Comment by sauravvishal8797** [comment]
@codedsun Cool. 👍

**Comment by abishekvashok** [comment]
@codedsun do we need this?

**Comment by codedsun** [comment]
I have sent the PR.
