### ISSUE TITLE
Upload History UI can be improved.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1468]
**Actual Behaviour**

The upload history items are currently shown in a cardview with lot of space between the attributes and the image displayed is too small.

**Expected Behaviour**

The UI can be further improved to display the attributes with better arrangement.

**Steps to reproduce it**

Go to Upload History.

**Screenshots of the issue**

![screenshot_2017-11-03-23-40-33-306_org fossasia phimpme](https://user-images.githubusercontent.com/20841578/32389401-88be5e1a-c0f0-11e7-8cfb-48ff3792ec5d.png)

**Would you like to work on the issue?**

Yes.

**Comment by srv-twry** [comment]
@mariobehling Can i work on it ?

**Comment by sauravvishal8797** [comment]
@srv-twry Already working on it, will send the PR soon.
