### ISSUE TITLE
Implementing Search Bar in LFMainActivity

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1471]
**Actual Behaviour**
Currently there is no search bar in the toolbar of LFMainActivity where we can enter the name of the album and search for it.
Something like the following can be implemented at the top.

![image](https://user-images.githubusercontent.com/20684618/32411166-2e4a636a-c1fa-11e7-9ee5-39903b5a6699.png)

**Would you like to work on the issue?**
Yes.There should be a search bar so that we can search for albums and filter out the required album out of the list of albums.

**Comment by Nirvan101** [comment]
Could you please tell your progress on this? I would also like to work on this.

**Comment by sridharjajoo** [comment]
I'll send a PR soon
