### ISSUE TITLE
Improving UI Of SharingActivity

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1472]
**Actual Behaviour**
The UI of Sharing activity can be improved by using card views for the already present apps for sharing.Other UI changes can also be added to give it a new look.

**Would you like to work on the issue?**
Yes!

**Comment by srv-twry** [comment]
@sridharjajoo Are you working on this ? If not, i would like to take it.

**Comment by sridharjajoo** [comment]
@srv-twry Yes you can work on it
