### ISSUE TITLE
App invite via facebook

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#148]
**Actual Behaviour**

Nothing in this regard.

**Expected Behaviour**

Users will be able to send personalised notification for app installs to their friends

**Screenshots of the issue**

![screenshot_2017-02-23-02-04-49-745_org fossasia susi ai](https://cloud.githubusercontent.com/assets/13241256/24006430/c298f1e2-0a91-11e7-8536-3a33011013ca.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
Then pls, but low priority.
