### ISSUE TITLE
Implemeting Locking Feature with Hidden Folder Vault in the app

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1481]
**Actual Behaviour**

Their's no feature to add images to specific hidden folder for hiding and privacy purpose.

**Expected Behaviour**

It should be present there! 
Adding user choice images to the hidden folder and which should be accessed by the password.

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@codedsun Are u still working on this?

**Comment by codedsun** [comment]
@sauravvishal8797 No! Feel free to assign to others
