### ISSUE TITLE
Adding security to the phimpme app

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1482]
**Actual Behaviour**
The password setup has only pin password.

**Expected Behaviour**

The password setup should have 

- [ ] Fingerprint Lock

- [ ] Pattern Lock

**Would you like to work on the issue?**

Yes! @mayank8318 @mohitmanuja @aditya98ak @anantprsd5

**Comment by mariobehling** [comment]
This kind of security would be expected from on a system basis. We should avoid this kind of security overhead on the Android app itself. Please do not proceed with it. This should not be included.
