### ISSUE TITLE
Password can be removed easily

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1489]
**Actual Behaviour**

The password can be removed from security activity by clicking on toggle button

**Expected Behaviour**

It should have an again security checkup for the same and then after matching the values, it should be removed else not.

**Steps to reproduce it**

GO to settings, then add security, setup the password and then u can remove it by just clicking on switch button.

**Would you like to work on the issue?**

Yes! @mohitmanuja @anantprsd5 @mayank8318 @aditya98ak

**Comment by mayank8318** [comment]
@codedsun But getting in requires password right?
