### ISSUE TITLE
Max file size issue fix

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#150]
**Actual Behaviour**

Maximum file size cannot be changed in settings.

**Expected Behaviour**

The user should be able to change the maximum file size by clicking the image button

**Screenshots of the issue**

![screenshot_2017-03-16-22-27-11](https://cloud.githubusercontent.com/assets/13241256/24008626/258ad526-0a98-11e7-81bf-86818456488a.png)

**Would you like to work on the issue?**

Yes, I am already working on it.

**Comment by Abhi2424shek** [comment]
Are you mentioning of the photo save size?

**Comment by rohanagarwal94** [comment]
oh yes. The settings in the above image to change max file size

**Comment by Abhi2424shek** [comment]
Ok then. Pls do it.
