### ISSUE TITLE
Implement Butterknife in `LFMainActivity`

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1500]
**Actual Behaviour**

Butterknife is not implemented in `LFMainActivity`

**Expected Behaviour**

It can be implemented.

**Would you like to work on the issue?**

Can be claimed by any GCI student

**Comment by mayank8318** [comment]
@anantprsd5 @mohitmanuja Should I do this?

**Comment by anantprsd5** [comment]
Seems a beginner task. You can do it if you want to but I would suggest to leave it for GCI students. Thanks!

**Comment by mayank8318** [comment]
@anantprsd5 Yes I too thought that would be better. :)

**Comment by abishekvashok** [comment]
It seems that in some activities Butterknife is just binded to the activity. eg) setting activity. For this, I need only bind down butterknife?

**Comment by mayank8318** [comment]
@abishekvashok Bind all the member view variables like it is done in other activities.
Check this for more info -
[http://jakewharton.github.io/butterknife/](url)

**Comment by abishekvashok** [comment]
@mayank8318 I know that, but I can see that but we should bind everything from buttons to toolbars right?

**Comment by anantprsd5** [comment]
@abhishekvashok Yes. Bind everything from buttons to toolbars.
