### ISSUE TITLE
[Feature request] Disable Google Play services dependency

### ISSUE THREAD

**Issue by Kristinita** [fossasia/phimpme-android#1509]
### 1. Request

It would be nice, if Phimpme will not have Google Play services dependency.

### 2. Justification

Users from [**4PDA**](http://4pda.ru/) (the largest Russian mobile developers forum) not use Google Play services:

1. Google Play Services take place in a RAM and smartphone memory;
1. Extra battery consumption;
1. Ads, metrics, unexpected notifications.

### 3. Steps to reproduce

I download and install [**latest Phimpme apk**](https://github.com/fossasia/phimpme-android/releases) from GitHub → I open Phimpme → I see notification:

![Update Google Play services](https://i.imgur.com/8NFm1HV.png)

> Update Google Play services
>
> Phimpme won't run unless you update Google Play services.

#### 1. Preferable

Working without Google Play services.

#### 2. Alternative

Add instructions, which services/receivers/activities user need to enable in programs such as [**My Android Tools**](https://4pda.ru/forum/index.php?s=&showtopic=587771&view=findpost&p=32834998).

Thanks.

**Comment by Kristinita** [comment]
@abishekvashok , reason, why issue is closed?

Thanks.

**Comment by abishekvashok** [comment]
@Kristinita Google play is a much needed dependency. I don't know if we could deliver support for cyanogen mod when cyanogen mod has been officially revoked.

**Comment by moeenio** [comment]
Seriously?
