### ISSUE TITLE
[Question] Upload images to Imgur account albums

### ISSUE THREAD

**Issue by Kristinita** [fossasia/phimpme-android#1510]
### 1. Briefly

I don't understand, how I can upload images to my Imgur albums.

### 2. Steps to reproduce

I open Phimpme → I select image → `Share` → `Imgur` → `OK` → `Personal` → I see message `Sign in from account`.

![Sign in](https://i.imgur.com/7SOM8WQ.png)

I press to `OK` → nothing occurs.

### 3. Expected behavior

Successful upload image to selected Imgur albums.

### 4. Did not help

I don't find, where I can add my Imgur account in:

1. Phimpme settings.
1. Repository description.

Thanks.

**Comment by codedsun** [comment]
Hi @Kristinita , you have to made an account on imgur developers and add the app key(In Constants.java) to test this feature as this is the code of development branch and you have to make your own app and test the feature 👍. I hope this resolves your query, ping us if it's not.

**Comment by Kristinita** [comment]
@codedsun , I'm sorry, I'm not Android developer( .

I open **<https://api.imgur.com/>** → `Register an Application`. What data should I enter? Can you tell me step-by-step?

Thanks.

**Comment by codedsun** [comment]
@Kristinita  No Problem, then you should try to download the app from playstore or just clone the master repo and build that on your phone and please close this issue.!

**Comment by anantprsd5** [comment]
Hi @Kristinita  You need to log in to your Imgur account from the accounts section of Phimpme Application.
Steps - Open Phimpme → Go to Accounts section from Bottom Navigation bar → Press the toggle button beside Imgur to sign in.
After this, sharing to your personal account should work fine. Thanks.

**Comment by Kristinita** [comment]
@anantprsd5, I sign in to my Imgur account:

![Imgur account](https://i.imgur.com/oqXWWCL.jpg)

I have the same behavior: I select image → `Share` → `Imgur` → `OK` → `Personal` → I see message `Sign in from account`.

If don't reproduce, my hardware and software:

+ ARK Benefit S401,
+ Android 5.1.1,
+ Cyanogen 12.1 ROM.

Thanks.

**Comment by Kristinita** [comment]
@abishekvashok , reason, why issue is closed?

Thanks.

**Comment by abishekvashok** [comment]
It works for me in the latest app to share to imgur. Maybe you can try this one @Kristinita
