### ISSUE TITLE
Change the background color of item selected in EditImageActivity

### ISSUE THREAD

**Issue by srv-twry** [fossasia/phimpme-android#1514]
**Actual Behaviour**

Currently on selecting an option,there is no change in the background color of the button/view. 

**Expected Behaviour**

The background color should be changed which will make it clear to the user that the option has been selected.

**Steps to reproduce it**

Open any image and press the edit icon.

**LogCat for the issue**

NA

**Screenshots of the issue**

![screenshot_2017-12-08-15-11-19-09](https://user-images.githubusercontent.com/21277837/33760469-b933b508-dc2b-11e7-8523-bb08596049bd.png)
![screenshot_2017-12-08-15-11-23-34](https://user-images.githubusercontent.com/21277837/33760471-ba3b3e58-dc2b-11e7-903d-3a76b66fe2da.png)
In the first screenshot filter option has been selected while in the second transform has been selected but there is no clear distinction from the image. User experience can be enhanced by changing the background color upon selection.

**Would you like to work on the issue?**

Yes

**Comment by mayank8318** [comment]
@srv-twry Working for me. Are you sure you have the updated version?
![image](https://user-images.githubusercontent.com/22395998/33762030-1cf46a10-dc31-11e7-8f72-94a94d17aa6f.png)

![image](https://user-images.githubusercontent.com/22395998/33762041-22e52ae0-dc31-11e7-8824-e70f9b307595.png)

**Comment by srv-twry** [comment]
Yup, i have the update version.

**Comment by divyabaid16** [comment]
@srv-twry, it is working for me as well.

**Comment by sridharjajoo** [comment]
@srv-twry Are you using MIUI?This issue is prevelant in Redmi Mobile device

**Comment by srv-twry** [comment]
@sridharjajoo I don't think so , I am on oppo f1.

**Comment by sridharjajoo** [comment]
@srv-twry So this might be an issue on a few devices.Although the code for the background is already there

**Comment by yashLadha** [comment]
Ping @abishekvashok for closing the issue.
