### ISSUE TITLE
Update Screenshots in README.md

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1515]
**Actual Behaviour**

The current screenshots in README.md are old

**Expected Behaviour**

The screenshots should be replaced with the latest screenshots wherever required.

**Would you like to work on the issue?**

This issue can be claimed by any GCI student

**Comment by duttaditya18** [comment]
On it!

**Comment by abishekvashok** [comment]
@duttaditya18 are you working on it?

**Comment by duttaditya18** [comment]
Go ahead.

**Comment by abishekvashok** [comment]
@duttaditya18 thank you :)

**Comment by duttaditya18** [comment]
What are the changed that I must take new screenshots of?

**Comment by yashLadha** [comment]
@abishekvashok status
