### ISSUE TITLE
Replace hardcoded strings with string resources

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1516]
**Actual Behaviour**

Currently there are various places in the XML files where hardcoded strings are being used.

**Expected Behaviour**

Strings resources should be used everywhere.

**Would you like to work on the issue?**

This issue can be claimed by any GCI student

**Comment by abishekvashok** [comment]
Can I do this pls? Working on it :)

**Comment by nikit19** [comment]
@abishekvashok sure go ahead

**Comment by abishekvashok** [comment]
On it.. @nikit19
