### ISSUE TITLE
Adding Image to Favourites Error 

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1522]
**Actual Behaviour**

Adding an image to the favourites, jst shows a toast

**Expected Behaviour**

It should create a new folder and the images should be added to that folder, so that favourites image are showed to the user

And the Favourites Icon should also be added to the bottom toolbar!

**Steps to reproduce it**

Open an Image and Add that Image to Favourite.

**Would you like to work on the issue?**

Yes! @anantprsd5 @mayank8318

**Comment by codedsun** [comment]
@anantprsd5 whether this should be done or not?

**Comment by sauravvishal8797** [comment]
@codedsun Already working on it. #1289 Had mentioned it in the first PR #1320 that will be doing it in two parts, first implementing the feature to mark favourite and second displaying all the favourite marked photos in a separate activity. Have almost completed working on it, will be sending the PR soon.
