### ISSUE TITLE
Image detail attributes not visible properly for some of the images. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1523]
**Actual Behaviour**

Image details attributes are not visible properly in the blurred background for some images. 

**Expected Behaviour**

Image details attributes should be properly displayed for all sort of images. 

**Steps to reproduce it**

Click on the details option for any image. 

**Screenshots of the issue**

![screenshot_2017-12-17-04-06-10-828_org fossasia phimpme](https://user-images.githubusercontent.com/20841578/34074970-d6455038-e2df-11e7-8d7d-1225662ec324.png)

**Would you like to work on the issue?**

Yes.

**Comment by sauravvishal8797** [comment]
Here the blurred background is not working for some cases. I think we should probably stick to a particular layout/background for the details view. @mayank8318 @nikit19 @codedsun What's your opinion on this?

**Comment by raj10071997** [comment]
@sauravvishal8797 I also faced this issue and I think you are right, the app should probably stick to a particular layout/background for the details view.
