### ISSUE TITLE
Images cannot be opened from Upload History

### ISSUE THREAD

**Issue by Nirvan101** [fossasia/phimpme-android#1531]
**Actual Behaviour**
Upload history only shows the thumbnails of images uploaded. There is no provision for opening the images by clicking on the thumbnails.

**Expected Behaviour**
In Upload history, the user must be able to click on the image thumbnails to open them in fullscreen. 

**Steps to reproduce it**
Under navigation drawer, click on Upload History. This will show the thumbnails of the uploaded images. Try clicking on them. Nothing happens, the images don't open in fullscreen.

**Would you like to work on the issue?**
Yes

**Comment by sauravvishal8797** [comment]
@Nirvan101 U still working on this?

**Comment by Nirvan101** [comment]
@sauravvishal8797 Yes I am, I have been discussing the implementation on Gitter.
