### ISSUE TITLE
No Uniformity for Orientation change

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1535]
**Actual Behaviour**

When the device is rotated the text size of the headers does not change, but different orientations have different text sizes otherwise.

**Expected Behaviour**

Text size should either not change at all or the change should be reflected on rotation as well.

**Steps to reproduce it**

Open gallery and rotate to go Horizontal position.
Now open gallery when phone is in horizontal position.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/22395998/34286990-36baf0f2-e70a-11e7-9240-8481b20bc6a7.png)

![image](https://user-images.githubusercontent.com/22395998/34286992-3c2a096a-e70a-11e7-956a-1f37ca023316.png)

**Would you like to work on the issue?**

Yes

**Comment by mayank8318** [comment]
@anantprsd5 @mohitmanuja @codedsun @nikit19 @sauravvishal8797 What looks better in your opinion?

**Comment by nikit19** [comment]
Second screenshot looks better

**Comment by sauravvishal8797** [comment]
@mayank8318 Would agree with @nikit19 , the second screenshot looks better.

**Comment by mayank8318** [comment]
@nikit19 @sauravvishal8797 Yes even i like the second one. I guess it is because of same bottom nav icons and a smaller font in the 1st one. So I will remove that font size change for horizontal orientation.
