### ISSUE TITLE
Image Editor Only

### ISSUE THREAD

**Issue by baokk** [fossasia/phimpme-android#1537]
Hi ,

Is there anyway to using only image editor function only. My application only wants to edit it and save file.
as below screen
![image](https://user-images.githubusercontent.com/2900549/34296804-f8b884da-e746-11e7-98dd-3528923c0b6e.png)

**Comment by codedsun** [comment]
Go the specific image, and then click on to open that image with this app. you will directly land to this activity.
I think that clears your issue.
