### ISSUE TITLE
Discard button not deleting the images

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#155]
**Actual Behaviour**

After taking photo from the camera, the discard button does not work and it saves the picture.

**Expected Behaviour**

The photo taken should be deleted on clicking discard button.

**Steps to reproduce it**

Open camera, Take picture, click on the discard button

**Would you like to work on the issue?**

Yes.

@pa1pal @Abhi2424shek Please review.

**Comment by CloudyPadmal** [comment]
Hey wasn't this solved in issue #90 by @harsu-ag?

**Comment by anantprsd5** [comment]
@CloudyPadmal Yeah sorry. My bad, I thought the discard button was to remove the pic. Now got to know it was to discard the edits. Thanks. :)

**Comment by CloudyPadmal** [comment]
@anantprsd5 it was closed and you couldn't see nuh! :see_no_evil: I remembered it coz I've done the double save discard :see_no_evil:
