### ISSUE TITLE
Further enhancements in favourites collection.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1559]
**Actual Behaviour**

Further enhancements in the favourites section required.

**Expected Behaviour**

State here what the feature should enable the user to do.

- [ ] Adding multiple items to favourites collection at once, removing the move to option(since it is a collection to store/display users liked photos no requirement for copy or move operations here).

- [ ] When deleting a photo from the favourites collection, a choice should be given to delete the photo permanently from the device.

**Steps to reproduce it**

Delete photos from the favourites collection, adding photos to the favourites collection.

**Would you like to work on the issue?**

Yes.

**Comment by codedsun** [comment]
@sauravvishal8797 #1522 I am working on it !

**Comment by sauravvishal8797** [comment]
@isuruAb Please reopen this issue, this issue was divided into two tasks the PR for the first part is merged, but I'm still working on the second part.

**Comment by sauravvishal8797** [comment]
@isuruAb Please reopen the issue, the second part is yet to be addressed.
