### ISSUE TITLE
Using the material scroll bar inside the app

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1573]
**Actual Behaviour**
Currently there is a dependency to include the material scroll bar inside the app but isn't being used.I would like to implement the feature to enable fast scrolling.
Following is the link to it:```https://github.com/turing-tech/MaterialScrollBar ```
I also have a particular doubt regarding the scrolling the behaviour that when we scroll what should be displayed in the scrolling pop up (the name of album or the date)??
@anantprsd5 @mohitmanuja @mayank8318 

![image](https://user-images.githubusercontent.com/20684618/34469428-9c82206c-ef44-11e7-9216-63390d0eab63.png)

**Would you like to work on the issue?**
Yes!

**Comment by codedsun** [comment]
@sridharjajoo I think we don't need as of the app is lagging and has too many memory leaks.
Kindly close this issue.

**Comment by sridharjajoo** [comment]
@codedsun Adding this would not affect the app in any bad wy
