### ISSUE TITLE
Adding dragging and select multiple recycler view items

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1575]
**Actual Behaviour**
Currently there is no feature to select multiple photos by dragging over the recycler view.The effect is similar to the drag and select in Google Photos to select multiple photos.

**Would you like to work on the issue?**
Yes

Can I work on this?
@anantprsd5 @mohitmanuja

**Comment by codedsun** [comment]
Can I work on this issue? @sridharjajoo
