### ISSUE TITLE
Adding fingerprint authentication for security.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1576]
**Actual Behaviour**

Password protection is available for security, no fingerprint authentication.

**Expected Behaviour**

Fingerprint authentication should be implemented.

**Steps to reproduce it**

Enable security from the security option in the settings page.

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
I am sorry pls don't continue on this one.
https://github.com/fossasia/phimpme-android/issues/1482

**Comment by sauravvishal8797** [comment]
@abishekvashok Oh. I didn't see that. Closing this issue.
