### ISSUE TITLE
Cannot remove images from the Upload Photos list

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#158]
**Actual Behaviour**

Once we add an image to the _Upload Photos_ list, no option available to remove it from the list!

**Expected Behaviour**

User must be given with an option to remove it from the _Upload Photos_ list

**Steps to reproduce it**

1. Open app
2. Go to _Upload_
3. Add images and try to remove any

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

If this is an issue which is not addressed before, I would like to!

**Comment by Abhi2424shek** [comment]
Yes pls do it
