### ISSUE TITLE
Label visible when images are added to Upload Photos List

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#159]
**Actual Behaviour**

When there are images in the _Upload Photos_ list, empty list label is still visible

**Expected Behaviour**

When there are images in the list, `No Picture Selected :(` label should disappear

**Steps to reproduce it**

1. Open app
2. Go to _Upload Photos_
3. Add one or two images and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![device-2017-03-17-213913](https://cloud.githubusercontent.com/assets/14261304/24052127/5d2fe1b6-0b5a-11e7-938a-ea9f828ec071.png)

**Would you like to work on the issue?**

I think a beginner will find this interesting!

**Comment by heysadboy** [comment]
@CloudyPadmal https://github.com/fossasia/phimpme-android/issues/151 Hey issue was created here and fixed here https://github.com/fossasia/phimpme-android/pull/154

**Comment by CloudyPadmal** [comment]
Hey @heysadboy !! I've built from an old branch! :see_no_evil: Closing!! :innocent:
