### ISSUE TITLE
Bug in landscape mode of Description of image

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1602]
**Actual Behaviour**
When the phone is rotated and description of an image is seen , the details are cutoff i.e there should be a scroll view so that all the details can be seen.

**Steps to reproduce it**
Open any image and in the bottom navigation bar , select the description/details option.
Rotate the phone to view in landscape mode.

**Screenshots of the issue**
![rsz_potrtait](https://user-images.githubusercontent.com/20684618/34638141-c0ce739e-f2eb-11e7-9905-0bf337fd98c3.png)

![rsz_landscape](https://user-images.githubusercontent.com/20684618/34638147-e7325424-f2eb-11e7-9fe9-505a9d612837.png)

**Would you like to work on the issue?**
Yes!

**Comment by batbrain7** [comment]
@sridharjajoo may I work on this?

**Comment by sridharjajoo** [comment]
@batbrain7 Ok go ahead!...I will close this issue
