### ISSUE TITLE
Bug in Camera on clicking the menu icon on top right

### ISSUE THREAD

**Issue by batbrain7** [fossasia/phimpme-android#1604]
**Actual Behaviour**

In landscape mode on clicking the menu icon on the top right the popup is not completely scrollable in the landscape mode and some information is not seen in landscape mode

**Expected Behaviour**

the popup should be completely scrollable

**Steps to reproduce it**
open the camera and click on menu icon on top right and then rotate the device.

Device is a XOLO Android phone running Android 6.0.1

**Screenshots of the issue**

![17fd11c3-108d-4b55-b8a3-bca5d95c39a7](https://user-images.githubusercontent.com/16780496/34638996-332b45f0-f2fd-11e7-831f-d1f1f87a7227.jpg)
**Would you like to work on the issue?**
Yes

**Comment by DhruvamSharma** [comment]
I want to work on the issue.

**Comment by yashLadha** [comment]
But it is not occuring on my device @batbrain7 . Can you again test the same.

![anim-optim](https://user-images.githubusercontent.com/18033231/37206776-113b3d94-23c0-11e8-8e74-892df8c53a69.gif)

**Comment by abishekvashok** [comment]
Closing as it's not being experienced in the latest version of the app.
