### ISSUE TITLE
The app stops working on clicking gallery after opening map activity

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#161]
**Actual Behaviour**

The app stops working on clicking gallery after opening map activity.

**Expected Behaviour**

The gallery should successfully open.

**Steps to reproduce it**

1. Select map activity from bottom tabs.
2. Select gallery icon after step 1.
3. App stops working.

**LogCat for the issue**

![screenshot from 2017-03-17 22-01-41](https://cloud.githubusercontent.com/assets/13241256/24053083/c233efe6-0b5d-11e7-848c-2f33a3edb6bc.png)

**Would you like to work on the issue?**

Yes, I am already working on it.

**Comment by CloudyPadmal** [comment]
Hello @rohanagarwal94 !! :) when you're fixing it do you mind removing 590 & 591 lines? :innocent:

**Comment by Abhi2424shek** [comment]
Yes pls work on it.

**Comment by optnio00** [comment]
This issue is fixed by Changing a simple line in MapsActivity.java file
public class MapsActivity extends FragmentActivity.......         by

public class MapsActivity extends AppCompatActivity

`public class MapsActivity extends AppCompatActivity implements OnMapReadyCallback, BottomNavigationView.OnNavigationItemSelectedListener {

`

**Comment by optnio00** [comment]
now app is not stop working But also it going smoothly from MapsActivity to Gallery

**Comment by dynamitechetan** [comment]
I replaced MapActivity with MapFragment. Its working smoothly.

**Comment by rohanagarwal94** [comment]
@cloudypadmal already did :+1: . @dynamitechetan @optnio00 I have fixed the issue already by including the toolbar widget in the xml file. We were not using the support action bar hence the error. @optnio00 no need to send the PR for this. Also as a practice, try to solve 1 issue per PR.

**Comment by rohanagarwal94** [comment]
closing this since the issue got solved in @dynamitechetan PR #149 .
