### ISSUE TITLE
Bug in the landscape mode of an image.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1613]
**Actual Behaviour**

When you click on an image,it opens in portrait mode and when you rotate the image to landscape mode the first image of the current album is as shown in the below screenshot.Even after rotating back to portrait mode the images are not displayed properly.

**Expected Behaviour**

There should be no space above the image and the first image must be shown properly.

**Steps to reproduce it**

Open the image in portrait mode, and when you view it in landscape mode it should be displayed properly.

**Screenshots of the issue**

![26655443_2002590003349428_1186741276_o](https://user-images.githubusercontent.com/24502136/34649518-e23480fa-f3d6-11e7-99c9-3acb52bc08f6.png)

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@raj10071997 I have already sent a pr regarding this issue, please close close this issue as it is an already existing issue #1144
