### ISSUE TITLE
Multi coloumn preference max value should be limited to 3 or 4.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1614]
**Actual Behaviour**

Maximum no of coloumns that can be displayed for albums or media is set to 6. Displaying as many as 6 albums in a single row makes the UI dull.

**Expected Behaviour**

Maximum no of coloumns should be limited to 3 or 4.

**Steps to reproduce it**

Change the multi coloumn preference in settings to 6.

**Screenshots of the issue**
![screenshot_2018-01-07-23-38-13-440_org fossasia phimpme](https://user-images.githubusercontent.com/20841578/34652505-1ddb15dc-f405-11e7-9777-e8270c8d9860.png)

**Would you like to work on the issue?**

Yes.

**Comment by nikit19** [comment]
@sauravvishal8797 the user has the choice of setting the number of columns according to his needs.
Taking this choice away from the user and limiting the number of columns doesn't seem to be a wise decision to be. In your device this many columns might not look good but with devices having a larger screen it might make sense having more columns

**Comment by sridharjajoo** [comment]
@sauravvishal8797 I agree with @nikit19 .It is upto the user how many columns he desires.

**Comment by sauravvishal8797** [comment]
@nikit19 @sridharjajoo I guess most of the smartphones screen sizes these days are normal or maybe small, and for those Screen layout sizes it wouldn't make sense having more than 4 coloumns as it wouldn't look good at all, and for the larger Screen layout devices we could set the options accordingly after checking the screensizes programatically.
