### ISSUE TITLE
Display Toast when photo is deleted

### ISSUE THREAD

**Issue by Nirvan101** [fossasia/phimpme-android#1621]
**Actual Behaviour**
There is no message displayed when a photo is deleted. 

**Expected Behaviour**
There should be a message displayed (eg Toast) when a photo is deleted, to indicate that the deletion was successful. 

**Steps to reproduce it**
Open a photo in the gallery and delete it. 

**Would you like to work on the issue?**
yes

**Comment by abhinavraj23** [comment]
I want to work on this issue.

**Comment by Nirvan101** [comment]
@abhinavraj23 I've already made a pull request, but please feel free to review it or give suggestions.

**Comment by DhruvamSharma** [comment]
I want to work on the issue.

**Comment by Ananthusubramanian** [comment]
I have added snackbar .Can anyone review the PR
