### ISSUE TITLE
Improvement in Preview Camera Layout

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#163]
**Actual Behaviour**

The flash button and switch camera icon takes up a lot more space in preview fragment

**Expected Behaviour**

Their size should be reduced and placed at corner for better preview 

**Would you like to work on the issue?**

@Abhi2424shek Yes i would like to work on this issue.

**Comment by CloudyPadmal** [comment]
:+1:

**Comment by Abhi2424shek** [comment]
Yep

**Comment by madhavrathi** [comment]
@Abhi2424shek Please Review
