### ISSUE TITLE
Issue in Image details view.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1634]
**Actual Behaviour**

The image titles exceeding single line are not visible properly.

**Expected Behaviour**

The image titles exceeding single line should be visible properly.

**Steps to reproduce it**

Open details for any image.

**Screenshots of the issue**

![screenshot_2018-01-10-19-17-00-626_org fossasia phimpme](https://user-images.githubusercontent.com/20841578/34781847-f12addb6-f64c-11e7-806a-4e11df089ec7.png)

**Would you like to work on the issue?**

Yes.

**Comment by Shubham2320** [comment]
@sauravvishal8797 can I work on it?

**Comment by sauravvishal8797** [comment]
@Shubham2320 I have already referenced a PR with this issue. The issue is fixed.
