### ISSUE TITLE
image is automatically zoomed out when systemUI gets hidden in SingleMediaActivity.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1635]
**Actual Behaviour**

When you open an image in SingleMediaActivity and zoom it when the system UI is not hidden. After five seconds as when interface switches to full screen the image is automatically zoomed out which should not happen. Because of this the user has to zoom in again.

**Expected Behaviour**
The image should remain zoomed in even after switching to full screen mode, when the systemUI is hidden i.e. the toolbar and bottom bar are not visible.

**Gif of the issue**
![zoom](https://user-images.githubusercontent.com/24502136/34789455-57436b4c-f664-11e7-9ed0-c650f62654db.gif)

**Would you like to work on the issue?**
yes

**Comment by raj10071997** [comment]
@codedsun  @nikit19  @sauravvishal8797  @sridharjajoo  can you suggest any other way for resolving this issue. I know that this issue is because of the flags set in hideSystemUI() method in SingleMediaActivity. These are the lines that causes this issue.

 getWindow().getDecorView().setSystemUiVisibility(
                        View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
                                | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
                                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                                | View.SYSTEM_UI_FLAG_IMMERSIVE);

can anyone please suggest any other way???

**Comment by sparrow007** [comment]
is someone working on it?

**Comment by sauravvishal8797** [comment]
@sparrow007 If you want to work on it, please go ahead.

**Comment by sparrow007** [comment]
@sauravvishal8797 i will send the PR soon
