### ISSUE TITLE
Deleting image in AllPhotosMode changes the order of appearance of images.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1636]
**Actual Behaviour**

when you switch to AllPhotosMode and delete a photo when you are in LFMainActivity . You will see that the order of appearance of images changes after deleting the image. And the order changes back to the previous one after refreshing the activity.

**Expected Behaviour**
The order must not change after deleting an image in AllPhotoMode.

**Gif of the issue**
![dh](https://user-images.githubusercontent.com/24502136/34790523-0e3f14e2-f668-11e7-9a74-c68a90cb1bc8.gif)

**Would you like to work on the issue?**

yes

**Comment by sauravvishal8797** [comment]
@raj10071997 I have already created an issue for this purpose. #1568. This PR #1570 addresses the same.
