### ISSUE TITLE
Delete Images of Previous Filters from drawable Folder

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#164]
**Actual Behaviour**

We have replaced the previous filter photobuttons and their icons are still present in drawable which takes up some amount of size.
**Expected Behaviour**

We should delete them.

**Would you like to work on the issue?**

@Abhi2424shek  Yes.

**Comment by madhavrathi** [comment]
@Abhi2424shek Hey this issue is yet to solved. Why close it ?

**Comment by Abhi2424shek** [comment]
Wasn't it solved in the PR, you referenced it?

**Comment by madhavrathi** [comment]
@Abhi2424shek No i haven't referenced it. I will send a PR for this in a while.
