### ISSUE TITLE
After selecting an image in AllPhotoMode the toolbar and the bottom bar disappears.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1643]
**Actual Behaviour**
When we select an image a little bit after sliding down in AllPhotoMode when the toolbar disappears, the bottom bar also disappears with the toolbar. This should not happen.

**Expected Behaviour**
After selecting the image the toolbar must appear to take further actions.

**Screenshots of the issue**

![d](https://user-images.githubusercontent.com/24502136/34838040-aa3ea76c-f722-11e7-85ee-dcd9a74125f0.png)

**Would you like to work on the issue?**

yes

**Comment by nikit19** [comment]
Actually this is done so that there is more space in the screen to view the images. You don't really need the bottom bar when you have selected an image.
And the toolbar appears as soon as you scroll up

**Comment by raj10071997** [comment]
But this doesn't happen in album view , in album view as soon as you select an image the toolbar is visible to take further actions.

**Comment by nikit19** [comment]
I don't see any difference in both the cases.
In both the cases,toolbar disappears  only when you scroll down and appears again when you scroll up

**Comment by nikit19** [comment]
Okay, you are right. I wan't able to understand what you were doing. Go ahead :+1:
