### ISSUE TITLE
Albums have a move to option but it is not implemented.

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1646]
**Actual Behaviour**

Select any album and choose to move to. It will repeatedly ask for SD card permission.

**Expected Behaviour**

It should move all the photos to the desired destination.

**Steps to reproduce it**

Select any album.
From the menu select Move To
Select any destination folder

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@mayank8318 I think while debugging, I have solved this issue, can I send the PR as it will help me fix #1444 more soon.

**Comment by mayank8318** [comment]
@codedsun I am adding a move all photos for when an album is selected and it is nearly finished. Though #1686 is true in the sense that when the permission is prompted for and the user accepts it, the operation is not performed. This is a serious issue as maybe the user selected 100 pics from a bunch of 1000 pics say and he is prompted for permission and he agrees. But according to the current implementation he will lose all his selection and will have to do the tedious process again.
