### ISSUE TITLE
Bug in onLongpressed in albums mode

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1647]
**Actual Behaviour**
Currently in the photos mode when we select a picture by long pressing it and select another picture by long pressing, then all the photos lying in between those indices are selected. But when the same thing is applied to albums mode or show all photos, it doesn't select the intermediate photos.

**Expected Behaviour**
It should select the photos lying between the two indices.

**Would you like to work on the issue?**
Yes

**Comment by Avjeet** [comment]
I want to work on this issue

**Comment by sridharjajoo** [comment]
I'm sending the pr soon.you can work on any other issues.
Thanks
