### ISSUE TITLE
Add the documentation for Cloudrail setup

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1658]
**Actual Behaviour**

Their is no documentation for Cloudrail account setup

**Expected Behaviour**

There should be one

**Instructions to be followed**
.1.Go to site http://cloudrail.com/
2.Add the documentation to create an app and get the key
3.Add the details of how to enable various services within their app
(refer: https://cloudrail.com/integrations/interfaces/CloudStorage;serviceIds=Dropbox,GoogleDrive,OneDrive)
**Would you like to work on the issue?**

No!

**Comment by raj10071997** [comment]
I would like to work on the issue. @codedsun  Can I work on it?

**Comment by raj10071997** [comment]
@codedsun it's been quite a long time, so I taking up this issue.

**Comment by codedsun** [comment]
@raj10071997 You can go on sure! I have written above that I am not working on this issue.

**Comment by abishekvashok** [comment]
@raj10071997 updates?

**Comment by mariobehling** [comment]
Out of scope right now due to small team.
