### ISSUE TITLE
Adding animations when sliding for next or previous image. 

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1660]
**Actual Behaviour**

Currently we just slide left or right for the next or the previous image and the image comes sliding. There can be more animations for sliding for the next or previous image like 3D rotating image, parabola, Cube in, Cube out, card, zoom, etc. 

**Expected Behaviour**

There should be more than one animation to slide the images.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@raj10071997 You can add animations to the slideshow option as of now, as there are many animations effect previously available that are cause of the app lag on most of the phones.

**Comment by codedsun** [comment]
Kindly do the following in the slideshow options, i.e. when user goes for the slideshow option he shall be able to select various animations and implement them.
Ping us if you get stuck 👍

**Comment by sauravvishal8797** [comment]
@raj10071997 @codedsun As for the slideshow animations, I've already created an issue for the same. #1645 . And I also think that the multiple animation option for the page flips could be reserved for later.

**Comment by raj10071997** [comment]
@codedsun  I will make a PR regarding this issue , so that if it is not required now, you can add it later. Is this fine?

**Comment by codedsun** [comment]
@raj10071997 I think there are many more issues which are still left to be solved, and spending time on issues which is not certain to be merged or not is not suitable.May be we can spend more time on left over ones and solve that first.

**Comment by raj10071997** [comment]
ok then I will make a PR later about this issue.
