### ISSUE TITLE
No star icon to directly add image to favourites.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1665]
**Actual Behaviour**

There is no star icon to directly add the image to favourites. Rather than this, there can be a star icon on the toolbar or the bottom bar.

**Expected Behaviour**

There should be a star icon to directly add the images to favourites.

**Would you like to work on the issue?**

Yes

**Comment by raj10071997** [comment]
@codedsun what's your opinion on this?

**Comment by sauravvishal8797** [comment]
@raj10071997 We have the option to add a particular image to favourites via the overflow menu option in the SingleMediaActivity and also to move multiple/single images to favourites via the long press operation. So I don't think we really require the star icon here.

**Comment by raj10071997** [comment]
@sauravvishal8797 you are right but generally in apps if we have the option to add something to favourites then there is a star icon visible there.

**Comment by sridharjajoo** [comment]
@raj10071997 I think doing this will bring redundancy and if we are able to add to favourites via overflow menu,it might not be wise to add further complication to the app

**Comment by raj10071997** [comment]
@sridharjajoo  that's why I am suggesting that there should be a star icon and not an "Add to favourite" option in overflow menu. As generally in apps , "Add to favourite" option is not present in overflow menu rather than the option there is a star icon. But since most of you disgree with this lets keep this issue for later.
