### ISSUE TITLE
Pin to top icon not proper for dark theme.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1669]
**Actual Behaviour**

The pin to top icon colour not proper for dark theme.

**Expected Behaviour**

The pin to top icon should be of light colour for the darker theme.

**Steps to reproduce it**

Switch to darker theme.

**Would you like to work on the issue?**

Yes.

**Comment by sridharjajoo** [comment]
Duplicate issue [#1601](https://github.com/fossasia/phimpme-android/issues/1601)

**Comment by sauravvishal8797** [comment]
Oh! Didn't see that, closing the issue.
