### ISSUE TITLE
No message displayed when search is not available

### ISSUE THREAD

**Issue by nikit19** [fossasia/phimpme-android#1670]
**Actual Behaviour**

Currently we see a blank screen when we search for a folder that is not available

**Expected Behaviour**

A text message like "Folder with that name is not available" should be displayed instead of a blank screen

**Steps to reproduce it**
Open the app.
Search for a folder that is not available

**Screenshots of the issue**

![screenshot_20180116-012310](https://user-images.githubusercontent.com/20878145/34959448-925a2116-fa5c-11e7-8181-b929a2855e25.png)

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@nikit19 I have already addressed this problem in the issue #1659 .

**Comment by nikit19** [comment]
Didn't see that. Closing this
