### ISSUE TITLE
NDK Error

### ISSUE THREAD

**Issue by rahul107** [fossasia/phimpme-android#1676]
I am new in Android and i download your project and open it in android studio but it causes error for ndk prebuild. mk i attach the error message image with this.

Please help me to solve this error.

Thanks..

![error](https://user-images.githubusercontent.com/26810084/34974397-b9408bc0-fab2-11e7-8f55-e4a55dc2eee6.png)

**Comment by codedsun** [comment]
@rahul107 Hello, please follow the guidelines of setting up the project and feel free to ping in the channel if you get stuck.

**Comment by rahul107** [comment]
i tried that all but no success.

On Tue, Jan 16, 2018 at 1:01 PM, Suneet Srivastava <notifications@github.com

**Comment by danhdc0812** [comment]
Hi @rahul107 , 
First please make sure you already install NDK , follow this https://developer.android.com/ndk/guides/index.html.

 Then, check file **local.properties** of your app. Have ndk path like this ?: 
> ndk.dir=/....../Library/Android/sdk/ndk-bundle

**Comment by lucius165** [comment]
Hi!
i got the same problem with @rahul107 

i have installed LLDB, CMake, NDK, copy 'OpenCV-android-sdk/sdk/native/3rdparty' and 'OpenCV-android-sdk/sdk/native/libs'.

i have also try to deleting 'externalNativeBuild' and 'build' folder but still not working. did i forgot something?

**Comment by danhdc0812** [comment]
@lucius165 please upload error image.
@rahul107 please make sure you already copy 'OpenCV-android-sdk/sdk/native/3rdparty' and 'OpenCV-android-sdk/sdk/native/libs'. into phimpme project, the error you sent say you missing folder "jniLibs"

**Comment by rahul107** [comment]
i installed latest version of NDK and also check local.property of my app
and path is right at ndk-bundle but problem still there..

**Comment by codedsun** [comment]
@lucius165 @rahul107 Kindly make sure that you go with each and every step in the setup guide.If still the problem persist, kindly ping here.We are happy to help :)

**Comment by rahul107** [comment]
solved i copied all files from opencv/native/libs and 3rdparty and it solve.

i imported opencv 3 and you used 2 that opencv3 is missing some files in
jniLibs/x86 and also in  jniLibs/armeabi-v7a i just copied all files and it
solved.

Thank You

**Comment by sridharjajoo** [comment]
@rahul107 If you issue is solved , kindly close this issue.

**Comment by prudhvir3ddy** [comment]
@rahul107 please help i got the same error and i didnt understood how u solved it

**Comment by codedsun** [comment]
@prudhvir3ddy Ping in the channel, if you need any help!

**Comment by rahul107** [comment]
@prudhvir3ddy  i add files (OpenCV) according to READ ME file in my project and it solved.
