### ISSUE TITLE
Changing the delete string in favourites Activity.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1679]
**Actual Behaviour**

Currently there is an option to add images to favourites but there is no option to remove images from favourites.

**Expected Behaviour**

There should be an option to remove images from favourites.

**Would you like to work on the issue?**
Yes

**Comment by sauravvishal8797** [comment]
@raj10071997 There is a delete option to remove images from the favourites collection. So please explain what do you want to imply here?

**Comment by sauravvishal8797** [comment]
@raj10071997 The delete option does deletes the image from the favourites database, however it does not deletes the image from the Android System MediaProvider database. And providing the user option to delete it permanently from the system database too, was a part of this issue #1559 which is closed by mistake by a mentor, and I have already asked him to reopen the issue.

**Comment by raj10071997** [comment]
@sauravvishal8797 I checked this issue before opening it. Since you have to reopen #1559 , I am closing this issue.
