### ISSUE TITLE
onSingleTap stops working

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1681]
**Actual Behaviour**

When you open an image in SingleMediaActivity and before the SystemUI hides slide to the next image and come back to the previous image. After this if you tap on the image the navigation bars don't disappear ,that is, the SingleTap on the image stops working.

**Expected Behaviour**

The SingleTap on the screen should work in SingleMediaActivity.

**Would you like to work on the issue?**
yes

**Comment by sparrow007** [comment]
@mariobehling would you please check my PR.
