### ISSUE TITLE
Fingerprint Authentication

### ISSUE THREAD

**Issue by ashley8jain** [fossasia/phimpme-android#1682]
**Actual Behaviour**

There is password option to protect media only

**Expected Behaviour**

There should be fingerprint authentication option to view hidden folders instantly

**Steps to reproduce it**

[FingerPrint API](https://www.androidhive.info/2016/11/android-add-fingerprint-authentication/)

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@ashley8jain Issues have been created earlier for this same purpose but were advised not to proceed with. #1576

**Comment by ashley8jain** [comment]
@sauravvishal8797 o sorry, 
Now further, I will see both closed & open issue before creating new issue. Thank you
