### ISSUE TITLE
back button function

### ISSUE THREAD

**Issue by ashley8jain** [fossasia/phimpme-android#1683]
**Actual Behaviour**

press back button lead to camera page fragment while on gallery page.

**Expected Behaviour**

Press back button while on gallery page would exit the app.

**Steps to reproduce it**

modify onBackPressed() function

**Screenshots of the issue**

![screencast](https://user-images.githubusercontent.com/16614355/35005365-2f4beea2-fb19-11e7-979c-2a2afd8df269.gif)

**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
It's been kept that way.

**Comment by ashley8jain** [comment]
@sridharjajoo ok
