### ISSUE TITLE
The Toolbar doesn't appear on LongPress in favourites images.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1684]
**Actual Behaviour**

While you see all the favourite images and if click on an image the toolbar and the bottom both disappears same as happened in the issue  #1643.

**Expected Behaviour**

The toolbar should appear to take further actions.

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@raj10071997 It is kept that way i.e in the edit mode the bottom bar disappears since the further actions should be performed only on the selected items in the edit mode.

**Comment by raj10071997** [comment]
But this doesn't happen in other albums mode neither it happened in All
photos mode. See the issue mentioned.
