### ISSUE TITLE
Move option not working

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1686]
**Actual Behaviour**

The move option is not working, as when it obtains the permission, no move is performed

**Expected Behaviour**

It should work

**Steps to reproduce it**

From the LFMainActivity(Main Screen) select an album or image by clicking on that and then try to move that image into a folder.

The following is working when you go on to the SingleMediaActivity i.e. when you open an image and then move the image.

**Screenshots of the issue**

It shows a snackbar that permissions are obtained but no move is performed.

**Would you like to work on the issue?**

Yes!

Working on this which will further help me in solving Fix #1444

**Comment by codedsun** [comment]
@sauravvishal8797 @nikit19 @mayank8318 Do confirm.

**Comment by codedsun** [comment]
I followed the following issue, in LFMain Activity

**Comment by mayank8318** [comment]
@codedsun It is not working for the album because wrong method is being called. I  made an issue for it and am about to submit a PR for that. 
But as far as photos is concerned, yes it should continue if you give the permission to access SD card data.

**Comment by codedsun** [comment]
@mayank8318, kindly tag in the issue you raised for the above.So, I can close this

**Comment by mayank8318** [comment]
#1646

**Comment by sauravvishal8797** [comment]
@codedsun The move option does works for moving images to a folder in the sd card once the permission is given.

**Comment by codedsun** [comment]
@sauravvishal8797 I am really messing around this issue for a while. @mayank8318 Also confirmed the issue. Can u please check once again?

**Comment by mayank8318** [comment]
@sauravvishal8797 What I mean is if you give "yes" permission for SD card you have to redo the entire process. It shouldn't be like this and the process should continue if you grant the permission.

**Comment by codedsun** [comment]
@mayank8318 I have issue that my file is still not moving even after giving permissions.It just asks me to give permission every time

**Comment by codedsun** [comment]
Please follow the steps to reproduce this and then report it what's the issue.

**Comment by sauravvishal8797** [comment]
@codedsun I guess in the all photos mode, it asks for permission again and again but in the allbums the move operation is performed successfully after granting the permission, though you'll have to redo the move operation(which shouldn't happen as @mayank8318 said).

**Comment by mayank8318** [comment]
@codedsun Moving will not work for albums as it is not implemented yet. But I am not getting repeated permission request. Is there any specific pattern to photo selection?

**Comment by codedsun** [comment]
@sauravvishal8797 @mayank8318 What I am following 

1.Open the app select one album or two, 
2.Try to move that in a folder
3.It request for permissions.(The selections are lost as what mayank said)
4.Repeated the proccss again I get into step 3.

Please follow this above and tell me what you all are facing as I am working on that only

**Comment by raj10071997** [comment]
@codedsun  I am facing the same error as you do . Even this same error is shown in AllPhotosMode when we try to move a photo from AllPhotoMode but that same photo can be moved if we move it from the album.

**Comment by codedsun** [comment]
@sauravvishal8797 @mayank8318 what to do now
?
