### ISSUE TITLE
Image size is not proper after changing orientation

### ISSUE THREAD

**Issue by ashley8jain** [fossasia/phimpme-android#1709]
**Actual Behaviour**

Image size is not proper after changing screen orientation to landscape or vice versa

**Expected Behaviour**

Proper Image size should be there after changing screen orientation

**Screenshots of the issue**

![2018_01_22_00_21_36](https://user-images.githubusercontent.com/16614355/35197759-77f02d68-ff0a-11e7-83bb-9e20ffb95aed.gif)

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@ashley8jain it is addressed in #1144

**Comment by ashley8jain** [comment]
@batbrain7 thanks for pointing out. closing this issue
