### ISSUE TITLE
Opening image selected from photo map

### ISSUE THREAD

**Issue by heysadboy** [fossasia/phimpme-android#171]
**Actual Behaviour**

Currently the map just displays the image on clicking the marker. 

**Expected Behaviour**

When the image pops up the user must be able to click on it and see the image in full view.

Clicking the image on map
![screenshot_2017-03-19-16-54-53](https://cloud.githubusercontent.com/assets/22588035/24080620/6138ca6e-0cc9-11e7-8bd6-0860cd695d2c.png)

Opens full image
![screenshot_2017-03-19-19-47-02](https://cloud.githubusercontent.com/assets/22588035/24081792/346d1604-0ce0-11e7-9e89-041047701fd2.png)

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by heysadboy** [comment]
Send new pull request here https://github.com/fossasia/phimpme-android/pull/277 and closing this.

**Comment by Abhi2424shek** [comment]
Hey i think you pressed the wrong button . Was the issue closed intentionally @heysadboy
