### ISSUE TITLE
Slideshow issue for all photos and favourites.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1717]
**Actual Behaviour**

Slideshow does not stops after displaying the last media in the favourites and all photos mode.

**Expected Behaviour**

Slideshow should stop after displaying the last media.

**Steps to reproduce it**

Click on any photo in the favourites collection, then choose the slideshow option in the menu to play the slideshow.

**Would you like to work on the issue?**

Yes.

**Comment by abishekvashok** [comment]
Is this required.
