### ISSUE TITLE
Photo save location edittext issue.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1721]
**Actual Behaviour**

On selecting the new folder option in the photo save location(file system) setting, the edittext to enter the new folder name appears but the softkeyboard doesn't pops up automatically and hint is not displayed for the edittext.

**Expected Behaviour**

When the edittext to enter the name of the folder gets focus, the softkeyboard should pop up automatically and hint should be displayed, since this is the format for all the other edittexts.

**Steps to reproduce it**

Go to settings activity, then Camera settings, thereafter More camera controls, then choose the new folder option in the Save Location setting.

**Would you like to work on the issue?**

Yes.

**Comment by Ananthusubramanian** [comment]
Yes ,I like to work on the issue .Is it ok to forcefully open the softkeyboard using the InputMethodManager class .

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian I'm already working on it.
