### ISSUE TITLE
Adding a search button to search a setting

### ISSUE THREAD

**Issue by vgoyal1996** [fossasia/phimpme-android#1724]
**Actual Behaviour**

There is no option to search a setting in the settings menu.

**Expected Behaviour**

A search button should be provided to search a particular setting and move directly to that setting.

**Screenshot**

![setting__01](https://user-images.githubusercontent.com/12955559/35291786-7cee7690-0094-11e8-85b8-898c9eece50e.jpg)

**Would you like to work on the issue?**

Yes

**Comment by Ananthusubramanian** [comment]
Is anyone working on this issue?

**Comment by abishekvashok** [comment]
Considering the inactivity @Ananthusubramanian please proceed

**Comment by Ananthusubramanian** [comment]
@abishekvashok  I am confused with adding texts like "Theme" ,"General" in between a recycler view ,without these subsections it would be easy.

**Comment by abishekvashok** [comment]
It's fine that the heading don't appear in the search results.

**Comment by Ananthusubramanian** [comment]
My idea of doing this is to add all the items to a sectioned recyclerview and filter it by the string given by user, but I am stuck with different items in activity_settings.xml. Now the items  in settings activity are just created in xml itself .There is no common items .How to solve it?or should I add 3 settings item ,the code is little big . Would this work?

**Comment by sauravvishal8797** [comment]
Not necessarily required at the moment.
