### ISSUE TITLE
Maximum images shown to user in gallery

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/phimpme-android#173]
**Actual Behaviour**

Only 21 images is shown in gallery

**Expected Behaviour**

Images should be loaded when user scroll down dynamically

**Would you like to work on the issue?**

I would love to but need guidance

**Comment by Abhi2424shek** [comment]
The plus button?

**Comment by mohitmanuja** [comment]
@vaibhavsingh97  Yes you are right. It should be done in this way.

**Comment by dynamitechetan** [comment]
Main purpose of this app is not to show the gallery images. 
When we will show him more grids of photos uploading sites user will have to scroll to bottom and then see them. So no need to load more images on scroll.

**Comment by vaibhavsingh97** [comment]
That means, if the user wants to edit photos then he have to click on "plus" icon numerous time to get his/her photo and then he/she can edit.  If gallery will show images dynamically then the user will find an easy way to edit his/her photo.

**Comment by Abhi2424shek** [comment]
IMO, we should have lazy loading on scroll. @pa1pal your opinion is this needed now?

**Comment by pa1pal** [comment]
Yes scroll option would be much better.

**Comment by rohanagarwal94** [comment]
@vaibhavsingh97 are you working on this, or should I start?

**Comment by vaibhavsingh97** [comment]
@rohanagarwal94 I will work on this issue. Please give me some time as I have minor exams till 23 Mar

**Comment by amitiwary999** [comment]
@vaibhavsingh97 have you started working on it? this issue is creating  problem so if you are busy let's other to slove this.

**Comment by vinaysajjanapu** [comment]
is anyone currently working on this issue? 

I'm interested to work on it

**Comment by vaibhavsingh97** [comment]
@vinaysajjanapu @amitiwary999 I am working on the issue

**Comment by vinaysajjanapu** [comment]
@vaibhavsingh97 It has been 10 days since you opened the issue. So I sent a PR. you may improve it if you wish.

**Comment by Abhi2424shek** [comment]
Closed via #309
