### ISSUE TITLE
Bug in offline sharing images

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1732]
**Actual Behaviour**

When you share an image in offline mode from LFMainActivity and see the upload history, the images are seen like the below 2nd screenshot and when you come back to albumsmode and refresh the albums are seen like 1st screenshot.

**Expected Behaviour**
Either the images should not be sent in offline mode or if they are sent the images should properly be displayed in upload history.

**Steps to reproduce it**

Send an image in offline mode from LFMainActivity and open the upload history. Now open LFMainActivity in albumsMode and refresh.

**Screenshots of the issue**
![lf](https://user-images.githubusercontent.com/24502136/35336082-444c11cc-013d-11e8-8012-9c7c3cd75250.png)
![uphis](https://user-images.githubusercontent.com/24502136/35336083-447d8428-013d-11e8-800d-08cc5c68ae46.png)

**Would you like to work on the issue?**

Yes.

**Comment by mariobehling** [comment]
Seems to be working now.
