### ISSUE TITLE
The image description not visible clearly on light or white coloured images

### ISSUE THREAD

**Issue by batbrain7** [fossasia/phimpme-android#1737]
**Actual Behaviour**

Any photo with white or light colour, the image description is not clearly visible due to overlapping of similar light shaded or white shaded colours.

**Expected Behaviour**

The description maybe of any other colour but it should be clearly visible no matter the colour of the photo.

**Steps to reproduce it**

Open any white or light coloured image in the gallery and click on the image description button.

here is a screenshot for a problem.

**Screenshots of the issue**

![screenshot_20180124-213104](https://user-images.githubusercontent.com/16780496/35342510-427e5790-014e-11e8-89bb-0082f4570eef.png)

**Would you like to work on the issue?**

Yes

**Comment by raj10071997** [comment]
@batbrain7 issue is already there #1523. Please close this.

**Comment by sauravvishal8797** [comment]
@batbrain7 As @raj10071997 said an issue is already created for this purpose. #1523 .The PR addressing the issue is #1740 up.

**Comment by batbrain7** [comment]
@sauravvishal8797 Sorry my bad.
Closing this issue now
