### ISSUE TITLE
The album doesn't remain at the same position when pinned to top.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1738]
**Actual Behaviour**

When you pin the album to top, after refreshing the layout by swiping down, the album changes the position.

**Expected Behaviour**

The album shouldn't change the position.

**Would you like to work on the issue?**

Yes.

**Comment by mayank8318** [comment]
@raj10071997 Isn't this the purpose of pinnning it to the top? You pin it to top so that the pinned album is displayed first and hence it will change position.
@nikit19 @codedsun

**Comment by codedsun** [comment]
Yes! i think that's what means to pinning the album to top.

**Comment by raj10071997** [comment]
@mayank8318 @nikit19 @codedsun  I was saying that if you pin only one album to the top and refresh the layout by swiping down the first album displayed is Phimp.me and not the one we pinned at the top. And if you pin multiple album at the top and they are arranged in order  of the time they are pinned. But as soon as swipe down , same Phimp.me album is displayed first which is not pinned.
