### ISSUE TITLE
Save option is not working after adding filter - Phimp.me

### ISSUE THREAD

**Issue by Tanvir-rahman** [fossasia/phimpme-android#1754]
#### Expected behavior
The image should be saved auto or save option should be visible after a filter is added.

#### Actual behavior
After adding a filter, it is not saving.

#### How to reproduce
1.	Open phimp.me app.
2.	Go to edit option and select an image.
3.	Apply filter and press the tick option.
<br/><br/>

* Operating system: Android

#### Recording Of The Bug
![1.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516855784/rbqfjqztndfyeszz81qx.jpg)
![2.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516855791/v763owtdrzmuzz0s1smf.jpg)
![3.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516855798/f9kgvyoxa7ekeai2vkkt.jpg)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tanvirrahman/save-option-is-not-working-after-adding-filter-phimp-me">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sauravvishal8797** [comment]
@Tanvir-rahman There is a save button in the discard changes dialog along with the Cancel and Confirm buttons. Please make sure that you have cloned the development branch.

**Comment by Tanvir-rahman** [comment]
Ok i was actually using release version

**Comment by sridharjajoo** [comment]
@Tanvir-rahman Could you close this issue :)
