### ISSUE TITLE
The image description not completely visible in landscape mode

### ISSUE THREAD

**Issue by batbrain7** [fossasia/phimpme-android#1758]
**Actual Behaviour**

When we click on image description button and rotate the phone the complete image description is not shown instead only the half part is shown and rest is cutoff, as there is no scrollview present

**Expected Behaviour**

All the details of the image should be present.

**Steps to reproduce it**

Open any photo from the gallery then click on image description option and rotate the phone.

**Screenshots of the issue**

![screenshot_20180127-235526](https://user-images.githubusercontent.com/16780496/35475065-c7d6a26e-03bd-11e8-924d-7161d222eb64.png)

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@batbrain7 An issue is already there for this purpose. #1602

**Comment by batbrain7** [comment]
sorry my bad again @sauravvishal8797 ,
Will remember it for the next time
