### ISSUE TITLE
album gets permanently hidden

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1774]
**Actual Behaviour**

I was hiding and unhiding my last albums repeatedly, then suddenly half of my albums where hidden. There were no albums in HiddenFolders. So when I uninstall the app and reinstall it the albums became visible but my last album is still not visible neither in LFMainActivity nor in HiddenFolders and I am not able to get it back.

**Expected Behaviour**

The hiding option should work correctly.

**Steps to reproduce it**

Try hiding and unhiding one or more albums repeatedly.

**Would you like to work on the issue?**

Yes.

**Comment by yashLadha** [comment]
I wasn't able to reproduce this issue @raj10071997 . Can you send some ss or error logs, else ping @abishekvashok to close this issue due to inactivity.

**Comment by raj10071997** [comment]
@yashLadha The issue was valid and I even lost my messenger album photos. But I am not able to reproduce the effect now. @abishekvashok  you can close this issue, if I get this issue again, I'll try to get the gif of the issue. For now you can close this.

**Comment by yashLadha** [comment]
@raj10071997 Just delete the .nomedia file from the folder and they will be back.

**Comment by yashLadha** [comment]
Ping @abishekvashok  to close the issue and flag as manufacturer issue.

**Comment by raj10071997** [comment]
@yashLadha At that time I read about it, did that and I got my photos back, but at that time I didn't know about it at the first time. So I posted this issue as most of the user are unaware about these changes that are made when we hide the album. And this might happen with anyone (as with me).
