### ISSUE TITLE
Improvement in Camera UI 

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/phimpme-android#178]
**Expected Behaviour**
![Camera UI prototype](https://cloud.githubusercontent.com/assets/8705386/24079774/2a9e048c-0cb6-11e7-8495-97fce7d27e47.png)
We can change our camera layout. need suggestions on this layout
Additions of small features:
+ Gridlines #271 
+ HDR mode #162 
+ Tap to focus #162 
**Would you like to work on the issue?**
Yes

**Comment by Abhi2424shek** [comment]
You could work on grids as ithe things are being worked out others currently.
