### ISSUE TITLE
Grammatical error in README.md

### ISSUE THREAD

**Issue by achalpandeyy** [fossasia/phimpme-android#1793]
**Actual Behaviour**

There is an unnecessary period at the end of 8th point in 'Features' section in README.md.
It reads-

> Write anything on the images in your handwriting!!.

**Expected Behaviour**

There is no need for the period since exclamation mark is already present.
It should be-

> Write anything on the images in your handwriting!

**Would you like to work on the issue?**

Yes

**Comment by AdityaGupta030697** [comment]
can I work on this?

**Comment by isuruAb** [comment]
@achalpandeyy  are you still working on this issue?

**Comment by yashLadha** [comment]
If @isuruAb No PR is sent for this. I am sending a Patc. Issues are pilling up in the Repo. If it is suitable for you.
