### ISSUE TITLE
There is no way to change the password protection on local folders.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1799]
**Actual Behaviour**

The only way to change the password protection on local folders is to turn it off and then turn it on for changing the protection ( say adding more local folders for protection).

**Expected Behaviour**

There should be a way to change the password protection without turning it off.

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@raj10071997  Are u still working on this?
