### ISSUE TITLE
Add more emojis.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1805]
**Actual Behaviour**

Limited no of emojis are available in the editing option.

**Expected Behaviour**

User should be presented with more emoji options.

**Steps to reproduce it**

Click on the edit photo option, go to stickers, then go to emojis.

**Would you like to work on the issue?**

Yes.

**Comment by mayank8318** [comment]
@sauravvishal8797 I made an issue for this #1801

**Comment by sauravvishal8797** [comment]
@mayank I thought you'll be adding more items to the stickers list rather than modifying particular items in the stickers list such as emojis, hashtags etc. Can you please mention if you will be modifying the items already present in the stickers section as well?

**Comment by mayank8318** [comment]
@sauravvishal8797 oh sorry for not being clear. I meant adding items to already present lists like emojis, hashtags etc. As in adding more emojis and stuff.

**Comment by sauravvishal8797** [comment]
@mayank8318 OK.cool. I'm closing this issue.
