### ISSUE TITLE
Error:(44, 0) *** Android NDK: Aborting    .  Stop.

### ISSUE THREAD

**Issue by gokuls02** [fossasia/phimpme-android#1806]
**Actual Behaviour**

When i am trying to import the file to Android Studio it is showing this error.

**Expected Behaviour**

Perfectly build and with no errors

**Screenshots of the issue**

![screenshot 1](https://user-images.githubusercontent.com/31446109/35788077-e6dd4cca-0a58-11e8-8773-f7c76c3a61a3.png)

**Would you like to work on the issue?**

Yes

**Comment by AhmedSaber0** [comment]
solved?

**Comment by abishekvashok** [comment]
This is because of your android config.
