### ISSUE TITLE
Password visible while entering in dialog box

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1811]
**Actual Behaviour**
When password is applied to individual folders in the main activity , the password is visible while we are typing.

**Expected Behaviour**
The password should be starred.

**Steps to reproduce it**
Apply password to any of the folders and then try to access it later.

**Screenshots of the issue**
![password](https://user-images.githubusercontent.com/20684618/35855784-25a8a114-0b5a-11e8-9f3f-76904e443584.png)

**Would you like to work on the issue?**
Yes!

**Comment by sauravvishal8797** [comment]
@sridharjajoo  I have already created an issue for this purpose. #1766
