### ISSUE TITLE
All details are not visible in landscape mode.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1823]
**Actual Behaviour**

When you view the details of an image in landscape mode, all the details are not visible.

**Expected Behaviour**

All the details should be visible.

**Screenshots of the issue**

![details](https://user-images.githubusercontent.com/24502136/36031572-2fbc7d64-0dd1-11e8-99f1-b8b54d76a67f.png)

**Would you like to work on the issue?**
Yes

**Comment by batbrain7** [comment]
@raj10071997 please close this issue, #1602 is already there and a PR has already been sent regarding this issue.
