### ISSUE TITLE
Cluttered animation while switching Activities

### ISSUE THREAD

**Issue by yashLadha** [fossasia/phimpme-android#1825]
**Actual Behaviour**

Same entry animation is being applied on different fragments, because of which ui is looking very much cluttered.

**Expected Behaviour**

The transition between different views should be smooth.

**Steps to reproduce it**

Just switch over between Camera, Gallery and Accounts.

**LogCat for the issue**

None

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/18033231/36033892-340e8d42-0dd8-11e8-83a9-7435344d2299.png)

**Would you like to work on the issue?**

Yes

**Comment by Pravesh-Jamgade** [comment]
by smooth transition ,means you want instant change or a delay screen

**Comment by yashLadha** [comment]
By smooth means, i means it should not the show black screen while transition. As you can see in the gif @Pravesh-Jamgade . I am not getting time to make adjustments. Will send PR in weekend.
