### ISSUE TITLE
position of the scrollbar doesn't remain same when orientation changes.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1829]
**Actual Behaviour**

When you view a long album or view images in AllPhotosMode, if you scroll down a little bit and change the orientation, you will see that you reach the beginning of the album or the AllPhotosMode.

**Expected Behaviour**
The scrollbar should remain at the same position and the user should not be taken to starting of the album or AllPhotosMode.

**gif of the issue**

![scroll](https://user-images.githubusercontent.com/24502136/36039902-dd3c39d0-0de9-11e8-8d54-078795924e44.gif)

**Would you like to work on the issue?**

Yes.

**Comment by Avjeet** [comment]
I want to work on this issue.

**Comment by raj10071997** [comment]
@Avjeet  I am sorry but I am currently working on this. If you want to work on some issues, you can work on those issues which have been pending from over a month and there is no progress on those issues. Just ask the author of that issue that you want to work on the issue. If he/she says yes, you can work on it. :smile:

**Comment by Avjeet** [comment]
ok ..
