### ISSUE TITLE
Back button is not working properly

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#183]
**Actual Behaviour**

If we click back button in gallery activity then it shows dialog box but in other activity on pressing back button app closed.

**Expected Behaviour**

it should not happen.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
Yes pls go on.
