### ISSUE TITLE
Bottom Navigation Menu item Orientation Change

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [fossasia/phimpme-android#1837]
**Actual Behaviour**

Orientation of the bottom navigation bar menu items do not change when Camera is active, where as the shutter, options, camera flip icon changes and so on changes it's orientation when the device is rotated. 

**Expected Behaviour**

Orientation of the text and icon of the bottom navigation menu items should change in accordance with the current screen orientation.

**Screenshots of the issue**

![issue](https://user-images.githubusercontent.com/26897680/36073433-61e555f0-0f56-11e8-8f2e-b606ff9c75ba.jpeg)

**Steps to reproduce it**

- Run the app in any Android Device.
- Select Camera in the bottom navigation menu.
- Change Orientation.

**Comment by DhruvamSharma** [comment]
I want to work on it.
