### ISSUE TITLE
Favourites collection modification.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1838]
**Actual Behaviour**

Images in the favourites collection are also displayed with star icon. Images already marked favourite is again provided with option to add to favourites in SingleMediaActivity.

**Expected Behaviour**

The images in the local/folders those have been added in the favourites collection are displayed with star icon mark to differentiate those from the other photos, but in the favourites collection since only the favourite marked photos are displayed there is no need to display the photos with star mark.

**Steps to reproduce it**

Add photos to favourites, go to the favourites collection.

**Would you like to work on the issue?**

Yes.

**Comment by raj10071997** [comment]
@sauravvishal8797  I have already made a PR #1707 for the second case.

**Comment by sauravvishal8797** [comment]
@raj10071997 Oh, didn't see that. Will remove the second part of this issue. Maybe you could display the heart icon with some colour suppose yellow(could be same as that of the star mark) for the images which have already been added to favourites.

**Comment by raj10071997** [comment]
@sauravvishal8797 Your suggestion is good. I'll make the changes regarding this.
