### ISSUE TITLE
No indication for showing more available options when editing image.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1846]
**Actual Behaviour**

There is no way to indicate the user that there are more options available for editing the image, unless the user himself slides to the left for more options. Also a lot of options have not been explained in the EditImageActivity which the user has to himself understand by using them. One of the problem can be seen in the below screenshot. In this screenshot it seems that there are 5 options for filtering. It is up to the user, unless he/she slides to the left to see more available options, the user is unknown of these.

**Expected Behaviour**

There should be a MaterialShowCase which guides the user about the EditImageActivity for the first time.

**Screenshots of the issue**

![edit](https://user-images.githubusercontent.com/24502136/36133760-53d13b4a-10a6-11e8-823d-331cae9ab1df.png)

**Would you like to work on the issue?**

Yes.

**Comment by sauravvishal8797** [comment]
@raj10071997 I'd agree with @codedsun , there is no need to add material design showcase view here, instead for your concern what can be done I guess is a simple icon can be added at the end of the filter list here, which on clicking will perform the left swipe action. In this way with the display of the icon the user will know that there are more options.

**Comment by raj10071997** [comment]
@codedsun @sauravvishal8797 First I thought of the same thing as said by @sauravvishal8797 . But there are some icons which I have never seen in general editing apps. Like the Middle button (bef_aft) which flips the changes back to the original image. Like the back and forward arrow buttons to revert changes backward and forward. That's why I thought of adding a materail design show case. But also adding a material design showcase will only increase complexity of the file. I think a small little icon to display more available options is good.
