### ISSUE TITLE
Different selectors for images

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#185]
**Actual Behaviour**

There are three different image selectors available in the app at
1. Gallery
2. Image picker
3. Upload image list

**Expected Behaviour**

There has to be a single image selector through out the application

**Steps to reproduce it**

1. Open app
2. Go to gallery
3. Long press an image in the gallery (Blue check box)
4. Go to Upload
5. Click on _Add Images_ and go to image picker
6. Click on an image (Blue circle tick)
7. Click _Done_ and go to Upload image list
8. Long press an image in the upload photo list (White circle tick)

**LogCat for the issue**

> Not available

**Screenshots of the issue**
- Gallery
![Gallery](https://cloud.githubusercontent.com/assets/14261304/24081509/3c1ccc96-0cdb-11e7-98f0-7bc347a7d774.png) 
- Image picker
![Image Picker](https://cloud.githubusercontent.com/assets/14261304/24081510/3c2230be-0cdb-11e7-8f5a-ece95d6f6aa3.png)
- Upload Image list
![Upload image list](https://cloud.githubusercontent.com/assets/14261304/24081511/3c25bb58-0cdb-11e7-8c57-172e521f391f.png)

**Would you like to work on the issue?**

Yes! But first need to clarify which icon is more suitable for the selector.

**Comment by pa1pal** [comment]
I think the last one, in upload Screen is better

**Comment by CloudyPadmal** [comment]
It looks good! :relaxed: I'll implement it!!
