### ISSUE TITLE
No option to remove from favorites when a favorite photo is selected.

### ISSUE THREAD

**Issue by arpank10** [fossasia/phimpme-android#1855]
**Actual Behaviour**

When a favorite photo is selected, add to favorites option is visible in menu,which on clicked displays the toast that it is already in favorites. 

**Expected Behaviour**

Menu should have option of remove from favorite when only favorite photos are selected.

**Steps to reproduce it**

Select a favorite photo from local folders.There is no option to remove it from favorites.

**Screenshots of the issue**

![whatsapp image 2018-02-13 at 11 06 53 pm](https://user-images.githubusercontent.com/24573296/36164600-d4913a7a-1112-11e8-8936-247192a089e8.jpeg)

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@arpank10  Photos can be removed from favourites by going to the favourites collection and performing the delete operation . I guess that is fine for removing from favourites for the time being.

**Comment by codedsun** [comment]
@arpank10 Thanks for opening the issue, but we have this option in the Favourites section! You can pickup the many other issues which are availaible.Thanks and please close this issue.
