### ISSUE TITLE
App should show toast when selecting filters

### ISSUE THREAD

**Issue by Navd15** [fossasia/phimpme-android#1860]
**Actual Behaviour**

**No** toast when user select filters on camera tab

**Expected Behaviour**

Show toast to user with filter name on it.

**Steps to reproduce it**

When user selects the filter icon toast will be shown for a short duration

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@Navd15 I think the app displays the selected filter very clearly, so adding the toast message would just be a redundant addition.

**Comment by Navd15** [comment]
@batbrain7 ...actually i am talking about the main camera window, when user selects the live filters it just changes without notifying the user....if i am not wrong i think you are refering to the below activity 

![device-2018-02-17-175823](https://user-images.githubusercontent.com/22269757/36340931-68325088-140c-11e8-9824-040b1a7d0f23.png)

**Comment by batbrain7** [comment]
Yeah, I was talking about the editor of the app, my apologies
Go ahead please 👍

**Comment by Navd15** [comment]
no problem bru

**Comment by sauravvishal8797** [comment]
This is not necessarily required at the moment, therefore closing this issue.
