### ISSUE TITLE
Changing UI

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1868]
**Actual Behaviour**

Currently, the UI is very problematic. It is laggy and is not beautiful enough. 

**Expected Behaviour**

The UI should be eye pleasing. 

**Steps to reproduce it**

The layout of the main activity to be changed such that it looks beautiful and less laggy.

**LogCat for the issue**

The problem was on Moto G5 Android Nougat 7.1

**Screenshots of the issue**

![screenshot_20180220-133258](https://user-images.githubusercontent.com/18664195/36413244-8728239e-1643-11e8-9b97-ccbb63080da2.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by mayank8318** [comment]
@DhruvamSharma Proposed change?

**Comment by sridharjajoo** [comment]
@DhruvamSharma What changes are you planning to inculcate inside the app?Please post the related screen shots

**Comment by DhruvamSharma** [comment]
Changing UI represents changes in the main activity, the sharing page, settings page. I will make a pull request and then post the screen shot.

**Comment by abishekvashok** [comment]
Better make a screenshot then a pr please @DhruvamSharma

**Comment by DhruvamSharma** [comment]
![android mobile 1](https://user-images.githubusercontent.com/18664195/37301335-491c5eba-264e-11e8-8763-84315bae059c.png)
@abishekvashok @yashLadha  Please see the UI

**Comment by sauravvishal8797** [comment]
@DhruvamSharma Are u still working on this?
