### ISSUE TITLE
Removing unnecessary setting options.

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1869]
**Actual Behaviour**

Currently, the user is provided with a lot of options to meddle with. Like the 3 themes option, column option. Primary colour, Accent colour, status bar, coloured navigation bar etc.

**Expected Behaviour**

The expected behaviour is to provide with less customisation to the user for Themes. The app UI is designed by the experienced developers. They should provide just 2 themes and with these themes, all the other colours, like accent, primary and primary dark should be set. 
This way the branding of the project is still maintained.

**Steps to reproduce it**

1. Providing only 2 themes.
2. On clicking on any theme, all the colours are set accordingly.
3. Changing the code in the files.

**Screenshots of the issue**

![screenshot_20180220-134357](https://user-images.githubusercontent.com/18664195/36413767-d337155e-1645-11e8-859c-f5432e90be5e.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by sauravvishal8797** [comment]
@DhruvamSharma Are u still working on this?
