### ISSUE TITLE
Changing the icon of the app. (UI)

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1872]
**Actual Behaviour**

The icon has rounded corners but the icon looks mismanaged and has white space left around the corner.

**Expected Behaviour**

The icon should not have white space around the icon.

**Steps to reproduce it**

The icon needs to be reproduced using photo Editors or icon Makers. 

**Screenshots of the issue**

![screenshot_20180220-152646](https://user-images.githubusercontent.com/18664195/36418049-b34ba256-1653-11e8-9032-1d8f376bb164.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by raghavpuri31** [comment]
Is anyone working on the issue @DhruvamSharma

**Comment by DhruvamSharma** [comment]
I already am.
