### ISSUE TITLE
2 images in the view-port at the same time after orientation change to landscape.

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1874]
**Actual Behaviour**

When the orientation is changed from portrait to landscape, 2 images in the viewport appears. 

**Expected Behaviour**

When the orientation is changed, the image should get smaller and there should be only 1 image in the viewport in the landscape mode. 

**Steps to reproduce it**

1. Resize the image to shorter size.
2. Make them visible on the viewport.

**Screenshots of the issue**

![screenshot_20180220-154228](https://user-images.githubusercontent.com/18664195/36419052-e0a1b85a-1656-11e8-999a-784930faa253.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by yashLadha** [comment]
Still not able to produce the issue @DhruvamSharma . Using Moto G5 Plus as device.
