### ISSUE TITLE
Smaller image after Orientation change in portrait mode.

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1875]
**Actual Behaviour**

When the orientation is changed from landscape to portrait, some images become smaller in size.

**Expected Behaviour**

The image should resize back to normal state, as when they were when the app was opened.

**Steps to reproduce it**

Need to handle the orientation change system when viewing the photos.

**Screenshots of the issue**

![screenshot_20180220-154241](https://user-images.githubusercontent.com/18664195/36419270-72091bbc-1657-11e8-97c5-e8e28b0d64b1.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by yashLadha** [comment]
I am not able to reproduce the issue @DhruvamSharma
