### ISSUE TITLE
Reduce size of Repository

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/phimpme-android#188]
**Actual Behaviour**

Currently, the size of the repository is 135 MB which is due to the apk branch. 

**Expected Behaviour**

Since only latest apk is required for testing purposes, we need not maintain all previous APKs that were generated, so an orphan branch can be made with just one commit, that maintains latest APK and current branch can be overwritten by that after each apk generation on a commit.

**Steps to reproduce it**

Clone the repo in local system.

**Would you like to work on the issue?**
Yes

**Comment by pa1pal** [comment]
@harshitagupta30 you can work on this issue.

**Comment by Abhi2424shek** [comment]
@harshitagupta30 just a info --- only the latest apk is maintained in the apk branch.

**Comment by harshitagupta30** [comment]
@Abhi2424shek Sorry I didn't see that :+1:

**Comment by Abhi2424shek** [comment]
Its ok. Well you could update the repository readme mentioning of the cloning only the development branch. This will save a lot of size, I mean MBs. Can you do that @harshitagupta30?

**Comment by harshitagupta30** [comment]
@Abhi2424shek Sure I can do that :+1:
