### ISSUE TITLE
Add option to unfavourite images

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1884]
**Actual Behaviour**
Currently there is no option to unfavourite any image. An option can be added to the overflow menu when a favourite image is selected if the user wants to unfavourite it or not.

**Would you like to work on the issue?**
Yes!

**Comment by sauravvishal8797** [comment]
@sridharjajoo The user can go to the favourites collection and remove image/images from favourites. I guess that is fine for the time being.

**Comment by sridharjajoo** [comment]
@sauravvishal8797 If i add the option in the photos mode as well , its better for the user. And also if we want to remove an image from favourites mode , the process is not very clear as the option to delete an image and remove an image from favourites are both the same
