### ISSUE TITLE
App crashing in favourites mode

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1885]
**Actual Behaviour**
When we navigate to the favourites photo mode and click on any of the photo , the app is crashing. This crash is happening after the favourites option was added to the bottom menu bar.

**Steps to reproduce it**
Go to favourites mode and select any picture.

**Would you like to work on the issue?**
Yes!

**Comment by sauravvishal8797** [comment]
@sridharjajoo  There is an issue already there for this purpose. #1880
