### ISSUE TITLE
Add more fonts to Write option in editing

### ISSUE THREAD

**Issue by Navd15** [fossasia/phimpme-android#1891]
**Screenshots of the issue**

![device-2018-02-23-232102](https://user-images.githubusercontent.com/22269757/36608630-615a6514-18f0-11e8-8b42-049808501252.png)

**Would you like to work on the issue?**
yes

**Comment by roudabeh** [comment]
Do you find any solution for this?

**Comment by iman100** [comment]
how add fonts RTL with assets folder??

**Comment by iman100** [comment]
> 
> 
> how add fonts RTL with assets folder??

how read font files from assets folder and add to Class FontManeger
