### ISSUE TITLE
Using Material design icons in the app

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1901]
**Actual Behaviour**
In the following image in the slider the icons for apply and cross aren't material design icons and even the thickness isn't the same.The images should be consistent.
![screenshot_2018-02-26-00-12-35-970_org fossasia phimpme](https://user-images.githubusercontent.com/20684618/36645099-dd4b1bf6-1a89-11e8-8071-cf1d576d064f.png)

**Expected Behaviour**
Material design icons should be used

**Steps to reproduce it**
Go to edit mode of the app.

**Comment by yashLadha** [comment]
Are you working on this issue? If not i am ready to take up this issue?

**Comment by sridharjajoo** [comment]
I am...I'll send the pr soon

**Comment by sauravvishal8797** [comment]
@sridharjajoo Are u still working on this?

**Comment by sridharjajoo** [comment]
No @sauravvishal8797
