### ISSUE TITLE
App crashes when you try to edit a gif

### ISSUE THREAD

**Issue by umair1209** [fossasia/phimpme-android#1903]
#### Expected behavior

I was on the app and I thought of editing a photo while I came across a gif and tried editing that but it didn't let me do that. 

#### Actual behavior
When I clicked on the edit option, the application crashed. 
I tried multiple time with different gifs but the result was same. 

#### How to reproduce
- Open phimp.me
- Select a gif and click edit
- The application will crash

* Operating system: Android 6.0.1 
I am using the latest version of phimp.me

#### Recording Of The Bug

![20180223_012421.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519329956/eoboazy5yauepszuggmd.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/app-crashes-when-you-try-to-edit-a-gif">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by saitejach1998** [comment]
is anyone working on it?
