### ISSUE TITLE
Issue in Accounts section bottom bar.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1911]
**Actual Behaviour**

The bottom is displayed in a different colour than the primary colour.

**Expected Behaviour**

The bottom bar should be displayed in the primary colour.

**Steps to reproduce it**

Go to accounts section by taping on the icon on the LFMainActivity bottom bar.

**Would you like to work on the issue?**

Yes..

**Comment by raj10071997** [comment]
@sauravvishal8797  can you check if the toggle button which sets the primary color of the navigation bar in the settings was on or off?

**Comment by sauravvishal8797** [comment]
@raj10071997 The button was on.

**Comment by raj10071997** [comment]
@sauravvishal8797  Can you please rewrite the steps to reproduce the issue as I am not able to reproduce the effects? In my app the Accounts activity tool bar and bottom bar both are being displayed according to primary color.

**Comment by sauravvishal8797** [comment]
@raj10071997 Guess it was just a one-time problem, working fine for me too therefore I'm closing this issue.
