### ISSUE TITLE
Font Issues

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/phimpme-android#192]
**Actual Behaviour**
Font of ActionBar at gallery is not same as font of Toolbars in other fragments

**Expected Behaviour**
Font of ActionBar at gallery must be same as font of Toolbars in other fragments

**Would you like to work on the issue?**
No. A beginner can try.

**Comment by anuja-k** [comment]
I want work on this issue. Should I proceed

**Comment by Abhi2424shek** [comment]
@anuja-k can you reply, are you still on it.

**Comment by anuja-k** [comment]
@Abhi2424shek 
Sorry, I am not on it

**Comment by Abhi2424shek** [comment]
OK, closed via #280
