### ISSUE TITLE
Image is no fully visible in SingleMediaActivity

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1925]
**Actual Behaviour**

When you open some images in SingleMediaActivity the image is not fully visible. 

**Expected Behaviour**

The image should be fully visible.

**Steps to reproduce it**

Take a any screenshot in your mobile and open it in the SingleMediaActivity. You will see that the bottom is not fully visible in SingleMediaActivity. You can even take the screenshot in the albumsMode and view that screenshot in SingleMediaActivity, you will see that the bottom bar is not full visible.

**Would you like to work on the issue?**

Yes.

**Comment by DhruvamSharma** [comment]
Same as https://github.com/fossasia/phimpme-android/issues/1873

**Comment by raj10071997** [comment]
@DhruvamSharma  Yes it same as #1873. I am closing this issue.
