### ISSUE TITLE
Adding Kaleidoscope filter

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1937]
**Actual Behaviour**

There is no Kaleidoscope filter in the app

**Expected Behaviour**

Adding Kaleidoscope filter.

**Steps to reproduce it**

 Selfie x Selfie is an Android Experiment that uses your phone’s camera, motion sensors, and graphics hardware to generate a reactive 3D universe that responds to your movements. Selfie x Selfie was built using Cinder for Android at Google. 
Using their open sourced code to produce the same effect as a filter.

**Screenshots of the issue**

![screenshot_20180307-012939](https://user-images.githubusercontent.com/18664195/37055579-15599714-21a8-11e8-8a5c-3ce437eefbf1.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by sauravvishal8797** [comment]
Not required at the moment.
