### ISSUE TITLE
Add option to select all images in the image selector

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#194]
**Actual Behaviour**

There is no option to select all images in any image selector.

**Expected Behaviour**

There should be option on the toolbar on long pressing an image to select all the images at once.

**Screenshots of the issue**

![screenshot_2017-03-20-00-16-40-759_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24083719/a532810e-0d02-11e7-95a6-fa7f2028dd1d.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
One issue per time would be great :)
