### ISSUE TITLE
Add On-boarding Screen

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1940]
**Actual Behaviour**

Whenever the user opens the app for the first time, the user is directly presented the app without telling what the top level features are. 

**Expected Behaviour**

The user should be made aware what features the app has and what all can it do for the first time. 

**Steps to reproduce it**

After the splash screen, the user should b shown with the Top Level Benefits of the app only the first time. This is made by the use of Preference Class in the app.

**Screenshots of the issue**

![onboarding-screen](https://user-images.githubusercontent.com/18664195/37106213-39dec302-2257-11e8-9202-30ce344d538d.gif)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by mayank8318** [comment]
@DhruvamSharma I like the idea of letting the user explore on his own after we have shown him/her the main navigational directions. After all, this is an image editing app and you expect these features to be there. Also, IMO everything is very much intuitive. Just my opinion though :)

**Comment by DhruvamSharma** [comment]
I think few features like **safety vault** and **extra customization**, **uploading and sharing** in a different way is something user should be made aware of such that he is excited to learn more.

The main purpose of onBoardingScreen:



 1. Welcome users and excite them about the experience ahead
 2. Help users implicitly or explicitly understand how the app can be used in their lives
 3. Drive users to take actions that increase engagement and retention in the first seven days

**Comment by DhruvamSharma** [comment]
@batbrain7  What do you expect?

**Comment by batbrain7** [comment]
@DhruvamSharma I agree with @mayank8318 material design specs look good 👍 
implement it :)

**Comment by DhruvamSharma** [comment]
@batbrain7  So you think I should implement an onBoarding Screen like this?

**Comment by batbrain7** [comment]
Well it is my opinion let other developers share their opinion too, but this should be done in way that you add some new tutorial options in the form that is already existing in the app.

**Comment by sauravvishal8797** [comment]
@DhruvamSharma I guess the feature preview mentioning about the gallery, camera and accounts section for first install is ok and might be better if the user is allowed to explore other functionalities on his own, because sometimes previewing about every functionality via the onBoarding screen might just not have the first good impact on the user about the application and as @mayank8318  said it's an image editing app so those features are expected to be there(Just my opinion).

**Comment by abishekvashok** [comment]
If we want to include an on boarding screen make sure we include the correct set of slides with precise not on text and the images.

**Comment by mayank8318** [comment]
I agree with @abishekvashok. If we are to implement it then it has to be done suiting the theme of the app.

**Comment by DhruvamSharma** [comment]
Thanks everyone for your opinion. I will implement these ideas.

**Comment by DhruvamSharma** [comment]
This is the new prototype. Does this comply with the theme? @mayank8318 
![android mobile 3](https://user-images.githubusercontent.com/18664195/37220147-b114f3f2-23eb-11e8-81be-3f32a8011541.png)

**Comment by DhruvamSharma** [comment]
No.
