### ISSUE TITLE
Unknown usage of button

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#195]
**Actual Behaviour**

The button placed in the action bar is not working in the gallery fragment

**Expected Behaviour**

The expected behaviour is unknown.

**Screenshots of the issue**

![screenshot_2017-03-20-00-04-54-611_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24083808/4fc2fc60-0d04-11e7-97d6-a4df24f43292.png)

**Would you like to work on the issue?**

If we just need to remove it, let some beginner do it.

**Comment by dynamitechetan** [comment]
its working

**Comment by rohanagarwal94** [comment]
@dynamitechetan unclear on the usage. Secondly, not working on xiaomi mi3, mi4i.

**Comment by dynamitechetan** [comment]
it adds more images in the gallery grid. You can see them by scrolling the grid. Images are added at the end of grid. Working on OnePlus2, OnePlus3.

**Comment by rohanagarwal94** [comment]
My bad, its working. However it is misleading. I think auto addition of images on scrolling till the end of the 21 images might make more sense. @Abhi2424shek @pa1pal will that be worthy of an issue?

**Comment by pa1pal** [comment]
#173  issue is already open for this
