### ISSUE TITLE
Create option for whitelisting folders in the settings

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#196]
**Actual Behaviour**

Currently the app scans through the phone's folders to get all the images.

**Expected Behaviour**

The users will be able to whitelist folders in the settings to avoid those folders being scanned.

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
Pls work on one issue at a time :)
