### ISSUE TITLE
Too many Grammatical errors in Contributing.md

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/phimpme-android#1966]
**Actual Behaviour**

There are too many grammatical errors in Contributing.md

**Expected Behaviour**

The file should be error-free.

**Would you like to work on the issue?**

Yes, i would like to work on the issue.

**Comment by n1ghtshade** [comment]
I can help if you like!

**Comment by DhruvamSharma** [comment]
Already a PR regarding this issue. @n1ghtshade
