### ISSUE TITLE
Error:(44, 0) *** Android NDK: Aborting   Stop

### ISSUE THREAD

**Issue by hariharanc** [fossasia/phimpme-android#1981]
I followed all the development steps but i faced this issue in my android studio 3.0.1 version,
I used Ubuntu 64 bit OS,I installed ndk,CMake,LLDB all the setups.But i face this issue,I try to google it lot but i could not find the solution,Kindly help us to resolve this issue.
Thanks.

External Native Build Issues
Build command failed.
Error while executing process /home/hari/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/hari/Desktop/phimpme/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/hari/Desktop/phimpme/app/src/main/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-17 NDK_OUT=/home/hari/Desktop/phimpme/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/home/hari/Desktop/phimpme/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/home/hari/Desktop/phimpme/app/src/main/jni/Android.mk:opencv_contrib: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/hari/Desktop/phimpme/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_contrib.a exists  or that its path is correct   
Build command failed.
Error while executing process /home/hari/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/hari/Desktop/phimpme/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/hari/Desktop/phimpme/app/src/main/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-17 NDK_OUT=/home/hari/Desktop/phimpme/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/home/hari/Desktop/phimpme/app/build/intermediates/ndkBuild/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/home/hari/Desktop/phimpme/app/src/main/jni/Android.mk:opencv_contrib: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/hari/Desktop/phimpme/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_contrib.a exists  or that its path is correct   
/home/hari/sdk/ndk-bundle/build/core/prebuilt-library.mk
Error:(44, 0) *** Android NDK: Aborting    .  Stop.
<a href="openFile:/home/hari/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>
Error:(44, 0) *** Android NDK: Aborting    .  Stop.
<a href="openFile:/home/hari/sdk/ndk-bundle/build/core/prebuilt-library.mk">Open File</a>

**Comment by bhaveshjabuvani-credencys** [comment]
Same issue i facing in Andorid Studio 3.0.1

**Comment by bhaveshjabuvani-credencys** [comment]
Same issue i facing in Andorid Studio 3.0.1. Please help me.

**Comment by azri92** [comment]
The clue is here:
`Android NDK: Check that /home/hari/Desktop/phimpme/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_contrib.a exists or that its path is correct`

**This worked for me:**
1. Go to `app/src/main/jni/OpenCV.mk`
2. Change `OPENCV_LIBS_DIR:=$(OPENCV_THIS_DIR)/../jniLibs/$(OPENCV_TARGET_ARCH_ABI)` to `OPENCV_LIBS_DIR:=$(OPENCV_THIS_DIR)/libs/$(OPENCV_TARGET_ARCH_ABI)`.
3. Copy the folder `OpenCV-android-sdk/sdk/native/libs` into `app/src/main/jni`.
4. Copy the folder `OpenCV-android-sdk/sdk/native/libs` into `app/src/main/` and rename to jniLibs.
5. Copy the folder `OpenCV-android-sdk/sdk/native/3rdparty` to `app/src/main/`.
6. Clean build & run.

Somehow, you still need step 4. Else you'll get a "No implementation found.." error.

**Comment by azri92** [comment]
This [SO answer](https://stackoverflow.com/a/33581520/4253952) also helped me solve a problem I had with opencv. In `app/src/main/jni/Application.mk`, I changed APP_ABI to `APP_ABI := all`. Then I added the following into the app build.gradle:
```
android {
   ...   
   sourceSets {
        main {
            jni.srcDirs = ['src/main/jni']
            jniLibs.srcDirs = ['src/main/jni/libs']
        }
    }
```

**Comment by azri92** [comment]
Can you check that `armeabi-v7a/libopencv_contrib.a` is really in `E:/Android_Work/ExamplesNDemoes2/ImageFilter/phimpme/app/src/main/jni/libs/`?

**Comment by azri92** [comment]
You might also have to delete `app/.externalNativeBuild` & `app/build`, then do _invalidate cache & restart_ Android studio.

**Comment by bhaveshjabuvani-credencys** [comment]
**"armeabi-v7a/libopencv_contrib.a" is not present in this path E:/Android_Work/ExamplesNDemoes2/ImageFilter/phimpme/app/src/main/jni/libs/?** 
I had delete app/.externalNativeBuild & app/build, then do invalidate cache & restart Android studio
still not working.
Can you please download latest source code and then try to configure project in your pc.
I think you will got the problem

**Comment by hariharanc** [comment]
Thanks @azri92 its working...

**Comment by Aashima-Gupta** [comment]
Hi, I am getting this error:
Build command failed.
Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments **{NDK_PROJECT_PATH=null** APP_BUILD_SCRIPT=C:\Users\guptaa82\Desktop\FaceRecognitionApp\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\guptaa82\Desktop\FaceRecognitionApp\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=C:/Users/guptaa82/Desktop/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\guptaa82\Desktop\FaceRecognitionApp\app\build\intermediates\ndkBuild\debug\lib NDK_DEBUG=1 NDEBUG=null C:/Users/guptaa82/Desktop/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libface-lib.so}

**Comment by Aashima-Gupta** [comment]
Please Reply Asap.

**Comment by stevebaros** [comment]
Are you sure your NDK_MODULE_PATH variable is properly defined
