### ISSUE TITLE
[Feature request] Add color picker to text overlay

### ISSUE THREAD

**Issue by ghost** [fossasia/phimpme-android#1985]
When adding text to an image, a color picker dialog to select a color other than white would be an excellent feature.
I don't have the skill to implement this, but it could be a simple task for the right person.
[Example library](https://github.com/TurkiAlkhatib/Material-Color-Picker)

![68747470733a2f2f7261772e6769746875622e636f6d2f5475726b69416c6b68617469622f4d6174657269616c2d436f6c6f722d5069636b65722f6d61737465722f657a6769662e636f6d2d726573697a652e676966](https://user-images.githubusercontent.com/17913997/38439693-e06455ec-399b-11e8-9f70-73b6f6b52efb.gif)

**Would you like to work on the issue?**
No

**Comment by Diksha2008** [comment]
I would like to take this up!

**Comment by angmas1** [comment]
This feature has been added. Close this issue.
