### ISSUE TITLE
Images in the gallery not persistent on app minimisation

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#199]
**Actual Behaviour**

On app minimisation, the additional images opened is not persistent. Also, the selection of the images is not persistent.

**Expected Behaviour**

The additional images opened in the gallery should be persistent.

**Steps to reproduce it**

1.Open app.
2.Click on add button in gallery to open more images.
3. Select images.
4.Minimise the app.
5.Open the app again.
6. Neither the additional images are shown nor the selected images are known.

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by rohanagarwal94** [comment]
@pa1pal update on this?

**Comment by pa1pal** [comment]
@rohanagarwal94 you can work on it.
