### ISSUE TITLE
I followed the instructions to build the project I keep getting the same error: Cause: executing external native build for ndkBuild C:\Proyecto_photo_editor\phimpme-android\app\src\main\jni\Android.mk

### ISSUE THREAD

**Issue by cardaguh** [fossasia/phimpme-android#1992]
**Actual Behaviour**

The project doesn't build.

**Expected Behaviour**

Follow the steps in the documentation. The same error

**Steps to reproduce it**

Follow the steps in the documentation.

**LogCat for the issue**

No debuggable Processes appear.

**Screenshots of the issue**

**Would you like to work on the issue?**

I can or someone else.
![ndk_error](https://user-images.githubusercontent.com/5774603/39657552-66680b6e-4fce-11e8-9a75-4978ffe672a7.png)

**Comment by cardaguh** [comment]
Cause: executing external native build for ndkBuild C:\Proyecto_photo_editor\phimpme-android\app\src\main\jni\Android.mk

**Comment by sauravvishal8797** [comment]
@cardaguh Please make sure that you have properly installed the NDK and the repositories stated in the setup guidelines of this project in the Readme.md file of this project.
