### ISSUE TITLE
App is crashing on choosing the photo edit option in the SingleMediaActivity.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1998]
**Actual Behaviour**

App is crashing on selecting the photo edit option in the SingleMediaActivity.

**Expected Behaviour**

App should not crash on selecting the photo edit option.

**Steps to reproduce it**

Open an image via the SingleMediaActivity and choose the photo editing option.

**Would you like to work on the issue?**

Yes.

**Comment by gokuls02** [comment]
Hey bro this only works on android 6 and above . It also has a problem when installing in Redmi phones. I would prefer to use samsung. It also has got memory leak problem also.

**Comment by sauravvishal8797** [comment]
@gokuls02 You mean the edit function causing crash happening on the devices below android 5 and the redmi ones?
