### ISSUE TITLE
Settings features not working, app crash on click.

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#20]
Most of the features in settings activity are not working.
On click app crashed.

**Comment by pa1pal** [comment]
Most of the features are not needed anymore in the app. Will clean the code.

**Comment by anantprsd5** [comment]
@pa1pal There is a crash whenever the user wants to delete downloaded photos in the App. Shall I fix that or remove that functionality as of now?

**Comment by pa1pal** [comment]
@anantprsd5 Yes sure, do the necessary changes and send PR.

**Comment by Abhi2424shek** [comment]
@anantprsd5 any updates regarding the issue?

**Comment by anantprsd5** [comment]
@abhi2424shek I solved it in the PR #46. Its merged.
Thanks.

**Comment by anantprsd5** [comment]
@abhi2424shek There are no crashes currently in the settings activity on button click so I think this issue can be closed now.
