### ISSUE TITLE
App Crash in uploading image

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#200]
**Actual Behaviour**

The app is crashing in the uploading section in a particular workflow.

**Expected Behaviour**

The app should not crash.

**Steps to reproduce it**

1. Open upload section.
2. Add images to upload.
3. After the images are added in the upload fragment, select one of the images to add filters to it.
4. DO not change anything, and click discard.
5. Click the same image again.

**LogCat for the issue**

![screenshot from 2017-03-20 02-33-40](https://cloud.githubusercontent.com/assets/13241256/24084751/47afa9da-0d16-11e7-8066-fbd24014cce2.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by pa1pal** [comment]
not happening in my case. But if it is crashing in yours so you can work on it.

**Comment by Abhi2424shek** [comment]
It's not happening for me either.

**Comment by vinaysajjanapu** [comment]
Not happening for me too
