### ISSUE TITLE
Design new activity for modifying image in the uploading image section

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#201]
**Actual Behaviour**

The activity design does not follow material design guidelines.

**Expected Behaviour**

The activity should be completely redesigned keeping in mind the new support design library.

**Steps to reproduce it**

1. Go to upload tab.
2. Add images to upload.
3. After the images are selected in the image selector, click one of the thumbnail in the upload grid in the upload fragment.

**Screenshots of the issue**

![screenshot_2017-03-20-02-39-56-502_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24084783/ef1886ce-0d16-11e7-8906-717acffa9bf2.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by dynamitechetan** [comment]
#174 is pending, in continuation of #30.

**Comment by Abhi2424shek** [comment]
Yep @dynamitechetan is working on it :)
