### ISSUE TITLE
Redundancy in uploading images

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#202]
**Actual Behaviour**

The images are added again if selected from the image selector in the upload section.

**Expected Behaviour**

The uploaded image should not be readded. A unique hash should exist for each image.

**Steps to reproduce it**

1. Go to upload tab and upload image from the image selector.
2. After uploading, click on upload image button again.
3. The image selector opens, and same images can be added again.

**Screenshots of the issue**

Images 2 and 4 are same.

![screenshot_2017-03-20-02-32-38-040_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24084898/97e048ae-0d18-11e7-8138-318c8ac38e16.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
Yep work on it
