### ISSUE TITLE
Confirmation in Deleting Uploaded Pics From Fragment

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#203]
**Actual Behaviour**

When the user selects to delete photos from uploaded section, the photos just get deleted without any dialogue box for confirmation.

**Expected Behaviour**

There should be a confirmation Alert dialogue box in case the user accidentally presses the delete icon

**Would you like to work on the issue?**

Already Working on it. @Abhi2424shek  Should i send the PR ?

**Comment by Abhi2424shek** [comment]
Ok.

**Comment by pa1pal** [comment]
#205
