### ISSUE TITLE
Removing unused and unnecessary imports and code from files.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#2032]
**Actual Behaviour**

Currently, there are a lot of unnecessary code and imports are present in many of the files.

**Expected Behaviour**

There should not be any unnecessary and unused code and imports in the files.

**Would you like to work on the issue?**

Yes

**Comment by Akramhussain4** [comment]
Can I work on this issue?

**Comment by abishekvashok** [comment]
@Akramhussain4 sure, go on.

**Comment by codedsun** [comment]
@Akramhussain4 Are you working on it?

**Comment by codedsun** [comment]
@abishekvashok @sauravvishal8797 Shall I send the PR?

**Comment by abishekvashok** [comment]
Yes
