### ISSUE TITLE
Android 8 share an photo crashes the app

### ISSUE THREAD

**Issue by husnanlateef** [fossasia/phimpme-android#2077]
**Actual Behaviour**

Android 8.1, Whenever the share button is tapped and then you press others, it crashes the app.

**Expected Behaviour**

I suppose it should query pm and show a list of apps that can open said file type.

**Would you like to work on the issue?**

Yeah.

**Comment by sauravvishal8797** [comment]
@husnanlateef Can u please share the crash logs.

**Comment by husnanlateef** [comment]
How do I do that
