### ISSUE TITLE
Images are saved even if user does not click save button

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#210]
**Actual Behaviour**

After clicking image on pressing back button images are getting saved even if user does not click save button.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

yes

**Comment by pa1pal** [comment]
@amitiwary999 The discard button is to discard the edits. So Image will get saved as you click. 
#90 #155 issues already closed for this. 
Please do explore all the issues before opening a new one.  Also fill all the details in issue template.
