### ISSUE TITLE
Implement instagram and twitter sharing function just like facebook

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#211]
**Actual Behaviour**

Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
Closing as the issue doesnot state anything in the body. @amitiwary999
