### ISSUE TITLE
Yaydoc Documentation issue.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#2117]
**Actual Behaviour**

Yaydoc documentation.

**Expected Behaviour**

1. Setup Yaydoc -> https://github.com/fossasia/yaydoc
2. Run it on Heroku
3. Deploy Gh-pages branch with Yaydoc
4. Might fix something on yaydoc Github

**Would you like to work on the issue?**

Yes.

**Comment by abishekvashok** [comment]
Updates?
