### ISSUE TITLE
Fdroid merge request update.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#2119]
**Actual Behaviour**

There are some issues in the merge request for Fdroid inclusion.

**Expected Behaviour**

Fix the issues and post updates here.

**Comment by sauravvishal8797** [comment]
One issue resolved, PR #2121

**Comment by sauravvishal8797** [comment]
Working on fixing the maven repo issue https://gitlab.com/fdroid/rfp/issues/655]

**Comment by TripodKnight** [comment]
I've been keeping an eye on this as someone who wants to see this on F-Droid. Unfortunately I'm not much of a programmer, but you mentioned this is a color-picker issue? Simple Calendar ( https://f-droid.org/en/packages/com.simplemobiletools.calendar/ ) has a color picker for events. Would using that fix the issue?

**Comment by yashk2000** [comment]
Closed as discussions for fdroid release are being carried out on #1181
