### ISSUE TITLE
Camera tab should be open by default

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#212]
**Actual Behaviour**

The gallery tab is the one that opens on app initialisation.

**Expected Behaviour**

Since its a camera app, the camera should open by default initially.

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by heysadboy** [comment]
I think the goal of the app is to share images, you can tell it as the major features are for only that. Camera is a part of the app so user can take pictures to upload without other camera application. What are your views?

**Comment by dynamitechetan** [comment]
I agree with varun. I see this app as a photos aggregator not a camera app.

**Comment by rohanagarwal94** [comment]
The FOSSASIA idea lists suggest otherwise. The aim is to replace other photo apps. And to be that, the core feature set of the app should focus on camera rather than as an photo aggregator. @pa1pal @mariobehling views?
![screenshot from 2017-03-21 00-38-30](https://cloud.githubusercontent.com/assets/13241256/24117067/c2352adc-0dce-11e7-8c98-b1d42c6f069b.png)

**Comment by rohanagarwal94** [comment]
@pa1pal @Abhi2424shek views on this?

**Comment by pa1pal** [comment]
@rohanagarwal94 I agree.
But app's primary feature is sharing photos. The camera is equally important. But we cannot open camera by default. Considering from the use case perspective as well. The user will be more engaged with sharing and editing image. Initiating camera by default, will increase one click.

**Comment by rohanagarwal94** [comment]
@pa1pal accepted. Hence closing this.
