### ISSUE TITLE
Update apk branch readme

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#214]
**Actual Behaviour**

The apk branch readme is out of sync with development branch readme

**Expected Behaviour**

The readme should be updated to the development branch readme.

**Screenshots of the issue**

![screenshot from 2017-03-21 02-06-21](https://cloud.githubusercontent.com/assets/13241256/24120590/2648ce82-0ddb-11e7-989b-d7cdcaabfc5d.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
@rohitagarwal pls do so not by statically updating it. But by updating the update_apk.sh script.

**Comment by Abhi2424shek** [comment]
So that it gets changed for each change in the readme :)
