### ISSUE TITLE
Security feature enhancement.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#2157]
**Actual Behaviour**

At the moment there is no forget password feature, so if a user forget's the password he'd need to reset all the settings to access the secure functionality again.

**Expected Behaviour**

There should be a forget password feature that would allow the user to reset the password without having to reset all the settings.

**Would you like to work on the issue?**

Yes.

**Comment by sparrow007** [comment]
@sauravvishal8797 we can ask restore password question like his DOB then we will create the password and whenever he put the wrong password we will show him a question which is his DOB then he should be able to create new password. tell me what do you think?
