### ISSUE TITLE
App Crashes when Local Images are Loaded

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#216]
**Actual Behaviour**

App is crashing when we choose not to show local pictures in settings, but press load more button in gallery fragment.

**Expected Behaviour**

We should Handle the exception by displaying  a Toast.

**Screenshots of the issue**

![screenshot_2017-03-21-03-40-19-725_vn mbm phimp me](https://cloud.githubusercontent.com/assets/22375731/24124317/2567d31a-0de9-11e7-9774-075b94564612.png)
![screenshot_2017-03-21-03-44-15-460_com miui bugreport](https://cloud.githubusercontent.com/assets/22375731/24124318/256aea5a-0de9-11e7-8705-163f7b43f539.png)

**Would you like to work on the issue?**

Yes, Already Working on it. @Abhi2424shek @pa1pal  Please Review.

**Comment by amitiwary999** [comment]
@madhavrathi someone is already working on removing that button and automatic loading of images with scroll. That's why I didn't open this issue.

**Comment by madhavrathi** [comment]
@amitiwary999  No that's completely fine, but till the time someone replaces it, i guess it should work correctly. @Abhi2424shek what do you think ? Should i send PR ?

**Comment by amitiwary999** [comment]
@madhavrathi I don't remember that issue number but if you find that issue and work on it then it will be better.

**Comment by madhavrathi** [comment]
@amitiwary999 Ok i will look into it. Thanks For the Head's Up
