### ISSUE TITLE
Not able to rename folders with pictures

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2167]
**Actual Behaviour**

Not able to rename folders on the SD card even though I have granted it permission, and hit okay. 

**Device**
Moto Z Force Android

**Comment by iamadeveloper12345678** [comment]
But it works well on playstore version

**Comment by codepoet2017390** [comment]
I have been working on this issue and i have found out that the same bug exists in the playstore version as well. Also the app is unable to move albums that are on the SD card to selected location.

**Comment by sparrow007** [comment]
is someone working on this issue?

**Comment by codepoet2017390** [comment]
Yes i am

**Comment by abishekvashok** [comment]
> Also the app is unable to move albums that are on the SD card to selected location.

Please open a separate issue for it

**Comment by codedsun** [comment]
@iamareebjamal PR Merged also solves this. Please close this
