### ISSUE TITLE
App crashed when changing the orientation

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2173]
**Actual Behaviour**

App is crashing when we edit the image in landscape mode and when we come to portrait mode the app is crashed.

**Expected Behaviour**

App should not crashed while changing in landscape mode and then change it to the portrait mode.

**Steps to reproduce it**

Step 1.
Select any image and click on the edit button.

Step 2.
Move your phone into landscape mode and make changes in the image.

Step 3
Again move your phone in portrait mode without doing anything.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**
  yes

**Comment by hrprt96** [comment]
yes

**Comment by codepoet2017390** [comment]
Actually there is more specification into the issue. The app will only crash if you haven't saved your edit by pressing the tick-mark icon provided at the bottom. In such case if you rotate your phone the app crashes but if you keep saving your edits it does not crash.
