### ISSUE TITLE
App crashes on editing image after compressing it.

### ISSUE THREAD

**Issue by vinmaxx99** [fossasia/phimpme-android#2174]
**Actual Behaviour**

App crashes on trying to edit image after compressing it by dimension.

**Expected Behaviour**

App must not crash and user should be able to edit image after compressing it.
  
**Steps to reproduce it**

1. Open the app and select any image.
2. Compress the image by dimension.
3. After the image is compressed click on the edit button ,the app crashes.(BUG)

**Would you like to work on the issue?**

Yes.

**Comment by sparrow007** [comment]
@vinmaxx99  are you still working on this issue??

**Comment by vinmaxx99** [comment]
Yes I am working on it.

**Comment by abishekvashok** [comment]
It's working now
