### ISSUE TITLE
Edits not being saved when switching from portrait to landscape mode while editing an image

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2175]
**Actual Behaviour**

Currently the edits made and saved to an image are not being retained while switching from portrait to landscape mode 

**Expected Behaviour**
Edits made should be retained when the orientation is changed so that the user can edit the image further. 

**Steps to reproduce it**
  Step 1.
Select any image and click on the edit button.

Step 2.
 make changes in the image and keep saving each of them by clicking the tick-mark icon provided. 

Step 3.
change the orientation of you phone.

Step 4.
 The changes made are reset(BUG).

**Would you like to work on the issue?**
 YES

**Comment by Divyanshu2132** [comment]
YES

**Comment by codepoet2017390** [comment]
> YES

 Could you please clarify the context of your comment @Divyanshu2132

**Comment by yashk2000** [comment]
This issue has been fixed by pr https://github.com/fossasia/phimpme-android/pull/2790
