### ISSUE TITLE
issue with fab button in PhimpMeGallery

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#218]
**Actual Behaviour**

If fab button is open on clicking outside of fab button it is not get closed 

**Expected Behaviour**
If fab button is open then on clicking outside it should close.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by pa1pal** [comment]
While opening issue, if you don't have information for all the points, at least delete the sample line written.
