### ISSUE TITLE
Onboarding does not show up at the first launch

### ISSUE THREAD

**Issue by riyadhctg** [fossasia/phimpme-android#2184]
**Actual Behaviour**
Onboarding does not show up at the first launch. It shows up in the following launch.

**Expected Behaviour**
Onboarding should show up at the first launch 

**Steps to reproduce it**
Install the app and launch the app

**Would you like to work on the issue?**
Yes

**Comment by sparrow007** [comment]
There is no onboarding right now in the app, see this issue #2057

**Comment by riyadhctg** [comment]
I am referring to this --> https://imgur.com/a/H3UfHgt
Not sure if this has a different name than onboarding...  it's probably called onboarding tooltips... Regardless of the name, I believe this feature was intended to be shown at the first launch...

**Comment by sparrow007** [comment]
yes but usually onboarding is different section where it gives the information about the app in the slides and currently this is called tutorial of different parts in the app and definitely there should not exist both at the same app.

**Comment by riyadhctg** [comment]
I see... Didn't know this had a different name... thanks for sharing.... However, I guess the idea is that this tutorial should be shown at the first launch?
