### ISSUE TITLE
improve UX in readme file by adding a mobile frame to screenshots

### ISSUE THREAD

**Issue by prudhvir3ddy** [fossasia/phimpme-android#2187]
**this is the kind of screenshots we are using currently**

![ss_1](https://user-images.githubusercontent.com/20471162/46301172-39928b80-c5c3-11e8-905f-080324ece8f8.png)

**readme will look a lot better if we use this kind of screenshots**

![ss_1](https://user-images.githubusercontent.com/20471162/46301322-a0b04000-c5c3-11e8-931a-c6545bcfb485.png)

**Would you like to work on the issue?**
yes

please assign this issue to me

**Comment by abishekvashok** [comment]
Go on, maybe try on with a less bezel design. (No notch either)
