### ISSUE TITLE
App crashes if the orientation is changed when click on the crop of the image

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2194]
**Actual Behaviour**

App crashes if click on crop (Transform section) and then on orientation change.

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

Step 1. Click on edit button of the image and select the transform section.

Step 2. Click on crop button and changed the orientation without saving it then app will crash.

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
@prashantkh19 yes. You can either work on your own, or coordinate with @sparrow007 so that you can work together.
