### ISSUE TITLE
Bottom Navigation disappears on changing activities while album is selected 

### ISSUE THREAD

**Issue by vinmaxx99** [fossasia/phimpme-android#2200]
**Actual Behaviour**

Currently when an album is selected in albums mode and activity is switched to any other activity from the navigation drawer (ex. about activity) then on coming back to the local folders activity the bottom navigation bar disappears leaving the user no option to access camera and accounts.

**Expected Behaviour**

The bottom navigation bar must appear normally.

**Steps to reproduce it**

1. select any album in the albums mode.
2. open navigation drawer and click on any option (ex. about option)
3. press back button to go back to the local folders activity.
4. the bottom navigation bar does not appears.(BUG)

**Would you like to work on the issue?**

Yes

**Comment by sparrow007** [comment]
@vinmaxx99 good catch but when album selected isn't navigation shouldn't open??

**Comment by vinmaxx99** [comment]
Yes maybe it should get disabled on selecting albums but I think it would be better if we could have a comment from the maintainers of this project so that the correct fix is delivered with the PR.

**Comment by sparrow007** [comment]
yes you are right, we should ask maintainers for this issue.
