### ISSUE TITLE
Image window not visible when selecting frames while editing

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2206]
**Actual Behaviour**
When we select a frame while editing any image in landscape mode the image window disappears

**Expected Behaviour**
The image should remain on display to the user.

**Steps to reproduce it**
1) Select an image and open editing activity in landscape mode.
2) Select frames and then select any frames displayed.
3) The image window disappears.

**Would you like to work on the issue?**
 Yes

**Comment by sparrow007** [comment]
@codepoet2017390  would you please add the screenshot of this if possible.

**Comment by codepoet2017390** [comment]
Ya sure
![20181005_024250](https://user-images.githubusercontent.com/37406965/46503487-95ba1180-c848-11e8-999c-3dcc29e89c0a.gif)

**Comment by sparrow007** [comment]
I added the frames in vertical when orientation changes and at that time this issue is not out there , this issue is created when you push a pull request for issue #2166 so i think this happens because of this pull request https://github.com/fossasia/phimpme-android/pull/2202
