### ISSUE TITLE
App exits without showing any dialogue asking user choice.

### ISSUE THREAD

**Issue by sanjay-kd** [fossasia/phimpme-android#2211]
**Actual Behaviour**

App does not show a dialogue asking user to exit the app with Yes/No options.

**Expected Behaviour**

A dialogue should should be shown asking him to exit the app or he pressed back button by mistake.

**Would you like to work on the issue?**

Yes

**Comment by codepoet2017390** [comment]
Actually the app has a different functionality for this where the user has to press the back button twice for exiting the app. The user is also shown the exit button when he presses the back button once.

**Comment by sanjay-kd** [comment]
Ohh..i saw this now!
