### ISSUE TITLE
No message is shown when password and confirm password does not match

### ISSUE THREAD

**Issue by sanjay-kd** [fossasia/phimpme-android#2214]
**Actual Behaviour**

Password and confirm password taking dialogue exits when password and confirm pass does not match.

**Expected Behaviour**

A message should be displayed saying that password and confirm password does not match.

**Would you like to work on the issue?**

Yes.

**Comment by Balram02** [comment]
I would like to work on this issue may i...?

**Comment by sanjay-kd** [comment]
Sorry bro i m working on it!
