### ISSUE TITLE
Bottom navigation should hide in camera section

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2220]
**Actual Behaviour**

Bottom navigation is shows all the time on the screen in the camera section.

**Expected Behaviour**

Bottom navigation should not be there  all time,  it should disappear after few second it will increase the user experience.

**Screenshots of the issue**

<img src = "https://user-images.githubusercontent.com/22986571/46583268-a13c5100-ca71-11e8-9123-1bd5312548bb.jpeg" widht = "300" height = "400">

**Would you like to work on the issue?**

yes.

**Comment by abishekvashok** [comment]
Then how will user switch to gallery? Or accounts after 5s?

**Comment by sparrow007** [comment]
either by back button or by swipe above.

**Comment by abishekvashok** [comment]
We discussed this before, please keep the current way in which things are done in respect to this matter.
