### ISSUE TITLE
App crashes on applying frames to images and then changing orientation

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2230]
**Actual Behaviour**
Presently the App crashes if we apply a frame to an image and then change the orientation of the image.

**Expected Behaviour**
The app should not crash.

**Steps to reproduce it**
1) Select an image and go to the editing activity.
2) Select any frame you like and save your edit by pressing the tick-mark icon.
3) Now rotate your phone to landscape mode.
4) App crashes(BUG).

**Would you like to work on the issue?**
 YES

**Comment by codepoet2017390** [comment]
@sparrow007 does the pr https://github.com/fossasia/phimpme-android/pull/2231 solve this Issue

**Comment by mariobehling** [comment]
This seems to be resolved. Thank you.
