### ISSUE TITLE
README.md is only available in the English language

### ISSUE THREAD

**Issue by Jithin-Jude** [fossasia/phimpme-android#2233]
**Actual Behaviour**

README.md is only available in the English language

**Expected Behaviour**

README.md should available in other languages also.

**Would you like to work on the issue?**

Yes, I can add **Malayalam** version of README.md

**Comment by sauravvishal8797** [comment]
@Jithin-Jude I don't think this is required. English is just fine, as it's sort of a global language.

**Comment by abishekvashok** [comment]
Closinng it as of.
