### ISSUE TITLE
Show location feature never works

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2234]
**Actual Behaviour**
The image description shows an attribute of location but it never shows the location when clicked.

**Expected Behaviour**

All images clicked via Phimpme should show the location in Google maps when clicked.   

**Steps to reproduce it**
1) Click  an image via the Phimpme Camera. 
2) Open the image in the albums section and click on image description.
3) There is an attribute called location but it never actually shows the location.  

**Screenshots of the issue**
![ef71c3a3-69a2-423f-9693-a1ca75cbfb37](https://user-images.githubusercontent.com/37406965/47268259-496f1100-d56c-11e8-94a7-1faa0b931d8d.jpg)

**Would you like to work on the issue?**
  Yes

**Comment by abishekvashok** [comment]
Enable location, provide the permission, and try clicking it.

**Comment by sauravvishal8797** [comment]
@codepoet2017390 As @abishekvashok said we have an option in the permission settings for enabling or disabling the location, try with that option first.

**Comment by codepoet2017390** [comment]
ohh yes its working i just checked
