### ISSUE TITLE
Hardcoded strings in some of the Activities.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#2240]
**Actual Behaviour**

Some of the activities including SettingsActivity, TrashBinActivity etc. have hardcoded strings.

**Expected Behaviour**

Proper string resources should be created in the `strings.xml` file for those hardcoded strings.

**Steps to reproduce**

Navigate through the code.

**Activities containing such code:**

- [ ] SettingsActivity
- [ ] TrashBinActivity.

_Note: If you find more activities, comment here_

**Comment by ho-dor** [comment]
I am a first-time open source contributor. Please help me. I want to work on this issue.

**Comment by codepoet2017390** [comment]
Hello @ho-dor  please join this gitter channel https://gitter.im/fossasia/phimpme and ask any doubt you have regarding anything on the project.

**Comment by sauravvishal8797** [comment]
@ho-dor This task is for gci students.

**Comment by STEdirisuriya** [comment]
@sauravvishal8797 I like to work on this, but I need some more details. Could you please explain to me what you're mentioned by the hardcoded strings?
