### ISSUE TITLE
App crashes on creating GIF for images

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2248]
**Actual Behaviour**

App crashes on creating GIF's for selected images

**Expected Behaviour**

App should not crash

**Steps to reproduce it**
1) Open any album and select some images.
2) Press the menu button in the top left right corner and select Create GIF.  
3) App crashes(BUG)

**Would you like to work on the issue?**
YES

**Comment by mariobehling** [comment]
This seems to be resolved. Thanks.
