### ISSUE TITLE
Error:(7, 25) java: package org.opencv.engine does not exist

### ISSUE THREAD

**Issue by kingnightdrifter** [fossasia/phimpme-android#2250]
**Actual Behaviour**

When i am configuring project i have done all the required changing but one point i got be image
![firstimage](https://user-images.githubusercontent.com/15875083/47525019-a7299300-d8b5-11e8-8936-885a6c631fee.png)

**Expected Behaviour**

I need to configure it without any error

**Steps to reproduce it**

stated above

**LogCat for the issue**

Provide logs for the crash here

`Error:(47, 15) java: cannot find symbol
  symbol:   class OpenCVEngineInterface
  location: class org.opencv.android.AsyncServiceHelper`

**Screenshots of the issue**

![firstimage](https://user-images.githubusercontent.com/15875083/47525107-d9d38b80-d8b5-11e8-8ec4-1d908d576056.png)

![secondimage](https://user-images.githubusercontent.com/15875083/47525154-fbcd0e00-d8b5-11e8-9184-0785564d54b2.png)

**Would you like to work on the issue?**

Yes. But Please first let me know how to configure it correctly and where i am getting wrong.

**Comment by codepoet2017390** [comment]
@kingnightdrifter  this is does not seem to be an Issue with the project. I looks like there is some problem while configuring your Android Studio Ndk and plugins. Please read the readme.md and follow each and every step mentioned there . Even if after that u run into a problem you can always ask. Also join the project gittter channel to ask your doubts there if any

**Comment by kingnightdrifter** [comment]
@codepoet2017390 Thanks for the reply well I have been set almost all the environment and it is near to build now hope to final step. But when i am making build of it I got the bellow error 


"error: cannot find symbol class OpenCVLoader ;"

Also Please see bellow screen short and help me what could be the issue. 

![errorimg](https://user-images.githubusercontent.com/15875083/47586919-dce47f80-d97a-11e8-9dd0-7c5838f3d48d.png)

**Comment by codepoet2017390** [comment]
@kingnightdrifter  please re-check if you have pasted the files mentioned in readme.md in the right location

**Comment by kingnightdrifter** [comment]
@codepoet2017390  more than the readme i have been worked on it but vained. If one error gone the next comes up. No i am getting bellow error

`Error:(6, 39) java: package android.support.test.annotation does not exist`

**Comment by kingnightdrifter** [comment]
Also One erro Check below Screenshort
![error](https://user-images.githubusercontent.com/15875083/48025608-bcc87380-e165-11e8-9eb1-6af5467d2256.png)
