### ISSUE TITLE
Autogenerate APKs from dev branch and master branch on merged PRs and document it in Readme.md

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2251]
The apks for master and development branch should get generated automatically on each merged PR.

1. The APKs for master branch should only be updated (overwritten) once master branch is updated. The development branch APKs should be updated when the dev branch is updated. The master branch APKs should be updated when the master branch is merged.

2. Generate the names according to master or dev branch e.g.:
* app-dev-debug.apk
* app-dev-release.apk
* app-master-debug.apk
* app-master-release.apk

3. Document what the different names stand for in the APK branch Readme.md

**Comment by codepoet2017390** [comment]
@mariobehling  is this a GCI task?

**Comment by yashk2000** [comment]
This has been done.
