### ISSUE TITLE
Website not generated automatically - consider using Travis

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2252]
Yaydoc is currently not running and it would be good to switch to Travis instead in order to generate the website automatically from the Readme.md file. Images are currently neither always correctly displayed. Please help to get the site up and running and updated automatically.

**Comment by abishekvashok** [comment]
We moved of Travis in #2253

I am closing this is ref to your comments on gitter.

**Comment by mariobehling** [comment]
You are confusing things. We need this and the PR merged does not follow this.
