### ISSUE TITLE
Update website design (GCI Task)

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/phimpme-android#2253]
**Actual Behaviour**

The phimp.me Android project has a basic website using the Mark-down files. 

**Expected Behaviour**

New Website with Material Design (Lading Page)
QR Codes

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
The task in GCI was mentioned as follows.

 Please help to build a simple website similarly to the website of fossasia.org and implement the automatic site generation with Travis CI. 

Create the website using Jekyll and create a design for Jekyll. Please also help by opening relevant issues and solve at least one issue to solve this task. To complete this task ensure your contribution is substantial. One-line code changes or text only changes are not sufficient. Your code should result in a substantial improvement. Here is the issue to start with: https://github.com/fossasia/phimpme-android/issues/2252 

Here are a few ideas for improvements:
* Implement a design using Material UI using the same colors as the app
* Create a menu bar similarly to https://susi.ai appearing / disappearing on scroll
* Create different sections for screenshots, team etc.
* Create a footer with different columns
* Add QR codes for Fdroid and Playstore
* Ensure the sites loads fast
* Add section social media channels
* Add section for contributions

REQUIREMENTS
* Knowledge in HTML, Jekyll, CSS
* A test page on your own Github repo
* Avoid external services and plugins

**Comment by niteshkumarniranjan** [comment]
@mariobehling does it means to use .md files
