### ISSUE TITLE
Access by password should remember the password if it has been setup early

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2255]
**Actual Behaviour**

The Security feature requires a password to be set up and it asks to set it up again and again.

**Expected Behaviour**

The app should remember the password and not ask for it again and again

**Steps to reproduce it**
1) Go to app settings and then go to security. 
2) Set up a password and then uncheck the Access by password.
3) Se it up again. It asks again for password.

**Would you like to work on the issue?**

YES

**Comment by ho-dor** [comment]
can I work on this @codepoet2017390 ?

**Comment by codepoet2017390** [comment]
Sorry im almost done with the solution
