### ISSUE TITLE
Twitter integration in Accounts Section does not work

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2258]
**Actual Behaviour**
Like other options provided which work, the Twitter integration does not work in Accounts section.

**Expected Behaviour**
The twitter integration should work and the required activity should open up.

**Steps to reproduce it**
1) Go to accounts section and click the button next to Twitter.
2) An endless progress bar appears which lasts for about 2 seconds and then it dissapears
3) Nothing else happens.

**Would you like to work on the issue?**
YES

**Comment by kk63852** [comment]
are you still working on this??

**Comment by imrrahul** [comment]
@codepoet2017390 are you working on this issue?

**Comment by codedsun** [comment]
@iamareebjamal Please close this!
