### ISSUE TITLE
Camera View not responding to Jelly Bean!

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#226]
**Actual Behaviour**

When using Jelly Bean 4.2.2 API17, The camera doesn't open and the application freezes. After about half a minute, a system popup is displayed saying _Phimpme isn't responding_

**Expected Behaviour**

The application should be compatible with Jelly Bean

**Steps to reproduce it**

1. Open app in a Jelly Bean device
2. Click on _Camera_ icon in the bottom navigation bar

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![device-2017-03-22-205459](https://cloud.githubusercontent.com/assets/14261304/24205615/db8a8a12-0f41-11e7-92dc-d5c5b325164e.png)

**Would you like to work on the issue?**

Okay!

**Comment by Abhi2424shek** [comment]
Yes pls work on it.

**Comment by CloudyPadmal** [comment]
It was some internal issue in the device. It works in Jelly! Hence closing the issue :)
