### ISSUE TITLE
app not responding !

### ISSUE THREAD

**Issue by adnan29sk** [fossasia/phimpme-android#2265]
i just downloaded the app and opened it and it was stuck in this screen and was responding to any of my taps
![screenshot_20181103-171739](https://user-images.githubusercontent.com/44690562/47961779-65c48080-e037-11e8-8882-4cf7967c5a55.png)

**Comment by mayank8318** [comment]
@adnan29sk Please try to stick to the issue template next time onwards :)

**Comment by adnan29sk** [comment]
Thank you so much sir next I will take care

**Comment by mayank8318** [comment]
@adnan29sk No need to call me sir, we are all learners here! :) You can add photos to the issue by dragging and dropping photos in the issue box or selecting "add image" image link at the bottom of the box. Please edit your issue and add the screenshot.
