### ISSUE TITLE
The App crashes often and not able to edit some Images

### ISSUE THREAD

**Issue by Hackerbone** [fossasia/phimpme-android#2266]
**Actual Behaviour**
1)The App crashes often.
_Refer Below.._

![image 2018-11-05 11 23 44](https://user-images.githubusercontent.com/20267705/47980560-3fade780-e0ee-11e8-8899-ee121c7b79af.jpg)
_

2)Whenever the edit button is clicked, the image disappears, a black screen appears and no image is shown.
_Refer Below.._
![image 2018-11-05 11 25 06](https://user-images.githubusercontent.com/20267705/47980460-c0b8af00-e0ed-11e8-8dc0-af5120657a6d.jpg)

**Expected Behaviour**
Whenever the edit button is clicked, the image should be able to get edited.

**Steps to reproduce it**

1. Click on any folder with images in them.
2. Click an image and click on edit button.
Then a black screen like this would appear....
![image 2018-11-05 11 32 12](https://user-images.githubusercontent.com/20267705/47980721-f4e09f80-e0ee-11e8-826d-3e88eacd2ea3.jpg)

**Screenshots of the issue**

![image 2018-11-05 11 25 06](https://user-images.githubusercontent.com/20267705/47980608-7dab0b80-e0ee-11e8-9dd0-5e23b7ee5068.jpg)
![image 2018-11-05 11 23 44](https://user-images.githubusercontent.com/20267705/47980611-800d6580-e0ee-11e8-8e92-2864ea4f5d48.jpg)

![image 2018-11-05 11 32 12](https://user-images.githubusercontent.com/20267705/47980606-7683fd80-e0ee-11e8-8eda-574a718223b8.jpg)

**Comment by codepoet2017390** [comment]
@Hackerbone  what device and what android version are you using and please make sure you successfully set up the project on your local machine without making any change to any gradle files and then try again.
