### ISSUE TITLE
Not able to build project 

### ISSUE THREAD

**Issue by tronku** [fossasia/phimpme-android#2267]
Getting error in NDK -
**No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android**

I have even removed and reinstalled NDK again but it's not working. Got a way to solve it on SO but that will require to update Gradle version and build tools.

**Comment by codepoet2017390** [comment]
Can u please share logs here

**Comment by codepoet2017390** [comment]
@tronku  Also please follow the issue template from now onwards

**Comment by tronku** [comment]
Here's the log 
Gradle sync failed: No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android. Consult IDE log for more details 

I found that previous NDK versions have such files, newer versions don't have them. I haven't changed anything in gradle files.

**Comment by codepoet2017390** [comment]
@tronku  please revert to NDK 16 as NDK 17 gives issues with the project.

**Comment by tronku** [comment]
its working now!
