### ISSUE TITLE
App crash on using Tap to focus in front camera

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#227]
**Actual Behaviour**

The App crashes while tapping the screen when using the front camera

**Expected Behaviour**

The App should not crash

**Steps to reproduce it**

Open App, go to camera, tap to focus- It works fine
Now switch camera - tap to focus - App crashes

**Problem**

Only some front cameras support manual focus functionality so it may not crash for users having front camera with manual focus support.

**Would you like to work on the issue?**

Solved it already. Will send the PR soon.

**Comment by Abhi2424shek** [comment]
@anantprsd5 fine.
