### ISSUE TITLE
Caption not copied when sharing via Messenger and Instagram

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2274]
**Actual Behaviour**
Captions  are not copied when sharing image via Messenger and Instagram.

**Expected Behaviour**
Captions should be copied.

**Steps to reproduce it**
1) Go to sharing activity write a caption and share via messenger or instagram.
2) Captions are not copied.

**Would you like to work on the issue?**
YES

**Comment by AshutoshDas07** [comment]
Can i work on it?

**Comment by codedsun** [comment]
@yashk2000  @iamareebjamal  This is not possible as they have stop accepting the text from intent. please close this issue
