### ISSUE TITLE
Improve the website

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/phimpme-android#2277]
@mariobehling I would like to ask, can I work on this? before I'm completing it.

## Actual Behaviour

https://github.com/fossasia/phimpme-android/issues/2253
Here are some ideas for improvements given by @mariobehling, I am going to work on some points.
- [ ] Implement a design using Material UI using the same colours as the app
- [ ] Add QR codes for Fdroid and Playstore
- [ ] Add section social media channels
- [ ] Create a footer with different columns

**Expected Behaviour**

Improved website.

**Would you like to work on the issue?**

Yes.

**Comment by abishekvashok** [comment]
Closing as the website should be autogenerated
