### ISSUE TITLE
Redundant editing pages.

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#228]
**Actual Behaviour**

After choosing the edit option in the photo from the gallery it transfers to edit image page. This page does not have the same UI and does not contain the same filters as the edit page it directs after taking the photo from the camera. This conflict the uniformity of the app. 

**Expected Behaviour**

In my perspective after choosing the edit option from the image taken from the gallery, it should direct to the same edit image page that we go after clicking a picture from the camera button. 

**Steps to reproduce it**
The app should directly go to the edit page that it goes through taking a photo from the camera.  

**Screenshots of the issue**
Currently we can edit an image from the page below:
![screenshot_2017-03-22-21-55-33-343](https://cloud.githubusercontent.com/assets/17337006/24209478/6d1f1182-0f4c-11e7-8b92-63b8a2700f10.jpeg)
Instead, the app can directly go to this page:  
![screenshot_2017-03-22-22-24-54-761](https://cloud.githubusercontent.com/assets/17337006/24210254/89699a5e-0f4e-11e7-93af-d6a94827e927.jpeg)

**Would you like to work on the issue?**
Yes, I would like to work on the issue.

**Comment by Abhi2424shek** [comment]
Your apk seems old. The second one (pls fetch the updated version) is my choice.

**Comment by Subhankar29** [comment]
Yeah, but I think the editing page should be same. Right now we two different editing pages. One for the photo from the gallery and the other from the camera. This is Redundant.

**Comment by Abhi2424shek** [comment]
Yes you can work on it. @Subhankar29 first update your fork, then please work, the second one is better (not the issue in the pic but the current one).

**Comment by Subhankar29** [comment]
working on it

**Comment by Subhankar29** [comment]
Sorry, I couldn't work on it because of my exams. Started working on it. Will send PR ASAP.

**Comment by Abhi2424shek** [comment]
@Subhankar29 sure.
