### ISSUE TITLE
App should not require SMS permissions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2281]
If your app does not require access to Call Log or SMS permissions: Make appropriate changes to your app by removing the specified permissions from your app's manifest or migrating to an available alternative implementation by January 9, 2019. 

![screenshot from 2018-12-18 13-55-42](https://user-images.githubusercontent.com/1583873/50155609-d1536c00-02cc-11e9-858a-9e58dcf88dd4.png)

> Please read through the Permissions policy and the Play Console Help Center article, which describes intended uses, exceptions, invalid uses, and alternative options for use of Call Log or SMS permissions, to determine which of the following options apply to your affected app(s):

> Option 1) Your app does not require access to Call Log or SMS permissions: Remove the specified permissions from your app's manifest, or migrate to an alternative implementation by January 9, 2019. If you require additional time to remove permissions or migrate to an alternative option, submit a Permissions Declaration Form to request an extension until March 9, 2019. 

> Option 2) Your app is a default handler, or you believe your app qualifies for an exception: If you haven't already done so, submit a request using the Permissions Declaration Form by January 9, 2019. We are currently reviewing submissions and will respond to your request. Note: You do not need to make changes to your app in order to be eligible to submit a request.
Make sure that your app is otherwise compliant with all other Developer Program Policies to prevent your app from being removed.

> We appreciate your continued support to make Google Play a positive experience for both developers and our users.

> Affected apps
Affected apps and permissions are listed below, up to 20; if you have additional apps, please ensure that they are also compliant with the Permissions policy.

> org.fossasia.phimpme
   READ_SMS, RECEIVE_SMS

**Comment by ankush-01** [comment]
i want to work on this issue

**Comment by abishekvashok** [comment]
Working on it as it's high priority.

**Comment by abishekvashok** [comment]
Ugh, app doesn't request the permission

**Comment by kk63852** [comment]
is the issue fixed?

**Comment by kk63852** [comment]
my app does not ask for sms permissions. i checked it thoroughly.

**Comment by mariobehling** [comment]
According to this email from Google the app still requires these permissions: https://groups.google.com/forum/#!topic/phimpme/sIBjAq9rKj8

**Comment by yashk2000** [comment]
@mariobehling should these lines be removed from the AndroidManifest.xml :

`<uses-permission android:name="android.permission.READ_SMS"
        tools:node="remove"/>
    <uses-permission android:name="android.permission.RECEIVE_SMS"
        tools:node="remove"/>`

**Comment by yashk2000** [comment]
@mariobehling  since call/SMS permissions are not required by the app, can we write all the SMS/call related permissions in the manifest and use tools:node="remove" on them?

**Comment by mariobehling** [comment]
Please remove any SMS/phone permission in any place in the app, yes.
