### ISSUE TITLE
Edit button not working

### ISSUE THREAD

**Issue by epicvarun23** [fossasia/phimpme-android#2282]
While testing the features of this app, I came across an issue while trying to edit the picture. Instead of allowing me to enter the edit feature, the app would just crash and restart to the gallery. This proved to be a problem as instead of allowing me to edit the picture, it would take me back to the screen where the gallery of all your pictures was. I think this is a problem which can be easily fixed through debugging and fixing some line of code that instead of directing the user back to the edit feature, it sends them back to the home screen. Even though this may be a quick fix, On the other hand good job on the app, it successfully takes pictures and also serves as a nice way to organize your social media apps. However, if the edit function were to be fixed, this app would most likely receive a ten out of ten from me.

**Comment by sparrow007** [comment]
@epicvarun23 would please tell me which APK you have installed means is it from the play store or you build this project in your android studio and then you install the APK ?.

**Comment by abishekvashok** [comment]
Working for me
