### ISSUE TITLE
Remove From Favourites

### ISSUE THREAD

**Issue by smaliaquib** [fossasia/phimpme-android#2283]
**Actual Behaviour**

Unnecessary Dialog box When We remove pics from Favourite 

**Expected Behaviour**
To make it more Optimized by simply clicking in heart icon to remove and add Snackbar kind of message "It got removed" 

**Screenshots of the issue**

![img_20181120_103410](https://user-images.githubusercontent.com/12525340/48752724-c0551200-ecb0-11e8-8c9c-0971cb6804cb.jpg)

**Would you like to work on the issue?**
YES

**Comment by abishekvashok** [comment]
It's necessary, please don't remove it
