### ISSUE TITLE
Enhance design and modify all the Icons/Images using Material Design

### ISSUE THREAD

**Issue by isiratc** [fossasia/phimpme-android#23]
Hello,
I'm a student who participate google code in contest.
I would like to improve the user interface using material design.
Thank you.

**Comment by pa1pal** [comment]
Hi @isiratc. Welcome.
Fork the repo and run in your system. Come up with few ideas for design improvements.

**Comment by mariobehling** [comment]
Please open specific issues for defined areas. Closing it therefore.
