### ISSUE TITLE
Improve Readme.md and implement developers in table view with 0 borders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2301]
Please implement the developers section as follows:
* 4 columns
* no borders
* icons should be stored in /docs/images/

![screenshot from 2018-12-09 04-50-54](https://user-images.githubusercontent.com/1583873/49693268-448f0c80-fb6e-11e8-818f-b0aac27424af.png)

**Comment by kk63852** [comment]
i would like to work on this issue.

**Comment by kk63852** [comment]
please review my pr#2327
