### ISSUE TITLE
Add swipe functionality to switch between different tabs (camera , gallery , accounts)

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/phimpme-android#2304]
#### This is related to a feature .
There should be functionality that allows user to swipe between different tabs (Camera,Gallery,Accounts) for easy navigation .

**Screenshots of the issue**
![2018_12_09_13_43_30](https://user-images.githubusercontent.com/26023139/49694976-a45ed500-fbb9-11e8-8c10-12b619d8ce10.gif)

**Would you like to work on the issue?**
No , just a review

**Comment by abishekvashok** [comment]
It's against material deaing guidelines
