### ISSUE TITLE
The developers' section looks very bad

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/phimpme-android#2305]
**Actual Behaviour**

Poor looking developers' section

**Expected Behaviour**

Good, weel-styled section

**Steps to reproduce it**

Remove old one
Create and add a new one

**Screenshots of the issue**

<img width="977" alt="screenshot 2018-12-10 at 12 19 58 pm" src="https://user-images.githubusercontent.com/24372680/49715316-efd6b900-fc75-11e8-9de9-d1a48497704b.png">

**Would you like to work on the issue?**

Yeah

**Comment by saarthakchats** [comment]
<img width="829" alt="screenshot 2018-12-10 at 12 31 44 pm" src="https://user-images.githubusercontent.com/24372680/49715826-a12a1e80-fc77-11e8-933a-54841780a530.png">
Why can't I push to the gh-pages branch?

**Comment by abishekvashok** [comment]
Looks cool to me
