### ISSUE TITLE
error when editing a photo/image

### ISSUE THREAD

**Issue by justdoit-andyliang** [fossasia/phimpme-android#2312]
**Actual Behaviour**

when editing a photo using a pencil, the screen will turn to a white page with ‘1of 0’ in its left top corner.

**Expected Behaviour**

the photo should be display correctly.

**Steps to reproduce it**

Get into the Gallery then tap a photo, then press the pencil button to edit it, here comes the mistake: when tapping the button in the right top corner, the button that has the shape of a rectangle with an arrow in it pointing to the right, sometimes the screen will turn to a white page with ‘1of 0’ in its left top corner instead of leaving the editing.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/45822216/49873903-fd4b9900-fe57-11e8-9e5c-fbb47f5d9ac5.png)

**Would you like to work on the issue?**

no. I think I cannot work it out.

**Comment by yashk2000** [comment]
This is not a valid issue. The button used to be irresponsive due to some permission errors, but that has been fixed now by https://github.com/fossasia/phimpme-android/pull/2782
