### ISSUE TITLE
Add camera raw support

### ISSUE THREAD

**Issue by isaacullah** [fossasia/phimpme-android#2315]
This is just a feature request to add support for RAW file development. 

Potential library to look at would be libraw: https://www.libraw.org/ 

Consider also joining in our FOSS imaging community at pixls.us: https://pixls.us/ Lot's of very enthusiastic users and developers over there!!

Thanks for the devel work on this fun tool so far!

**Comment by Robert321245** [comment]
Also lensfun lib
You guys could look at the code of RawTherapee and Darktable
Two very nice raw photo editors

**Comment by mariobehling** [comment]
Out of scope at the moment.
