### ISSUE TITLE
App crashes on changing orientation while cropping

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2318]
**Actual Behaviour**

while cropping a image, on changing the screen orientation and clicking on tick mark the app crashes.

**Expected Behaviour**

image should cropped irrespective of screen orientation change.

**Steps to reproduce it**

Select an image and go to the editing activity.
Select transform.
Navigate to crop.
Now rotate your phone to landscape mode.
Tap on the tick button.
App crashes(BUG).

**LogCat for the issue**

![screenshot 1](https://user-images.githubusercontent.com/31561661/50177670-95e68b00-0328-11e9-99e9-6550d2042a16.png)

**Screenshots of the issue**

![whatsapp image 2018-12-19 at 00 43 09](https://user-images.githubusercontent.com/31561661/50177903-2cb34780-0329-11e9-9d8a-680226e55695.jpeg)
![whatsapp image 2018-12-19 at 00 43 31](https://user-images.githubusercontent.com/31561661/50177914-32a92880-0329-11e9-91ad-3dc887c357f2.jpeg)
![whatsapp image 2018-12-19 at 00 43 52](https://user-images.githubusercontent.com/31561661/50177923-376ddc80-0329-11e9-8e88-90951a7ad1bd.jpeg)
![whatsapp image 2018-12-19 at 00 43 59](https://user-images.githubusercontent.com/31561661/50177933-3dfc5400-0329-11e9-8ae3-960e4f8bc2e7.jpeg)

**Would you like to work on the issue?**

Yes.

**Comment by abishekvashok** [comment]
We've already got an issue for that, can you please comment there?

**Comment by kk63852** [comment]
the issues #2173 and #2192 are similar to this but not the same.

**Comment by codedsun** [comment]
Taking this up
