### ISSUE TITLE
App crashing in Some Devices like tablet on click of an image in gallery fragment.

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#232]
**Actual Behaviour**
 
The app is crashing in newGallery fragment while clicking on any image.
We should use srcCompact instead of src in AppCompatActivity in PhimpMeGallery.

**Expected Behaviour**
The image should open.

![screenshot_2017-03-23-16-24-43](https://cloud.githubusercontent.com/assets/9361754/24244514/45f9b4ba-0fe5-11e7-94b9-64eb2033b057.png)

**Steps to reproduce it**

Open app and click on any image in tablets.

**Would you like to work on the issue?**

Yes, I solved the error. App is working fine in all devices. Want to send PR.

**Comment by mohitmanuja** [comment]
@Abhi2424shek Should I proceed with PR.

**Comment by Abhi2424shek** [comment]
Yes pls
