### ISSUE TITLE
Color of the radio button does not change as per accent color.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2324]
**Actual Behaviour**

the color of the radio button does not as per the accent color change. it stays the same.

**Expected Behaviour**

the button color should be same as the accent color. 

**Steps to reproduce it**

1. go to settings and change the accent color.
2. open any album.
3. navigate to sort image button.
4. the radio button color stays the same(blue).

**Screenshots of the issue**

![whatsapp image 2018-12-22 at 22 22 17](https://user-images.githubusercontent.com/31561661/50376794-8624ba80-0638-11e9-871e-7ec1163a7c88.jpeg)

**Would you like to work on the issue?**

yes.

**Comment by angmas1** [comment]
I would like to work on this issue.

**Comment by kk63852** [comment]
go ahead...

**Comment by sparrow007** [comment]
@kk63852 i want to work on this issue.

**Comment by kk63852** [comment]
Go ahead..

**Comment by sparrow007** [comment]
@kk63852 it depends on the style theme so if we want to do this we have to define different style in styles.xml which is not useful and we can't change the color of particular style dynamically (using java code).

**Comment by yashk2000** [comment]
Closing this issue as it cannot be fixed. We will need to make different styles, and even then we won't be able to change the style every time the app theme is changed.
