### ISSUE TITLE
permanent delete option issue trash bin

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2329]
**Actual Behaviour**

permanently deleting a image from trash bin via the delete permanent in the item menu does not require password even when the security is on

**Expected Behaviour**

it should ask for password first if the security feature is on.

**Steps to reproduce it**

1. turn on security from settings.
2. navigate trash bin section.
3. select the delete permanent option from the menu in the item view(it does not ask for password).

**Would you like to work on the issue?**

yes.

**Comment by yashk2000** [comment]
@kk63852 are you still working on this issue?

**Comment by kk63852** [comment]
no.

**Comment by yashk2000** [comment]
@kk63852 can I please work on it?

**Comment by kk63852** [comment]
Go ahead..

**Comment by yashk2000** [comment]
@kk63852 ok. I'm working on this issue.

**Comment by sparrow007** [comment]
@kk63852 can i work on this issue?

**Comment by kk63852** [comment]
Sure. @sparrow007
