### ISSUE TITLE
change password edit field issue

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2338]
**Actual Behaviour**

the edit field hint displays "Password".

**Expected Behaviour**

it should display "New Password"

**Steps to reproduce it**

go to security in settings. navigate to change password. the edit field hints are displayed("Password","Confirm Password").

**Screenshots of the issue**

![whatsapp image 2018-12-26 at 14 17 42](https://user-images.githubusercontent.com/31561661/50439743-1d2f9200-0919-11e9-84a9-fbd0a3a2e6f3.jpeg)

**Would you like to work on the issue?**

Yes.

**Comment by kkshitij-agrawal** [comment]
So if I have a solution to this issue, I'm supposed to comment here?

**Comment by yashk2000** [comment]
@kkshitij-agrawal you can solve issues that have been inactive for a long time if they do not have existing prs. Or you can create a new issue and work on it if you find anything wrong with the app. If an issue is new, ask the creator whether they are still working on it or not first, before solving it.
