### ISSUE TITLE
Remove un-used tags from manifest

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#234]
**Actual Behaviour**

All unused tags should be removed. Like .GalleryMap , .UploadMap  and all activity tag which are now changed in fragments.

**Steps to reproduce it**

Find in Manifest file.

**Screenshots of the issue**

![screenshot from 2017-03-23 17 38 20](https://cloud.githubusercontent.com/assets/9361754/24246941/8b1812d0-0fef-11e7-9fa9-6a8bfe93dc81.png)

**Would you like to work on the issue?**

Yes.

**Comment by Abhi2424shek** [comment]
Yep
