### ISSUE TITLE
accent color line color picker issue 

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2346]
**Actual Behaviour**

the accent line color picker is not reflecting every change made in the primary color even when its value is set to primary color.

**Expected Behaviour**

the line color picker should show the current value which is set to accent color.

**Steps to reproduce it**

go to settings and change the primary color and also its shade. a dialog appears asking for accent color to be same as the primary color. tap ok. navigate to accent color and it can be seen that the value set is not reflected in the line picker. 

**Screenshots of the issue**

![whatsapp image 2018-12-29 at 14 06 41](https://user-images.githubusercontent.com/31561661/50536041-400ab200-0b76-11e9-8e63-ac3c48fb88bf.jpeg)
![whatsapp image 2018-12-29 at 14 07 12](https://user-images.githubusercontent.com/31561661/50536042-4305a280-0b76-11e9-98f4-aa0115674dcf.jpeg)
![whatsapp image 2018-12-29 at 14 10 29](https://user-images.githubusercontent.com/31561661/50536043-4567fc80-0b76-11e9-87cf-8c8dff9f94d3.jpeg)
![whatsapp image 2018-12-29 at 14 10 36](https://user-images.githubusercontent.com/31561661/50536046-4ac54700-0b76-11e9-8d69-993e03e585b3.jpeg)

**Would you like to work on the issue?**

yes.

**Comment by kk63852** [comment]
i think that accent color should also have the same two line color picker arrangement as the primary color. Any suggestions @sauravvishal8797 @abishekvashok

**Comment by abishekvashok** [comment]
Sure go on
