### ISSUE TITLE
slideshow feature has no time limit

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2351]
**Actual Behaviour**

slideshow feature has no time limit and the app crashes if the value is too high.

**Expected Behaviour**

there should be a maximum time limit.

**Steps to reproduce it**

open a image and navigate to menu options. go to slideshow feature and enter a very large value, the app would crash.

**Would you like to work on the issue?**

yes.

**Comment by kk63852** [comment]
as a user i think that the maximum time limit should be 10 sec because no user would open a slideshow with each slide duration greater than 10 sec.
any suggestions @sauravvishal8797 @abishekvashok

**Comment by sauravvishal8797** [comment]
@kk63852 Ok, do it.
