### ISSUE TITLE
theme does not apply to camera settings.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2362]
**Actual Behaviour**

theme does not apply to camera settings.

**Expected Behaviour**

camera settings background should change with the theme change.

**Steps to reproduce it**

go to settings and change the theme. open camera settings. the applied theme would be dark irrespective of the theme change.

**Screenshots of the issue**

![whatsapp image 2019-01-02 at 18 17 22](https://user-images.githubusercontent.com/31561661/50592669-1a094880-0ebb-11e9-8fb2-54308a903919.jpeg)
![whatsapp image 2019-01-02 at 18 17 22 1](https://user-images.githubusercontent.com/31561661/50592672-1bd30c00-0ebb-11e9-8d3b-1856066e354b.jpeg)
![whatsapp image 2019-01-02 at 18 17 22 2](https://user-images.githubusercontent.com/31561661/50592673-1e356600-0ebb-11e9-8aca-7a413ad60dc7.jpeg)

**Would you like to work on the issue?**

yes.

**Comment by kk63852** [comment]
i am able to change the theme as per the user sets the theme but when the theme is set to white, the text colors are also white which makes them almost transparent. need help on how to change the text and subtext colors of a preference screen. @abishekvashok @sauravvishal8797

**Comment by kk63852** [comment]
still waiting for an answer. @abishekvashok @sauravvishal8797

**Comment by yashk2000** [comment]
@kk63852 try finding the file where all the text views of the camera file are initialized. There set the color of all the text views to be colorPrimary.

**Comment by kk63852** [comment]
i'll try doing that. thanks@yashk2000

**Comment by neel1998** [comment]
@kk63852  are you still working on this issue. If not i would like to work since I am also working on another issue in camera settings fragment

**Comment by kk63852** [comment]
sure. go ahead. @neel1998

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok this issue cannot be fixed easily. The camera module is a separate app in itself, opencamera, and has a very different architecture. It will take an unnecessarily large amount of time and resources to introduce the option of different modes here. 
I don't think it is practical to do this. Please tell me whether to close the issue or not.

**Comment by yashk2000** [comment]
Closing this issue because of the above reason.
