### ISSUE TITLE
Request permissions again when denied by checking Don't ask again

### ISSUE THREAD

**Issue by frextrite** [fossasia/phimpme-android#2363]
**Actual Behaviour**

Permission is not requested again when it is denied by checking ```Don't ask again```. Permission Required dialog box is shown and nothing happens when pressing on ```OK```.

**Expected Behaviour**

An option must be provided to the user to either exit the app or redirect the user to the app's settings page to grant the permission manually.

**Steps to reproduce it**

1. Open app
2. Deny the permission
3. Dialog box is shown informing the user why the app needs the specific permission, tap on ```OK```
4. Check ```Don't ask again``` and deny the permission
5. Click ```OK```

**LogCat for the issue**

--

**Screenshots of the issue**

![screenshot_2019-01-03-19-23-16-408_org fossasia phimpme](https://user-images.githubusercontent.com/29180487/50642828-65daf100-0f92-11e9-91d6-a0d6f7ae13ba.png)

**Would you like to work on the issue?**

Yes

**Comment by yashk2000** [comment]
I am working on this issue. A pull request for implementing an exit button has already been made.

**Comment by frextrite** [comment]
I intended to work on this but due to some prior commitments I wasn't able to till today. I was just about to start working on this but if you've already started, you can go ahead and work on this. Cheers.
