### ISSUE TITLE
Undo not working for Paint Text

### ISSUE THREAD

**Issue by tronku** [fossasia/phimpme-android#2364]
**Actual Behaviour**
In the "Write" section of editing a picture, the undo operation only works for "Text" not for "Paint".

**Expected Behaviour**
The Undo operation should work both for "Text" and "Paint" write options.

**Steps to reproduce it**
Select or capture a picture and then select the "Edit" icon. In the bottom section, select the "Write" editing feature. Choose "Paint" option and draw anything on the picture. You will notice that undo icon is currently disabled. Choose "Text" option and write anything, now the undo icon will get enabled and only reverses the changes happened due to "Text" option.

**Comment by abishekvashok** [comment]
Please proceed

**Comment by kk63852** [comment]
i could not the issue. can you please elaborate. @tronku

**Comment by yashk2000** [comment]
This is not a valid issue. While you are painting, there is an eraser to erase the things done. Once you are done with the painting, and press the tick mark button, then the changes are saved. Now the undo option will become activated and you can use it. Same is the case with the text method. 
While editting, there is the backspace or eraser button to undo changes. Once the tick button to save is pressed, the undo button will activate.
