### ISSUE TITLE
Choosing local folders to be secured can be done only once.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2368]
**Actual Behaviour**

When the user selects secure local folders, the user can just choose the folders to secure once. If the user has to remove/add security to any other local folder, local folders security has to be turned off and set again by selecting all the desired folders.

**Expected Behaviour**

Once security on local folders is on, an option should be provided to the user to add or remove folders which can be secured.

**Steps to reproduce it**

1) Open security setting and set a password if not set already.
2) Activate security for local folder. A menu is shown for choosing folders to be secured.
3) Close the menu after choosing desired folders.
4) Now if security is to be added or removed from a folder, it cannot be done without removing the security on local folders.

**Would you like to work on the issue?**

Yes.

**Comment by theabhishekavi** [comment]
@yashk2000 I found this bug too. Basically, i was thinking to add an onclicklistener on the textview 'Local Folder' which will open the the same dialog box of the secured folder and we don't need to toggle on and off again and again. And one more thing, when we go back and open the securedfolder list we get an empty dialog box. All the previous local folder list is lost. As a good practice we should always show the previously selected folders. If anyone is not working on this issue,shall i take this issue.
