### ISSUE TITLE
New Feature : Image should be zoom able in gallery Fragment & Refactor Gallery

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#238]
**Actual Behaviour**

We can't able to zoom image right now.

**Expected Behaviour**

It should be zoomable.

**Steps to reproduce it**

Click on any image in Gallery Fragment. 

**Would you like to work on the issue?**

Yes.

**Comment by Abhi2424shek** [comment]
Ok pls go on.
