### ISSUE TITLE
issue in first demo screen

### ISSUE THREAD

**Issue by kb54** [fossasia/phimpme-android#2390]
**Actual Behaviour**
need to tap on "GOT IT" in first demo screen
**Expected Behaviour**
whole screen should be allowed to be tapped,just like in next demo screen.
**Steps to reproduce it**
1.Clear data and cache of Application.
2.Restart it.
**Screenshots of the issue**
![screenshot_20190111-220946](https://user-images.githubusercontent.com/42945991/51111105-d8fd2680-1820-11e9-9aec-72de55f94fe4.png)
while in next demo screen you can tap on whole screen
![screenshot_20190111-220907](https://user-images.githubusercontent.com/42945991/51111175-1feb1c00-1821-11e9-9b71-db9fdcffc420.png)

**Would you like to work on the issue?**
Yes

**Comment by Bhavnaharitsa** [comment]
I would like to work on this issue ?

**Comment by kb54** [comment]
Sorry you can't work ,since I am already working

> I would like to work on this issue ?



> I would like to work on this issue ?

Sorry You can't ,Since I am  working on this issue.
