### ISSUE TITLE
Mapfragment taking too much time to instantiate 

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#240]
**Actual Behaviour**

Currently, the mapfragment takes too much time. Its mostly stuck on progress bar.

**Expected Behaviour**

The mapfragment should open quickly.

![screenshot from 2017-03-25 03-04-04](https://cloud.githubusercontent.com/assets/13241256/24314574/4d812c62-1108-11e7-8889-0e0909893d21.png)

![screenshot_2017-03-25-02-34-25-139_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24314591/6867b15e-1108-11e7-87a4-49aa8cafc139.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
That would be awesome.
