### ISSUE TITLE
Improve Travis CI build time

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#243]
**Actual Behaviour**

The build time is very long.

**Expected Behaviour**

The build time should be reduced by running jobs in parallel.

**Steps to reproduce it**

See the Travis CI dashboard.

**Would you like to work on the issue?**

Anyone can take it excluding Abishek V Ashok.

**Comment by jaisurya** [comment]
Steps to reduce it

Parallel and Deamon Configuration

Would you like to work on the issue?

Yes I want to.

**Comment by Abhi2424shek** [comment]
@jaisurya then you may!
