### ISSUE TITLE
sharing activity has no internet check.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2431]
**Actual Behaviour**

if the internet is turned off while sharing an image, nothing is displayed.

**Expected Behaviour**

a snackbar is needed when the internet is off while sharing.

**Steps to reproduce it**

open a image and navigate to share option when the internet is turned off. tap on any sharing feature nothing is returned. 

**Would you like to work on the issue?**

yes.

**Comment by yashk2000** [comment]
@kk63852 the pull request you have sent for this issue currently has lots of extra changes. #2446 has a fix which is very similar to this issue. Should I address this issue also in the fix for #2446 or do you want to send a separate fix for this one?

**Comment by kk63852** [comment]
extra changes like what??

**Comment by yashk2000** [comment]
@kk63852 you've made unnecessary changes in the AccountsActivity. There was also no need to remove the checkNetwork() function.

**Comment by kk63852** [comment]
Those where just extra lines for internet check which where supposed to diaplay a snackbar if not connected.. they didn't seem to be working so i just optimised the code by removing extra lines...

**Comment by yashk2000** [comment]
ok then. Also since #2446 is similar should I fix this issue in that, along with allowing the user to share by offline means? Both the issues have almost the same fix.

**Comment by kk63852** [comment]
Go ahead.
