### ISSUE TITLE
implementing swip-able tabs to maximize the camera screen size 

### ISSUE THREAD

**Issue by anirudh0228** [fossasia/phimpme-android#2434]
**Actual Behaviour**

Currently , the switching between tabs takes place through the bottomNavigationView .
This looks good in the 2 tabs (The Home and the accounts tabs) but really reduces the screen size available in Camera tab .

**Expected Behaviour**

The BottomNavigationView should be there in  home(LFMainActivity) and accounts tab along with swipe to switch while it should be replaced by swipe gesture in the camera activity similar to apps like instagram, WhatsApp etc. 

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
Don't do that, it's against the material deisng guidelines. Closing this therefore along with the pr.
