### ISSUE TITLE
Implementing View Pager for navigation in main page

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#244]
**Actual Behaviour**

 For navigating between pages (gallery, maps ...), we had to click on the bottom navigation menu.

**Expected Behaviour**

Navigating between fragments using swipe gesture.

**Would you like to work on the issue?**

yes

**Comment by dynamitechetan** [comment]
this is against the bottombarnavigation guidelines

**Comment by vinaysajjanapu** [comment]
No, it is not against the guidelines. As per guidelines, it is not a good practice to have both tablayout and bottomnavigationnbar for same task. But we can link viewpager and bottomnavigationbar.

**Comment by vinaysajjanapu** [comment]
PR merged by @pa1pal
