### ISSUE TITLE
no option to reset password if security answer is forgotten

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2441]
**Actual Behaviour**

if the user forgets the password, he can reset it by answering the security question set by him. but if he forgets the answer , the user is left with no option to reset the password.

**Expected Behaviour**

the user should be allowed to give a personal info (like date of birth) which can be used at the time when he forgets the password and answer all together. in this way the security is kept confidential and user is allowed to reset the password.

**Steps to reproduce it**

go to settings and setup security, if not set earlier. use any feature that involves security. tap on forgot password and input wrong answers to the security question. this continues forever and the password could not reset.

**Would you like to work on the issue?**

yes.

**Comment by yashk2000** [comment]
@kk63852 I do not think this is needed at all. This is a photo editing app, not a photo vault. If the user forgets the password as well as the security answer, the user can reset the settings. And answers such as date of birth are not secure. People besides the user will know the date of birth of the user and can then easily reset the password.

**Comment by abishekvashok** [comment]
Closing this there after
