### ISSUE TITLE
there should be a select all feature in secured folder dialog.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2447]
**Actual Behaviour**

in secured folder dialog, there is no select all button to check all the album check-boxes.

**Expected Behaviour**

there should be a select all button.

**Steps to reproduce it**

in the security activity navigate to secure folder. in the dialog a select all feature is missing.

**Would you like to work on the issue?**

yes.

**Comment by yashk2000** [comment]
@kk63852 can I please work on this issue?

**Comment by yashk2000** [comment]
Closing this issue as it was already implemented, but we no longer have security settings.
