### ISSUE TITLE
*** Android NDK: Aborting    .  Stop.

### ISSUE THREAD

**Issue by vishallandepatil** [fossasia/phimpme-android#2451]
Build command failed.

Error while executing process /Users/vishallandepatil/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-17 NDK_OUT=/Users/vishallandepatil/Downloads/phimpme-android-development/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/vishallandepatil/Downloads/phimpme-android-development/app/build/intermediates/ndkBuild/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

Android NDK: ERROR:/Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/Android.mk:opencv_contrib: LOCAL_SRC_FILES points to a missing file    

Android NDK: Check that /Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_contrib.a exists  or that its path is correct   

*** Android NDK: Aborting    .  Stop.
Open File

Build command failed.

Error while executing process /Users/vishallandepatil/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-17 NDK_OUT=/Users/vishallandepatil/Downloads/phimpme-android-development/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/vishallandepatil/Downloads/phimpme-android-development/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

Android NDK: ERROR:/Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/Android.mk:opencv_contrib: LOCAL_SRC_FILES points to a missing file    

Android NDK: Check that /Users/vishallandepatil/Downloads/phimpme-android-development/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_contrib.a exists  or that its path is correct   

*** Android NDK: Aborting    .  Stop.
Open File

**Comment by yashk2000** [comment]
@vishallandepatil this is not an issue. This error in building the app arises if you are not using ndk 16. Replace whatever version of ndk you are using with ndk 16. If you have any doubts, join the gitter channel. Also, this is not the proper way to create an issue, please follow the proper issue template in the future.
