### ISSUE TITLE
Appearance of the accounts section.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2457]
**Actual Behaviour**

There is a bar above the app bottom bar which does not look good in the accounts section.

**Expected Behaviour**

This bar should not be present.

**Steps to reproduce it**

Switch to accounts section, there is a bar present above the bottom bar of the app.

**Screenshots of the issue**

![screencap](https://user-images.githubusercontent.com/41234408/51836271-fd2f2c00-2325-11e9-9e9b-5634eafba09d.png)

**Would you like to work on the issue?**

YES.

**Comment by yashk2000** [comment]
@kk63852 it might look fine in white theme, but try switching to the dark theme. It looks a bit peculiar.

**Comment by kk63852** [comment]
It does look bad.
