### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#246]
**Actual Behaviour**

There are lot of unused classes which needs to be removed in order for new developers to contribute effortlessly.

**Expected Behaviour**

The unused classes will be removed. The classes will be placed in respective folders.

**Screenshots of the issue**

![screenshot from 2017-03-28 00-36-39](https://cloud.githubusercontent.com/assets/13241256/24373342/ada61f24-134e-11e7-9e93-1ef8f3d3668d.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
Most of the codebase contains old stuff however if you can pick unused classes from them you may.

**Comment by mohitmanuja** [comment]
@rohanagarwal94 Are you working on it. If not may I proceed. ?

**Comment by rohanagarwal94** [comment]
Yes I am. It's just that I am working on improving the background tasks of the app along side this, therefore it's taking me time.

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 5, 2017 at 12:22 AM, Mohit Manuja<notifications@github.com> wrote:   
@rohanagarwal94 Are you working on it. If not may I proceed. ?
