### ISSUE TITLE
Inactive snackbars in the app.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2467]
**Actual Behaviour**

Currently, there are many redundant and inactive snackbars in the app.

**Expected Behaviour**

The redundant snackbars should be removed and the inactive ones should be corrected so as to be displayed when required.

**Would you like to work on the issue?**

YES.

**Comment by naman653** [comment]
I would love to work on this issue. Please tell me which part of the app is showing these snack bars.

**Comment by yashk2000** [comment]
@naman653 Sorry, but I am currently working on this issue.
