### ISSUE TITLE
Initialise camera of the map fragment

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#247]
**Actual Behaviour**

On opening the map fragment, the camera is initialised to the map of the world.

**Expected Behaviour**

The camera of the map should be initialised to the city location of the user which is most likely where he must have clicked the most photos.

**Screenshots of the issue**

![screenshot_2017-03-28-02-44-23-424_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24378632/422fde70-1361-11e7-82e6-2a90ebb693f0.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
What happens if he has gps turned off?

**Comment by rohanagarwal94** [comment]
It will take location through either gps or internet. So, that wont be an issue.
