### ISSUE TITLE
accent color dialog issue.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2477]
**Actual Behaviour**

after setting up the primary color from settings a dialog pops up asking the user to set the accent color same as primary color. the dialog buttons currently displayed are "cancel" and "ok".

**Expected Behaviour**

the dialog buttons should be "yes" and "no" because the user is given a choice here.

**Steps to reproduce it**

open settings and set up primary color.  after this the dialog would pop up and thedialog buttons displyed are cancel and no.

**Screenshots of the issue**

![whatsapp image 2019-02-02 at 17 27 48](https://user-images.githubusercontent.com/31561661/52163958-195d0f80-2710-11e9-846a-61eb7f04c7bd.jpeg)

**Would you like to work on the issue?**

yes.

**Comment by yashk2000** [comment]
@kk63852 is this really needed? ok and cancel give the exact same message as yes or no.

**Comment by kk63852** [comment]
Yes and no would be more comfortable. I experienced that as a user.
