### ISSUE TITLE
The map shows no info in no internet state

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#248]
**Actual Behaviour**

The map fragment shows nothing on installation of app in no internet state. Happens with Xiaomi phones where the latest update makes a new installed application run without wifi on default.

**Expected Behaviour**

A dialog box should appear to direct the user to connect to internet in order to instantiate the map.

**Steps to reproduce it**

1. Install the application.
2. Switch off the wifi
3. Go to the Mapfragment tab.

**Screenshots of the issue**

![screenshot_2017-03-28-03-08-48-155_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24379266/f7a3639c-1363-11e7-831b-e6a99ecc31d6.png)

![screenshot_2017-03-28-02-55-55-529_vn mbm phimp me](https://cloud.githubusercontent.com/assets/13241256/24378920/5d1cd610-1362-11e7-89b4-71891d01f3e0.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
We should display no internet connection dialog or redirect to an activity when we really require internet access :) pls bear that in mind :)
