### ISSUE TITLE
swipe to refresh enabled for various empty folders

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2480]
**Actual Behaviour**

swipe to refresh enabled for various empty folders like favourite photos, upload history etc.

**Expected Behaviour**

it should be disabled for empty ui.

**Steps to reproduce it**

empty any of the given folders. swipe to refresh is set to true even if the folder is empty.

**Would you like to work on the issue?**

yes.

**Comment by sparrow007** [comment]
Swipe to refresh runs the method to ensure that there is any update , in case of empty UI user use the swipe to refresh function to ensure that there is any update in data or not.

**Comment by kk63852** [comment]
@sparrow007 i understand that but when the folder is already empty then there would be no use of swipe to refresh feature. thats why it should be disabled for empty ui.

**Comment by sparrow007** [comment]
@kk63852 there may be chances that data would be updated when user use this function , in your case user have to reopen the application for checking his updates in empty UI.

**Comment by kk63852** [comment]
this will be only disabled when the folders get empty. however in these folders data does not change with the refresh feature.
