### ISSUE TITLE
Add a filter to the app that gives an oil painting effect to the image

### ISSUE THREAD

**Issue by agh372** [fossasia/phimpme-android#2487]
**New Feature**

Add a filter to the app that gives an oil painting effect to the image

**Would you like to work on the issue?**

Yes

Already worked on it and this is how it would look. If you like it, I can send a pull request (edit: edited the image because a scenery looks better)
![oil](https://user-images.githubusercontent.com/37753430/52225679-9606ff80-2870-11e9-8bb5-f59a2c4964f0.jpg)

**Comment by abishekvashok** [comment]
Isn't there an oil painting similar filter there?

**Comment by agh372** [comment]
@abishekvashok if you mean cartoonify, then no, its quite different from that. This is more minimalistic!

**Comment by yashk2000** [comment]
@abishekvashok @iamareebjamal this feature has been implemented. This issue can be closed.
