### ISSUE TITLE
Get gps data from users IP

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#249]
**Actual Behaviour**

We are only fetching gps coordinates when user is having gps turned on.

**Expected Behaviour**

We should be able to take gps coordinates from ip address. We should also put an option in settings to disable it so as to give user more piracy if he wishes to.

**Would you like to work on the issue?**

/0

**Comment by AliAyub007** [comment]
Yes I would like to work on it.

**Comment by Abhi2424shek** [comment]
Ok pls then

**Comment by AliAyub007** [comment]
@Abhi2424shek my laptop got broken I had almost completed this so I will send PR with in 2-3 days as I will get my laptop fixed. :)

**Comment by Abhi2424shek** [comment]
Sure

**Comment by anantprsd5** [comment]
Due to inactivity of @AliAyub007 , I will be working on this issue from now on.

**Comment by anantprsd5** [comment]
@Abhi2424shek I guess we are extracting the location even when the gps is off from the network. Can you please specify where the problem is?

**Comment by Abhi2424shek** [comment]
@anantprsd5 currently when GPS is off, the location data is 0 even when internet is on.

**Comment by anantprsd5** [comment]
@Abhi2424shek While clicking the photo, even when the GPS is disabled, I am getting the latitude and longitude via network provider.
'''
lat = locationManager.getLastKnownLocation(LocationManager.NETWORK_PROVIDER).getLatitude();
'''

**Comment by Abhi2424shek** [comment]
Is it me only whom it is not fetching any results?

**Comment by anantprsd5** [comment]
@pa1pal Don't know. I will have a check in other devices. Thanks.

**Comment by pa1pal** [comment]
@anantprsd5 no lat lang value when GPS is off.
