### ISSUE TITLE
removing media from favourite folder and upload history while security is on requires password.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2498]
**Actual Behaviour**

removing media from favourite folder and upload history while security is on requires password.

**Expected Behaviour**

this should not require password as only a copy of image is being deleted.

**Steps to reproduce it**

add some image to favourite folder while security is on. tap on delete. it would require password yo proceed.

**Would you like to work on the issue?**

yes.

**Comment by yashk2000** [comment]
@kk63852 should security on upload history be left? If a photo is removed from upload history, you can not add it there again. It's okay to remove from favorites as the user can add a photo as a favorite again.

**Comment by kk63852** [comment]
i don't think so. because it just represent whatever image has been shared or uploaded. and after all the original image stays as it is.

**Comment by yashk2000** [comment]
Yes it is just a copy of the image, but if it is removed from upload history, the upload history cannot be recovered. A photo can be added as a favorite again, but if someone other that the user removes a photo from upload history, the user will not be able to know which photo was removed.

**Comment by kk63852** [comment]
i know it can't be recovered but don't you think that it will be quite annoying that you have to go through security every time just to clear the copy of image which is permanently present in your phone. after all it just upload history folder, it is serving its purpose but if you still want the password feature to be enabled let me know i'll send another pr.

**Comment by yashk2000** [comment]
No. I guess it's alright to remove the security feature from upload history also.

**Comment by abishekvashok** [comment]
Let's stay with it, it is a feature rather than a bug

**Comment by sauravvishal8797** [comment]
@kk63852 @yashk2000 As @abishekvashok said I guess we should keep the security option available for upload history so that only the user is able to delete images from there and at all points of time user has access to information regarding which images have been shared through the app.
