### ISSUE TITLE
adding settings option to the overflow menu of upload history

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2500]
**Actual Behaviour**

settings option is missing from the overflow menu of upload history.

**Expected Behaviour**

it should be added to the menu because settings should be accessed from anywhere.

**Steps to reproduce it**

navigate to upload history. open the overflow menu. settings option missing.

**Would you like to work on the issue?**

yes.

**Comment by kk63852** [comment]
Is it needed? @yashk2000 @angmas1

**Comment by yashk2000** [comment]
@kk63852 , yes I think this should be done.
