### ISSUE TITLE
Adding settings to overflow menu of about and trashbin activities.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2501]
**Actual Behaviour**

An option to go to settings directly from about or trashbin is not there.

**Expected Behaviour**

Settings button should be added to go to settings directly from these activities.

**Would you like to work on the issue?**

YES.

**Comment by kk63852** [comment]
Instead of making a similar issue, you could have just told me to add settings to these activities too while adding it to upload history folder.

**Comment by yashk2000** [comment]
No problem, I'll do it.
