### ISSUE TITLE
App Crashing on touching near right and bottom border in camera fragment

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#251]
**Actual Behaviour**

App is crashing if we touch anywhere on right and bottom border in camera fragment (in rear camera). 

**Expected Behaviour**

It shouldn't crash instead it should also focus by tapping there. 

**LogCat for the issue**

![error](https://cloud.githubusercontent.com/assets/25840461/24389796/d2162544-139d-11e7-8887-ecb1f891fdb8.PNG)

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@AliAyub007 I have just gone through the code and found what caused the issue. Shall I send the PR or do you want to work on it?

**Comment by AliAyub007** [comment]
@vinaysajjanapu  I wanted to work on this I just got home but it's totally fine if you have solved it and want to send PR.

**Comment by vinaysajjanapu** [comment]
@AliAyub007 fine. thank you.
