### ISSUE TITLE
Favourite photos activity is scrollable even if empty.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2510]
**Actual Behaviour**

Favorite photos activity is scrollable even if it is empty.

**Expected Behaviour**

It should not be scrollable when it is empty.

**Steps to reproduce it**

Go to favorite photos activity when it is empty. It is still scrollable even though there is no need for it.

**Would you like to work on the issue?**

YES.

**Comment by sparrow007** [comment]
@yashk2000 may i work on this ?

**Comment by yashk2000** [comment]
@sparrow007 go ahead.
