### ISSUE TITLE
Rate us is not working

### ISSUE THREAD

**Issue by imrrahul** [fossasia/phimpme-android#2512]
**Actual Behaviour**

On clicking on rate us option inside the application it redirects to Google play store where it shows item not found,which is not good for app development as it will reduce the chances of application development.
**Expected Behaviour**
It should the application in playstore so that it can be rated.

**Would you like to work on the issue?**

Yes

**Comment by kk63852** [comment]
Google removed the app from play store when it was asking unnecessary sms and call permissions.  This feature will start working when the app is uploaded once again on playstore.

**Comment by yashk2000** [comment]
@imrrahul this is temporary as the app will be back on play store soon. There is no need for this issue.
