### ISSUE TITLE
Insert password dialog issue.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2513]
**Actual Behaviour**

The ok and cancel buttons in insert password dialog are placed opposite of where they are in other dialogs. 

**Expected Behaviour**

In most dialogs, ok is to the left and cancel to the right. Insert password dialog should follow the same convention.

**Would you like to work on the issue?**

YES. I will also check other dialogs with ok cancel or yes no buttons and make all of them follow a common convention.

**Comment by kk63852** [comment]
Does it matter? Many of the apps have does not follow the same convention. I don't think its needed.

**Comment by yashk2000** [comment]
I think it should be done. I myself faced the Issue of pressing the cancel button in the insert password dialog in place of the ok button several times. The user gets accustomed to a particular convention and finds it comfortable if it is followed everywhere.

**Comment by kk63852** [comment]
You can do it if you want but i don't think its necessary.

**Comment by yashk2000** [comment]
I'll do it. It'll make the user experience of the app better.
