### ISSUE TITLE
a snackbar should be shown whenever theme is changed.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2518]
**Actual Behaviour**

no message is displayed when the theme is changed.

**Expected Behaviour**

a snackbar should be shown whenever theme is changed asking the user to restart the app as some of the color change would not occur unless restarted.

**Steps to reproduce it**

change the theme color . look around some of the overflow menu color does not change unless restarted.

**Screenshots of the issue**
![whatsapp image 2019-02-11 at 12 49 41 1](https://user-images.githubusercontent.com/31561661/52549916-adf3fb80-2dfb-11e9-87ad-6f6b4c5876ec.jpeg)
![whatsapp image 2019-02-11 at 12 49 41](https://user-images.githubusercontent.com/31561661/52549919-b0565580-2dfb-11e9-8e43-36dbd9602a43.jpeg)

**Would you like to work on the issue?**

yes.

**Comment by kk63852** [comment]
after basic theme dialog i think we should have a dialog asking the user to restart the app. like below:

![whatsapp image 2019-02-11 at 19 25 17](https://user-images.githubusercontent.com/31561661/52567782-19a58b00-2e33-11e9-9634-117eb991cd7a.jpeg)

any suggestions? @sauravvishal8797 @abishekvashok

**Comment by yashk2000** [comment]
@kk63852 I don't think it's needed. The change theme does not affect the performance of the app in anyway. This dialog will be more of a hindrance. A snackbar is enough. If the user wants to restart the app immediately, user can do it after seeing the snackbar.

**Comment by kk63852** [comment]
but some of colors does not change with the theme unless restarted. 
set a theme and navigate around for a while and change the theme again. now open an overflow menu (like from favourites or local folders) the color would not changed and when you restart the app it changes.

**Comment by kk63852** [comment]
for this problem i think we should have a dialog to restart the app.

**Comment by yashk2000** [comment]
Yes, but it doesn't affect the performance of the app. That's why I personally think it would he a bit irritating to see the dialog every time the theme is changed. Even if the overflow menu stays white, there is no change in it's performance or functionality.

**Comment by kk63852** [comment]
ok. i'll just add a snackbar. thanks.
