### ISSUE TITLE
App crash in orientation change while apply the effect

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2523]
**Actual Behaviour**

App is crashing when select the effect and change orientation then apply the effect.

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

Step 1. Click on the edit image button and go to enhancement select any effect.
Step 2. Change the orientation and then select the apply button (right tick icon).

**Would you like to work on the issue?**

Yes

**Comment by yashk2000** [comment]
This issue is no longer happening. It has been fixed along with https://github.com/fossasia/phimpme-android/pull/2790
