### ISSUE TITLE
Actionbar size increases when keyboard shown

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2527]
**Actual Behaviour**

Action bar size increase when keyboard show in setting.

**Expected Behaviour**

Size of action bar should not increasing. 

**Steps to reproduce it**

Step 1. Click on setting inside the navigation drawer 
 
Note : You should already setup your security password 

Step 2. Click on security it appear a dialog along with keyboard which increase the size of actionbar.

**Screenshots of the issue**

<img src = "https://user-images.githubusercontent.com/22986571/52585039-be3ac380-2e59-11e9-94af-a552daf3137b.jpeg" width = 250  height = 400>

**Would you like to work on the issue?**

Yes.

**Comment by yashk2000** [comment]
@sparrow007 could you please describe the issue in more detail? please specify which part is increasing in size. I am not able to reproduce this issue on my device.

**Comment by sparrow007** [comment]
@yashk2000 toolbar height, you can also see in the image (background of dialog).

**Comment by yashk2000** [comment]
Yes. I noticed it now.

**Comment by yashk2000** [comment]
This also happens if security is on and settings are to be reset. When the password is asked, the same thing happens. Please fix this issue there also.
