### ISSUE TITLE
Description of image no visible in landscape mode.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2528]
**Actual Behaviour**

In landscape mode, the description of the image is not visible in the details fragment.

**Expected Behaviour**

Description of the image should be visible in details fragment even in landscape mode.

**Would you like to work on the issue?**

YES.

**Comment by kk63852** [comment]
Could you please elaborate on this?

**Comment by yashk2000** [comment]
When you press on the details option, the "i" button in landscape mode, the description of the image does no appear. @kk63852 could you please tell me whether this happens on your device too?

**Comment by kk63852** [comment]
No its working fine on my device.

**Comment by yashk2000** [comment]
@kk63852 I also tried on another device, it works. But on my device it is showing up like this:

![screencap](https://user-images.githubusercontent.com/41234408/52633923-dce99a80-2eeb-11e9-9f96-be6eab5e28f4.png)

**Comment by kk63852** [comment]
> @kk63852 I also tried on another device, it works. But on my device it is showing up like this:
> 
> ![screencap](https://user-images.githubusercontent.com/41234408/52633923-dce99a80-2eeb-11e9-9f96-be6eab5e28f4.png)

since this is working just fine in other devices you should close this issue.

**Comment by yashk2000** [comment]
@kk63852 yes, I'm closing it. It only appears on my device for some reason. Thanks for checking it in your device.

**Comment by kb54** [comment]
@yashk2000 @kk63852  No, it's not appearing on my screen also .See this
![whatsapp image 2019-02-13 at 6 39 27 pm](https://user-images.githubusercontent.com/42945991/52713991-cfe9ab80-2fbe-11e9-98f2-738adb20db22.jpeg)

**Comment by yashk2000** [comment]
@kb54 thanks for checking it. I'll try to find the cause of this issue since it is appearing on 2 different devices.
