### ISSUE TITLE
Issue while renaming an image.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2532]
**Actual Behaviour**

If the user renames an image to "imagename".mp3(any extension), no warning is given and the image is renamed.

**Expected Behaviour**

The user should be given a warning saying that the image might not be recognized if any extension is added.

**Steps to reproduce it**

Try renaming an issue to "anyname".mp3. The image is renamed but then is not visible in the gallery as the signature has been changed.

**Would you like to work on the issue?**

YES.

**Comment by kk63852** [comment]
Don't you think nobody will be adding a extension while changing the name of an image in a gallery app. This is highly unlikely.

**Comment by sparrow007** [comment]
@yashk2000  i try to rename a image to "chirs.mp3" it still showing me the image

**Comment by sparrow007** [comment]
Predefined method is take the whole string, written in the dialog as the name of image it's not including as extension (".mp3"). For example 

<img src = "https://user-images.githubusercontent.com/22986571/52587830-fe517480-2e60-11e9-9d70-e1f661bae432.jpeg" width = 270 height = 450>

**Comment by yashk2000** [comment]
@sparrow007 it might depend upon the phone. I renamed a few images and ended them with .mp3, all stopped appearing in the gallery.

@kk63852 but a user might just do it. File explorers also warn when a user starts adding extensions by adding a ".". A user might just be trying to rename the image and might add a "." by mistake. Hence a warning should be shown if a "." is detected while renaming the image.

**Comment by yashk2000** [comment]
@

> Predefined method is take the whole string, written in the dialog as the name of image it's not including as extension (".mp3"). For example
> 
> <img alt="" width="270" height="450" src="https://user-images.githubusercontent.com/22986571/52587830-fe517480-2e60-11e9-9d70-e1f661bae432.jpeg">

This is not what might happen in all systems. In mine due to this change in extensions, the image stops appearing in the gallery. It's not proper to name an image in that way.

**Comment by kk63852** [comment]
I tried changing the name to some .mp3 , the image still exists.

**Comment by yashk2000** [comment]
In my phone, the image does not stay there. But even if the image might still be there, allowing an image to be named "anything"."something".png is not a good convention. If the user does this by mistake, a message should at least be shown to warn the user.

**Comment by imrrahul** [comment]
@yashk2000 @kk63852 After changing the name to a.mp3 , the file name is changed to a.mp3.png and the image is still opening but the image is shaking slightly while opening.
