### ISSUE TITLE
If password is off,open insert password dialog box before entering the Security Activity

### ISSUE THREAD

**Issue by theabhishekavi** [fossasia/phimpme-android#2537]
**Actual Behaviour**

When password is off,security activity opens and there we toggle password to open insert password dialog box.

**Expected Behaviour**

When password is off ,we should not enter in security activity directly, instead insert password dialog box should appear to set the password first.

**Would you like to work on the issue?**
  Yes

**Comment by theabhishekavi** [comment]
@abishekvashok @yashk2000 what do you think,should i work on this?

**Comment by yashk2000** [comment]
@theabhishekavi this would not be practical I think. The user should be allowed to decide whether the security should be switched on or not after seeing what switching on the security does. If we add this, the user would not even be able to enter the security settings if a password is not set. That would be impractical I think.

**Comment by theabhishekavi** [comment]
@yashk2000 as the security folder consists of using password only, so i think it should be a good practice to create password for the settings before entering it.

**Comment by yashk2000** [comment]
What if the user is only browsing through settings? It's not necessary that user wants to set a password if the user opens security settings. In your phone if no password is set, you can still enter the security settings and see all features available. I do not think this should be implemented.

**Comment by yashk2000** [comment]
@kk63852 what's your opinion on this?

**Comment by kk63852** [comment]
> What if the user is only browsing through settings? It's not necessary that user wants to set a password if the user opens security settings. In your phone if no password is set, you can still enter the security settings and see all features available. I do not think this should be implemented.

seems right to me. i don't think its needed.

**Comment by theabhishekavi** [comment]
okay. i think i should close this issue.
