### ISSUE TITLE
First Image of Locked Folder should not be visible

### ISSUE THREAD

**Issue by theabhishekavi** [fossasia/phimpme-android#2540]
**Actual Behaviour**

The first image of Locked Folder is always visible.

**Expected Behaviour**

For better privacy, first image of locked folder should not be visible

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/35160400/52684987-17941700-2f6e-11e9-91df-e907241e55df.png)

The above folders are locked but still anyone can see the first image.
For better privacy it should not be visible.

**Would you like to work on the issue?**

 Yes

**Comment by theabhishekavi** [comment]
@abishekvashok should i work on this?

**Comment by abishekvashok** [comment]
Yep
