### ISSUE TITLE
No code of conduct for the project.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2543]
**Actual Behaviour**

There is currently no code of conduct of the project.

**Expected Behaviour**

There should be a code of conduct for the project.

**Would you like to work on the issue?**

YES.
@abishekvashok @sauravvishal8797 should I add a code of conduct for the project?

**Comment by abishekvashok** [comment]
Nope. Instead we follow the general code of conduct of FOSSASIA. Adding one here isn't necessary.

**Comment by yashk2000** [comment]
ok. I'll close the issue.
