### ISSUE TITLE
"No search result found for" still persists on screen.

### ISSUE THREAD

**Issue by theabhishekavi** [fossasia/phimpme-android#2551]
**Actual Behaviour**
If we exclude all the local folders and then search for any random folder, "No search result found for" persists on screen.Even if we include all those excluded folders the above text of no search result is still there over the images

**Expected Behaviour**
The text of "No search result found for" should not be always there on screen

**Steps to reproduce it**
1.Select and Exclude all the local folders.
2.Search for a random folder and press back button
3.The text of No search result found for is still there
4.Now remove all those folders from exclude, the text of no search result found is displayed over all the images.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/35160400/52739092-2cb48880-2ff6-11e9-9a14-bae58479cc55.png)
![image](https://user-images.githubusercontent.com/35160400/52739120-36d68700-2ff6-11e9-97ba-7d3429390191.png)

**Would you like to work on the issue?**
 Yes

**Comment by theabhishekavi** [comment]
@abishekvashok should i work on this issue?

**Comment by abishekvashok** [comment]
Yes
