### ISSUE TITLE
Text and radio button is hidden when changing the orientation

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2554]
**Actual Behaviour**

"Local folder" text and radio button is not visible when changing the orientation.

**Expected Behaviour**

It should visible after changing the orientation .

**Steps to reproduce it**

Step 1. Go to Security section of setting 

Step 2. Change the orientation.

**Screenshots of the issue**

![whatsapp image 2019-02-14 at 4 20 21 am](https://user-images.githubusercontent.com/22986571/52749819-5c708a00-3010-11e9-9edb-5d6268da7a09.jpeg)

**Would you like to work on the issue?**

Yes.

**Comment by yashk2000** [comment]
This issues is not happening on my device.

**Comment by sparrow007** [comment]
It appear in my phone and there may be other phones who's get the same error.

**Comment by yashk2000** [comment]
Ok..must like #2528

**Comment by kb54** [comment]
@sparrow007  it is happening on my phone as well.
