### ISSUE TITLE
xml has many occurrences of paddingLeft/Right, marginLeft/Right etc. 

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2558]
**Actual Behaviour**

There are many occurrences of paddingLeft/Right, marginLeft/Right etc.

**Expected Behaviour**

Left/Right should be replaced with Start/End to support RTL devices.

**Would you like to work on the issue?**

YES.

**Comment by neel1998** [comment]
@yashk2000  I have made the necessary changes .. If you dont mind..I would like to make the PR.

**Comment by yashk2000** [comment]
@neel1998 I am working on this issue. I will send the pr when it's done.
