### ISSUE TITLE
Twitter link is not working

### ISSUE THREAD

**Issue by imrrahul** [fossasia/phimpme-android#2561]
**Actual Behaviour**

Twitter link is not working in accounts section #2223 solved this problem but it still exists.
**Expected Behaviour**

Twitter link should work and link user twitter account with phimpme application

**Would you like to work on the issue?**

yes

**Comment by yashk2000** [comment]
@imrrahul please don't open duplicate issues. Close this issue and mention that you are working on this in #2258.

**Comment by imrrahul** [comment]
@yashk2000 Thank you for notifying me I thought this issue was earlier raised and solved in #2223 ......Thank you for the information
