### ISSUE TITLE
Securedfolder names are not clickable in secure local folders.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2565]
**Actual Behaviour**

Currently, when the dialog to choose secured folders pops up, user has to click the checkbox to select folder to be secured.

**Expected Behaviour**

The securefolder name should also be clickable for better access.

**Would you like to work on the issue?**

YES.

**Comment by neel1998** [comment]
Can I please work on this issue.

**Comment by neel1998** [comment]
@yashk2000  I have already made necessary change to implement this feature. If you dont mind can I make a PR?
