### ISSUE TITLE
Unnecessary snackbar appear after put wrong password

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2566]
**Actual Behaviour**

.Unnecessary snackbar appear after putting wrong password in security dailog in trash bin section.

**Expected Behaviour**

Snackbar should not appear.

**Steps to reproduce it**

Note : You must have setup security on delete of image.

Step 1: Go to trash bin section of navigation drawer.

Step 2: Click on delete button and dialog will appear.

Step 3: Put the wrong password in the insert password then there a text appear in dialog at same time snackbar also appear.

**Screenshots of the issue**

<img src = "https://user-images.githubusercontent.com/22986571/52868773-37902a00-316a-11e9-812b-533c7d21f2b2.jpeg" width = 230 height = 420>

**Would you like to work on the issue?**

Yes.

**Comment by yashk2000** [comment]
@sparrow007 fix this issue, but can you please leave out the snackbar related issue for now? I am working on them under issues I created earlier. It is taking a bit of time, but I'm working on it. I have created an issue for removing the unused/redundant snackbars.

**Comment by sparrow007** [comment]
@yashk2000 don't worry take your time , i will work on this after your create your pull request of that issue.

**Comment by yashk2000** [comment]
@sparrow007 thanks, but if you want to fix this, do it as soon as possible. Else it might be fixed by #2467.

**Comment by kk63852** [comment]
actually i've already created this issue in #2444 and sent a pull request #2445.

**Comment by sparrow007** [comment]
@kk63852 thanks for notify me , i didn't see that so i am closing this issue.
