### ISSUE TITLE
Images should be share with all messaging apps instead of custom bluetooth

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#257]
**Actual Behaviour**
Right now on click on share button, the custom Bluetooth interface is opening.

![screenshot_2017-03-29-01-48-18-065_vn mbm phimp me](https://cloud.githubusercontent.com/assets/9361754/24425637/83eec3dc-1422-11e7-9ec1-cd8337a6bf7b.png)

**Expected Behaviour**
Instead of custom Bluetooth the user can also able to share with others available messaging apps currently present on the android device.

![screenshot_2017-03-29-01-51-02-159_android](https://cloud.githubusercontent.com/assets/9361754/24425643/8cb10cd2-1422-11e7-91fa-afb20b832e2a.png)

![screenshot_2017-03-29-01-51-13-382_com google android gm](https://cloud.githubusercontent.com/assets/9361754/24425653/951b30b4-1422-11e7-9588-2373c1e74cfd.png)

**Steps to reproduce it**

Open upload fragment and select multiple images. Now click on share button it will ask you to share images using Bluetooth. 

**Would you like to work on the issue?**

Yes, I have done with this want to send PR. Should I proceed ?

**Comment by mohitmanuja** [comment]
@Abhi2424shek Please review it.

**Comment by pa1pal** [comment]
@mohitmanuja This issue is same as #83 and the PR is in progress.
I am closing it for now. Please reopen if there is any difference.

**Comment by mohitmanuja** [comment]
@pa1pal Hey, Actually #83 is the same but it is raised for sharing single images from gallery fragment fab share option but my issue is sharing multiple images from upload fragment.
I think It is different although sharing option should be changed from both places. So should I send PR for #83 because the PR for #83 is flagged as invalid?

**Comment by Abhi2424shek** [comment]
It's not invalid. See it pls #87. @harsu-agu has done the work, but it has now conflicts. I think pinging him would be good so pinging.

**Comment by mohitmanuja** [comment]
okay @Abhi2424shek but that issue is for sharing single image so either we can ping him to add for sharing multiple images too. :-)

**Comment by Abhi2424shek** [comment]
Yea it would be easy. So I pinged him :) let's wait.

**Comment by mohitmanuja** [comment]
Okay @Abhi2424shek (y)
