### ISSUE TITLE
Repeatedly create new password issue

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2570]
**Actual Behaviour**

Every time we on the security (Access by password) we need to create new password even if there is an option for change password.

**Expected Behaviour**

It should ask or show dialog only for first time.

**Would you like to work on the issue?**

Yes.

**Comment by kk63852** [comment]
So how do you expect a person to setup the password if he turns off the security immediately after turning it on?

**Comment by sparrow007** [comment]
Person knows that he set the password for security and if he turns off the security immediately after turning it on then Access by the password turns on without any password dialog.

**Comment by kk63852** [comment]
Okay.

**Comment by sparrow007** [comment]
> So how do you expect a person to setup the password if he turns off the security immediately after turning it on?

if you talk about the first time he did this tricky thing it would not work because dialog is only starting invisible when there is password setup otherwise it show the dialog.

**Comment by kk63852** [comment]
So basically this should happen only if he is in security settings and navigating around. Is this the issue?

**Comment by sparrow007** [comment]
> So basically this should happen only if he is in security settings and navigating around. Is this the issue?

i did not get you , please explain ?

**Comment by kk63852** [comment]
What i meant was that a user would have to setup password only once if he is in security settings and turn it off and on again again if he is just navigating around in the settings. Isn't this you want to implement?

**Comment by sparrow007** [comment]
I just want to implement that user would not need to setup a new password every time he turn on the security and rest of the flow is same.

**Comment by kk63852** [comment]
Cool. I think it should be done.

**Comment by sparrow007** [comment]
This issue has been resolved so i am closing it.
