### ISSUE TITLE
Position of OK/ Cancel button on Password Dialog not consistent

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2572]
**Actual Behaviour**

Position of OK/Cancel button on Insert Password/ Change Password dialog not consistent with other Pop-ups. 

**Expected Behaviour**

Ok button should be on right and Cancel on Left if password dialog box.
**Steps to reproduce it**

Change/Insert Password

**Screenshots of the issue**

![screenshot_20190216-015629](https://user-images.githubusercontent.com/32041242/52883051-9fa53700-318f-11e9-9576-a2a5c0d551f1.png)

**Would you like to work on the issue?**

Yes

**Comment by sparrow007** [comment]
@neel1998  we already have similar issue #2513

**Comment by yashk2000** [comment]
@neel1998 I have already created an issue and made a pull request. Please close this issue.
