### ISSUE TITLE
security folder view alignment issue.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2575]
Security folder views are not aligned properly. there is an unnecessary gap present.

Screenshot:
![whatsapp image 2019-02-16 at 19 18 18](https://user-images.githubusercontent.com/31561661/52900786-8a2c1d80-3220-11e9-8111-4cdc914e41cf.jpeg)

**Comment by yashk2000** [comment]
I don't see what's the Issue here. Could you please elaborate it?

**Comment by kk63852** [comment]
the alignment of views below use password for. i think they should be aligned equally with views above those.

**Comment by yashk2000** [comment]
I think it's fine. It was made that way. Access by password and change password are the main features. The ones below are sub features. They should be segregated by the gap.

**Comment by kk63852** [comment]
i don't think its fine this way. it doesn't matter much

**Comment by yashk2000** [comment]
I really think it should not be done. There should be some difference between the main and sub settings. I think this should be closed.

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok @mariobehling this issue can be closed as we no longer have security settings.
