### ISSUE TITLE
After deleting, move to trashbin message issue.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2583]
**Describe the bug**
The message of "n image moved to trashbin" always treats any number as singular. 

**Expected Behaviour**
For more than 1 image, images moved to trashbin should be shown.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 Plus|
|Android Version|Android 9   |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by neel1998** [comment]
@yashk2000  are you working on this one?. If not I would like to

**Comment by yashk2000** [comment]
@neel1998 ok..work on it.
