### ISSUE TITLE
local folders view not visible in landscape mode.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2587]
**Describe the bug**
in security settings, local folders view is not visible in landscape mode.

**To Reproduce**

**Expected behavior**

the view should be visible in landscape mode.

**Screenshots**

![whatsapp image 2019-02-18 at 19 47 35](https://user-images.githubusercontent.com/31561661/52956937-8af6b800-33b6-11e9-8fff-09454aa51171.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[Samsung J7 next] |
|Android Version|[Oreo 8.1]  |

**Would you like to work on the issue?**

- * [x]  Yes
- * [ ]  No

**Comment by kk63852** [comment]
@yashk2000 @theabhishekavi could you please confirm this issue by checking it in your device?

**Comment by yashk2000** [comment]
Yes this is an issue in some devices. @sparrow007 fixed it by #2555

**Comment by kk63852** [comment]
thanks.

**Comment by theabhishekavi** [comment]
it is visible on my device.
![image](https://user-images.githubusercontent.com/35160400/52957669-394f2d00-33b8-11e9-9b2f-e0fbfba4aa63.png)
