### ISSUE TITLE
security settings views issue

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2588]
**Describe the bug**

Security folders views should be clickable in order to turn on the button.
**To Reproduce**

**Expected behavior**

clicking on the view should be enough to turn on the button.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1 |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by yashk2000** [comment]
@kk63852  I have already done this in #2453.
