### ISSUE TITLE
Unable to delete an image which is on internal storage

### ISSUE THREAD

**Issue by theabhishekavi** [fossasia/phimpme-android#2589]
**Describe the bug**
Sd-Card write permission issues. I have no sd-card on my device. All files are stored on internal storage.
Deleting a file which is on internal storage causes app to restart.

**To Reproduce**
1. Open a folder which is on internal storage
2. Try to delete it
3. App restarts

**Expected behavior**
It should delete the file and move to trashbin.

**Screenshots**
![ ](https://media.giphy.com/media/fnoUeIrITJsBOrrTWP/giphy.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[Redmi Note-6] |

**Would you like to work on the issue?**

 Yes
 Other:- After discussion

**Comment by theabhishekavi** [comment]
@yashk2000 is this issue arises because i don't have sd card?

**Comment by theabhishekavi** [comment]
@yashk2000 are you able to delete an image which is on internal storage?

**Comment by yashk2000** [comment]
@abishekvashok @iamareebjamal @mariobehling this issue arises in case of improper permissions given. I tried to reproduce the error on my device(which does not have an SD card) but I was able to delete any photo.
