### ISSUE TITLE
snackbar should be displayed if image is deleted permanently

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2590]
**Describe the bug**

no message is displayed if image is deleted permanently.
**To Reproduce**

1. select few images.
2. Click on 'delete'
3. uncheck the checkbox which ask the item to move it to trashbin.
4. no message is displayed if the images are deleted permanently.

**Expected behavior**

a snackbar should be displayed.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by yashk2000** [comment]
@kk63852 a  snackbar exists, but it is not visible. I am trying to fix this issue. I have already opened issues related to snacbars.

**Comment by kk63852** [comment]
i didn't see any snackbar in the code. could you please help navigating me there?

**Comment by yashk2000** [comment]
I saw that code in LFMainActivity. It might not be in SingleMediaActivity. If it is not there, can you please wait a week before fixing this issue? If I am unable to fix the snackbar issues by then, then work on this.

**Comment by kk63852** [comment]
cool.

**Comment by yashk2000** [comment]
Thanks:+1:

**Comment by yashk2000** [comment]
@kk63852 I fixed the position of snackbars in SingleMediaActivity. You can now work on this issue. When you call SnackbarHandler, just set the bottom margin to `bottomBar.getHeight()*2)-22`. This gives proper position to the snackbar.
