### ISSUE TITLE
in share Image, Caption Text Highlight not visible in Dark AMOLED theme

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2596]
**Describe the bug**

When try to edit the already given caption in share image, with dark AMOLED theme, text highlight is not visible.

**To Reproduce**
1. Change theme to Dark AMOLED
2. Select and image and click on share icon
3. Add Some Caption and press 'ok'
4. Again click on caption 

**Expected behavior**

Caption text should have highlight

**Screenshots**

![screenshot_20190220-013540](https://user-images.githubusercontent.com/32041242/53044234-739bf580-34b0-11e9-8205-33b9d4280e0b.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus|
|Android Version| Oreo 8.1  |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
The caption should be highlighted only if the user has set a caption already and then again presses on the option to set the caption.

**Comment by neel1998** [comment]
yes..it is not highlighted after the user tries to edit or delete the caption after setting it once
