### ISSUE TITLE
No option to remove or change album cover once set.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2599]
**Describe the feature you'd like**
Right now an image can be set as an album cover. But that image cannot be removed from the album cover, nor can the album cover be changed.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by neel1998** [comment]
I was able to change the album cover . Can you explain the bug in more detail? .Also what do you men by removing album cover. What should be the cover after removing some image from cover..

**Comment by yashk2000** [comment]
When you set a particular image as album cover, that image is fixed as the album cover. There is no option to revert back such that the first image in the album is the album cover.
