### ISSUE TITLE
There are several edit texts where ok has to pressed even after pressing keyboard tick.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2600]
**Describe the bug**
Right now there are several text views where ok button jas to be pressed even after pressing keyboard tick.

**Expected behavior**
Pressing the keyboard tick should be an action for ok.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |nokia 7 plus|
|Android Version|Android 9    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by neel1998** [comment]
I am already working on similar issue

**Comment by yashk2000** [comment]
I know. I won't work on the slideshow dialog. I'll work on all the rest of the dialogs in which this issue is present.

**Comment by neel1998** [comment]
okay

**Comment by neel1998** [comment]
@yashk2000  if you haven't started working on this. I have made the change for slide show dialog, i will apply similar changes to other places as well. if you don't mind.

**Comment by yashk2000** [comment]
Sorry, I have already started working on it. I'm almost done.

**Comment by neel1998** [comment]
No problem
