### ISSUE TITLE
Renaming an image with the same name gives no notification.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2610]
**Describe the bug**
While renaming an image, if the image is renamed with the same name, the image is still being renamed.

**To Reproduce**
Try to rename an image with the same name as it has. No notification is given.

**Expected behavior**
The image should not be renamed and a snack bar should be shown saying that there was no change in the name of the image.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 PLus|
|Android Version|Android 9   |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by kk63852** [comment]
this is not needed. since many of standard gallery app show no notification when an image is renamed. this is not something that is bringing a change in functionalities of the app which needs to display a message or notification.

**Comment by yashk2000** [comment]
I am doing it because if an album is named with the same name, an alert is shown and no renaming is done. Similar behavior should also be for individual photos to keep the behavior uniform throughout the app.
