### ISSUE TITLE
No indication that a password has been set.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2611]
**Describe the bug**
If a password has been set once, then removed and set again, there is no indication that a password has been set.

**To Reproduce**
Set a password once, remove it, set it again. No indication is shown that password has been set.

**Expected behavior**
An indication should be given to show that the password has been set.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 plus|
|Android Version|Android 9    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by kk63852** [comment]
it is really unnecessary. why would anyone set a password and remove only it set it again. we have change password for that we shows a snackbar with the message password changed.

**Comment by yashk2000** [comment]
Due to a recently merged commit, if the password is set once and then removed, the password is stored in the memory. If a password is set again anytime else, no matter however later, the user should be shown a notification that password has been set, like it was being done till now.
