### ISSUE TITLE
Slideshow dialog, if keyboard tick is pressed, dialog closes even if input is incorrect.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2612]
**Describe the bug**
When enter button on the keyboard is pressed, the dialog keyboard disappears no matter what the input is.

**To Reproduce**
Open slideshow, enter an incorrect value. Press enter on the keyboard, the keyboard will disappear.

**Expected behavior**
The keyboard should not disappear. It should stay there for the user to input correct data. And also instead of a toast, a snackbar should be shown when slideshow starts after pressing enter on the keyboard.

**Would you like to work on the issue?**

- [ ] Yes
- [X] No
- Other: @neel1998 would you like to work on this issue since you fixed a similar one today?

**Comment by neel1998** [comment]
@yashk2000  can you please elaborate the issue. I didnt get it properly

**Comment by yashk2000** [comment]
Try entering a value greater than 10 in the slideshow dialog. It is a wrong input. When enter is pressed on the keyboard, goes down. Prevent it from going down. It should go down if the user presses cancel or enters the correct input.

**Comment by yashk2000** [comment]
Also, when slideshow starts after pressing enter from the keyboard, a toast is shown. Replace the toast with a snackbar. Will you work on these things @neel1998 ?

**Comment by neel1998** [comment]
@yashk2000 i will make this changes
