### ISSUE TITLE
Go to Top FAB doesn't appear when viewing all the albums on the home screen 

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2620]
**Describe the bug**

No go to top fab for home album screen

**To Reproduce**

1. Scroll down in albums list

**Expected behavior**

go to top fab should appear 

**Screenshots**
![20190222_202020](https://user-images.githubusercontent.com/32041242/53250055-a4ae3d00-36df-11e9-8e04-951232c71fbb.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |  Moto G5s Plus |
|Android Version|  Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
Is this really needed? A user will generally have 10-12 albums at max. Even if it is more than that like 15-16, it's not such a large number that a got to top button is needed.

**Comment by neel1998** [comment]
i dont think so... 15 - 16 is too less. I myself have 119 albums xD. And i believe it is a nice feature. We cant predict how many album a user might create

![screenshot_20190222-202805](https://user-images.githubusercontent.com/32041242/53250524-914fa180-36e0-11e9-8ad7-d16a6344eb1c.png)

**Comment by yashk2000** [comment]
119 albums? Almost all people just have few basic albums: camera, screenshots, 3-4 for social media apps, 1-2 for photo editing apps. This is generally the case. Most people will not store icons/drawables of an app in their phones.

**Comment by neel1998** [comment]
i know not everyone will have 119 albums. Still i dont find any negative effects of having a go to top fab on home screen

**Comment by yashk2000** [comment]
Ok. But I think make the fab button appear only if the user is 14-15 albums down.

**Comment by neel1998** [comment]
Okay. this seems reasonable. Will make changes accordingly

**Comment by abishekvashok** [comment]
I don't think it's needed
