### ISSUE TITLE
Go to top fab while viewing photos of album/favourites appears too late

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2621]
**Describe the bug**

Go to top fab while viewing photos of album/favourites appears too late

**To Reproduce**
1. Scroll down to 2-3 pages in any album

**Expected behavior**

go to top fab should appear after scolling down a single pages

**Screenshots**

![20190222_202423](https://user-images.githubusercontent.com/32041242/53250323-3158fb00-36e0-11e9-8ad1-f01915ed3e78.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
This is not needed. The user should have gone some way down the album. It's not as if the user will go to the top of the album immediately after starting to go down. I think the time at which the go to top button appears is optimum. Any time sooner will be too soon as the user would not have gone down enough.

**Comment by neel1998** [comment]
okay. Let's keep it as it is
