### ISSUE TITLE
Sort option visible on favourites screen even if only one image is present

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2626]
**Describe the bug**

Sort option is visible in favourite screen with one image

**To Reproduce**

1. Add onlyn one image in favourites

**Expected behavior**

Sort option should be hidden

**Screenshots**

![screenshot_20190223-125733](https://user-images.githubusercontent.com/32041242/53283344-11224e00-376b-11e9-922c-af5331b81998.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version|Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by sparrow007** [comment]
@neel1998 close this issue.
