### ISSUE TITLE
colored navigation bar in settings does not work.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2628]
**Describe the bug**

colored navigation bar in settings does not work.
**To Reproduce**

1. Go to 'Settings'
2. Click on 'Colored Navigation Bar'
3. no change in the ui if it turned on or off again.

**Expected behavior**

the navigation bar color should change accordingly.

**Screenshots**

![whatsapp image 2019-02-23 at 19 17 24 2](https://user-images.githubusercontent.com/31561661/53287293-0fbf4880-37a0-11e9-87b9-7b804095b6fc.jpeg)
![whatsapp image 2019-02-23 at 19 17 24](https://user-images.githubusercontent.com/31561661/53287294-11890c00-37a0-11e9-825e-1115f2612754.jpeg)
![whatsapp image 2019-02-23 at 19 19 28](https://user-images.githubusercontent.com/31561661/53287295-151c9300-37a0-11e9-8d6f-52d0570bf26e.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1  |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by yashk2000** [comment]
@kk63852 I do not face this issue. The navbar color changes in my device on pressing the button.

**Comment by kk63852** [comment]
Okay. I'll just confirm on 2-3 devices before closing the issue. Thanks for checking by the way.
