### ISSUE TITLE
"Add to favourites" option should not be visible in menu if selected image is already in favourites

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2640]
**Describe the bug**

"Add to favourites" option is visible even if image is already in favourites

**To Reproduce**

1. Add image to favourite
2. Select that image in album mode and open menu

**Expected behavior**

Add to favourites option should not be visible

**Screenshots**

![screenshot_20190224-172031](https://user-images.githubusercontent.com/32041242/53298798-deef1a00-3858-11e9-8651-6c16f7330a09.png)

![screenshot_20190224-172042](https://user-images.githubusercontent.com/32041242/53298797-deef1a00-3858-11e9-9676-fa1d780d17d5.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
This is not happening in my app. If an image is already added to favorites, then remove from favorites is shown in the menu.

**Comment by neel1998** [comment]
We need to check with someone else as well..Because i checked several times and it is not working as expected.

@kk63852  can you check once?

**Comment by kk63852** [comment]
this is what i am getting in my device if an image is already added to favourites.:

![whatsapp image 2019-02-24 at 18 48 51](https://user-images.githubusercontent.com/31561661/53299767-0e0b8880-3865-11e9-92ab-6a8a0ae22644.jpeg)

**Comment by yashk2000** [comment]
I'm getting the same thing

**Comment by neel1998** [comment]
I guess then it is not working on my device only.. Should i close the issue?

**Comment by yashk2000** [comment]
Yes. It is working on majority of phones so I guess it can be closed.
