### ISSUE TITLE
No SnackBar shown upon setting some image as contact picture

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2641]
**Describe the bug**

No indication given when the image is set as contact picture

**To Reproduce**

1. Make one image contact picture

**Expected behavior**
 There should be a snackbar to indicate that contact image has been set

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1  |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
How will you make the snackbar appear? When the image is being set as the contact photo, the action is not being done by phimpme. Phimpme just selects the photo.

**Comment by neel1998** [comment]
I will check once if there is once.. If there is nothing I can do i will close this issue

**Comment by yashk2000** [comment]
> How will you make the snackbar appear? When the image is being set as the contact photo, the action is not being done by phimpme. Phimpme just selects the photo.

@abishekvashok @iamareebjamal @mariobehling closing this issue because of the above-mentioned reason.
