### ISSUE TITLE
Title of sort menu visible in Main Screen and not in individual album screen

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2642]
**Describe the bug**
Title of sort menu visible in Main Screen and not in individual album screen
**To Reproduce**

1. Open sort menu in main screen and individual albums screen 

**Expected behavior**
Sort menu title should be visible in individual album activity

**Screenshots**

![screenshot_20190224-174501](https://user-images.githubusercontent.com/32041242/53299101-45296c00-385c-11e9-85c6-5e1db2b0beb4.png)
![screenshot_20190224-174453](https://user-images.githubusercontent.com/32041242/53299102-45c20280-385c-11e9-9763-a714f15c53fe.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version|  Oreo 8.1    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
There is no need for this. The icon which you press to open the menu is an icon for sorting itself. There is no need to give a heading. Please close the issue.

**Comment by neel1998** [comment]
Then why do we need it in the first case as well...

**Comment by yashk2000** [comment]
It was there already..leave it. There is no need for it. The button with the sort action is indication enough that you're sorting.

**Comment by neel1998** [comment]
Okay i will close the issue
