### ISSUE TITLE
unused variables in some activities.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2643]
**Describe the bug**

there are some unused variables in some activities.

**Expected behavior**

unused variables should be removed.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
Please do it carefully. Remove only those variables which are not being used by any of the commented or unused methods. It will create a problem otherwise. Remove only those which are absolutely not used anywhere after declaration.
