### ISSUE TITLE
wrong position of snackbar in single media activity.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2644]
**Describe the bug**

while using any of the functions like renaming, moving etc the snackbar displayed are positioned incorrectly.
**To Reproduce**

1. Go to 'any album'
2. Click on ' an image'
3. open the overflow menu.
4. perform any action. the snackbar displayed are positioned incorrectly.

**Expected behavior**

the snackbar displayed should lie just above the navigation bar.

**Screenshots**

![whatsapp image 2019-02-25 at 01 00 31](https://user-images.githubusercontent.com/31561661/53304254-f3eb9d80-3898-11e9-8b5e-4a4a1122239a.jpeg)
![whatsapp image 2019-02-25 at 01 00 32](https://user-images.githubusercontent.com/31561661/53329067-5aac9d80-3911-11e9-9241-6f7d3f15f227.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
@kk63852 I was working on this issue and sent a pr. But i guess #2592 did not fix this problem. Can I please try to continue working on it for some time?

**Comment by kk63852** [comment]
its ok. i'll do it.

**Comment by yashk2000** [comment]
ok

**Comment by codedsun** [comment]
@yashk2000 Please confirm. For me it's working fine now please close the issue if working

**Comment by yashk2000** [comment]
@codedsun it does not occur on my device too. But I think it might still occur on other devices as currently the height has been hardcoded. We need to figure out a way to automatically calculate the height so it works on all devices.

**Comment by codedsun** [comment]
@yashk2000 Okay will check.

**Comment by codedsun** [comment]
Taking this up
