### ISSUE TITLE
No snackbars displayed in camera settings fragment upon changing settings

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2651]
**Describe the bug**
No snackbars displayed in camera settings fragment upon changing settings
**To Reproduce**

1. open camera settings activty

**Expected behavior**

There should be snackbar upon changing any settings

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
This part of processing is done by a separate module, the openCamera module. Making changes like introducing snackbars in this module will be a bit difficult as it follows a very difficult architecture from the rest of the app. It will take an unnecessary amount of time and resources to add snackbars to all settings and then the sub-settings inside. Closing this hence.
