### ISSUE TITLE
Logos for "Photo settings" and "Location settings" in camera settings are not matching with entire app theme

### ISSUE THREAD

**Issue by neel1998** [fossasia/phimpme-android#2654]
**Describe the bug**
Logos for "Photo settings" and "Location settings" in camera settings are not matching with entire app theme
**To Reproduce**

1. Open camera settings fragment

**Expected behavior**

Logos should be some 2d monotone clipart .

**Screenshots**
![screenshot_20190227-003316](https://user-images.githubusercontent.com/32041242/53439242-a6ea0180-3a27-11e9-9668-08de5a3f86eb.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by neel1998** [comment]
@yashk2000  @kk63852  I think this issue needs to be solved. Still i would like to know your opinions.

**Comment by yashk2000** [comment]
I agree that the icons are different from those used in other places in the app. But I think you should ask the project maintainers whether to make this change or not.

**Comment by neel1998** [comment]
@abishekvashok  @mariobehling  Your thoughts?

**Comment by abishekvashok** [comment]
Change it
