### ISSUE TITLE
hardcoded strings at many places.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2658]
**Describe the bug**

there are many hard-coded strings in the app code like messages, keys, name etc.

**Expected behavior**

the hardcoded strings should be saved in strings xml.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by abishekvashok** [comment]
We will just close it now and focus on real **issues** and get back to such silly refractions later.

**Comment by kk63852** [comment]
i think this should be implemented as their are many hardcoded preference keys and strings which are being used at multiple places. any views on this @sauravvishal8797 ?

**Comment by sauravvishal8797** [comment]
@kk63852 Have you already accomplished a significant part of the task?

**Comment by kk63852** [comment]
Yes..

**Comment by sauravvishal8797** [comment]
@kk63852 Ok. I'm opening this issue, please push all the changes in a single commit only.
