### ISSUE TITLE
Deselect all images in gallery fix

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#266]
**Actual Behaviour**

It is not appropriate to call onresume to deselect all the images in the menu item menu_gallery_deselect_selected. Due to this, the images selected also gets lost on resume for which I have opened another issue. For solving that, I need to solve this first.

**Expected Behaviour**

The deselecting of the images should be implementing correctly.

**Screenshots of the issue**

![screenshot from 2017-03-30 20-22-20](https://cloud.githubusercontent.com/assets/13241256/24510533/1b6c9382-1587-11e7-8374-4a6e79cf8e98.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by vinaysajjanapu** [comment]
@rohanagarwal94 Have you worked on this? 
if not, then can you explain what's going wrong? I don't understand clearly.
