### ISSUE TITLE
app now accesses password even if settings is reset.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2669]
**Describe the bug**

when security is setup and settings is restarted, app accesses the password even after settings was reset.

**Expected behavior**

app should not access the previous password if settings is reset.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1 |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by kk63852** [comment]
can you please check on your devices too?@yashk2000

**Comment by yashk2000** [comment]
I checked it on my device. A new password has to be set up if settings are reset.

**Comment by kk63852** [comment]
Thanks @yashk2000. I'll just have a few more before closing this issue.
