### ISSUE TITLE
Replace bottomnavigationview with Tablayout

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#267]
**Issue**

Bottomnavigationview is not getting animated perfectly with viewpager. The tasks bottomnavigationview performs can also be achieved by using a tablayout. Viewpager also works best with tablayout. So, I prefer replacing bottomnavigationview with tablayout.

**Would you like to work on the issue?**

yes.

**Comment by pa1pal** [comment]
#269
