### ISSUE TITLE
Adding a filter does not stop after cross is pressed.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2673]
**Describe the bug**
Even if the cross button is pressed, the filter might be added if it takes a bit of time to customize the image.

**To Reproduce**
Go to add a filter to an image. Add the oil filter image. PRess cross. The oil filter image takes time to be applied and if the cross button is pressed, it keeps on working and is applied later.

**Expected behavior**
The filter effect should be canceled totally if cross is pressed. 

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 Plus|
|Android Version|Android 9.0    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by kk63852** [comment]
Seems to be working fine on my device.

**Comment by yashk2000** [comment]
While the filter is being added, if you press the cross, then also adding the filter stops immediately?

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok I couldn't find any way to stop the application of a filter once it starts. I think that we should remove the oil painting filter. 
It takes 8-10 seconds to be applied. I don't think that any user will spend so much time to apply a filter.
