### ISSUE TITLE
Bottom Navigation Bar Behavior

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/phimpme-android#268]
https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior
Read this. 
Using swipe gestures on the content area does not navigate between views.
4cc8f7cbbbaed0496fb38624e0fc387d3b2a345e commit was regarding this only.
again issue #267 is similar to this.

Please follow the guidelines.
I request to revert the merge for swipe gestures in bottom navigation bar and view pager.

**Comment by madhavrathi** [comment]
@dynamitechetan is right. I guess maintainers should revert the commits. @Abhi2424shek @pa1pal

**Comment by pa1pal** [comment]
@dynamitechetan I though that swipe will be good for easy navigation. Sorry, I didn't saw that earlier. 
Following guidelines is always foremost priority. 
Thanks for pointing out.
