### ISSUE TITLE
View of Rotation and Crop options in landscape mode.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2680]
**Describe the bug**
In rotation and crop options, in landscape mode, both options get distorted.

**To Reproduce**
Enter landscape mode.
Go to edit mode, transform and enter rotation or crop options.
The menus of both options get distorted. Also if an image is rotated in portrait mode, and then the phone is rotated, the data is lost and rotation has to be done again.

**Expected behavior**
This issue should not be there.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

@kk63852 can you please test this on your phone and upload a screenshot of how the rotate and crop options look on your phone in landscape mode?

**Comment by kk63852** [comment]
![WhatsApp Image 2019-03-11 at 19 42 26](https://user-images.githubusercontent.com/31561661/54130342-36cf7880-4436-11e9-9acf-bd8df25e3a58.jpeg)

**Comment by yashk2000** [comment]
@kk63852 thanks for checking it :) It's an issue and I'll start working on it.
