### ISSUE TITLE
upload history long press issue.

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2688]
**Describe the bug**

no response is returned if an item is long pressed in upload history folder.

**Expected behavior**

the item should be selected if long pressed and the user should enter edit mode.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by abishekvashok** [comment]
Voting against this
