### ISSUE TITLE
Build Faild

### ISSUE THREAD

**Issue by anveshana99** [fossasia/phimpme-android#2696]
I just import the project and did changes as mentioned in description. Still facing this issue.
I'm using android studio 3.2.1
classpath 'com.android.tools.build:gradle:3.1.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

Build command failed.

Error while executing process /Users/gamenexastudios/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/gamenexastudios/Documents/phimpme-android-development/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/gamenexastudios/Documents/phimpme-android-development/app/src/main/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-17 NDK_OUT=/Users/gamenexastudios/Documents/phimpme-android-development/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/gamenexastudios/Documents/phimpme-android-development/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

Android NDK: ERROR:/Users/gamenexastudios/Documents/phimpme-android-development/app/src/main/jni/Android.mk:opencv_contrib: LOCAL_SRC_FILES points to a missing file    

Android NDK: Check that /Users/gamenexastudios/Documents/phimpme-android-development/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_contrib.a exists  or that its path is correct   

*** Android NDK: Aborting    .  Stop.
Open File

**Comment by yashk2000** [comment]
This is most probably because you're using a higher NDK version. Downgrade bdk to version 16. 

Also this is not an issue. It's a problem faced while building the app. If you face such problems, please discuss in the gitter channel. Please close this issue and ask any further doubts related to building the app in the gitter channel.

**Comment by anveshana99** [comment]
Hi yashk2000, Thanks for replying. i have done what you said by downgrade to 16 version. Still i'm facing the same issue. @yashk2000. Ok i will do in channel i'm closing now.
