### ISSUE TITLE
Automatically build an apk file in the apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#27]
The goal of this issue is to get an apk on each merged pull request build in the apk branch.

Use travis to build apks automatically. You can check other FOSSASIA projects e.g. Open Event Android and Susi Android how it is done there.

**Comment by Heredroky** [comment]
@mariobehling I will work on this

**Comment by Heredroky** [comment]
@mariobehling Is it mandatory to generate the apk in the apk branch?

**Comment by Heredroky** [comment]
@mariobehling Check #28

**Comment by mariobehling** [comment]
This issue is not solved yet unfortunately. There is a sample apk folder in the master branch, but the goal of this issue is to get automatically generated apks in the apk branch.

**Comment by pa1pal** [comment]
I will fix this.

**Comment by Abhi2424shek** [comment]
Is it fixed in #32?

**Comment by pa1pal** [comment]
Yes #32 met all the specifications.
