### ISSUE TITLE
App crashes when changing the orientation in dimension compress

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2700]
**Describe the bug**
App is crashing when changing the orientation in the dimension compress section.

**To Reproduce**

1. Select any image and click on compress
2. Click on By dimension button
3. Change the orientation.

**Expected behavior**
App should not crash.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A |
|Android Version|7.1.2  |

**Would you like to work on the issue?**
- Yes

**Comment by yashk2000** [comment]
Closing this issue as I tried this on 2 devices, but the app did not crash. Also, https://github.com/fossasia/phimpme-android/pull/2779 will take care of the dialog disappearance issue on orientation change which is the problem.
