### ISSUE TITLE
Options became invisible when switch to Dark AMOLED theme

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2712]
**Describe the bug**

Options from trash bin and upload history became invisible when we apply the dark amoled theme.

**Expected behavior**

It should visible according to the theme.
**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A|
|Android Version|7.1.2  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by yashk2000** [comment]
This issue has already been opened by @kk63852.

**Comment by yashk2000** [comment]
#2516

**Comment by sparrow007** [comment]
@yashk2000 thanks for inform and i think you have take this up so go head buddy :)
