### ISSUE TITLE
Repetition call of background task in gallery 

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2723]
**Describe the bug**

Currently in the app when we click on home button (Gallery) it calls the asyncTask (background task) again and again.

**Expected behavior**
After one call of background task call it should not call .

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A |
|Android Version|7.1   |

**Additional context**

For repetition of background task there is already swipe to refresh is available.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
Should this really be done? What if a user clicks a photo? The user will have to refresh manually to make the photo appear. Also if the user edits a photo, the edited photo will not be visible unless the user refreshes the gallery. I do not think refreshing in instances such as these will be preferred by the user. It is better to let the gallery refresh each time it is opened.

**Comment by sparrow007** [comment]
@yashk2000 you are correct buddy but in this issue i want to remove repetition because if user already in gallery and then he again click on gallery button after that background task will execute. according to your point if user in camera and he shift to gallery then at that time it will call the background task for updating in list.

**Comment by yashk2000** [comment]
Ok, got it. That should be done:+1:
