### ISSUE TITLE
Position is same after changing the section

### ISSUE THREAD

**Issue by sparrow007** [fossasia/phimpme-android#2726]
**Describe the bug**

Currently in the app position is same (position in local folder same as position in hidden folder).
**To Reproduce**
1. Scroll the album in local folder 

2. Change the section from local folder to hidden folder using navigation drawer

3. Position of image in hidden is same as we left in local folder.

**Expected behavior**

When we change the section (local to hidden folder) it should start from beginning. 
**Logs**

|               | |
|---------------|-|
|Device         |Redmi 5A
|Android Version|7.1 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by yashk2000** [comment]
@sparrow007 I did not get this issue. Could you please elaborate on how to reproduce it? And also add a screenshot or a GIF?

**Comment by sparrow007** [comment]
@yashk2000 hope this would help you

<img src="https://user-images.githubusercontent.com/22986571/56458930-6f099580-63aa-11e9-9533-54d9a65be36f.gif" width = 220 height = 420/>

recyclerview position is same as in local folder and in hidden folder. It should start from beginning when it changes to hidden folder.
