### ISSUE TITLE
Cannot Find Download Page On Google Play Store

### ISSUE THREAD

**Issue by trymeouteh** [fossasia/phimpme-android#2727]
I cannot find this app on Google Play and when I click on the link that is on the main page for fossasia/phimpme-android it does not work. Please fix this and also please add this app on F-Droid.

https://play.google.com/store/apps/details?id=org.fossasia.phimpme

**Comment by yashk2000** [comment]
@abishekvashok @sauravvishal8797 @mariobehling since the permissions issue has been resolved, when will the app be uploaded to Google Play Store again?

**Comment by abishekvashok** [comment]
Yep

**Comment by sparrow007** [comment]
I think app will update on play store after fixing some vulnerable bugs and adding to master branch (may be updated version).
