### ISSUE TITLE
No confirmation on back button pressed in edit image page

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#273]
**Actual Behaviour**

The activity just closes when back button is pressed in edit image page (CropImage activity). This may cause loss of edited image when back button got pressed accidentally.

**Expected Behaviour**

Should display a dialog asking a confirmation from the user to close the activi

**Steps to reproduce it**

Select image in gallery page. Press edit FAB. Perform some edits. Press back button.

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
Ok cool work on it then pls.

**Comment by rohanagarwal94** [comment]
@vinaysajjanapu I suggest you implement the fix in the application class itself, so that whichever activity the user is in , the dialog will be shown.

**Comment by vinaysajjanapu** [comment]
@rohanagarwal94 I hope it is not necessary for all activities and the dialog needed will also be different for different activities.

**Comment by Abhi2424shek** [comment]
Closed via #275
