### ISSUE TITLE
App contains only 32 bit native binaries.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2744]
**Describe the chore**
The app currently contains only 32-bit native binaries. These will be banned after August. They should be replaced with 64-bit binaries.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by mariobehling** [comment]
Google does not see the 64 builds yet.

> By August 1, 2019, all apps that use native code must provide a 64-bit version in order to publish an update. As of the sending of this email, at least one of your apps* does not yet meet the requirement: Phimp.me

Please resolve this on the app store as well.

**Comment by iamareebjamal** [comment]
Play Store Artifact Library Release v1.8.0 - 

Native platforms | arm64-v8a, armeabi-v7a, x86, x86_64

**Comment by yashk2000** [comment]
@mariobehling this is already done.

**Comment by yashk2000** [comment]
Closing this issue as it is already fixed.
