### ISSUE TITLE
Empty space taken by shadow 

### ISSUE THREAD

**Issue by heysadboy** [fossasia/phimpme-android#278]
**Actual Behaviour**

The view creates thin line which is visible in camera and map activity.

![screenshot_2017-03-31-20-33-46](https://cloud.githubusercontent.com/assets/22588035/24556513/43fe6994-1652-11e7-8c7c-fc854a239a39.png)

**Expected Behaviour**

Although shadow is good but it should not push up other views.

![screenshot_2017-03-31-20-35-05](https://cloud.githubusercontent.com/assets/22588035/24556520/4ade82f8-1652-11e7-8d6f-0c9fa31fbf28.png)

**Steps to reproduce it**

So removing it.

**Would you like to work on the issue?**

Yes.

**Comment by Abhi2424shek** [comment]
@heysadboy remove the shadow only when the background is not white or any shade of white.

**Comment by Abhi2424shek** [comment]
That's ^ only my opinion, let's wait for others and then only pls do work on it ;)

**Comment by madhavrathi** [comment]
@heysadboy @Abhi2424shek  I guess the shadow distinguishes the bottom navigation bar from the current view. I guess this is a good feature.

**Comment by heysadboy** [comment]
@madhavrathi @Abhi2424shek  I think the color of bottom navigation bar is distinguishable enough to view separate that in gallery and I think it looks a bit unpolished to have gaps between views.

**Comment by madhavrathi** [comment]
@heysadboy That is true. It looks kinda unpolished.

**Comment by AliAyub007** [comment]
@heysadboy With Shadow doesn't it look bit promising and distinguishable if there is white background? For camera and gallery it does look unpolished i think.

**Comment by heysadboy** [comment]
I think I should come up with some other solutions for this.

**Comment by Abhi2424shek** [comment]
@heysadboy I encourage you to take a look at the Google photos app, they are giving low zindex for the shadow and allowing it to be overlapped so that it looks like it is in the background. Your thoughts @pa1pal
