### ISSUE TITLE
Edits in image not saved on orientation change.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2789]
**Describe the bug**
While editing the image if orientation is changed, the changes made in the image are not saved.

**Expected behavior**
The changes made should be saved even on orientation change.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
@abishekvashok @iamareebjamal should I lock rotation mode to whatever mode the user enters edit mode in?
If the user enters edit mode in landscape mode, then the rotation will be locked to landscape while the user edits the image.
Should I do that? This will solve #2702 also.

**Comment by abishekvashok** [comment]
Nope don't do that, just retain the edit on rotation.

**Comment by yashk2000** [comment]
@abishekvashok yes. That's what I'm trying to do, but I'm unable to find the bitmap to be retained on orientation change. 
I meant this solution just as a workaround until I found the correct thing.
