### ISSUE TITLE
Fix the auto release script.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2797]
**Describe the chore**
Fix the auto release script.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by mariobehling** [comment]
Please also reduce the number of APKs generated and change the name of the APKs files as follows:

- phimpme-dev-debug.apk (formerly phimpme-dev-app-debug.apk)
- eventyay-organizer-master-debug.apk (formerly phimpme-master-app-debug.apk)
- eventyay-organizer-master-unsigned.apk (formerly phimpme-master-app-release-unsigned.apk)

**Comment by yashk2000** [comment]
On it.
