### ISSUE TITLE
After editing first time user gives Bluetooth access, on the second edit user is again requested to give access

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2807]
Expected: The user should just give access to use Bluetooth once.

**Comment by sonusourav** [comment]
@mariobehling Can I work on this?

**Comment by yashk2000** [comment]
@sonusourav you can work on any issue you want as long as no one else is working on it :)

**Comment by yashk2000** [comment]
@mariobehling I am not able to reproduce this issue. When I run the app with Bluetooth off, after editing, I do not get any alert to turn on Bluetooth. Bluetooth is not required to be turned on when a picture is edited.

**Comment by mariobehling** [comment]
Ok, seems to be wrong. Closing it.
