### ISSUE TITLE
Images overlapping with bottom navigation bar

### ISSUE THREAD

**Issue by sonusourav** [fossasia/phimpme-android#2809]
**Describe the bug**
Some of the images are overlapping with the bottom navigation bar

**To Reproduce**

1. Open any images that have dimensions similar to shown below ( portrait, big enough to cover the screen)
2. Observe that it overlaps.

**Expected behavior**
Fixed margin should be given between the image and the bottom navigation bar.

**Screenshots**

![WhatsApp Image 2019-07-05 at 9 26 22 PM](https://user-images.githubusercontent.com/34706326/60737732-6d974480-9f79-11e9-98ce-5d5f4cd6eb31.jpeg)
![WhatsApp Image 2019-07-05 at 10 56 18 PM](https://user-images.githubusercontent.com/34706326/60737733-6d974480-9f79-11e9-9744-73901e577606.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 4|
|Android Version| Android Nougat    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
I don't think it is an issue. Toolbar and navigation bar should hide after clicking on the image, and visible on again clicking. As all gallery apps do.

**Comment by yashk2000** [comment]
@sonusourav I think @liveHarshit is right. We cannot have different sized toolbars for every different sized image. If user wants the full view of the image, the user can click the image, hiding the toolbar and entering the full screen mode.

**Comment by sonusourav** [comment]
@liveHarshit  You are right in some sense. Let me put it this way. If we don't fix the maximum area over which the image can be displayed, then chances are there that the images will get cropped also. That's what happened in #1926  and #1873 . Also, in such cases when you see the image in other orientation, the image gets definitely cropped. You may check that.
@yashk2000  We don't need different sized toolbars, instead fix the height of bottom navigation bar, add a fixed margin between the bottom navigation bar and the area over which image is displayed. 
I think that the images should scale according to the provided area.

**Comment by yashk2000** [comment]
@sonusourav ok. Proceed with the issue :+1:

**Comment by codedsun** [comment]
@yashk2000 What has to be done for this?

**Comment by yashk2000** [comment]
@codedsun let's leave this issue for now. 

> I don't think it is a bug. Toolbar and navigation bar should hide after clicking on the image, and visible on again clicking. As all gallery apps do.

This is a correct point and so I think we shouldn't waste time on this issue.
