### ISSUE TITLE
Add multiple selection in Upload History

### ISSUE THREAD

**Issue by sonusourav** [fossasia/phimpme-android#2811]
**Describe the feature you'd like**
Currently, there is no feature to select items ( either one or all by the long press) in Upload History. This would be required if a user wants to remove selected images or share selected images in the upload history.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by yashk2000** [comment]
@sonusourav thanks for reporting the issue. We already have similar issues. https://github.com/fossasia/phimpme-android/issues/2602 and https://github.com/fossasia/phimpme-android/issues/2604. Please work on this issue there. These issues only focus on delete options, but you can add share option for upload images too.
Closing this issue hence.

**Comment by sonusourav** [comment]
Sorry, but since the title was not proper, it was not displayed in similar issues. Thanks for bringing it to my notice. Next time, I will take care.
