### ISSUE TITLE
Update ExoPlayer to v2.x.x

### ISSUE THREAD

**Issue by TacoTheDank** [fossasia/phimpme-android#2849]
**Describe the chore**

- Update ExoPlayer to v2.x.x

Here's some documentation to help:
- https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#r200
- https://medium.com/google-exoplayer/exoplayer-2-x-why-what-and-when-74fd9cb139#.am7h8nytm

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: I'd like to work on this but I don't trust myself to do it correctly (plus I'm new to programming in general), so... no... Anyone is welcome to though...

**Comment by yashk2000** [comment]
Thanks for this issue. But we left it deliberately when updating the dependencies because exoplayer version 2.x.x seems to use androidx. Our app currently does not support androidx and hence updating to version 2.x.x will cause manifest merger errors. Closing this hence.

**Comment by TacoTheDank** [comment]
hmm, ok
