### ISSUE TITLE
Update Glide to 4.x.x

### ISSUE THREAD

**Issue by TacoTheDank** [fossasia/phimpme-android#2852]
**Describe the chore**

Update Glide from 3.x.x to 4.x.x

https://github.com/bumptech/glide/releases
https://bumptech.github.io/glide/doc/migrating.html

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Someone who has the know-how can do this :)

**Comment by yashk2000** [comment]
@iamareebjamal while migrating to version 4, I cannot find a replacement for AnimatedGifEncoder. Could you please tell me if there is an alternative to this in version 4, or do we need to keep using version 3?

**Comment by iamareebjamal** [comment]
It's supported by default I guess

**Comment by yashk2000** [comment]
@iamareebjamal when I change to glide 4.9.0, this `import com.bumptech.glide.gifencoder.AnimatedGifEncoder;` stops working and it shows gifencoder not found.

**Comment by iamareebjamal** [comment]
Yeah because it is not needed now

**Comment by yashk2000** [comment]
But we are using `AnimatedGifEncoder` in phimpme.

**Comment by iamareebjamal** [comment]
For what?

**Comment by TacoTheDank** [comment]
It still exists as far as I can tell: https://bumptech.github.io/glide/javadocs/490/index.html "com.bumptech.glide.gifencoder"

**Comment by yashk2000** [comment]
@TacoTheDank thanks :+1:

**Comment by yashk2000** [comment]
@iamareebjamal on updating the version to 4.9.0, we need to make a lot of changes. We also need to make changes in some of the custom animation modules. So should we update to 4.x.x or keep it to the current 3.7.x version?

**Comment by iamareebjamal** [comment]
Your choice

**Comment by TacoTheDank** [comment]
I mean, the longer we use old dependencies, the harder upgrading will potentially be later when we will have to upgrade. I'd say we should tackle the old dependency issue sooner rather than later, I guess.

**Comment by codedsun** [comment]
i have completed this issue and upgraded the dependency to 4.10.0, sending a pr shortly!
