### ISSUE TITLE
Provide APKs on releases pages

### ISSUE THREAD

**Issue by niansa** [fossasia/phimpme-android#2857]
As i think, **every** open source project should at least provide it's own build and not **bind** users to download from some closed-source store with bad privacy practice. Sure, they could download from ApkMirror but there is always the risk to have malware included.

**Comment by yashk2000** [comment]
@niansa did you perhaps checkout our [apk branch](https://github.com/fossasia/phimpme-android/tree/apk). It is updated with all our apks.

Also, we are working on a fdroid release. We have already created a pr. The fdroid packagers need to package the app now.

Closing this issue hence.

**Comment by niansa** [comment]
Alright, fine thank you

**Comment by rancidfrog** [comment]
@yashk2000 
Why dont you attach as assets in release section, since you already have detailed changelog:
https://github.com/fossasia/phimpme-android/releases
