### ISSUE TITLE
convert the app from v7 support versions to androidx

### ISSUE THREAD

**Issue by prudhvir3ddy** [fossasia/phimpme-android#2860]
v7 support version is going to be deprecated soon and we have to migrate the app to androidx

**Comment by codedsun** [comment]
@prudhvir3ddy @yashk2000 Can I take this?

**Comment by yashk2000** [comment]
If @prudhvir3ddy is not working on it, go ahead @codedsun.

**Comment by codedsun** [comment]
@prudhvir3ddy Please confirm and let me know. Thanks

**Comment by yashk2000** [comment]
@codedsun you can work on this issue.

**Comment by prudhvir3ddy** [comment]
@codedsun @yashk2000 working on this issue. sorry i didn't get notification. i'll send the PR by tomorrow
