### ISSUE TITLE
Improving permission flow in the splash screen

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#2863]
**Describe the bug**
The permission flow is not correctly implemented, it should be done correctly when returning from application settings page while clicking on grant permission option in dialog

**To Reproduce**

1. Go to 'Splash screen'
2. Deny the permission
3. check don't ask again
4. A dialog will appear of permission required 
5. Click on grant permission, go to settings page and return

App get's stucked

**Expected behavior**
This should work and we should not be needing to restart the app after giving permission. Can we convert this class to kotlin @yashk2000 ?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by codedsun** [comment]
@yashk2000 Please let me know to convert in Kotlin?

**Comment by yashk2000** [comment]
@codedsun currently we are not migrating the app to Kotlin. We'll be using Java only.
