### ISSUE TITLE
how add custom Font from Assets folder??

### ISSUE THREAD

**Issue by iman100** [fossasia/phimpme-android#2873]
how read font files from assets folder and add to Class FontManeger. 

![36608630-615a6514-18f0-11e8-8b42-049808501252](https://user-images.githubusercontent.com/13415270/65331639-6d026780-dbd2-11e9-980b-dabb45d88af6.png)

**Comment by codedsun** [comment]
What you want to achieve?

**Comment by codedsun** [comment]
@yashk2000 @iman100 Please close the issue

**Comment by iman100** [comment]
> 
> 
> What you want to achieve?



add custom font rtl for Txt on app
