### ISSUE TITLE
Picture get rotated by itself.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#288]
**Actual Behaviour**

After clicking images from camera image get rotated by itself.

**Expected Behaviour**

picture should not rotate by itself.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-04-02-10-47-02](https://cloud.githubusercontent.com/assets/14003244/24584716/d5967dd2-1793-11e7-8bb3-4d367578b4e1.png)
![screenshot_2017-04-02-10-46-29](https://cloud.githubusercontent.com/assets/14003244/24584723/0d16ed0a-1794-11e7-8534-e183ceb4d5ba.png)

**Would you like to work on the issue?**

Yes

**Comment by Abhi2424shek** [comment]
First, please do update the issue template.
