### ISSUE TITLE
Project building issue related android NDK?

### ISSUE THREAD

**Issue by Susith1995** [fossasia/phimpme-android#2893]
process_begin: CreateProcess(NULL, "", ...) failed.
C:/Android_ndk/android-ndk-r20/build//../build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

Android Studio 3.5 / Windows 10

also...

Android NDK: ERROR:D:\FossAsia_CodeHeat\phimpme-android\app\src\main\jni\Android.mk:opencv_dnn: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that D:/FossAsia_CodeHeat/phimpme-android/app/src/main/jni/../staticlibs/armeabi-v7a/libopencv_dnn.a exists  or that its path is correct

**Comment by codedsun** [comment]
Have you followed the guidelines?
