### ISSUE TITLE
Feature : Local Gallery images should be scrollable

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#290]
**Actual Behaviour**
The user is not able to scroll to more images by swiping left and right. They have to go back and select another image.

**Expected Behaviour**

The user should able to scroll to more images by swiping left and right. 

**Steps to reproduce it**

Click on any image from local gallery and try to swipe right and left.

**Screenshots of the issue**

![screenshot_2017-04-02-14-25-54-897_vn mbm phimp me](https://cloud.githubusercontent.com/assets/9361754/24585795/7c90c11c-17b0-11e7-913b-b9de1fdee81b.png)
![screenshot_2017-04-02-14-26-22-703_vn mbm phimp me](https://cloud.githubusercontent.com/assets/9361754/24585796/7c954444-17b0-11e7-9c55-82115bfdea54.png)

**Would you like to work on the issue?**

Yes. @Abhi2424shek @pa1pal  Please review.

**Comment by Abhi2424shek** [comment]
Ok seems cool.

**Comment by Abhi2424shek** [comment]
Closed via #303
