### ISSUE TITLE
Gradle Version needs to be Updated in build.gradle file

### ISSUE THREAD

**Issue by Rajchowdhury420** [fossasia/phimpme-android#2906]
**Describe the chore**
Gradle version Needs to be Updated to latest from 3.5.0 to 3.5.2
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by codedsun** [comment]
@Rajchowdhury420 Please follow the template.

**Comment by Rajchowdhury420** [comment]
where is it Exactly ?

**Comment by codedsun** [comment]
@Rajchowdhury420 Please check how other issues are made.

**Comment by Rajchowdhury420** [comment]
okay ! Thanks
