### ISSUE TITLE
About Screen: Redesign screen and follow standard UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2920]
Please implement a more standard looking about screen, e.g. compare to PSLab About screen. Change the following:
* use system colors and fonts
* use system bottom bar colors and transparency
* use standard structure as PSLab
* change any other non-standard looking way

![Screenshot_20191118_110624_org fossasia phimpme](https://user-images.githubusercontent.com/1583873/69021817-1360c280-09f4-11ea-8b23-04270aaef8a5.jpg)

**Comment by codedsun** [comment]
@mariobehling Taking this up. Also, I was thinking to redefine the UI and features like Google Photos.
