### ISSUE TITLE
Phimp.me app crashed on opeing. Android 8.1.0 #2930

### ISSUE THREAD

**Issue by IamJayshree** [fossasia/phimpme-android#2930]
#2930
**Describe the bug**
Installed the app from Playstore. 
Opened just once and explored, after that it fails to open. 
I've attached the screenshot of logs. Corrections are welcome.

**Screenshots**
![Screenshot_2019-11-22-19-58-56-404_com miui bugreport](https://user-images.githubusercontent.com/26122348/69434956-ab4c0c80-0d64-11ea-8412-c260ff249e63.png)
![Screenshot_2019-11-22-19-58-59-110_com miui bugreport](https://user-images.githubusercontent.com/26122348/69434957-abe4a300-0d64-11ea-84e9-6415eb16a5a8.png)

Device - Redmi Note 5 Pro
Android Version - 8.1.0

**Comment by codedsun** [comment]
@iamareebjamal @yashk2000 What shall be done in this case, this library has got some issues
`implementation 'com.github.deano2390:MaterialShowcaseView:1.2.0@aar`

Reference : https://github.com/deano2390/MaterialShowcaseView/issues/167

**Comment by iamareebjamal** [comment]
Remove it

**Comment by codedsun** [comment]
Taking it up, will send a PR asap
