### ISSUE TITLE
Cropping image using 'size percentage' is not working.

### ISSUE THREAD

**Issue by AbhinavSharma24** [fossasia/phimpme-android#2936]
**Describe the bug**
Cropping feature using 'size percentage' is not working.

**To Reproduce**
1. Go to 'phimp.me android application'
2. Select an image to 'edit' it.
3. Now at the bottom select the 'crop image' option.
4. Select 'by Size' option and set any value for 'Compress by size'.
5. Click 'set', it will crash the application 
4. See error : 'phimp.me stopped working'

**Expected behavior**
It should crop/compress the image according to the value given by user.

**Screenshots**
Bug reported:
https://github.com/AbhinavSharma24/AndroidCB19/blob/master/Screenshot_20191201-115057.png
Error:
https://github.com/AbhinavSharma24/AndroidCB19/blob/master/Screenshot_20191201-115102.png

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1 |

**Would you like to work on the issue?**

- [ 1] Yes, I can work on this issue.

**Comment by abishekvashok** [comment]
> Yes, I can work on this issue.

Please carry on with it then

**Comment by codedsun** [comment]
@AbhinavSharma24 Please provide the logcat, for me its' working fine - Android 9.0 - Realme 3

**Comment by codedsun** [comment]
@iamareebjamal Close this, no response yet
