### ISSUE TITLE
The app is not working on my phone

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/phimpme-android#2937]
**Describe the bug**
When the app opens it crashes.

**To Reproduce**

|               | |
|---------------|-|
|Device         |Google Pixel 3|
|Android Version|10 |

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

**Comment by STEdirisuriya** [comment]
![phimpme](https://user-images.githubusercontent.com/33794760/70048896-668c6500-15f1-11ea-9d7b-2d10d4fca690.jpg)

**Comment by codedsun** [comment]
Please attatch the log here, @STEdirisuriya

**Comment by abishekvashok** [comment]
Please fill in this table:
> Device |  
Android Version

**Comment by STEdirisuriya** [comment]
Done!

**Comment by codedsun** [comment]
@STEdirisuriya Similar to, please take this and get this resolved 
https://github.com/fossasia/phimpme-android/issues/2927

**Comment by STEdirisuriya** [comment]
Closing this because there's already similar issue #2927 @codedsun
