### ISSUE TITLE
Phimpme custom development - paid

### ISSUE THREAD

**Issue by alexm7** [fossasia/phimpme-android#2938]
I am looking for a developer that has experience working on the phimpme codebase that can provide software development services to create a customized version of phimpme.  I like the functionality of phimpme, but I need a simpler version for a specific application.  I need a developer to be able to customize and trim down the phimpme application to just the required functionality.  I realize the project is GPL, so all changes would be published as a fork.

If you have experience as a contributor to the project, know the code base and are interested in the work then please email me at mootsalex@gmail.com.

Thanks!
Alex.

**Comment by codedsun** [comment]
@iamareebjamal Close this

**Comment by alexm7** [comment]
Can you provide some details as to why this is not a valid question here?  Should it be posted somewhere else?
Thanks
Alex.

**Comment by iamareebjamal** [comment]
This is GitHub, not Craigslist
