### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by 18Aaron** [fossasia/phimpme-android#2942]
Whenever I take a screenshot of the app or use it to delete any photos through the app , it stops working please resolve this issue .

**Smartphone Info:**

|Device         ||
|Android Version|    |

**Comment by codedsun** [comment]
Can you please post the logs here?

**Comment by 18Aaron** [comment]
Hi . I'm sorry if this is a stupid question but what how do I get a log ?

**Comment by codedsun** [comment]
@18Aaron https://developer.android.com/studio/debug/bug-report or you can also connect your device to your pc and have adb commands extract the logs, but this is long process. Please check the link

**Comment by 18Aaron** [comment]
Hi . Thanks for your reply . I don't know what's happening but after
enabling bug reports all my apps are working fine even the occasional
crashes of the app stopped . I don't know why but I received a report and
I'll send it to you anyways
