### ISSUE TITLE
Text feature

### ISSUE THREAD

**Issue by Swkn1004** [fossasia/phimpme-android#2949]
In the write feature from the edit option
If we select the text option and start to type,the typed text is being placed at random places.
It would be much better if the user can change the position to place the text or edit the typed text.

In the following Screenshots from my android phone, Clearly show that the consecutive typed texts get placed at the same place making it look bad.

**Screenshots**

![Screenshot_2019-12-25-14-08-23-506_org fossasia phimpme](https://user-images.githubusercontent.com/58425876/71439935-83641600-2721-11ea-8679-4fe9d62b833f.png)

![Screenshot_2019-12-25-14-03-15-857_org fossasia phimpme](https://user-images.githubusercontent.com/58425876/71439919-70e9dc80-2721-11ea-8ed4-780718f67022.png)

**Comment by mariobehling** [comment]
out of scope currently.
