### ISSUE TITLE
Security Bug

### ISSUE THREAD

**Issue by STG284** [fossasia/phimpme-android#2954]
**Describe the bug**
Any website is accessible through in app web view. This is a security threat. Hacker can go to his own website thus run his code in the app and may hack into app.

**To Reproduce**
1. Go to Accounts section
2. Click on IMGUR
3. Scroll down to terms of service
4. You can access this website! Now you can click on any site on this page to go further. Like this you can possibly go to any other website by a series of intermediate sites.

**Expected behavior**
Any other site other than the login site must not be opened in the app, otherwise must be opened in other browser app.

**Would you like to work on the issue?**

I can but haven't explored the code yet,( was just testing the app).

**Comment by mariobehling** [comment]
Out of scope.
