### ISSUE TITLE
Image cropping doesn't save the cropped image

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#296]
**Actual Behaviour**

When I try to crop an image without applying any filter, it doesn't save the cropped image.

**Expected Behaviour**

When an image is being cropped, it should be saved when we click on _OK_ button

**Steps to reproduce it**

1. Open app
2. Select an image and open the full image view
3. Click on the FAB and select _Edit_ button
4. Crop the image **without** applying any filter
5. Click _OK_
6. Go to _Gallery_ and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

I've assigned myself one issue. So this one is open to anyone :)

**Comment by vinaysajjanapu** [comment]
I'll try

**Comment by CloudyPadmal** [comment]
@vinaysajjanapu okay! :)
