### ISSUE TITLE
Initialize Jekyll in gh-pages branch

### ISSUE THREAD

**Issue by MuhammadWasif** [fossasia/phimpme-android#2962]
**Describe the bug**
Jekyll files are not properly set up for a website. This should be a proper Jekyll site. 
Initialize Jekyll in the project

**To Reproduce**

1. Go to `gh-pages` branch

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by abishekvashok** [comment]
I am sorry to inform you but this is not a site built on Jekyll. gh-pages is generated using  https://github.com/fossasia/yaydoc

I am sorry, but we would need to close this down.

**Comment by MuhammadWasif** [comment]
> I am sorry to inform you but this is not a site built on Jekyll. gh-pages is generated using https://github.com/fossasia/yaydoc
> 
> I am sorry, but we would need to close this down.

I'm doing this as a Google Code-In task. [The task](https://codein.withgoogle.com/tasks/5926128217227264/?sp-organization=5183942706069504&sp-is_beginner=False&sp-search=phimp) says to initialize with **Jekyll**
