### ISSUE TITLE
App Not Responding

### ISSUE THREAD

**Issue by Lalithsai853** [fossasia/phimpme-android#2966]
When I attempt to open the app on my google pixel 3a, the app states that it is unable to respond and it keeps stopping. I don't know if this is a problem on my device, but even after I redownload it, it still gives mew the same error message.

**Comment by Lalithsai853** [comment]
Here is the screenshot of the problem via the link below.
https://drive.google.com/file/d/1OlHoaQBaeJ8cf4OzT6bVV5kxPnSkFAEs/view?usp=sharing

**Comment by TBog** [comment]
related to #2927

**Comment by gaymathur** [comment]
> When I attempt to open the app on my google pixel 3a, the app states that it is unable to respond and it keeps stopping. I don't know if this is a problem on my device, but even after I redownload it, it still gives mew the same error message.
It isalso not responding n my realme phone.

**Comment by TBog** [comment]
Is this the same as #2927?

**Comment by codedsun** [comment]
Please close this issue, we have multiple instances of the same issue created.

**Comment by Lalithsai853** [comment]
Hello Suneet Srivastava,

I will close it as soon as possible.

Thank you,
Lalithsai Posam
