### ISSUE TITLE
Cropped image quality is very low (with filters)

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#297]
**Actual Behaviour**

First of all not that I've mentioned (with filters) because it doesn't save cropped images without any additional change. When an image is cropped to the size same as the original image even, the image quality is very low

**Expected Behaviour**

Image quality should be at a satisfiable level

**Steps to reproduce it**

1. Open app
2. Select an image from gallery
3. Click on the FAB icon and select _Edit_ button
4. Crop the image just to the corners as in screenshots below and apply _Invert_ filter (Inverting won't affect quality I assume)
5. Click _OK_ and save image
6. Open the edited image and observe!

**LogCat for the issue**

> Not available

**Screenshots of the issue**

| Original Image  | Being cropped | Saved Image |
| ------------- | ------------- | ------------- |
| ![originalimage](https://cloud.githubusercontent.com/assets/14261304/24588231/2d69c796-17e2-11e7-921e-00099e30dc39.png)  | ![cropping](https://cloud.githubusercontent.com/assets/14261304/24588232/2d6c2edc-17e2-11e7-9397-28ff95f3eb92.png) | ![cropped](https://cloud.githubusercontent.com/assets/14261304/24588233/2d70df54-17e2-11e7-99ba-eb51d832c8fd.png) |

**Would you like to work on the issue?**

I have an issue assigned myself. So one can take this if you want! :)

**Comment by vinaysajjanapu** [comment]
working on it

**Comment by vinaysajjanapu** [comment]
@CloudyPadmal I got the issue. Check at line 196 of cropimage class. There the image is getting downsampled by 4.

A scaledbitmap is being created only with those images whose dimensions after downsampling are not even. But this should be performed even if the dimensions are even.

if the sample size is reduced, the quality should increase. 

Try these changes and check if there is any improvement.

I could have sent a PR but there is some problem with my fork.
