### ISSUE TITLE
Update the link to gh pages of Phimp.me in the read me.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2973]
**Describe the chore**
In the readme, the link to the gh pages of phimpme is given as "https://phimp.me". But the link is actually "fossasia.github.io/phimpme-android". This should be corrected in the gh pages section under branch policy in the readme. 

**Would you like to work on the issue?**

- [ ] Yes
- [X] No
- Other:

**Comment by Sid911** [comment]
@yashk2000 I actually fixed that in https://github.com/fossasia/phimpme-android/pull/2971 but I am working on #2974 so I will add those as well when I give a pr
