### ISSUE TITLE
Details for edit images are not being saved

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#298]
**Actual Behaviour**

When I try to give a name to an image I've edited, it's not saving with the name I've given. Instead it saved as a tmp_115151515.jpg something like that! This is the same for Lat Lon attributes as well.

**Expected Behaviour**

Image should be saved with the name it was given by the user

**Steps to reproduce it**

1. Open app
2. Select an image
3. Click on the FAB icon and click on _Edit_ button
4. Edit the image with a filter
5. Give a name
6. Click _OK_ and save image
7. Go to gallery and open the image again
8. Click on FAB icon and select the _Info_ button
9. Observe the name it has

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

This one is open to volunteers! :)

**Comment by madhavrathi** [comment]
@CloudyPadmal I would like to work on this.

**Comment by CloudyPadmal** [comment]
Sure @madhavrathi ! Go ahead! :)

**Comment by amitiwary999** [comment]
@madhavrathi are you working on this? can i work on this issue?

**Comment by madhavrathi** [comment]
@amitiwary999 I am figuring it out yet, if you have a solution, please go ahead

**Comment by vinaysajjanapu** [comment]
@madhavrathi @amitiwary999 Have you guys fixed this? if not I shall try.
