### ISSUE TITLE
Image Compression Not Working

### ISSUE THREAD

**Issue by Preetesh21** [fossasia/phimpme-android#2985]
**Describe the bug**

The image compression feature is not working as it's not providing a brand new image but just an empty folder.

**To Reproduce**
1. Go to 'app '
2. Click on 'any image'
3. Scroll down to 'compress image'

**Expected behavior**

I would expect the app to create a new compressed image as well save the original one in its place

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |< [ Samsung A20 ]|
|Android Version|< [ Oreo 8.1]    |

**Additional context**

**Would you like to work on the issue?**

- No

**Comment by ankushmundhra** [comment]
@Preetesh21 Can i work on this issue?
