### ISSUE TITLE
Application Crashes On Start

### ISSUE THREAD

**Issue by charlietharas** [fossasia/phimpme-android#2988]
**Describe the bug**
Upon pressing the application icon to start the app after installing it, the application window does not open Android opens a window "Phimp.me keeps stopping" and offers the user options to fix this issue.

**To Reproduce**

**Expected behavior**
The app was expected to open successfully to its homescreen.

**Logs**
Unavailable.

**Screenshots**
![Screenshot_20200120-105201](https://user-images.githubusercontent.com/55163594/72740351-83fe9980-3b73-11ea-88c6-d196190efaa3.png)

**Smartphone Info:**
Device: Google Pixel 4
Android Version: 10, Security Patch level 12/5/19, Play System Update 11/30/19

**Additional context**
Filing this issue as per Google Code-In 2019's task.

**Would you like to work on the issue?**
- I am unable to work on this issue

**Comment by codedsun** [comment]
Same issues #2927 Please refrain from opening multiple issues

**Comment by codedsun** [comment]
@iamareebjamal - Close this

**Comment by charlietharas** [comment]
Will comment on other issue to indicate it has been seen somewhere else.
Apologies.
