### ISSUE TITLE
Should we modify the design along with the theme

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#30]
The app currently uses a dark theme, used in older versions of android can we go for a complete make over  in design.

**Comment by mariobehling** [comment]
Sure, go ahead. A new light material design theme would be awesome!

**Comment by Abhi2424shek** [comment]
Sure then I would give a PR but it would take some time approx 15 days, I know that's long but national examinations are approaching sir so please give me some time for it! (That will be done not as part of GCI)

**Comment by dynamitechetan** [comment]
I would like to work on this.

**Comment by Abhi2424shek** [comment]
Go ahead @dynamitechetan

**Comment by haroonrashid235** [comment]
For those working on material design, what approach you guys are using?

**Comment by haroonrashid235** [comment]
I was looking to add a styles.xml in res/values to define UI styles for app

**Comment by dynamitechetan** [comment]
Yes. I have added a styles.xml file but not pushed it yet. 
Probably tomorrow I will do it.

**Comment by haroonrashid235** [comment]
@dynamitechetan Can i look at the work you have done so far?Maybe a screenshot?

**Comment by dynamitechetan** [comment]
https://cloud.githubusercontent.com/assets/14369357/23582013/b490fe68-0146-11e7-836e-cf27d5202232.png
<img scr="https://cloud.githubusercontent.com/assets/14369357/23582013/b490fe68-0146-11e7-836e-cf27d5202232.png" width="380px">

**Comment by Abhi2424shek** [comment]
@dynamitechetan is it finished? I think most layouts have been changed to comply.

**Comment by dynamitechetan** [comment]
yes. Most layouts have been changed.

**Comment by Abhi2424shek** [comment]
Can you please check which all are needed @dynamitechetan

**Comment by dynamitechetan** [comment]
image editing activities need some improvements, rest looks good to me.

**Comment by Abhi2424shek** [comment]
@pa1pal any opinions?

**Comment by pa1pal** [comment]
Which PR are you referencing here?

**Comment by Abhi2424shek** [comment]
It's the entire app's design which is to be evaluated @pa1pal, what do you think, can we safely close this one or should we go for improvements in design in any other areas? @pa1pal

**Comment by pa1pal** [comment]
if @dynamitechetan already has done some work on this, so we can have a look and merge it.

**Comment by dynamitechetan** [comment]
I did most of it and its already merged. @pa1pal I want you to look at the app now and check if anything is left. I think editing Image activities can be made better rest all things are done.

**Comment by pa1pal** [comment]
Yes I was thinking the same. The editing Image part has mismatch with the theme.
Any other update regarding this will be updated here only.
