### ISSUE TITLE
Create fdroid build variant of the app

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#301]
**Actual Behaviour**

Currently the mapfragment is the google play maps.

**Expected Behaviour**

There should be an alternate build variant of the app containing fdroid map to be able to submit the app into the fdroid playstore just like the FOSSASIA open-event-android.

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by dynamitechetan** [comment]
I think this app is not ready to be published on any app store.

**Comment by pa1pal** [comment]
agree with @dynamitechetan.
@rohanagarwal94 we will definitely do this, but before this we need to add a lot of feature. Right now the app is no near to release.

**Comment by mariobehling** [comment]
We should get on fdroid now.

**Comment by mariobehling** [comment]
Duplicate with https://github.com/fossasia/phimpme-android/issues/301
