### ISSUE TITLE
Switch not visible properly

### ISSUE THREAD

**Issue by AjayThakur12** [fossasia/phimpme-android#3017]
**Describe the bug**
Switch not visible properly when user  is in Dark AMOLED basic theme

**To Reproduce**
1. Go to  Setting
2. Click on Basic Theme
3. select Dark AMOLED 
3. Go to Accounts
4. See switch not visible properly if  switch is in off state

**Expected behavior**
User should able to see whether switch is off or on properly

**Screenshots**

![Screenshot 2020-02-15 at 2 31 20 PM](https://user-images.githubusercontent.com/29337604/74585174-dd85a700-4fff-11ea-8e83-457c2e227164.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Pixel 2|
|Android Version| 7.1 |

**Would you like to work on the issue?**

- [ ✓ ] Yes
- [ ] No
- Other:

**Comment by ArpitShukIa** [comment]
Why has this issue been reopened? The PR was once closed but opened again. I would like to work on this.
