### ISSUE TITLE
The filter layout should be of different colour.

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#303]
**Actual Behaviour**

Right now filter layout background colour is same as the background. Due to the transparency of icon, some icon is difficult to see.

**Expected Behaviour**

filter layout background colour should be of different colour.

**Steps to reproduce it**

Open image and click on edit from fab buttons. 

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.![screenshot_2017-04-04-00-33-06-152_vn mbm phimp me](https://cloud.githubusercontent.com/assets/9361754/24626265/5cbc77d6-18ce-11e7-9a08-d1847fd2fcfb.png)

**Would you like to work on the issue?**

Yes, Please suggest which colour should be used in background of filter layout.

**Comment by Abhi2424shek** [comment]
We will first move to a single edit activity and then add this. Open when needed. Is'nt that fine :)
