### ISSUE TITLE
Pixel 2 XL Android 10 (Q) Crashes

### ISSUE THREAD

**Issue by snajdovski** [fossasia/phimpme-android#3036]
Instructions to reproduce crash:
1)Download from Playstore
2)Try to open it
3)Crash

**Comment by ErunamoJAZZ** [comment]
Same thing with a Xiaomi A2 with android one.

**Comment by codeitram** [comment]
Hahah I think now it is fixed !

**Comment by ErunamoJAZZ** [comment]
https://github.com/fossasia/phimpme-android/issues/2927 (looks like that was the main issue)

Thanks for take care of this! :heart:

**Comment by ammgws** [comment]
Is this not broken for a lot of people? I ended up uninstalling the Play Store version and manually installing the latest dev apk in order to be able to use this again.
