### ISSUE TITLE
Update uCrop to 2.x

### ISSUE THREAD

**Issue by TacoTheDank** [fossasia/phimpme-android#3049]
**Describe the chore**

https://github.com/fossasia/phimpme-android/blob/development/app/build.gradle#L172
Update uCrop to 2.x. (https://github.com/fossasia/phimpme-android/pull/3023 I guarantee isn't the way it's supposed to be done)

**Would you like to work on the issue?**

No, sorry.

Notes to help:
https://github.com/Yalantis/uCrop/blob/develop/README.md#changelog (Not much help tbh, you'll probably just have to re-implement it from scratch)

**Comment by iamvs-2002** [comment]
Hey! May I look into this issue? 
Also could you please explain what exactly do you mean by 2.x? Does that refer to zoom in?

**Comment by TacoTheDank** [comment]
@iamvs-2002 It refers to the major version upgrade from 1.y.z to 2.y.z (where y and z are minor and patch versions, respectively).

**Comment by iamvs-2002** [comment]
> @iamvs-2002 It refers to the major version upgrade from 1.y.z to 2.y.z (where y and z are minor and patch versions, respectively).

Okay! Thanks.

**Comment by TacoTheDank** [comment]
This has been done. Correctly? IDK.
