### ISSUE TITLE
Accounts option on two screens (Upload and Settings)

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#305]
**Actual Behaviour**

There is Accounts option to show connected accounts on upload Screen with add accounts button and on settings screen there is Accounts option to show connected accounts.
**Expected Behaviour**

It should only be on setting and it should be like the way it is currently on upload screen. Add accounts button and Showing connected accounts.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.
![17797598_779864965497946_826588412_o](https://cloud.githubusercontent.com/assets/25840461/24630711/28d664fa-18d7-11e7-8a9e-3424584d68aa.png)

![17522258_779864962164613_262307701_o](https://cloud.githubusercontent.com/assets/25840461/24630735/3ba99a2a-18d7-11e7-87a7-96632ba9c2f1.png)

**Would you like to work on the issue?**

Yes as I think it would be good design practice to not repeat it in to activities and only placing it in settings and show connected accounts in settings.

**Comment by CloudyPadmal** [comment]
Hello @AliAyub007 !  I think the one in upload is to select to which account we want to upload the images in the list and the one in the settings is to add an account into the app. What do you think? :)

**Comment by AliAyub007** [comment]
@CloudyPadmal  Shouldn't it be in a way that all accounts will be connected and shown in settings  and user can select which account should be linked to upload photos and when someone click the upload images should be uploaded to linked accounts.

**Comment by Abhi2424shek** [comment]
That's whats happening now @AliAyub007 isn't it?

**Comment by AliAyub007** [comment]
yes @Abhi2424shek  I was just asking whether it should be in upload and settings both or it can be in settings only with the way it is working right now?

**Comment by Abhi2424shek** [comment]
I think the current way is fine. Is'nt it?

**Comment by AliAyub007** [comment]
I was just thinking it in a redundant way and good user practice but If you think it's fine then It is good to me too.

**Comment by pa1pal** [comment]
@AliAyub007 The upload screen shows all the connected accounts with checkboxes. So when user added the images can mark the accounts in which he/she wants to upload.
In settings it is to remove the connection.
I think it clears your confusion.
