### ISSUE TITLE
App flow causes lags. Move time consuming tasks to splashscreen.

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#307]
**Actual Behaviour**

Currently, there are different places where the cursor is reiterating over the mediastore class which is responsible for the lag in the application.

**Expected Behaviour**

I suggest to move all time consuming tasks to the splashscreen activity and save the result for future reference in the app.

**Would you like to work on the issue?**

Yes, its a core issue. I would like to work on it.

**Comment by Abhi2424shek** [comment]
OK seems cool.
