### ISSUE TITLE
Account Activity's RecyclerView.OnItemTouchListener not working

### ISSUE THREAD

**Issue by pranoppal** [fossasia/phimpme-android#3088]
**Describe the bug**
Touch on any of the Social platforms are not working.
I debugged the application and found the problem in onInterceptTouchEvent function in RecyclerItemClickListner class

**To Reproduce**

|               | |
|---------------|-|
|Device         |Nokia 8.1|
|Android Version| Android 10
![ezgif com-gif-maker](https://user-images.githubusercontent.com/39507443/95017527-6fb5ea80-0677-11eb-9ddc-f133f853aea9.gif)

|

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by nileshteji** [comment]
@pranoppal Hello.i Think this is not a bug .it is actually telling us which api is enabled in the application .For more information you can check the setup guidelines for this project

**Comment by pranoppal** [comment]
Hello @nileshteji sorry for the late reply,
Yes, I agree that it is telling which api is enabled. 
But if I click on any api then I should be able to login to the corresponding website, but the touch listener is not working and no action is taking place.
Even I'm having this issue with play store build also.

**Comment by nileshteji** [comment]
@pranoppal I think you are misunderstanding for the API to enable you to have to enter the API key in the application. Check the Setup Guide. Correct me if i am wrong.Thank you
