### ISSUE TITLE
CONTRIBUTING.md link broken in README.md

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/phimpme-android#315]
**Actual Behaviour**
Currently in README.md, the  contributing guide's link is broken. Also, the link should point to parent repo file instead of forked repo file. 
`[code of conduct]((https://github.com/jsroyal/phimpme-android/blob/development/CONTRIBUTING.md))`

**Expected Behaviour**
`[code of conduct](https://github.com/fossasia/phimpme-android/blob/development/CONTRIBUTING.md)`

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
Ok seems simple.
