### ISSUE TITLE
Selected Images in main gallery cannot be uploaded to upload list

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#318]
**Actual Behaviour**

If we select images in main screen multiple images cannot be uploaded to upload list.

**Expected Behaviour**

There should be an upload button also with delete option when you select multiple images.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![17820041_781557941995315_906642191_o](https://cloud.githubusercontent.com/assets/25840461/24754504/282e97aa-1af0-11e7-989b-f99e82223bc4.png)

**Would you like to work on the issue?**

I have assigned myself an other issue so anyone willing can work on it.

**Comment by mohitmanuja** [comment]
Okay, I will work on it.

**Comment by AliAyub007** [comment]
Sure @mohitmanuja  👍
