### ISSUE TITLE
Hide or show local photos Settings not getting saved upon closing app

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/phimpme-android#326]
**Actual Behaviour**

At present, the app does not preserve the ' hide or show photos settings ' state in which it was closed. By default when the app opens it shows local photos. 

**Expected Behaviour**
For the first run, it should show local photos, after it should show as per user's setting.

**Steps to reproduce it**

1. Uncheck the hide or show local photos checkBox
2. Close and restart the app.
3. Check if the state is maintained?

**Would you like to work on the issue?**

Yes, it's a simple issue, I would like to resolve it.
I doubt if it is intentional?

**Comment by Abhi2424shek** [comment]
Please do so
