### ISSUE TITLE
Google Play version does not open

### ISSUE THREAD

**Issue by RiqueFR** [fossasia/phimpme-android#3285]
The Google Play version does not open on my phone. When I try to open, it shows the logo, but do not proceed to the app.

**To Reproduce**
1. Download the app from the Play store
2. Open it

Expect the app to open

No logs

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Xiaomi Mi A2|
|Android Version| Android 10  |

**Would you like to work on the issue?**

- [ ] Yes
- [x ] No
- Other: I can try to test, but can't help to fix

**Comment by AadeshPatil** [comment]
Hey, is it still open ?
