### ISSUE TITLE
App crashes on pressing the back button.

### ISSUE THREAD

**Issue by neelanshsahai** [fossasia/phimpme-android#329]
**Actual Behaviour**
When on the main screen, app crashes on pressing the Back Button.

**Expected Behaviour**
on pressing the back button either the app should ask that are you sure to exit or should move to a home page.

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by Abhi2424shek** [comment]
OK please work on it if you can @neelanshsahai

**Comment by vinaysajjanapu** [comment]
@neelanshsahai which page do you mean by main screen?
I checked almost all pages and I don't find this error anywhere and the confirmation dialog has already been implemented.
Can you attach logcat for this issue?

**Comment by CloudyPadmal** [comment]
I guess it's fixed already as @vinaysajjanapu mentioning! :)

**Comment by Abhi2424shek** [comment]
I am not too seeing the bug, but you may work on it if you have it (please do try updating your fork)

**Comment by Abhi2424shek** [comment]
Can someone close this please, it seems not there now. I think I lost write access somehow, @pa1pal consider closing this pls?

**Comment by pa1pal** [comment]
closing. As already fixed.
