### ISSUE TITLE
Tab Transitions

### ISSUE THREAD

**Issue by neelanshsahai** [fossasia/phimpme-android#330]
**Actual Behaviour**
To Jump to the settings tab from the upload tab, the user has to click on the Settings Tab

**Expected Behaviour**
Swiping anywhere in the screen should switch between the tabs.

**Would you like to work on the issue?**
Yes, i would like to work on it.

**Comment by Abhi2424shek** [comment]
That's against the guidelines for the bottom navigation bar.
