### ISSUE TITLE
Loading Images from the Gallery

### ISSUE THREAD

**Issue by neelanshsahai** [fossasia/phimpme-android#331]
**Actual Behaviour**
Every time after a particular amount of images are loaded the user has to press the '+' Button for loading more images.

**Expected Behaviour**
Instead of pressing the '+' button again and again we can use a Loading Scroll View which on scrolling to the bottom of the list will automatically start loading more Images. In this manner the first screen of the app will be much more convenient.

**Would you like to work on the issue?**
Yes, I'd like to work on this Issue.

**Comment by CloudyPadmal** [comment]
Hello @neelanshsahai! This feature is already implemented by a recent PR! :) It's the development branch which has all the updated features!

**Comment by Abhi2424shek** [comment]
Already solved issue.
