### ISSUE TITLE
Image deletion in main gallery doesn't reflect in upload image list

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#332]
**Actual Behaviour**

I've selected a few images from the main gallery and clicked on upload menu button to add them to upload images list. Then I've deleted them. The image name and an entry is available in the upload image list. If I try to open it from there it says cannot load image! 

**Expected Behaviour**

When I delete an image from the main gallery, that image has to be removed from the upload image list as well.

**Steps to reproduce it**

1. Open app
2. Go to main gallery 
3. Long click on one image and select it
4. Click upload menu icon and add it to upload list
5. Delete the same image
6. Go to upload view
7. Click on the image and observe 

**LogCat for the issue**

> Not available 

**Screenshots of the issue**

![screenshot_2017-04-11-18-53-42](https://cloud.githubusercontent.com/assets/14261304/24911384/5ae67d2e-1ee8-11e7-8395-f5b64b2d621c.png)

**Would you like to work on the issue?**

Yes! :)

**Comment by Abhi2424shek** [comment]
Yes please do work on it.
