### ISSUE TITLE
Not enough touch space for Camera feature buttons

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#335]
**Actual Behaviour**

The existing _Switch Camera_, _Flash_ and _Grid_ buttons are stuffed and the space is inadequate! 

**Expected Behaviour**

According to Material Design Guidelines, there has to be a touch space like 48dp x 48dp for interactions

**Steps to reproduce it**

1. Open app
2. Go to _Camera_ and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![device-2017-04-12-164033](https://cloud.githubusercontent.com/assets/14261304/24955394/df8b751c-1fa0-11e7-857f-d6459a5ccf6c.png)

**Would you like to work on the issue?**

Yes :)

**Comment by AliAyub007** [comment]
@CloudyPadmal I suggest to make icons of same size too as flash icon is bigger than others.

**Comment by CloudyPadmal** [comment]
@AliAyub007 exactly! :metal:
