### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by Laxmi1722** [fossasia/phimpme-android#3356]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by abishekvashok** [comment]
Hey please fill in more context to reopen this issue.
