### ISSUE TITLE
Implementation of Instagram like timeline feature

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#337]
As most of the photo editing app in the current market, they have their own page(aka Timeline or newsfeed) to share their photos to the world. 

**Expected Behaviour**

Implementation of the Timeline on the app can enable the users to share their edited photos directly. All the uploaded photos will be visible on a card by implementing CardView.  This page will consist of the photos which are uploaded by the users and is made public for other users to view it. 

**Steps to reproduce it**

1. Connect the app to Firebase to store all the phots.
2. Implement the CardView on a new activity. 
3. Get all the data from Firebase to the load it on the CardView and display it to the users with the tags of the photo. 

**Would you like to work on the issue?**

Yes, This also includes in my GSOC proposal. I would like to start working on it as a head start.

**Comment by dynamitechetan** [comment]
this is a really big task. you have to implement login and everything. Also firebase storage is paid after some limit.

**Comment by vinaysajjanapu** [comment]
@Subhankar29 do you think this feature is really necessary in the app? just asking.
As phimpme is an image editing app, it would be better if we first focus on implementing and refining features for editing the pictures and sharing them on already available platforms. After implementing these features we may focus on this. This is my view. 
@mariobehling what do you think?

**Comment by Subhankar29** [comment]
Yes. I agree. This is not an initial step to take. I might work on it for gsoc project in the coming days.

**Comment by CloudyPadmal** [comment]
@Subhankar29 would it clash with implementations by other developers? :thinking:

**Comment by Subhankar29** [comment]
That we have to discuss after we go through the main features of the app.
