### ISSUE TITLE
No need of Load More button in main Gallery

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#338]
**Actual Behaviour**

There is load more button in main gallery view which was used to load more photos into grid view. Now you can scroll pictures till end without loading more.

**Expected Behaviour**

If it should remain in current state i.e showing all images in scroll view without any need of load more then load more button should be removed.

**Screenshots of the issue**

![17902842_785496301601479_1017654524_o](https://cloud.githubusercontent.com/assets/25840461/24976094/8e46006e-1fe1-11e7-8929-099c9274de84.png)

**Would you like to work on the issue?**

Yes if it is recommended.

**Comment by Abhi2424shek** [comment]
Yes please do so, @AliAyub007
