### ISSUE TITLE
Title of picture is not updated in camera section

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#342]
**Actual Behaviour**

After taking pic if user change title of pic it is not get updated.

**Expected Behaviour**

Title of pic should get updated

**Steps to reproduce it**

1.Take a picture.
2. Change title of picture .
3. click pic and check info from info fab button.
4. you can find that title is not updated.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by madhavrathi** [comment]
@amitiwary999  It is already reported https://github.com/fossasia/phimpme-android/issues/298
Please close this issue and comment there and we can work on this.

**Comment by amitiwary999** [comment]
@madhavrathi #298 is related to saved images and this issue is about images which is not saved yet.
