### ISSUE TITLE
Camera preview is distorted

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#349]
**Actual Behaviour**

The preview of the camera is distorted.

**Expected Behaviour**

Should be even.

**Steps to reproduce it**

View the preview of an image of circle.

**Screenshots of the issue**

![screenshot_20170414-121522](https://cloud.githubusercontent.com/assets/15368561/25035633/52186bb4-210c-11e7-9d29-7ff9c6ccea3e.png)

**Would you like to work on the issue?**

yes

**Comment by pa1pal** [comment]
The distorted and aspect ration problem was fixed in above PR. 
There is issue with the preview size in some devices.

**Comment by pa1pal** [comment]
@vinaysajjanapu as per the guidelines there should be one PR for one issue. So I am closing this now and open other issue for the same. I assigned this on the milestone.
