### ISSUE TITLE
No size info of image when exif data unavailable

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#353]
**Actual Behaviour**

If an image doesn't have exif data about its size, app shows it as zero. 
My phone doesn't save exif data of a screenshot. Phimpme app shows its size as 0x0 whereas builtin gallery app shows as 1920x1080.

**Expected Behaviour**

Info should be shown even if exif data is unavailable 

**Steps to reproduce it**

Take a screenshot and check its info(if your phone doesn't save exif data of screenshot) or download attached pics and check info.

**Screenshots of the issue**

![screenshot_20170414-145430](https://cloud.githubusercontent.com/assets/15368561/25039911/e4863d52-2123-11e7-959b-b378cb891ab1.png)
![screenshot_20170414-145044](https://cloud.githubusercontent.com/assets/15368561/25039914/e79203a0-2123-11e7-8c36-f55c75a9d6fb.png)

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
OK pls work on it.
