### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#358]
**Actual Behaviour**

The communication channel mentioned is still a slack channel.

**Expected Behaviour**

Update it to the gitter link. - https://gitter.im/fossasia/phimpme

**Would you like to work on the issue?**

No, I want a beginner to solve this.

**Comment by pa1pal** [comment]
https://github.com/fossasia/phimpme-android/commit/517169bd8b3b59ebacb9f2c96a767e1139a7a1d6
