### ISSUE TITLE
Zoom in camera is little buggy

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#360]
**Actual Behaviour**

- App crashes when you try to zoom in more than max zoom(if condition is not proper)
- Zoom functionality is not proper when more than 2 fingers are placed on screen.

**Expected Behaviour**

Zoom should be limited to max zoom
camera should zoom with only 2 fingers. not more than 2.

**Would you like to work on the issue?**

yes

**Comment by amitiwary999** [comment]
@vinaysajjanapu can you provide the step to check this error because it is working fine in my case.

**Comment by vinaysajjanapu** [comment]
Consider a case where maxzoom is 99 and current zoom 96. 'If condition' returns true so zoom will be incremented and it causes a crash when setting parameters with zoom more than maxzoom. 
It is working fine in your case because maxzoom of your phone's camera might be a multiple of 6.

The second issue
When I swipe with 3 or 4 fingers, sometimes it is zooming in and sometimes zooming out. So I thought zoom should be controlled only with two fingers.

Have a look at changes in PR, you'll understand clearly.
