### ISSUE TITLE
camera switch button not working properly

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#368]
**Actual Behaviour**

camera switch automatically from back to front and vice-verss

**Expected Behaviour**

It should not switch automatically

**Steps to reproduce it**

click on camera button at bottombar.
Now click switch button.
After that press any button at bottom bar.
Again click camera button. You will find that camera switches automatically.
now click a picture and discard it. You will find that camera switched again

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
I am not having any such issues

**Comment by amitiwary999** [comment]
@Abhi2424shek follow the step properly.
1. Switch from back camera to front camera.
2. Then click on any other button at bottom bar.
3.Again click on camera button. You will find that camera automatically switched to back camera.
4. Click a pic and discard it.

**Comment by heysadboy** [comment]
Yes, and status bar appears again too @amitiwary999 .
