### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/phimpme-android#37]
on importing the project to android studio, project build fails with the following error message "Gradle sync failed: Failed to find target with hash string 'Google Inc.:Google APIs:23' in: C:\Users\user\AppData\Local\Android\Sdk".

changing the compileSdkVersion to 24 in build.gradle file in app folder does the work. 

I can pr fr this ?

**Comment by Abhi2424shek** [comment]
I am sorry but isn't this the duplicate of #36? @DravitLochan

**Comment by DravitLochan** [comment]
my bad. i did not go down so many comments and title just talked about maps library.

**Comment by Abhi2424shek** [comment]
It's ok
