### ISSUE TITLE
Status bar color

### ISSUE THREAD

**Issue by heysadboy** [fossasia/phimpme-android#371]
**Actual Behaviour**

The status bar color must be a shade darker than title bar color but it is currently grey, I guess due to that theme management.

![screenshot_2017-04-18-22-43-17](https://cloud.githubusercontent.com/assets/22588035/25144227/b630d1be-248a-11e7-9c19-cbe1847ef3e9.png)

**Expected Behaviour**

It should be a darker shade of blue to follow material aesthetic.

Yes, I would like to work on it or you can tell if you want to solve this.

**Comment by Abhi2424shek** [comment]
@heysadboy is it compulsory to do so, currently we use blue as primary and grey as the secondary colour respectively and it looks good, doesn't it?

**Comment by heysadboy** [comment]
@Abhi2424shek Whatever you suggest. It is not compulsory though.

**Comment by Abhi2424shek** [comment]
Opening discussion, what are the opinions?

**Comment by pa1pal** [comment]
in my opinion this color `#0288D1` for status bar
and this `#03A9F4` as primary color

**Comment by AliAyub007** [comment]
I think it should be gray as menu on navigation bar is gray so as all buttons, icons and writing.  Giving it a darker shade of primary color is fine too but I think we should go for gray.
