### ISSUE TITLE
Front Camera takes lot of time to snap photo when flash is on

### ISSUE THREAD

**Issue by shivam21** [fossasia/phimpme-android#374]
**Actual Behaviour**

Its taking lot of time to snap the photo when flash is on.

**Expected Behaviour**

It should snap photo immediately.

**Steps to reproduce it**

Turn off flash as soon as the camera is switched to the front.

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by anantprsd5** [comment]
I would like to work on this due to inactivity of @shivam21 from many days.
