### ISSUE TITLE
Adding Timer to Camera 

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#376]
**Actual Behaviour**

There is no Timer option in Camera 

**Expected Behaviour**

There should be a timer in camera if someone wants to start timer for picture. 

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes I would like to work on it if suggested.

**Comment by Abhi2424shek** [comment]
Seems good
