### ISSUE TITLE
Use an Open Source Library for loading images and displaying them

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/phimpme-android#385]
**Actual Behaviour**

Currently the app takes up a lot of memory while loading images from local storage and displaying them.

**Expected Behaviour**

I believe if we use an open source library it will help in memory optimization of the app.

**Steps to reproduce it**

we have many options such as Glide(Recommended by Google), Fresco, Image loader and Picasso.
A comparison between them can be looked up [here](http://stackoverflow.com/questions/29363321/picasso-v-s-imageloader-v-s-fresco-vs-glide).

**Would you like to work on the issue?**

Yes, any suggestions are appreciated. @Abhi2424shek @pa1pal @mariobehling 
Thanks

**Comment by Abhi2424shek** [comment]
@madhavrathi IMO, it will be much more better if we could take inspiration from these libraries and then improve ours'. It would also avoid us from using more and more dependencies and become self sufficient. what do you think?

**Comment by madhavrathi** [comment]
@Abhi2424shek I believe you are right. In a production level application, dependencies should be minimum, I guess this issue should be closed.
