### ISSUE TITLE
Upload section contain duplicate photos.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#389]
**Actual Behaviour**

user can add same image two times

**Expected Behaviour**

The uploaded image should not be readded.

**Steps to reproduce it**

1.go to gallery activity, select any image and upload it.
2. Click pn that image and fromfab button click on upload button.
3. go to upload section. You will find that same picture is added two times.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-04-24-02-43-00](https://cloud.githubusercontent.com/assets/14003244/25317852/f0a9e6ec-289e-11e7-8578-2753c917f2ca.png)

**Would you like to work on the issue?**

yes

**Comment by CloudyPadmal** [comment]
Hello @amitiwary999! There was a discussion about this issue once. Having enabled duplicate images, we can edit each one independently! How's your idea about that feature? :)

**Comment by Abhi2424shek** [comment]
Yea @amitiwary999, that's how it's being done, so sorry for you as you have made a PR, I urge you to follow the best practises, i.e, making an issue, getting approval from a contributor, discussing how it would be implemented and then making a PR.

I am closing this one.

**Comment by amitiwary999** [comment]
@CloudyPadmal @Abhi2424shek it is good feature. But why only two times. There should be option to add image in upload section as many time as user want.
