### ISSUE TITLE
Issue with selected images in upload section

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#392]
**Actual Behaviour**

If images are selected and user press back button app is showing dialog box for closing app instead of unselect those images.

**Expected Behaviour**

f images are selected and when user press back button those images should get unselect.

**Steps to reproduce it**

Add images in upload section. Select picture and click back button.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes.

**Comment by pa1pal** [comment]
I agree. It's good you find out that. Go ahead.
