### ISSUE TITLE
How to implement internal APIs / Options for conversation UI and Voice UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#402]
At FOSSASIA we also develop SUSI.AI. What are the options to integrate the apps? Would it be possible that the Android app offers APIs that could be called from a SUSI Android app or something along those lines?

It would be fantastic to have a phimpme app, that could be controlled by a conversation user interface or a voice interface. What are your ideas?

**Comment by pa1pal** [comment]
For integrating some voice commands we can use Google Voice interaction api [Link](https://developers.google.com/voice-actions/interaction/voice-interactions).
We can perform some actions such as clicking of image, selecting upload accounts.
We can use susi as well after making it to trigger some of the voice commands for Phimpme.

**Comment by Subhankar29** [comment]
Yes. Apart from interacting with the camera through voice, we can also access the Phimpme camera activity through google now voice command.
