### ISSUE TITLE
App Crashing 

### ISSUE THREAD

**Issue by abhimanyukumar0007** [fossasia/phimpme-android#403]
**Actual Behaviour**
App crashing when accepted to delete all downloaded images from the app setting.

Please state here what is currently happening.
App is crashing

**Expected Behaviour**
It should delete all downloaded images from the phimpme application folder

State here what the feature should enable the user to do.
It allows the user to empty their gallery

**Steps to reproduce it**
Goto settings press delete downloaded photos and then press accept.

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**
Yes

Please let us know if you can work on it or the issue should be assigned to someone else.
Yes i can work on the following issue.

**Comment by Abhi2424shek** [comment]
It would be better if you could clean the issue template.

**Comment by vinaysajjanapu** [comment]
@abhimanyukumar0007 It is not happening for me.
