### ISSUE TITLE
Camera screen size error

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#408]
**Actual Behaviour**

The camera screen is not taking correct width and size in some devices. It is continuation of #349.

**Expected Behaviour**

Camera screen should take appropriate width and height.

**Steps to reproduce it**

Select the camera in bottom nav bar.

**Screenshots of the issue**
![camera_error](https://cloud.githubusercontent.com/assets/6936968/25773851/a464cbd6-32a2-11e7-977f-f7f8b59dde0d.png)

**Comment by vinaysajjanapu** [comment]
@pa1pal I think I might know the reason for this.
In supportedpreviewsizes of most devices width is large and height is less. eg. 1600x900
I took only this kind of cases into consideration and written the code. 
But after seeing your screenshot, I feel that my assumption is wrong. Can you please check that?

**Comment by pa1pal** [comment]
@vinaysajjanapu sure.
