### ISSUE TITLE
Changing the complete implementation of newGallery fragment

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#419]
**Actual Behaviour**

- [ ] Remove Grid View and add Recycler View in gallery fragment
- [ ] Add staggered grid layout manager
- [ ] Add lazy loading
- [ ] onClick listeners

**Would you like to work on the issue?**
Yes

**Comment by vinaysajjanapu** [comment]
@pa1pal I just changed gridview to recyclerview and added glide for loading images as part of fixing #416. I am checking other lags in gallery now. As I already started I will complete those two today and you may start working on other two tomorrow.

**Comment by pa1pal** [comment]
@vinaysajjanapu okay. 
push the code you added and fix #416. Rest points I will do.

**Comment by vinaysajjanapu** [comment]
yeah sure

**Comment by vinaysajjanapu** [comment]
@pa1pal do you think staggeredGridLayoutManager is necessary? I feel it look proper with normal gridLayoutManager.
