### ISSUE TITLE
compileSdkVersion 'Google Inc.:Google APIs:23' is depreciated

### ISSUE THREAD

**Issue by jsroyal** [fossasia/phimpme-android#42]
Error:Failed to find target with hash string 'Google Inc.:Google APIs:23' in:
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

Solve the issue 
compileSdkVersion 23  instead of compileSdkVersion 'Google Inc.:Google APIs:23'

**Comment by anantprsd5** [comment]
@jsroyal This issue has been fixed and compileSdk has been updated to 25. The working code is there in the development branch which will be moved feature wise to the master.
This issue can be closed now.
Thanks.

**Comment by jsroyal** [comment]
@anantprsd5 Okay .
