### ISSUE TITLE
Thumbnails are blurred

### ISSUE THREAD

**Issue by mohak1712** [fossasia/phimpme-android#426]
**Actual Behaviour**

Thumbnails look blurred due to small size (80 right now)

**Expected Behaviour**

Thumbnails should not be blurred

**Steps to reproduce it**

open the app and look at the thumbnails

**Screenshots of the issue**

![screenshot_20170510-134803](https://cloud.githubusercontent.com/assets/12782512/25890296/9d669dce-358a-11e7-8ad9-5c16fd852d5e.png)

**Would you like to work on the issue?**

Yes

**Comment by vinaysajjanapu** [comment]
@mohak1712 We are planning to have quality preference for user in settings. Currently the size is overrided to 80x80. If it is increased, the image loading may not be fast in all devices.

**Comment by mohak1712** [comment]
@vinaysajjanapu I want to add two things
1.  I don't think any user will compromise on thumbnails clarity.
2. I don't think they would try again and again to get the perfect thumbnail. It might get cumbersome.

what do you think?
