### ISSUE TITLE
Annoying white screen after Splash Screen

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#427]
**Expected Behaviour**

The White screen should not be visible.

**Steps to reproduce it**

Open the app and see after splash screen.

**Screenshots of the issue**

![whatsapp video 2017-05-10 at 3 04 22 pm](https://cloud.githubusercontent.com/assets/9361754/25892682/ba513176-3592-11e7-941e-8e4366c29299.gif)

**Would you like to work on the issue?**

Yes.

**Comment by anantprsd5** [comment]
@mohitmanuja  Wouldn't it be good if we remove the splash screen itself?

**Comment by mohitmanuja** [comment]
@anantprsd5 yes, but actually the white screen is not due to the splash screen, we have to disable the window preview in styles.xml and currently, we are doing nothing in splash screen so we can remove.

**Comment by Abhi2424shek** [comment]
Hey, for this we need to ensure that:

- we don't do any heavy work in onCreate() as doing heavy work could cause problems.

- we set the content view right after the super.onCreate() line.

- enable the windowDisabledPreview setting in styles for *every* theme we will be using.

**Comment by CloudyPadmal** [comment]
Image cursors can be loaded during the splash screen right?

**Comment by vinaysajjanapu** [comment]
@anantprsd5 I don't agree with removing splash screen. As @CloudyPadmal said it would be better if we move some tasks to splash screen
