### ISSUE TITLE
Image tuning features in Edit screen

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#439]
- [x] Crop
- [x] Angle
- [x] Brighness
- [x] Contrast
- [x] Saturation
- [x] Sharpening
- [x] Blur
- [x] Vignette
- [x] Temperature

**Comment by vinaysajjanapu** [comment]
@pa1pal I can work on part of this.

**Comment by Subhankar29** [comment]
@vinaysajjanapu the image editor has most of the features.

**Comment by vinaysajjanapu** [comment]
As the editor has only crop and angle adjustments, I will work on other features.
