### ISSUE TITLE
Camera screen features

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#445]
- [ ] ISO
- [ ] White balance
- [ ] Timer
- [ ] Sound
- [ ] Flash On/Off
- [ ] Exposure/saturation Controls
- [ ] Picture size
- [ ] Camera modes(Night/Cloudy/Daylight)

**Comment by mohitmanuja** [comment]
@pa1pal  Assign me and @anantprsd5 for this.

**Comment by anantprsd5** [comment]
@pa1pal Yes. Will divide the work.
