### ISSUE TITLE
BottomNavigationBar covers FAB in Gallery page

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#473]
**Actual Behaviour**

BottomNavigationBar covers Camera FAB in leafpic.

**Expected Behaviour**

That FAB is redundant, So it has to removed or assigned action other than camera.

**Steps to reproduce it**

In leafpic gallery setting enable FAB button

**Screenshots of the issue**

![screenshot_20170524-011820](https://cloud.githubusercontent.com/assets/15368561/26373397/0cdd6464-401f-11e7-848a-76fa95ece988.png)

**Would you like to work on the issue?**

Yes, but need suggestions first.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Yes, we can remove that
