### ISSUE TITLE
App crashes on opening video

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#474]
**Actual Behaviour**

Currently the video items are shown in the gallery which on being clicked makes the application crash.

**Expected Behaviour**

Since Phimpme is an image application, we can remove the video listings from the gallery or we can pass an intent to start video with different video players available in the phone.

**Steps to reproduce it**

1. Open camera.
2. Record Video.
3. Play it.

**Would you like to work on the issue?**

Yes but I need suggestions in this.
@pa1pal @vinaysajjanapu @mohitmanuja @Subhankar29

**Comment by vinaysajjanapu** [comment]
@anantprsd5 I think we don't need to show any videos in gallery and have to open them.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 I feel we don't need to show any videos in gallery and open them.

**Comment by Subhankar29** [comment]
Passing an intent to show the video is unnecessary as per my opinion.

**Comment by anantprsd5** [comment]
@Subhankar29 @vinaysajjanapu Okay then, I will remove the video listing in the gallery. Thanks.
