### ISSUE TITLE
Behaviour of bottomNavigationBar

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#479]
**Actual Behaviour**

Currently, the bottom navigation bar color is not app primary color.
The black color just above the navigation bar is visible due to extra padding.
Account activity is having different theme.

**Expected Behaviour**

App navigation bar color should always app primary color and padding should be removed. Account Activity should use the same theme.

**Screenshots of the issue**

![screenshot_2017-05-25-00-04-05-675_vn mbm phimp me](https://cloud.githubusercontent.com/assets/9361754/26434622/4bba96da-4127-11e7-9238-52a8fb56a5fe.png)

**Would you like to work on the issue?**
Yes.

**Comment by pa1pal** [comment]
@mohitmanuja also look into the color of `EditImageActivity` it should also same as primary color.

**Comment by mohitmanuja** [comment]
okay @pa1pal, will do that.

**Comment by mohitmanuja** [comment]
@pa1pal I think the edit feature is added as module we should add that as a package like we did for open camera and leafpic. So that we can use common Utilitties.

**Comment by pa1pal** [comment]
@mohitmanuja I created a issue #483 for the same assigned to myself.
