### ISSUE TITLE
Shifting ImageEditingLibrary from module to package

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#483]
**Actual Behaviour**

Currently, `imageEditingLibrary` is added as a separate module. 

**Expected Behaviour**

Shift this into packages as we added `leafpic` and `opencamera` for using common utilities.

**Would you like to work on the issue?**

Yes

**Comment by mohitmanuja** [comment]
@pa1pal Also do the toolbar and bottomnavigation color as appPrimaryColor.
