### ISSUE TITLE
Creating Account manager option in the app

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#494]
**Actual Behaviour**

Currently, the application has no dedicated sharing option.  

**Expected Behaviour**

Integrating image sharing option in the application. Adding account management activity in the application to connect different account in the app. Starting with basic sharing option through facebook.  

**Would you like to work on the issue?**
Yes.

**Comment by pa1pal** [comment]
@the-dagger we are planning to integrate other social network website and self hosted websites such as Wordpress, drupal etc by their respected APIs and SDKs. So user can share image directly using Phimpme app.
There is a separate tab in `bottomNavigationView` named account manager where all account will be linked.
