### ISSUE TITLE
Improving open camera setting

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#495]
**Expected Behaviour**

Right now the open camera setting contains thing about "open camera", donate option. It should be removed.

**Steps to reproduce it**

Open the camera and click on setting.

**Would you like to work on the issue?**

Yes. I think we should shift this setting to navigation bar setting as "camera setting". So there is only one place for all setting.
Need suggestions here.@anantprsd5 @pa1pal @vinaysajjanapu @Subhankar29

**Comment by anantprsd5** [comment]
@mohitmanuja I was also thinking about the same. We should have a common settings for everything.

**Comment by pa1pal** [comment]
@mohitmanuja yes one place for setting is easy to find and operate.

**Comment by Subhankar29** [comment]
@mohitmanuja Yes, Even I agree to this. More user-friendly.

**Comment by vinaysajjanapu** [comment]
I agree with you guys

**Comment by mohitmanuja** [comment]
Okay guys, I will shift camera setting. Thanks.
