### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#50]
We don't have tests currently. Checking that each function works correctly is an integral part in an app development and tests should be used. Currently the project doesnot have any tests and as indicated by codecov the code coverage is currently 0%.While we build the app on Travis and test the changes, it won't be enough, we need to start writing tests.

As a starting point, write junit tests for:

- [ ] ACRAReport.java
- [ ] AddAccountDialogFragment.java
- [ ] BluetoothShareMultipleFile.java
- [ ] CacheStore.java
- [ ] CollectUserData.java

**This should be done after all features start working as they have more priority than this**

**Comment by anantprsd5** [comment]
@Abhi2424shek Shall I work on this issue?

**Comment by Abhi2424shek** [comment]
Sure @anantprsd5 make sure first the code is working then write tests. Split the tests as well, like one junit test for one class file.

**Comment by anantprsd5** [comment]
@Abhi2424shek Sure, working on it.

**Comment by anantprsd5** [comment]
Hi, Someone please take this issue if you like to as I am currently working on issue #162 so I am not able to work on this.
Thanks (:

**Comment by Abhi2424shek** [comment]
Increasing priority as the main functions seems functional.

**Comment by saurabhjn76** [comment]
Hi, may I work on this ?

**Comment by Abhi2424shek** [comment]
Sure @saurabhjn76
