### ISSUE TITLE
Changes necessary in camera 

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#501]
In the current application, camera has 7 buttons on top. 
1)cam-switch 2)video 3)exposure 4)lock exposure 5)other 6)settings 7)recent photos

I feel that
- 2)video and 4)lock exposure are not necessary at all.
- @mohitmanuja removed 6)settings button in PR #498 
- 7)recent photos button is redundant. As phimpme is an image editing application we can show the preview of the image after its capture and give the user options to retake, accept, edit and share.
- It would be comfortable if the exposure slider is always visible on the edge of the screen rather than clicking on 3)exposure button to access exposure adjustment slider

After these changes we can have clean and better camera.

Need suggestions regarding this.
@pa1pal @mohitmanuja @anantprsd5 @Subhankar29

**Comment by anantprsd5** [comment]
1. Agree, video and exposure lock are not necessary.
2. I am working on this issue #490 and now I am opening editImage activity on picture click. In that activity only I can include the option to retake picture if its called from the cameraActivity. I will send the PR by tomorrow.
3. I don't think we should always show the exposure seekbar at the side. It should be visible on a button click.

**Comment by Subhankar29** [comment]
I agree with @anantprsd5 as not many people want to use exposure feature. Rest of it looks good.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Yes, we should remove 2, 4, 7 and exposure should be visible on button click.

**Comment by pa1pal** [comment]
@vinaysajjanapu yes go ahead.
