### ISSUE TITLE
Rotate image feature not working in singleMediaActivity

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#503]
**Actual Behaviour**

It gives a toast of coming soon on being clicked.

**Expected Behaviour**

We can remove this feature as the rotation feature is already there in the edit image or can implement this feature to rotate image in singleMediaActivity.
Need suggestions @mohitmanuja @pa1pal @vinaysajjanapu @subhankar29

**Would you like to work on this issue?**

Yes

**Comment by vinaysajjanapu** [comment]
@anantprsd5 As it is already present in edit image, I too find no necessity of its presence in singleMediaActivity. Yeah we can remove that.
