### ISSUE TITLE
Add contributors.md

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#51]
Adding instructions for contributors is a good way IMO. We can add things like guidelines for new contributors, tutorials on squashing, branching policy, commit message guidelines etc. What do you all say guys?

**Comment by heysadboy** [comment]
Yeah, I think it is a great idea. We should also add some information about the code to avoid conflicts.

**Comment by pa1pal** [comment]
Yes it is good for all. I think creating Wiki would be best for this.

**Comment by heysadboy** [comment]
@pa1pal Should I make one?

**Comment by Abhi2424shek** [comment]
Well wiki's should describe the project while the contributors guide guides the contributors @heysadboy feel free to do so.

**Comment by pa1pal** [comment]
@heysadboy Wiki are not enabled yet in the project. So I requested to owner to change settings. I will notify you when it is up.

**Comment by Abhi2424shek** [comment]
Well can't we have both? Wiki and the contributors guide in the CONTRIBUTING.md it pops up when you make an issue or a PR

**Comment by heysadboy** [comment]
I see @pa1pal, thanks.

**Comment by Abhi2424shek** [comment]
@heysadboy @pa1pal Mario sir has rejected the proposal for the wiki pages, so we need to go on with the contributing.md file.

I have another query for you guys, should we implement good commit message policy? --- This would improve the commit standard and the repo standard.

**Comment by heysadboy** [comment]
@Abhi2424shek I think it is necessary, we should go for it.

**Comment by pa1pal** [comment]
Yes we need to add contributing.md file now.
For the commit message. We can follow the basic guidelines which other fossasia projects follow. Like Open-event android.

**Comment by heysadboy** [comment]
@pa1pal Okay I will send the pull request in a while.
