### ISSUE TITLE
No option to mute the shutter sound

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#511]
**Actual Behaviour**

There is no option to mute the shutter sound, and it sounds on every click.

**Expected Behaviour**

There should be an option to mute the shutter sound in the settings or in the camera UI. Need suggestions on where to put it.

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@anantprsd5  you can put it in top row of popup that appears in camera
