### ISSUE TITLE
Remove video option from menu

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#515]
**Expected Behaviour**

The video option should be removed because we are not showing videos.

**Steps to reproduce it**

Open any image from gallery and tap on menu.

**Screenshots of the issue**

![screenshot_2017-06-02-02-48-38-972_vn mbm phimp me](https://cloud.githubusercontent.com/assets/9361754/26701404/9a2cfee4-473e-11e7-8b85-281aacf05021.png)

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
merged #516
