### ISSUE TITLE
Toggle button to choose between different colour effects

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#525]
**Actual Behaviour**
Currently, we have to go to options choose between different colour modes. For a user to change multiple times between the different colour modes, it will be a tedious process.

**Expected Behaviour**

Add a toggle Button on the camera screen to change between different colour modes. 

**Screenshots of the issue**

![screenshot_2017-06-03-17-45-04-273](https://cloud.githubusercontent.com/assets/17337006/26753489/15b8e798-4885-11e7-852c-377384929d2c.jpeg)

**Would you like to work on the issue?**

Yes

**Comment by Subhankar29** [comment]
@pa1pal, @mohitmanuja, @vinaysajjanapu @anantprsd5 your suggestions?

**Comment by vinaysajjanapu** [comment]
On the screen?

**Comment by Subhankar29** [comment]
Yes. I was thinking on the top right to look clean.

**Comment by Subhankar29** [comment]
or left.

**Comment by anantprsd5** [comment]
@subhankar29 Yes, put that at top left. What to do with the options in popupView then?

**Comment by Subhankar29** [comment]
Let's leave it as it is because of quicker selection for the user to choose a specific effect.
