### ISSUE TITLE
Enhance the home screen

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#55]
As stated in the features the home screen features would need enhancement:
- [ ] Show local captured images
- [ ] Grid view of images

**Comment by CloudyPadmal** [comment]
@Abhi2424shek I'm currently working on the Grid View! :+1:

**Comment by Abhi2424shek** [comment]
Sure @CloudyPadmal

**Comment by rupak0577** [comment]
@Abhi2424shek Can I work on the first issue?

**Comment by pa1pal** [comment]
@rupak0577 The two are related. The local captured photos are showing in Grid View which needs enhancement.
