### ISSUE TITLE
Zoom controls in the camera  

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#560]
**Actual Behaviour**

Right now when we install an app for the first time, the annoying zoom controls is visible.

**Expected Behaviour**

It should not visible and it is redundant because no one uses zoom controls to zoom camera.

**Steps to reproduce it**

Clear data open app click on the camera, on permission check the zoom control will be visible or turn on the visibility of zoom controls from the camera.

**Screenshots of the issue**

![screenshot_2017-06-09-15-20-13-663_com google android packageinstaller](https://user-images.githubusercontent.com/9361754/26970508-45b4bb74-4d27-11e7-9c40-0d58f985f8ed.png)

**Would you like to work on the issue?**

Yes. I think we should remove the zoom controls and seek bar for zoom completely from the app. Need Suggestions @pa1pal @anantprsd5 @vinaysajjanapu @subhankar29

**Comment by anantprsd5** [comment]
@mohitmanuja Yes, as it is of no use, I think we should remove it completely.
