### ISSUE TITLE
Refractor Camera settings

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#568]
**Actual Behaviour**

There are many options in settings which are not used at all. The following are:
1. Video Settings.
2. Almost all the settings in the On screen GUI.

**Expected Behaviour**

These can be removed since it is of no use.

**Steps to reproduce it**

1. Open Settings.
2. Open camera Settings.

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 As you are removing most of the settings, you can try to adjust the layout according to theme. In the current implementation <preference-screen/> is used for showing settings. We can barely modify its UI. @mohitmanuja what do you say? 

_Sent from my Xiaomi Redmi Note 4X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by anantprsd5** [comment]
@vinaysajjanapu I am not removing most of the settings. Just the video settings option and some controls which were not used under the On Screen GUI. I thought of removing the whole under On Screen GUI but some of them are actually useful I feel and are functioning properly. Check this PR #569  We can still try to change the camera settings layout according to theme but as you said it is difficult with current implementation so it will take time. So we can think about this after the first release in my opinion.
@mohitmanuja @vinaysajjanapu Suggestions?

**Comment by mohitmanuja** [comment]
@vinaysajjanapu @anantprsd5 Yes, I think we can modify it later after the first release.

**Comment by vinaysajjanapu** [comment]
merged #569
