### ISSUE TITLE
Adding Frame Layout on the filter option in Edit Image activity.

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#576]
**Actual Behaviour**

Currently, there is no option to apply frames on the image.  

**Expected Behaviour**

Users can choose to apply different frames from the Edit image activity. These frames will include different types of overlays and frame layouts. 

**Steps to reproduce it**

Add an option of frames on Edit image activity.
Display different types of frames to choose from.

**Would you like to work on the issue?**

Please, go ahead and assign it to yourself.

**Comment by devutsav** [comment]
Can I go ahead with this ? @Subhankar29

**Comment by Subhankar29** [comment]
@devutsav Yes go ahead

**Comment by vinaysajjanapu** [comment]
@devutsav any progress? are you working on it?

**Comment by neelanshsahai** [comment]
@Subhankar29 @vinaysajjanapu sir if no one is working on this issue then I would like to work on this one. So please assign this issue to me

**Comment by Subhankar29** [comment]
@neelanshsahai ok, work on it.
