### ISSUE TITLE
PhotoActivity opens thrice on clicking image in Exposure Bracketing mode

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#577]
**Actual Behaviour**

On taking the picture in Exposure bracketing mode, PhotoActivity opens thrice one above the other as this mode takes three pictures with different exposure values and saves them. 

**Expected Behaviour**

We can directly open singleMediaActivity where the user can directly view the three images on taking photos in Exposure Bracketing mode.

**Steps to reproduce it**

1. Open camera.
2. Select Expo{} mode from pop up camera settings.
3. Take picture.

**Would you like to work on the issue?**

Yes

**Comment by mohitmanuja** [comment]
@anantprsd5 I think we should open PhotoActivity only if it is in single click mode because it is also happening burst mode due to photoactivity. 
So just add a check if it is single shot and non-expo than open PhotoActivity. Need suggestions.

**Comment by anantprsd5** [comment]
@mohitmanuja Yes. I was thinking about the same.
