### ISSUE TITLE
Photos not appearing properly in PhotoActivity

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#588]
**Actual Behaviour**

On taking picure with very low resolutions with camera the photo doesn't fit in the center and half of the image is not visible

**Expected Behaviour**

Clicked image should be fully visible to the user

**Steps to reproduce**

1. Open camera
2. Change resolution to 0.92 or 1.3 mp
3. Click picture

**Screenshots of the issue**

![screenshot_20170613-121136](https://user-images.githubusercontent.com/20367966/27069428-460ccbf8-5032-11e7-8af7-08873ba80fa2.jpg)

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 There is a lot of empty space around the picture. Wouldn't it be better if you scale it to proper size on screen? 
![screenshot_2017-06-14-04-26-19-792_vn mbm phimp me](https://user-images.githubusercontent.com/15368561/27108252-c23e7dac-50b9-11e7-91c5-690b8ccdd1c2.png)
