### ISSUE TITLE
Buttons overlap in share image activity

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#597]
**Actual Behaviour**

Buttons overlaps in low resolution screen device(API 19, 480x800 )

**Expected Behaviour**

Shouldn't overlap

**Steps to reproduce it**

In a device with low screen resolution, edit an image and save it. you will enter share image page.

**Screenshots of the issue**

![screenshot_2017-06-15-22-25-01](https://user-images.githubusercontent.com/15368561/27192863-8145ab10-521a-11e7-9d11-c751ef8466ed.png)

**Would you like to work on the issue?**

yes

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Also improve this UI.
