### ISSUE TITLE
Toggle button in the camera doesn't hide on taking picture

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#598]
**Actual Behaviour**

Just like other buttons of the application, toggle button should hide itself on clicking the take picture button.

**Expected Behaviour**

1. Hide the button while taking the photo.
2. Remove the pop up menu options for photo effects.
3. Add showcase view to show toggle button functionality.
4. Add reset function on long pressing the toggle button.

**Steps to reproduce it**

1. Open camera.
2. Take photo 

**Would you like to work on the issue?**

Yes

**Comment by mohitmanuja** [comment]
@anantprsd5 I think we should remove this button as well as effects from the popup. @pa1pal @vinaysajjanapu @Subhankar29 @anantprsd5. Because we have better effects in our edit activity.
Need suggestions.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 ok that buttons should be hidden during photo capture.

@mohitmanuja I don't think we have to remove that button. Most people (including me) tend to use live filters(if they are good). So we will keep that button as it is and change the live filter types later on. 
We can remove that list of effects in popup as it is redundant.

**Comment by anantprsd5** [comment]
@vinaysajjanapu @mohitmanuja If we are keeping the toggle button then we also have to keep the pop up menu options so that user can cancel any effects easily or else they have to press the toggle button 14-15 times to return to normal mode.

**Comment by Subhankar29** [comment]
@mohitmanuja Even I think we should keep them. We can always improvise the effects. Plus user will know the look of the photo before clicking it.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 we can reset filter when filter button in long pressed.

**Comment by anantprsd5** [comment]
@vinaysajjanapu But how will the user know that effects will be reset on long press. I feel it is more user friendly their in the pop up settings. Suggestions?

**Comment by vinaysajjanapu** [comment]
@anantprsd5 that's not an issue. we can show some instructions when the user first time interacts with that button. I've seen this kind of method in some paid camera apps.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Yes, okay yes we can use good effects later on.
@anantprsd5 We can use Showcase to highlight the instruction when user will install our app.
I think we should include a showcase for the whole app. 
Example : https://github.com/amlcurran/ShowcaseView

**Comment by anantprsd5** [comment]
@mohitmanuja @vinaysajjanapu Okay then. I will remove the pop up options for all the effects and will include showcase view to show the toggle button functionality. Thanks for the link @mohitmanuja .

**Comment by mohitmanuja** [comment]
@anantprsd5 Try to find more attractive showcase or try MaterialDesginShowcase. Choose which looks best among them.
