### ISSUE TITLE
Choose image from other app is not working

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#599]
**Actual Behaviour**
The image choosing option is not working.

**Steps to reproduce it**

Open any app. i.e Gmail -> compose mail -> insert file -> choose image -> choose phimpme.

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@mohitmanuja Why don't we remove that?

**Comment by mohitmanuja** [comment]
@ I don't think so because it also includes gallery so we should keep it. Suggestions
