### ISSUE TITLE
Travis Build Failing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#6]
Error as below:

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'Google Inc.:Google APIs:23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

**Comment by pa1pal** [comment]
The reason is travis never work with Google APIs SDK version in normal way.
To do so I added **addon-google_apis-google-$ANDROID_API_LEVEL** Level in our case is 23.

After that there is alot of other exceptions as well.
This #7 PR in reference to all these.
