### ISSUE TITLE
Adding undo Button in Edit Image Activity. 

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#603]
**Actual Behaviour**

Currently, once the image is edited there is no way to get the initial image without leaving the activity. 

**Expected Behaviour**

Adding an undo button. On click of the undo button, the original image will appear

**Steps to reproduce it**

Adding Undo Button in Edit Image Activity. 
Setting Onclick for it. 

**Would you like to work on the issue?**

Yes.

**Comment by pa1pal** [comment]
@Subhankar29 I am taking this issue.

**Comment by pa1pal** [comment]
#633
