### ISSUE TITLE
Share activity opens even if you donot edit the picture

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#604]
**Actual Behaviour**

In editor when you press save&exit button even with original image, share activity is getting opened.

**Expected Behaviour**

Share Activity should open only when you click save&exit for edited image.

**Steps to reproduce it**

Select any image click edit then press save&exit button without doing any edits.

**Would you like to work on the issue?**

yes

**Comment by Subhankar29** [comment]
@vinaysajjanapu It goes in a flow. Like many other apps, it's not necessary to edit the image to share it(although we can share from the gallery). Doing what you discussed will create confusion. Your suggestions

**Comment by pa1pal** [comment]
@vinaysajjanapu in my opinion, I found the flow correct. What if user changes mind to not to edit the image and share. 
Or we can change the flow to show edited image only. And share activity will initiate when explicitly clicked to share.
