### ISSUE TITLE
Face Detection in Camera Activity

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#608]
**Actual Behaviour**

There is no Face Detection in the current camera preview. 

**Expected Behaviour**

Detect face and focus on the face. 

**Steps to reproduce it**

Get the coordinates of the face on the camera. 
Set focus on the specific coordinates. 

**Would you like to work on the issue?**
Yes

**Comment by mohitmanuja** [comment]
@Subhankar29 It's already there. Just check camera settings and turn on the face detection.

**Comment by Subhankar29** [comment]
@mohitmanuja oh, ok. Thanks for the info.
