### ISSUE TITLE
Implement danger with android app previews

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#61]
Travis doesnot check for runtime errors of the app currently, we could implement such a system with danger or maybe a bot account to post the previews of the app by taking screenshots or maybe a simple giff which shows the transition of screens and demonstrates button and function clicks as a comment to a PR via Travis or other CI, this could improve the testing, would result in an increase in overall app quality and there would be new contributors for sure. But it's a bit difficult. 

This is how I suggest a method (I couldn't give a flowchart so I am expressing it as steps):
1. User makes a PR (Already there)
2. Github calls Travis via git hook (Already being done)
3. Travis generates app (Already being done)
4. Travis runs espresso tests (Not being done)
4. After each espresso test we call in a function from a class which would be put into the tests folder, generating screenshots and saving them. (Not being done)
5. Another script would make a comment with this image or we could pass them to danger and danger makes a comment with them on the PR.

What are your opinions?

**Comment by Abhi2424shek** [comment]
Got one more idea, instead of using an API for images we could make use of google espresso. We can call in a class during the test to save the screenshot, thereby getting saved on the cloud. Updated the issue description.

**Comment by Abhi2424shek** [comment]
@mariobehling since @pa1pal has no objections and others are not repon ding whats your opinion?

**Comment by anantprsd5** [comment]
@Abhi2424shek Hey, I think it would be very nice to have this since there is always a chance of developer breaking something due to which app crashes in between. But do we have to use screenshots for this? Can't we just provide the logs for the errors?

**Comment by Abhi2424shek** [comment]
@anantprsd5 this would be given with PRs so that we could have previews of the app.

**Comment by Abhi2424shek** [comment]
Logs could also be used!

**Comment by Abhi2424shek** [comment]
Instead of images, commenting the app itself so that it can be tested manually. We are having the espresso tests toit would be ok.

**Comment by Abhi2424shek** [comment]
I have implemented danger it works. Now needing a bot account, shall I set one up @pa1pal. It's needed to comment the output.

**Comment by Abhi2424shek** [comment]
Creating a bit account named danger bot.
