### ISSUE TITLE
Various options is not working for album

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#610]
**Actual Behaviour**

Install shortcut is not working for an album.

**Expected Behaviour**

- [x] Install Shortcut should be removed.

- [x] Remove unused resources.

**Steps to reproduce it**

Select an album by long press -> click on options -> install shortcut.

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
@pa1pal  @vinaysajjanapu @anantprsd5  @Subhankar29 need suggestions.

**Comment by anantprsd5** [comment]
@mohitmanuja I think we should remove it. I don't find it useful.
