### ISSUE TITLE
Cancel edit button in edit Image Activity.

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#618]
**Actual Behaviour**

Cancel Image button doesn't work if the image is not edited at least once. The image has to be edited at least once for the button to work.

**Expected Behaviour**

If the button is pressed it should go back to SingleMediaActivity irrespective of the image being edited or not. 

**Steps to reproduce it**
->Click edit_cancel on the  Edit image category. 

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@Subhankar29 under **Steps to reproduce it** please mention the steps to check that error not how you are going to fix it
