### ISSUE TITLE
High Brightness toggle Button is not working in Setting

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#619]
**Actual Behaviour**

No effect of High Brightness toggle button when pressed in the setting activity.

**Expected Behaviour**

The brightness should be maximum while viewing a media when the toggle button is pressed on.

**Steps to reproduce it**

setting->under Media Viewer->High Brightness toggle button

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
It is working please check it again.

**Comment by anantprsd5** [comment]
Yes. Its working fine for me too.

**Comment by Subhankar29** [comment]
@mohitmanuja @anantprsd5 I have checked it again. For me, it is working on my Lenovo vibe4(Android version 6) and not in Moto G2(Android Version 6).

**Comment by anantprsd5** [comment]
@subhankar29 yes. Its not working in moto G2. Just checked. In other phones it's working fine.

**Comment by anantprsd5** [comment]
@subhankar29 Is the issue fixed?
