### ISSUE TITLE
Images taken from Camera shown twice in Gallery

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#62]
In Phimp, taking pictures from the camera results in duplicating the image. As I have observed, the image is saved in two different folders with two different names!

1. take_photo
2. PhimpMe_Photo_Effect

Hence when the images from the external storage is fetched, it will show the same image twice.

**Steps to re-produce**
- Open App and go to **_Camera_**
- Click on _Camera_ icon and take a picture
- Click _Save_

> Now go to **_Upload_** and click on the **_+_** icon to load the image gallery and you will see duplicates

> Also note that if I don't click _Save_ and click _Discard_, the camera will be open again. And if we go back, then only one image will appear in the gallery.

- Duplicates shown in new Gallery GridView
![duplicates](https://cloud.githubusercontent.com/assets/14261304/23545288/c17e98b4-0020-11e7-9c8a-c41d3da3e87a.png)

- Duplicates shown in Upload
![duplicates2](https://cloud.githubusercontent.com/assets/14261304/23545289/c17fd918-0020-11e7-9260-2b6b21e6b861.png)

- Duplicates don't occur if we discard and click back from the _Camera_ view
![single](https://cloud.githubusercontent.com/assets/14261304/23545290/c18410aa-0020-11e7-97da-abb12a0b4454.png)

**Comment by ronaksakhuja** [comment]
On it :)

**Comment by CloudyPadmal** [comment]
Hello @ronaksakhuja !! You can work on it! But shall we wait a little till @pa1pal or @Abhi2424shek give a comment on this one? I feel like since that _Save_ is for the edited image, they've keeping the original and the edit on purpose :thinking:

**Comment by ronaksakhuja** [comment]
@CloudyPadmal Alright .

**Comment by Abhi2424shek** [comment]
Ok, got an opinion for you guys to consider.
If this is intentionally a feature to edit images. Here is my opinion:
- Images should not be saved twice **if** no changes are made when editing.
- There must be an option in settings to turn editing after taking a photo on or off.
- The image editing activity should have a title stating to edit the image.

If it was not intentionally a feature to save images twice, i.e, it is a bug then my opinion is to:
- Remove the feature

I feel this was intentionally a feature but can't conclude without @pa1pal commenting his opinion!

**Comment by CloudyPadmal** [comment]
Agreed @Abhi2424shek !!

Or may be an implementation can be suggested to show the preview of the image and have some buttons and menus there to save or edit and save or discard the image!!

Once it is confirmed @ronaksakhuja can take it :)

**Comment by ronaksakhuja** [comment]
Agreed @Abhi2424shek .
We shall wait for @pa1pal .

**Comment by pa1pal** [comment]
agree with @Abhi2424shek. Firstly, we can work on fixing the bug of is saving images twice even when no editing done. 
Then settings option suggested by Abhishek is nice. Use sharedpref with checkbox of toggle Button for user preference.

**Comment by ronaksakhuja** [comment]
Will start working on it @pa1pal .
