### ISSUE TITLE
show step wise toggle before after button in EditImageActivity

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#637]
**Actual Behaviour**

Currently, before after toggle button compare the main image as before. 

**Expected Behaviour**

It should show stepwise comparison. To impact last edit made.

**Steps to reproduce it**

Open any image --> select Edit option --> apply operation --> click on toggle button

**Would you like to work on the issue?**

Yes

**Comment by vinaysajjanapu** [comment]
@pa1pal Check again. I implemented that already.

**Comment by pa1pal** [comment]
@vinaysajjanapu got it.
While it is in slider mode, or any effect is in progress. It shows just previous. And shows original image otherwise.
