### ISSUE TITLE
Sorting all photos not working as expected

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#643]
**Actual Behaviour**

Currently, all photos **sort option** is not working properly.

**Steps to reproduce it**

Open galley-> Click on all photes-> choose sort options.

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
I am having some issues while solving this. I need some help here.

**Comment by anantprsd5** [comment]
@mohitmanuja Sure, I have worked with all photos part before. would love to help.
