### ISSUE TITLE
Travis tried to deploy the app to apk on pull requests

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#65]
Travis credentials for the repo is needed to push the generated apk to the apk branch, since they are not available to pull requests, we could run these scripts on direct commits, since github addresses PR merge commits like direct commit, we can safely have the apk generated for PR merges.

This issue is very easy and can be solved by a one line solution with the help of a Travis variable. 

This would improve the build time for PR, as Travis currently tries to push after cloning the repo and it can't push and there is no need to do so!

**Comment by anantprsd5** [comment]
Working on it.
