### ISSUE TITLE
Integrate openCV4Android in to the app

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#688]
**Actual Behaviour**

All the image processing in editor is done using raw functions which are not optimized.

**Expected Behaviour**

OpenCV library has very large number of optimized IP functions. If we integrate it, we can optimize image editor's performance and can implement many other face processing which were very difficult using raw functions.

**Cons**

Adding OpenCV creates lib files for all architectures. By default lib files for all architectures gets included in apk which is unnecessary. So this causes apk size to increase a lot. But if we generate multiple apks (different apk for different architecture) we can use openCV and app size will also be very less. Most apps follow this method. If we upload apks of all architectures to playstore, it takes care of which one to download based on our device config.

So, I think we can integrate OpenCV4Android into our app. 

What say @pa1pal @mohitmanuja @anantprsd5 @Subhankar29 ?

**Would you like to work on the issue?**
yes.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu yeah sure. Go ahead. :+1:
