### ISSUE TITLE
Changing default primary color of app

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#691]
**Actual Behaviour**

Currently, the app primary color is dark blue.

**Expected Behaviour**

It should be light and which should look attractive.

**Steps to reproduce it**

See app toolbar, navigation drawer and bottom navigation color.

**Screenshots of the issue**
![screenshot_2017-06-29-18-32-19-098_org fossasia phimpme](https://user-images.githubusercontent.com/9361754/27688752-64b5f344-5cf9-11e7-9e3c-ee0ee8873580.png)

**Would you like to work on the issue?**
Yes.

**Comment by vinaysajjanapu** [comment]
@mohitmanuja please mention the color (color code) which you propose to use in app as primary color and see if everyone agree with that.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Sure.

**Comment by mohitmanuja** [comment]
1. md_light_blue_300 =>  #4FC3F7

![screenshot_1498759963](https://user-images.githubusercontent.com/9361754/27703344-aae2f576-5d24-11e7-8eb5-6566f6caab63.png)

2. md_purple_300 =>#BA68C8 

![screenshot_1498760031](https://user-images.githubusercontent.com/9361754/27703404-e010b210-5d24-11e7-8e3c-3fed75053649.png)

**Comment by mohitmanuja** [comment]
Suggestions required @pa1pal  @anantprsd5 @vinaysajjanapu @Subhankar29.

**Comment by anantprsd5** [comment]
@mohitmanuja First one md_light_blue seems fine
