### ISSUE TITLE
Should we add "code practices" section in readme.md?

### ISSUE THREAD

**Issue by chiragw15** [fossasia/phimpme-android#70]
**Actual Behaviour**

There is no fixed code practices.

**Expected Behaviour**

How about adding code practices like in other fossasia projects. eg https://github.com/fossasia/susi_android#code-practices

**Comment by Abhi2424shek** [comment]
We would go with a CONTRIBUTORS.md file as underlined in issue #51, whts your thoughts now @chiragw15
