### ISSUE TITLE
Replacement of Description activity with Dialog box

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#702]
**Actual Behaviour**

Currently we have description activity to store the info of the picture.

**Expected Behaviour**

We should use dialog boxes instead of Description activity as it is not required for just writing the info and it can be dealt with using a dialog box.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Would you like to work on the issue?**

Yes.

@mohitmanuja @pa1pal @vinaysajjanapu @Subhankar29 Need suggestion on this.

**Comment by mohitmanuja** [comment]
👍 Go ahead.
