### ISSUE TITLE
Image disappears when crop is applied immediately after rotation 

### ISSUE THREAD

**Issue by devutsav** [fossasia/phimpme-android#704]
**Actual Behaviour**

On applying Rotation and then immediately applying crop, the image disappears. (provided we have not confirmed or rejected the rotation on the image)

**Expected Behaviour**

If we rotate the image and don't confirm the rotation, then applying any other filter the rotation must be rejected.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Would you like to work on the issue?**

Need suggestions.

@pa1pal any suggestions on this one?

**Comment by vinaysajjanapu** [comment]
Thank you @devutsav for pointing out the error. 
I found the issue and fixed it.
