### ISSUE TITLE
Swipe gesture to navigate between the activities in Home Screen

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#711]
**Actual Behaviour**

Currently, the only to switch between CameraActivity, LFMainActivity and AccountActivity is navigation buttons. 

**Expected Behaviour**

To navigate between CameraActivity, LFMainActivity and AccountActivity through gesture swipe. 

**Would you like to work on the issue?**

Yes

**Comment by mohitmanuja** [comment]
@Subhankar29 I don't prefer it.

See references : https://github.com/fossasia/phimpme-android/issues/267 & https://github.com/fossasia/phimpme-android/issues/268

**Comment by pa1pal** [comment]
@Subhankar29  As per the guidelines **Avoid using lateral motion to transition between views**.

Link : https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior

**Comment by Subhankar29** [comment]
@mohitmanuja @pa1pal OK, then I will close the issue and the PR

**Comment by Subhankar29** [comment]
@mohitmanuja @pa1pal But the guidelines restrict showing transition when switching activities. I was thinking not to the transition and open the activity directly on swipe gesture. what is your suggestion? 
@the-dagger Any suggestion?

**Comment by the-dagger** [comment]
@shubhankar29 you can either use bottom sheet or use a viewpager.
Swiping to navigate in Bottomsheet is not a recommended practice, so let's keep things the way they are.

**Comment by Subhankar29** [comment]
OK then.
