### ISSUE TITLE
Copy and move to options open window even if no photo is selected

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#714]
**Actual Behaviour**

From the gallery even if no photo is selected, copy to and move to options open a window to choose a folder. 

**Expected Behaviour**

Check if any image is selected. Show snackbar to select an image 

**Steps to reproduce it**

From LFMainActivity choose: copy to or move to. 

**Would you like to work on the issue?**
Yes

**Comment by anantprsd5** [comment]
I think we should hide the copy to and move to options if selected media count is zero instead of displaying snackbar. @Subhankar29

**Comment by Subhankar29** [comment]
@anantprsd5 yes we can do that, but showing snackbar will remind the user for selection.

**Comment by mohitmanuja** [comment]
@Subhankar29 I think hiding options is best.

**Comment by Subhankar29** [comment]
@mohitmanuja @anantprsd5 Yes, I am implementing hiding option.
