### ISSUE TITLE
Local Photos Not Reponding

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/phimpme-android#72]
#60  after this merge the app is trying to load all the photos in my phone and its tuck after the splash screen. I have over 5000 images in my phone.
The log is
 I/CACHE: Saved file /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20160918-WA0012.jpeg (which is now /storage/emulated/0/.PhimpMeCache/040317015410104.png) correctly for each photo.
I think the previous method was good to show only 6 images at once and then load more on button click.
@pa1pal please check.

**Comment by CloudyPadmal** [comment]
Oh I see! We better integrate a lazy load to it right? Now it's loading the whole gallery!

**Comment by dynamitechetan** [comment]
I think the previous way is better (6 images at a time and then click to add more) . In this app we have to show images from different sources rg fb, Flickr, WordPress etc. so no need to show a user his full gallery.

**Comment by chiragw15** [comment]
How about displaying only one picture from each source i.e fb, wordpress, etc and folder and when a user clicks on it, all pictures of that folder gets displayed. Basically, what a normal gallery app in android phone does.

**Comment by CloudyPadmal** [comment]
I've implemented a way around huge galleries! So I've added the _Add_ button again.
- Once the app is open, it will load the first 21 images in the gallery. (21 % 3 = 0) [Any suggestions on how much to load at a time? :thinking: ]
- Upon clicking on the _Add_ button, it will load the next 21
- When the gallery is fully loaded, the _Add_ button will be disabled

> This way, it will fetch a potion at a time making it efficient against huge galleries!

@chiragw15 From what I observed the app generates different grid views to each source like facebook, google images and there's a ton of gallery support is there :D

I will send the PR soon! :mag:

**Comment by dynamitechetan** [comment]
please send PR. much needed. I am not able to even start the app.

**Comment by Abhi2424shek** [comment]
@CloudyPadmal a suggestion instead of:
> Upon clicking on the Add button, it will load the next 21
Load the images when the user scrolls to the bottom! --- It's a suggestion

**Comment by dynamitechetan** [comment]
### We can have card for all categories and when user click on that we can complete grid with lazy loading
@Abhi2424shek  @pa1pal reviews??


<img src="https://cloud.githubusercontent.com/assets/14369357/23578200/50e16a1e-00f7-11e7-91dc-3b3c01e39c83.png" width="380">

**Comment by pa1pal** [comment]
@dynamitechetan This UI looks very nice.

**Comment by Abhi2424shek** [comment]
@dynamitechetan yes it's very nice 😍 can you implement an additional intent when you press on each card or expand it when you press it. (IMO first one would nice as lazy loading can be done in scroll)

**Comment by dynamitechetan** [comment]
yes. I was thinking to do the same. Show some photos in the card and then open a new Activity to show all the photos with lazy loading.
