### ISSUE TITLE
Zoom feature in SharingActivity ImageView 

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#737]
**Actual Behaviour**

In the `SharingActivity` ImageView doesn't have zoom feature. 

**Expected Behaviour**

Can zoom the image in `SharingActivity`, as we already have a custom class of ImageView as ImageViewTouch. As used in SingleMediaActivity.

**Steps to reproduce it**

Open any image --> Select Share option from bottom --> ImageView in SharingActiivty

**Would you like to work on the issue?**

Yes

**Comment by vinaysajjanapu** [comment]
@pa1pal I don't think this feature is necessary. There should have been a small thumbnail, but instead we used a large image. That is more than enough in share page.

**Comment by pa1pal** [comment]
@vinaysajjanapu  I agree. But as we are already have a custom implementation of ImageViewTouch in our app, so why not use this in place of ImageView. It won't make any difference.
