### ISSUE TITLE
Unfortunately app has been stopped

### ISSUE THREAD

**Issue by optnio00** [fossasia/phimpme-android#74]
App has been stopped

When i select an image from gallery fragment ....
if image scale size is too large it has been crashed when image scale size is small it has no problem

we need to remove this issue. User can also upload large scale images and edit it and copped.

![screenshot_2017-03-03-16-40-39](https://cloud.githubusercontent.com/assets/15853647/23580138/dd8d5f70-0121-11e7-821e-e5f69a2eecc1.png)

**Comment by haroonrashid235** [comment]
Not having any problem with images I have tested on. how large a size you are talking about?

**Comment by optnio00** [comment]
1028*1028px+

**Comment by optnio00** [comment]
this is snapshot. you can see

**Comment by haroonrashid235** [comment]
I'll try to test on image that big tonight and come back on this

**Comment by Abhi2424shek** [comment]
Any updates?

**Comment by optnio00** [comment]
No but this is problem solved. Now app is not stop but now image is disappearing.

**Comment by Abhi2424shek** [comment]
Open up a new issue.
