### ISSUE TITLE
Change the name of directory where captured images gets saved 

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#742]
**Actual Behaviour**

Currently the directory name is opencamera

**Expected Behaviour**

It should have been phimpme-cam or something similar

**Steps to reproduce it**

Capture a photo using phimpme app.

**Would you like to work on the issue?**

I like to. but, if anyone is interested they can.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu I will do it :+1:
