### ISSUE TITLE
Perform sorting on Background Thread

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#774]
**Actual Behaviour**
When the user sorts the albums or photos, the app lags giving the impression that it has frozen

**Expected Behaviour**
Convey to the user that the photos are being sorted by means of a loader.

**Steps to reproduce it**
Sort photos

**Would you like to work on the issue?**
Yes

**Comment by anantprsd5** [comment]
Is it freezing when applying every sort action or just the number sort?

**Comment by mayank8318** [comment]
It is more noticeable on the number sort

**Comment by mayank8318** [comment]
@anantprsd5 what if we do sorting on a background thread?

**Comment by anantprsd5** [comment]
@mayank8318 please update the branch and check once, the progress dialog for the number sort is added. Please do so for the other actions if lag is noticeable. For me other sorts are snappy. Thanks.

**Comment by mayank8318** [comment]
@anantprsd5 I moved the sorting on a background thread and now all the sorts are butter smooth.
