### ISSUE TITLE
Change Drawer Header

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#780]
**Actual Behaviour**
The current drawer header doesnt look appealing.

**Steps to reproduce it**

Open the drawer.

**Screenshots of the issue**
Suggested Change-
![drawer-header-change-with color](https://user-images.githubusercontent.com/22395998/28200594-b7cb5618-688a-11e7-9b3c-9b6493c4467a.png)

Or if the primary color is to be used -

![drawer-header change](https://user-images.githubusercontent.com/22395998/28201148-510042f6-688d-11e7-87aa-541787a3c64f.png)

**Would you like to work on the issue?**

Yes
What do you think @anantprsd5 ?

**Comment by vinaysajjanapu** [comment]
@mayank8318 second one looks good as it goes with the selected primary color of the application. You can work on this if you wish. If you don't want to, then please comment here. So that some other person might work on it. Thanks.

**Comment by mayank8318** [comment]
Ya I was waiting for someone's opinion... I will create a pull request

**Comment by pa1pal** [comment]
@mayank8318 second one looks good.
