### ISSUE TITLE
Make all color of the app icon in Accounts Activity Black

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#789]
**Actual Behaviour**

The color of Flickr and NextCloud app icon is not black. This is improper for the uniformity of the application

**Expected Behaviour**

All the app icons in Accounts Activity Black.

**Steps to reproduce it**

AccountsActivity->Flickr
AccountsActivity->NextCloud

**Would you like to work on the issue?**

Yes

**Comment by vinaysajjanapu** [comment]
PR merged already.

**Comment by vinaysajjanapu** [comment]
#790
