### ISSUE TITLE
Add choose folder functionality

### ISSUE THREAD

**Issue by ShailyTyagi** [fossasia/phimpme-android#81]
**Actual Behaviour**

Currently the user has to scroll all the way down to the particular pictures and it becomes tough to find the picture he/she wishes to upload from a sea of pictures.

**Expected Behaviour**
A choose folder functionality will allow the user to choose from different folders on his/her device making the task much easier.

**Would you like to work on the issue?**

Yes,i would definitely like to work on the issue.

**Comment by Abhi2424shek** [comment]
Sure then, go on.

**Comment by Abhi2424shek** [comment]
@ShailyTyagi are you taking it up?

**Comment by ShailyTyagi** [comment]
Yes ,sorry for the delay.I am kind of a beginner. @Abhi2424shek

**Comment by Abhi2424shek** [comment]
@ShailyTyagi it's ok if you are on it.

**Comment by Abhi2424shek** [comment]
I think #286 is much better, and since @ShailyTyagi isn't working on it, closing it.
