### ISSUE TITLE
Setup Drupal website with Rest API

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#811]
**Actual Behaviour**

Currently, the Drupal website is outdated. In the https://github.com/fossasia/phimpme-drupal.

**Expected Behaviour**

Set up a new Drupal website with Drupal 8 and Rest API services. 

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
PR merged: https://github.com/fossasia/phimpme-drupal/pull/2
