### ISSUE TITLE
Please create a simple website without Jekyll with Material Design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#817]
Please create a simple website in the same design as the app itself, e.g. something simple like https://assistant.google.com

We should use Yaydoc for this. So, the Readme.md is converted into a startpage. Simply make the start page into a good resource.

**Comment by abishekvashok** [comment]
I could make you a simple website with materialize CSS (HTML) @mariobehling >> Do you want that?

**Comment by pa1pal** [comment]
@abishekvashok We are integrating yaydoc in all of our Fossasia projects. This is in progress. Will ping you in case of requirement.

**Comment by mariobehling** [comment]
@imujjwal96 Please help to finalize this.

**Comment by vaibhavsingh97** [comment]
can i work on this issue?

**Comment by abishekvashok** [comment]
@vaibhavsingh97 @mariobehling @imujjwal96  @pa1pal pls close this

**Comment by abishekvashok** [comment]
I am gonna close this one. If needed we can go for such a theme on yaydoc
