### ISSUE TITLE
Allowing share via multiple platforms

### ISSUE THREAD

**Issue by harsu-ag** [fossasia/phimpme-android#83]
**Actual Behavior**
Currently, the app allows photos to be shared explicitly via Bluetooth.

**Expected Behavior**
We can extend it to a 1 click share button that allows sharing via any app that allows Image content. 

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by Abhi2424shek** [comment]
Sure go on

**Comment by Subhankar29** [comment]
if the issue is not resolved I would I like to work on it.

**Comment by harsu-ag** [comment]
@Subhankar29 I have resolved it

**Comment by optnio00** [comment]
This issue is now solved. I already solved this add also make a PR

**Comment by Abhi2424shek** [comment]
Any one else interested on this?

**Comment by saurabhjn76** [comment]
may I work on this?

**Comment by Abhi2424shek** [comment]
@saurabhjn76 sure

**Comment by Abhi2424shek** [comment]
Closed via #314
