### ISSUE TITLE
Add other share in the toolbar in Sharing Activity

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#840]
**Actual Behaviour**

Currently, using share feature to other application is used in the table layout. 

**Expected Behaviour**

Remove other feature from the table layout and put in the toolbar.
**Steps to reproduce it**

SharingActivity->Other

**LogCat for the issue**

**Would you like to work on the issue?**

Yes.

**Comment by vinaysajjanapu** [comment]
@Subhankar29 any reason?

**Comment by Subhankar29** [comment]
@vinaysajjanapu yes, Currently, we have an extensive list of sharing options. If users want to share any image to a specific platform he or she performs it by scrolling down the list. But if the user shares it using Action_share he or she can do it directly from the toolbar button. This way the uniformity of the SharingActivity is preserved.

**Comment by mohitmanuja** [comment]
@Subhankar29 @vinaysajjanapu I think we should come up with something different, way because right now we have more than 8 accounts and it is difficult to scroll down (and by mistake if user click on any account then pic will be uploaded)  so I think instead of doing this we should think about to change the whole share activity.

**Comment by vinaysajjanapu** [comment]
@mohitmanuja We can just have a confirmation dialog on clicking the button.
But please wait until this #845 issue is done. 
Then we can think of further changes in flow and UI.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Okay.

**Comment by pa1pal** [comment]
can we close this now?

**Comment by mohitmanuja** [comment]
@pa1pal 'I think yes.

**Comment by pa1pal** [comment]
@Subhankar29 I'm closing this, reopen in case of adding this feature.
