### ISSUE TITLE
User Interaction Issues 

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/phimpme-android#86]
**Actual Behavior**

If you press back button on settings, upload and camera it goes back to gallery and then close the app promptly and we have to select the options from navigation given below. There are some Spelling and Grammar error in dialog boxes.

**Expected Behaviour**

It should go back to home screen and shouldn't close app. It can be made swipe view that if screen is swiped left then it goes to camera option and if swiped again it goes to upload and so on 

**Steps to reproduce it**

It might because of value which remain saved in key code it can be made right by making it to "0" after setting view to home screen. 
Screen can be converted into swipe view by viewpager. 

**Would you like to work on the issue?**

Yes I would like to work on these.

**Comment by dynamitechetan** [comment]
Read about Bottom Navigation Bar guidelines. 
Using swipe gestures on the content area does not navigate between views.
So no need to implement swipe gestures. You can work on the grammar and other issues.

**Comment by Abhi2424shek** [comment]
Yes pls work only on the grammar and english issues!

**Comment by Sanjayjeyavel** [comment]
Hey! I'm new to open source and would love to work on this!!

**Comment by AliAyub007** [comment]
Okay I will do this till tonight.

**Comment by AliAyub007** [comment]
@sanjayjeyavel If you are new to GitHub try taking tutorials they will you alot. You have to learn git for this and here is a link I think this will be useful kindly check this. 
https://idope.se/torrent/apps/https:/www.idope.se/torrent/essential/1c0c89e39140f598d30e71f42806d638e83626ef/

**Comment by Sanjayjeyavel** [comment]
@AliAyub007 I will!! Thank you.

**Comment by pa1pal** [comment]
@AliAyub007 The link you shared in your comment is torrent of a Paid online course. The torrent of copyrighted and paid material should not be promoted, it is completely illegal.
And that too on platform like GitHub. I updated your comment, don't do this from next time.

**Comment by AliAyub007** [comment]
@pa1pal  I am really sorry I didn't know this and I won't do this next time.

**Comment by Abhi2424shek** [comment]
Dont make multiple PRs for a small issue!
