### ISSUE TITLE
Google Now asking the same question twice

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#869]
**Actual Behaviour**

While taking a photo using Google Now, It is asking the same question twice. 

**Expected Behaviour**

Ask the same question only once. 

**Would you like to work on the issue?**

Yes.

**Comment by Siddharth-Singhs** [comment]
Subhankar29 please explain the issue briefly or provide some screenshot.

**Comment by Subhankar29** [comment]
@Siddharth-Singhs Follow the procedure: open Google Assistant->Give command: "Take a selfie"->Choose Phimpme. Assistant will few questions twice. If you want to work on it go ahead, I will assign this task to you.

**Comment by hardik124** [comment]
@Siddharth-Singhs  are you working on it ? Or can I take it up?

**Comment by Siddharth-Singhs** [comment]
@hardik124 yes i will work on it.

**Comment by anantprsd5** [comment]
@siddharth-Singhs Are you working on this? If not, please let us know so that others can work on it. Thanks!

**Comment by abishekvashok** [comment]
@anantprsd5 @Siddharth-Singhs status

**Comment by abishekvashok** [comment]
To be sure, it still exists

**Comment by yashLadha** [comment]
Also @Subhankar29 and @anantprsd5 If the photo is cliecked by the phimpme camera them the app crashes because of binding resources to an activity.

**Comment by meditat** [comment]
I want to work on this issue.

**Comment by Subhankar29** [comment]
@meditat go ahead and work on it.

**Comment by yashk2000** [comment]
I tried this on 2 phones with android 9. When I said `take a selfie`, I was shown an option for phimpme. On clicking it, the app directly opened.
