### ISSUE TITLE
Geolocation Button does not do anything

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#89]
**Actual Behaviour**

After selecting a photo from the gallery or taking a photo from the phone camera, the geolocation button does not do anything. The values of the latitude and longitude are -1. It does not change after clicking the button

**Expected Behaviour**

The values of latitude and longitude should change according to the user location.

**Steps to reproduce it**

1. Take user current location using locationListener.
2. Get the values of latitude and longitude.
2. Set the values of latitude and longitude. 

**Would you like to work on the issue?**

Yes, I would love to do it. Can I proceed with it?

**Comment by anantprsd5** [comment]
@Subhankar29 By clicking photos using the camera, the latitude and longitude of the photos are changing according to the location for me.

**Comment by Subhankar29** [comment]
@anantprsd5 can you send the screenshot?

**Comment by anantprsd5** [comment]
![screenshot_20170308-165441](https://cloud.githubusercontent.com/assets/20367966/23720273/4160aaf8-0464-11e7-8797-a164fef63bd3.jpg)

**Comment by harsu-ag** [comment]
![17200488_1809231109102393_177263458_o](https://cloud.githubusercontent.com/assets/12862633/23758103/ae7ae0ea-050e-11e7-9a98-3b987e1e4588.png)
@Subhankar29 @anantprsd5 It's not working for me either.

**Comment by dynamitechetan** [comment]
all those who are getting -1.0 as Lat Lang, your GPS is turned off. You might have given app the permissions to use location but your Locations is off.
I can write a check on this fragment if you want.

**Comment by harsu-ag** [comment]
@dynamitechetan actually, yes. That's the case. 

But in my case, I had just switched on the location services before taking the snap. So I suppose my last location was still blank.
 So, we should also put a trigger to requestLocationUpdate in the background if the last location is blank.

**Comment by Abhi2424shek** [comment]
I suggest to display 'GPS is off' when the location coordinates are not available with a button to turn gps on in place of the text boxes and display them only when gps is on.

**Comment by dynamitechetan** [comment]
Can I try.?

**Comment by Abhi2424shek** [comment]
Aren't you working on too many issues in parallel? This is a simple one. I think some beginner should try this. However you could try if you really want @dynamitechetan :)

**Comment by Subhankar29** [comment]
@Abhi242shek This issue is perfect for me to begin the contribution please allow me to go ahead and work on.

**Comment by Subhankar29** [comment]
@dynamitechetan I already started working on it.

**Comment by dynamitechetan** [comment]
Cool.

**Comment by dynamitechetan** [comment]
No problem.

**Comment by Abhi2424shek** [comment]
@Subhankar29 you may pls work.

**Comment by Abhi2424shek** [comment]
It's solved.
