### ISSUE TITLE
Discard button - image still gets saved

### ISSUE THREAD

**Issue by harsu-ag** [fossasia/phimpme-android#90]
**Actual Behavior**
When we press the discard button after taking a picture, the image still gets saved and shows up in gallery

**Expected Behavior**
Discard button should delete the saved copy

**Steps to reproduce it**
1. Take a picture. 
2. discard it. 
3. go to gallery tab, the image is still saved. 

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by harsu-ag** [comment]
Should I keep the image on back pressed.?

**Comment by Abhi2424shek** [comment]
Discard button is to discard the edits.
