### ISSUE TITLE
Create a vector logo for the app

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#901]
**Actual Behaviour**

Currently, the app logo which we are using is a set of pngs. PNGs are not scalable. So we are having 5 different pngs for each dpi.

**Expected Behaviour**

Instead of that we can create a single vector drawable and use it.
Same goes with the one used in the splash screen.

**Would you like to work on the issue?**

yes

**Comment by vinaysajjanapu** [comment]
Android Vector Drawable doesn't support color gradient. Is it fine if we use a plain background?
@anantprsd5 @mohitmanuja @pa1pal @Subhankar29

**Comment by mohitmanuja** [comment]
Yes, use blue background color as app default primary color.

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Also do the same thing for splash screen. And set the background as a active app primary color.
