### ISSUE TITLE
Cache Gradle Dependencies while building in Travis

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#92]
**Actual Behaviour**

Dependencies are not being cached and are downloaded again and again, Travis doesnot have that much internet speed!

**Expected Behaviour**

Gradle dependencies should be cached.

**Steps to reproduce it**

See the Travis CI log

**Would you like to work on the issue?**

No. Someone else could try.

**Comment by dynamitechetan** [comment]
i can try

**Comment by Abhi2424shek** [comment]
Sure then @dynamitechetan
