### ISSUE TITLE
Large size images taking time to load

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#979]
**Actual Behaviour**

Large size images taking time to load in single media acticity.

**Steps to reproduce it**

Open any large size image in single media activity.

**Would you like to work on the issue?**

Yes.

**Comment by pa1pal** [comment]
@mohitmanuja are you trying to scale the image? 
We can speed up after scaling the image according to the device.

**Comment by mohitmanuja** [comment]
@pa1pal Okay, I will try if this work will proceed with it.
